//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC.PowerApps.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PC.PowerApps.Common.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is another Participation for this Contact with the same Level starting one day after..
        /// </summary>
        public static string AdjacentParticipationAfter {
            get {
                return ResourceManager.GetString("AdjacentParticipationAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is another Participation for this Contact with the same Level ending one day before..
        /// </summary>
        public static string AdjacentParticipationBefore {
            get {
                return ResourceManager.GetString("AdjacentParticipationBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is another Participation for this Contact within this period..
        /// </summary>
        public static string AnotherParticipation {
            get {
                return ResourceManager.GetString("AnotherParticipation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is another Participation Fee Exemption for this Contact within the same period..
        /// </summary>
        public static string AnotherParticipationFeeExemption {
            get {
                return ResourceManager.GetString("AnotherParticipationFeeExemption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is another Participation Fee Rule within the same period..
        /// </summary>
        public static string AnotherParticipationFeeRule {
            get {
                return ResourceManager.GetString("AnotherParticipationFeeRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are already another active Settings..
        /// </summary>
        public static string AnotherSettings {
            get {
                return ResourceManager.GetString("AnotherSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} field {1} cannot be empty..
        /// </summary>
        public static string AttributeCannotBeEmpty {
            get {
                return ResourceManager.GetString("AttributeCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} field {1} is read-only..
        /// </summary>
        public static string AttributeIsReadOnly {
            get {
                return ResourceManager.GetString("AttributeIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} fields {1} are read-only..
        /// </summary>
        public static string AttributesAreReadOnly {
            get {
                return ResourceManager.GetString("AttributesAreReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} fields {1} cannot be empty..
        /// </summary>
        public static string AttributesCannotBeEmpty {
            get {
                return ResourceManager.GetString("AttributesCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete Scheduled Job with Status Reason In Progress..
        /// </summary>
        public static string CantDeleteScheduledJobInProgress {
            get {
                return ResourceManager.GetString("CantDeleteScheduledJobInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot manually create a Transaction..
        /// </summary>
        public static string CantManuallyCreateTransaction {
            get {
                return ResourceManager.GetString("CantManuallyCreateTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing non-payment amount from the transaction....
        /// </summary>
        public static string ClearingNonPaymentAmount {
            get {
                return ResourceManager.GetString("ClearingNonPaymentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marking the transaction as non-payment....
        /// </summary>
        public static string MarkingTransactionAsNonPayment {
            get {
                return ResourceManager.GetString("MarkingTransactionAsNonPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marking {0} of {1} transactions as non-payment....
        /// </summary>
        public static string MarkingTransactionsAsNonPayment {
            get {
                return ResourceManager.GetString("MarkingTransactionsAsNonPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participation Fee Exemption From must be less than or equal to Till..
        /// </summary>
        public static string ParticipationFeeExemptionFromGreaterThanTill {
            get {
                return ResourceManager.GetString("ParticipationFeeExemptionFromGreaterThanTill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participation Fee Rule From must be less than or equal to Till..
        /// </summary>
        public static string ParticipationFeeRuleFromGreaterThanTill {
            get {
                return ResourceManager.GetString("ParticipationFeeRuleFromGreaterThanTill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participation Fee Rule From must be a first day of the month..
        /// </summary>
        public static string ParticipationFeeRuleFromNotFirstDayOfMonth {
            get {
                return ResourceManager.GetString("ParticipationFeeRuleFromNotFirstDayOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participation Fee Rule Till must be a last day of the month..
        /// </summary>
        public static string ParticipationFeeRuleTillNotLastDayOfMonth {
            get {
                return ResourceManager.GetString("ParticipationFeeRuleTillNotLastDayOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participation From must be less than or equal to Till..
        /// </summary>
        public static string ParticipationFromGreaterThanTill {
            get {
                return ResourceManager.GetString("ParticipationFromGreaterThanTill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing the transaction....
        /// </summary>
        public static string ProcessingTransaction {
            get {
                return ResourceManager.GetString("ProcessingTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing {0} of {1} transactions....
        /// </summary>
        public static string ProcessingTransactions {
            get {
                return ResourceManager.GetString("ProcessingTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled Job Postpone Until must be greater than or equal to Execute On..
        /// </summary>
        public static string ScheduledJobPostponeUntilLessThanExecuteOn {
            get {
                return ResourceManager.GetString("ScheduledJobPostponeUntilLessThanExecuteOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending a debt reminder to {0} of {1} contacts....
        /// </summary>
        public static string SendingDebtRemindersToContacts {
            get {
                return ResourceManager.GetString("SendingDebtRemindersToContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending a debt reminder to the contact....
        /// </summary>
        public static string SendingDebtReminderToContact {
            get {
                return ResourceManager.GetString("SendingDebtReminderToContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a debt reminder to the contact?.
        /// </summary>
        public static string ShouldSendDebtReminderToContact {
            get {
                return ResourceManager.GetString("ShouldSendDebtReminderToContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send debt reminders to {0} contacts?.
        /// </summary>
        public static string ShouldSendDebtReminderToContacts {
            get {
                return ResourceManager.GetString("ShouldSendDebtReminderToContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of Transaction Payment Total Amount and Non-Payment Amount cannot be greater than Amount..
        /// </summary>
        public static string TransactionRemainingAmountNegative {
            get {
                return ResourceManager.GetString("TransactionRemainingAmountNegative", resourceCulture);
            }
        }
    }
}
