interface BulkDeleteFailure_Base extends WebEntity {
  bulkdeletefailureid?: string | null;
  errordescription?: string | null;
  errornumber?: number | null;
  orderedqueryindex?: number | null;
  owningbusinessunit?: string | null;
  owninguser?: string | null;
}
interface BulkDeleteFailure_Relationships {
  channelaccessprofile_bulkdeletefailures?: ChannelAccessProfile_Result | null;
  channelaccessprofileruleid?: ChannelAccessProfileRule_Result | null;
  externalparty_bulkdeletefailures?: ExternalParty_Result | null;
  externalpartyitem_bulkdeletefailures?: ExternalPartyItem_Result | null;
  regardingobjectid_account?: Account_Result | null;
  regardingobjectid_activityfileattachment?: activityfileattachment_Result | null;
  regardingobjectid_activitymimeattachment?: ActivityMimeAttachment_Result | null;
  regardingobjectid_activitypointer?: ActivityPointer_Result | null;
  regardingobjectid_annotation?: Annotation_Result | null;
  regardingobjectid_annualfiscalcalendar?: AnnualFiscalCalendar_Result | null;
  regardingobjectid_appaction?: appaction_Result | null;
  regardingobjectid_appelement?: AppElement_Result | null;
  regardingobjectid_applicationuser?: ApplicationUser_Result | null;
  regardingobjectid_appmodulecomponentedge?: AppModuleComponentEdge_Result | null;
  regardingobjectid_appmodulecomponentnode?: AppModuleComponentNode_Result | null;
  regardingobjectid_appointment?: Appointment_Result | null;
  regardingobjectid_appsetting?: AppSetting_Result | null;
  regardingobjectid_appusersetting?: AppUserSetting_Result | null;
  regardingobjectid_attributeimageconfig?: AttributeImageConfig_Result | null;
  regardingobjectid_attributemap?: AttributeMap_Result | null;
  regardingobjectid_bot?: bot_Result | null;
  regardingobjectid_botcomponent?: botcomponent_Result | null;
  regardingobjectid_businessunit?: BusinessUnit_Result | null;
  regardingobjectid_businessunitnewsarticle?: BusinessUnitNewsArticle_Result | null;
  regardingobjectid_calendar?: Calendar_Result | null;
  regardingobjectid_canvasappextendedmetadata?: CanvasAppExtendedMetadata_Result | null;
  regardingobjectid_cascadegrantrevokeaccessrecordstracker?: cascadegrantrevokeaccessrecordstracker_Result | null;
  regardingobjectid_cascadegrantrevokeaccessversiontracker?: cascadegrantrevokeaccessversiontracker_Result | null;
  regardingobjectid_catalog?: Catalog_Result | null;
  regardingobjectid_catalogassignment?: CatalogAssignment_Result | null;
  regardingobjectid_connectionreference?: connectionreference_Result | null;
  regardingobjectid_connector?: connector_Result | null;
  regardingobjectid_contact?: Contact_Result | null;
  regardingobjectid_conversationtranscript?: conversationtranscript_Result | null;
  regardingobjectid_customapi?: CustomAPI_Result | null;
  regardingobjectid_customapirequestparameter?: CustomAPIRequestParameter_Result | null;
  regardingobjectid_customapiresponseproperty?: CustomAPIResponseProperty_Result | null;
  regardingobjectid_customeraddress?: CustomerAddress_Result | null;
  regardingobjectid_customerrelationship?: CustomerRelationship_Result | null;
  regardingobjectid_datalakefolder?: datalakefolder_Result | null;
  regardingobjectid_datalakefolderpermission?: datalakefolderpermission_Result | null;
  regardingobjectid_datalakeworkspace?: datalakeworkspace_Result | null;
  regardingobjectid_datalakeworkspacepermission?: datalakeworkspacepermission_Result | null;
  regardingobjectid_displaystring?: DisplayString_Result | null;
  regardingobjectid_email?: Email_Result | null;
  regardingobjectid_emailserverprofile?: EmailServerProfile_Result | null;
  regardingobjectid_entityanalyticsconfig?: EntityAnalyticsConfig_Result | null;
  regardingobjectid_entityimageconfig?: EntityImageConfig_Result | null;
  regardingobjectid_entityindex?: EntityIndex_Result | null;
  regardingobjectid_entitymap?: EntityMap_Result | null;
  regardingobjectid_environmentvariabledefinition?: EnvironmentVariableDefinition_Result | null;
  regardingobjectid_environmentvariablevalue?: EnvironmentVariableValue_Result | null;
  regardingobjectid_exportsolutionupload?: ExportSolutionUpload_Result | null;
  regardingobjectid_fax?: Fax_Result | null;
  regardingobjectid_featurecontrolsetting?: featurecontrolsetting_Result | null;
  regardingobjectid_fixedmonthlyfiscalcalendar?: FixedMonthlyFiscalCalendar_Result | null;
  regardingobjectid_flowmachine?: flowmachine_Result | null;
  regardingobjectid_flowmachinegroup?: flowmachinegroup_Result | null;
  regardingobjectid_flowsession?: flowsession_Result | null;
  regardingobjectid_holidaywrapper?: holidaywrapper_Result | null;
  regardingobjectid_import?: Import_Result | null;
  regardingobjectid_importdata?: ImportData_Result | null;
  regardingobjectid_importfile?: ImportFile_Result | null;
  regardingobjectid_importlog?: ImportLog_Result | null;
  regardingobjectid_importmap?: ImportMap_Result | null;
  regardingobjectid_indexattributes?: IndexAttributes_Result | null;
  regardingobjectid_internalcatalogassignment?: InternalCatalogAssignment_Result | null;
  regardingobjectid_isvconfig?: IsvConfig_Result | null;
  regardingobjectid_kbarticle?: KbArticle_Result | null;
  regardingobjectid_kbarticlecomment?: KbArticleComment_Result | null;
  regardingobjectid_kbarticletemplate?: KbArticleTemplate_Result | null;
  regardingobjectid_keyvaultreference?: KeyVaultReference_Result | null;
  regardingobjectid_knowledgearticle?: KnowledgeArticle_Result | null;
  regardingobjectid_knowledgebaserecord?: KnowledgeBaseRecord_Result | null;
  regardingobjectid_letter?: Letter_Result | null;
  regardingobjectid_managedidentity?: ManagedIdentity_Result | null;
  regardingobjectid_mbs_pluginprofile?: mbs_pluginprofile_Result | null;
  regardingobjectid_monthlyfiscalcalendar?: MonthlyFiscalCalendar_Result | null;
  regardingobjectid_msdyn_aibdataset?: msdyn_AIBDataset_Result | null;
  regardingobjectid_msdyn_aibdatasetfile?: msdyn_AIBDatasetFile_Result | null;
  regardingobjectid_msdyn_aibdatasetrecord?: msdyn_AIBDatasetRecord_Result | null;
  regardingobjectid_msdyn_aibdatasetscontainer?: msdyn_AIBDatasetsContainer_Result | null;
  regardingobjectid_msdyn_aibfile?: msdyn_AIBFile_Result | null;
  regardingobjectid_msdyn_aibfileattacheddata?: msdyn_AIBFileAttachedData_Result | null;
  regardingobjectid_msdyn_aiconfiguration?: msdyn_AIConfiguration_Result | null;
  regardingobjectid_msdyn_aifptrainingdocument?: msdyn_AIFpTrainingDocument_Result | null;
  regardingobjectid_msdyn_aimodel?: msdyn_AIModel_Result | null;
  regardingobjectid_msdyn_aiodimage?: msdyn_AIOdImage_Result | null;
  regardingobjectid_msdyn_aiodlabel?: msdyn_AIOdLabel_Result | null;
  regardingobjectid_msdyn_aiodtrainingboundingbox?: msdyn_AIOdTrainingBoundingBox_Result | null;
  regardingobjectid_msdyn_aiodtrainingimage?: msdyn_AIOdTrainingImage_Result | null;
  regardingobjectid_msdyn_aitemplate?: msdyn_AITemplate_Result | null;
  regardingobjectid_msdyn_analysiscomponent?: msdyn_analysiscomponent_Result | null;
  regardingobjectid_msdyn_analysisjob?: msdyn_analysisjob_Result | null;
  regardingobjectid_msdyn_analysisresult?: msdyn_analysisresult_Result | null;
  regardingobjectid_msdyn_analysisresultdetail?: msdyn_analysisresultdetail_Result | null;
  regardingobjectid_msdyn_dataflow?: msdyn_dataflow_Result | null;
  regardingobjectid_msdyn_federatedarticle?: msdyn_federatedarticle_Result | null;
  regardingobjectid_msdyn_federatedarticleincident?: msdyn_federatedarticleincident_Result | null;
  regardingobjectid_msdyn_helppage?: msdyn_helppage_Result | null;
  regardingobjectid_msdyn_kalanguagesetting?: msdyn_kalanguagesetting_Result | null;
  regardingobjectid_msdyn_kmfederatedsearchconfig?: msdyn_kmfederatedsearchconfig_Result | null;
  regardingobjectid_msdyn_kmpersonalizationsetting?: msdyn_kmpersonalizationsetting_Result | null;
  regardingobjectid_msdyn_knowledgearticleimage?: msdyn_knowledgearticleimage_Result | null;
  regardingobjectid_msdyn_knowledgearticletemplate?: msdyn_knowledgearticletemplate_Result | null;
  regardingobjectid_msdyn_knowledgeinteractioninsight?: msdyn_knowledgeinteractioninsight_Result | null;
  regardingobjectid_msdyn_knowledgepersonalfilter?: msdyn_knowledgepersonalfilter_Result | null;
  regardingobjectid_msdyn_knowledgesearchfilter?: msdyn_knowledgesearchfilter_Result | null;
  regardingobjectid_msdyn_knowledgesearchinsight?: msdyn_knowledgesearchinsight_Result | null;
  regardingobjectid_msdyn_pminferredtask?: msdyn_pminferredtask_Result | null;
  regardingobjectid_msdyn_pmrecording?: msdyn_pmrecording_Result | null;
  regardingobjectid_msdyn_richtextfile?: msdyn_richtextfile_Result | null;
  regardingobjectid_msdyn_serviceconfiguration?: msdyn_serviceconfiguration_Result | null;
  regardingobjectid_msdyn_slakpi?: msdyn_slakpi_Result | null;
  regardingobjectid_msdyn_solutionhealthrule?: msdyn_solutionhealthrule_Result | null;
  regardingobjectid_msdyn_solutionhealthruleargument?: msdyn_solutionhealthruleargument_Result | null;
  regardingobjectid_msdyn_solutionhealthruleset?: msdyn_solutionhealthruleset_Result | null;
  regardingobjectid_msdyn_tour?: msdyn_tour_Result | null;
  regardingobjectid_msdynce_botcontent?: msdynce_botcontent_Result | null;
  regardingobjectid_organization?: Organization_Result | null;
  regardingobjectid_organizationdatasyncsubscription?: organizationdatasyncsubscription_Result | null;
  regardingobjectid_organizationdatasyncsubscriptionentity?: organizationdatasyncsubscriptionentity_Result | null;
  regardingobjectid_organizationsetting?: OrganizationSetting_Result | null;
  regardingobjectid_package?: package_Result | null;
  regardingobjectid_pc_bankaccount?: pc_BankAccount_Result | null;
  regardingobjectid_pc_participation?: pc_Participation_Result | null;
  regardingobjectid_pc_participationfeeexemption?: pc_ParticipationFeeExemption_Result | null;
  regardingobjectid_pc_payment?: pc_Payment_Result | null;
  regardingobjectid_pc_scheduledjob?: pc_ScheduledJob_Result | null;
  regardingobjectid_pc_settings?: pc_Settings_Result | null;
  regardingobjectid_pc_transaction?: pc_Transaction_Result | null;
  regardingobjectid_pdfsetting?: PDFSetting_Result | null;
  regardingobjectid_phonecall?: PhoneCall_Result | null;
  regardingobjectid_pluginpackage?: pluginpackage_Result | null;
  regardingobjectid_post?: Post_Result | null;
  regardingobjectid_privilege?: Privilege_Result | null;
  regardingobjectid_processstageparameter?: processstageparameter_Result | null;
  regardingobjectid_provisionlanguageforuser?: ProvisionLanguageForUser_Result | null;
  regardingobjectid_quarterlyfiscalcalendar?: QuarterlyFiscalCalendar_Result | null;
  regardingobjectid_queue?: Queue_Result | null;
  regardingobjectid_queueitem?: QueueItem_Result | null;
  regardingobjectid_recurringappointmentmaster?: RecurringAppointmentMaster_Result | null;
  regardingobjectid_relationshipattribute?: RelationshipAttribute_Result | null;
  regardingobjectid_relationshiprole?: RelationshipRole_Result | null;
  regardingobjectid_relationshiprolemap?: RelationshipRoleMap_Result | null;
  regardingobjectid_revokeinheritedaccessrecordstracker?: revokeinheritedaccessrecordstracker_Result | null;
  regardingobjectid_role?: Role_Result | null;
  regardingobjectid_routingrule?: RoutingRule_Result | null;
  regardingobjectid_routingruleitem?: RoutingRuleItem_Result | null;
  regardingobjectid_savedquery?: SavedQuery_Result | null;
  regardingobjectid_semiannualfiscalcalendar?: SemiAnnualFiscalCalendar_Result | null;
  regardingobjectid_serviceplan?: ServicePlan_Result | null;
  regardingobjectid_serviceplanmapping?: ServicePlanMapping_Result | null;
  regardingobjectid_settingdefinition?: SettingDefinition_Result | null;
  regardingobjectid_sla?: SLA_Result | null;
  regardingobjectid_socialactivity?: SocialActivity_Result | null;
  regardingobjectid_solutioncomponentattributeconfiguration?: solutioncomponentattributeconfiguration_Result | null;
  regardingobjectid_solutioncomponentbatchconfiguration?: solutioncomponentbatchconfiguration_Result | null;
  regardingobjectid_solutioncomponentconfiguration?: solutioncomponentconfiguration_Result | null;
  regardingobjectid_solutioncomponentrelationshipconfiguration?: solutioncomponentrelationshipconfiguration_Result | null;
  regardingobjectid_stagesolutionupload?: StageSolutionUpload_Result | null;
  regardingobjectid_subject?: Subject_Result | null;
  regardingobjectid_systemform?: SystemForm_Result | null;
  regardingobjectid_systemuser?: SystemUser_Result | null;
  regardingobjectid_systemuserauthorizationchangetracker?: SystemUserAuthorizationChangeTracker_Result | null;
  regardingobjectid_task?: Task_Result | null;
  regardingobjectid_team?: Team_Result | null;
  regardingobjectid_teammobileofflineprofilemembership?: teammobileofflineprofilemembership_Result | null;
  regardingobjectid_template?: Template_Result | null;
  regardingobjectid_territory?: Territory_Result | null;
  regardingobjectid_theme?: Theme_Result | null;
  regardingobjectid_userform?: UserForm_Result | null;
  regardingobjectid_usermapping?: UserMapping_Result | null;
  regardingobjectid_usermobileofflineprofilemembership?: usermobileofflineprofilemembership_Result | null;
  regardingobjectid_userquery?: UserQuery_Result | null;
  regardingobjectid_virtualentitymetadata?: VirtualEntityMetadata_Result | null;
  regardingobjectid_workflowbinary?: workflowbinary_Result | null;
  userentityinstancedata_bulkdeletefailure?: UserEntityInstanceData_Result[] | null;
}
interface BulkDeleteFailure extends BulkDeleteFailure_Base, BulkDeleteFailure_Relationships {
}
interface BulkDeleteFailure_Create extends BulkDeleteFailure {
}
interface BulkDeleteFailure_Update extends BulkDeleteFailure {
}
interface BulkDeleteFailure_Select {
  asyncoperationid_guid: WebAttribute<BulkDeleteFailure_Select, { asyncoperationid_guid: string | null }, { asyncoperationid_formatted?: string }>;
  bulkdeletefailureid: WebAttribute<BulkDeleteFailure_Select, { bulkdeletefailureid: string | null }, {  }>;
  bulkdeleteoperationid_guid: WebAttribute<BulkDeleteFailure_Select, { bulkdeleteoperationid_guid: string | null }, { bulkdeleteoperationid_formatted?: string }>;
  errordescription: WebAttribute<BulkDeleteFailure_Select, { errordescription: string | null }, {  }>;
  errornumber: WebAttribute<BulkDeleteFailure_Select, { errornumber: number | null }, {  }>;
  orderedqueryindex: WebAttribute<BulkDeleteFailure_Select, { orderedqueryindex: number | null }, {  }>;
  ownerid_guid: WebAttribute<BulkDeleteFailure_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit: WebAttribute<BulkDeleteFailure_Select, { owningbusinessunit: string | null }, {  }>;
  owninguser: WebAttribute<BulkDeleteFailure_Select, { owninguser: string | null }, {  }>;
  regardingobjectid_guid: WebAttribute<BulkDeleteFailure_Select, { regardingobjectid_guid: string | null }, { regardingobjectid_formatted?: string }>;
}
interface BulkDeleteFailure_Filter {
  asyncoperationid_guid: XQW.Guid;
  bulkdeletefailureid: XQW.Guid;
  bulkdeleteoperationid_guid: XQW.Guid;
  errordescription: string;
  errornumber: number;
  orderedqueryindex: number;
  ownerid_guid: XQW.Guid;
  owningbusinessunit: XQW.Guid;
  owninguser: XQW.Guid;
  regardingobjectid_guid: XQW.Guid;
}
interface BulkDeleteFailure_Expand {
  bulkdeleteoperationid: WebExpand<BulkDeleteFailure_Expand, BulkDeleteOperation_Select, BulkDeleteOperation_Filter, { bulkdeleteoperationid: BulkDeleteOperation_Result }>;
  channelaccessprofile_bulkdeletefailures: WebExpand<BulkDeleteFailure_Expand, ChannelAccessProfile_Select, ChannelAccessProfile_Filter, { channelaccessprofile_bulkdeletefailures: ChannelAccessProfile_Result }>;
  channelaccessprofileruleid: WebExpand<BulkDeleteFailure_Expand, ChannelAccessProfileRule_Select, ChannelAccessProfileRule_Filter, { channelaccessprofileruleid: ChannelAccessProfileRule_Result }>;
  externalparty_bulkdeletefailures: WebExpand<BulkDeleteFailure_Expand, ExternalParty_Select, ExternalParty_Filter, { externalparty_bulkdeletefailures: ExternalParty_Result }>;
  externalpartyitem_bulkdeletefailures: WebExpand<BulkDeleteFailure_Expand, ExternalPartyItem_Select, ExternalPartyItem_Filter, { externalpartyitem_bulkdeletefailures: ExternalPartyItem_Result }>;
  regardingobjectid_account: WebExpand<BulkDeleteFailure_Expand, Account_Select, Account_Filter, { regardingobjectid_account: Account_Result }>;
  regardingobjectid_activityfileattachment: WebExpand<BulkDeleteFailure_Expand, activityfileattachment_Select, activityfileattachment_Filter, { regardingobjectid_activityfileattachment: activityfileattachment_Result }>;
  regardingobjectid_activitymimeattachment: WebExpand<BulkDeleteFailure_Expand, ActivityMimeAttachment_Select, ActivityMimeAttachment_Filter, { regardingobjectid_activitymimeattachment: ActivityMimeAttachment_Result }>;
  regardingobjectid_activitypointer: WebExpand<BulkDeleteFailure_Expand, ActivityPointer_Select, ActivityPointer_Filter, { regardingobjectid_activitypointer: ActivityPointer_Result }>;
  regardingobjectid_annotation: WebExpand<BulkDeleteFailure_Expand, Annotation_Select, Annotation_Filter, { regardingobjectid_annotation: Annotation_Result }>;
  regardingobjectid_annualfiscalcalendar: WebExpand<BulkDeleteFailure_Expand, AnnualFiscalCalendar_Select, AnnualFiscalCalendar_Filter, { regardingobjectid_annualfiscalcalendar: AnnualFiscalCalendar_Result }>;
  regardingobjectid_appaction: WebExpand<BulkDeleteFailure_Expand, appaction_Select, appaction_Filter, { regardingobjectid_appaction: appaction_Result }>;
  regardingobjectid_appelement: WebExpand<BulkDeleteFailure_Expand, AppElement_Select, AppElement_Filter, { regardingobjectid_appelement: AppElement_Result }>;
  regardingobjectid_applicationuser: WebExpand<BulkDeleteFailure_Expand, ApplicationUser_Select, ApplicationUser_Filter, { regardingobjectid_applicationuser: ApplicationUser_Result }>;
  regardingobjectid_appmodulecomponentedge: WebExpand<BulkDeleteFailure_Expand, AppModuleComponentEdge_Select, AppModuleComponentEdge_Filter, { regardingobjectid_appmodulecomponentedge: AppModuleComponentEdge_Result }>;
  regardingobjectid_appmodulecomponentnode: WebExpand<BulkDeleteFailure_Expand, AppModuleComponentNode_Select, AppModuleComponentNode_Filter, { regardingobjectid_appmodulecomponentnode: AppModuleComponentNode_Result }>;
  regardingobjectid_appointment: WebExpand<BulkDeleteFailure_Expand, Appointment_Select, Appointment_Filter, { regardingobjectid_appointment: Appointment_Result }>;
  regardingobjectid_appsetting: WebExpand<BulkDeleteFailure_Expand, AppSetting_Select, AppSetting_Filter, { regardingobjectid_appsetting: AppSetting_Result }>;
  regardingobjectid_appusersetting: WebExpand<BulkDeleteFailure_Expand, AppUserSetting_Select, AppUserSetting_Filter, { regardingobjectid_appusersetting: AppUserSetting_Result }>;
  regardingobjectid_attributeimageconfig: WebExpand<BulkDeleteFailure_Expand, AttributeImageConfig_Select, AttributeImageConfig_Filter, { regardingobjectid_attributeimageconfig: AttributeImageConfig_Result }>;
  regardingobjectid_attributemap: WebExpand<BulkDeleteFailure_Expand, AttributeMap_Select, AttributeMap_Filter, { regardingobjectid_attributemap: AttributeMap_Result }>;
  regardingobjectid_bot: WebExpand<BulkDeleteFailure_Expand, bot_Select, bot_Filter, { regardingobjectid_bot: bot_Result }>;
  regardingobjectid_botcomponent: WebExpand<BulkDeleteFailure_Expand, botcomponent_Select, botcomponent_Filter, { regardingobjectid_botcomponent: botcomponent_Result }>;
  regardingobjectid_businessunit: WebExpand<BulkDeleteFailure_Expand, BusinessUnit_Select, BusinessUnit_Filter, { regardingobjectid_businessunit: BusinessUnit_Result }>;
  regardingobjectid_businessunitnewsarticle: WebExpand<BulkDeleteFailure_Expand, BusinessUnitNewsArticle_Select, BusinessUnitNewsArticle_Filter, { regardingobjectid_businessunitnewsarticle: BusinessUnitNewsArticle_Result }>;
  regardingobjectid_calendar: WebExpand<BulkDeleteFailure_Expand, Calendar_Select, Calendar_Filter, { regardingobjectid_calendar: Calendar_Result }>;
  regardingobjectid_canvasappextendedmetadata: WebExpand<BulkDeleteFailure_Expand, CanvasAppExtendedMetadata_Select, CanvasAppExtendedMetadata_Filter, { regardingobjectid_canvasappextendedmetadata: CanvasAppExtendedMetadata_Result }>;
  regardingobjectid_cascadegrantrevokeaccessrecordstracker: WebExpand<BulkDeleteFailure_Expand, cascadegrantrevokeaccessrecordstracker_Select, cascadegrantrevokeaccessrecordstracker_Filter, { regardingobjectid_cascadegrantrevokeaccessrecordstracker: cascadegrantrevokeaccessrecordstracker_Result }>;
  regardingobjectid_cascadegrantrevokeaccessversiontracker: WebExpand<BulkDeleteFailure_Expand, cascadegrantrevokeaccessversiontracker_Select, cascadegrantrevokeaccessversiontracker_Filter, { regardingobjectid_cascadegrantrevokeaccessversiontracker: cascadegrantrevokeaccessversiontracker_Result }>;
  regardingobjectid_catalog: WebExpand<BulkDeleteFailure_Expand, Catalog_Select, Catalog_Filter, { regardingobjectid_catalog: Catalog_Result }>;
  regardingobjectid_catalogassignment: WebExpand<BulkDeleteFailure_Expand, CatalogAssignment_Select, CatalogAssignment_Filter, { regardingobjectid_catalogassignment: CatalogAssignment_Result }>;
  regardingobjectid_connectionreference: WebExpand<BulkDeleteFailure_Expand, connectionreference_Select, connectionreference_Filter, { regardingobjectid_connectionreference: connectionreference_Result }>;
  regardingobjectid_connector: WebExpand<BulkDeleteFailure_Expand, connector_Select, connector_Filter, { regardingobjectid_connector: connector_Result }>;
  regardingobjectid_contact: WebExpand<BulkDeleteFailure_Expand, Contact_Select, Contact_Filter, { regardingobjectid_contact: Contact_Result }>;
  regardingobjectid_conversationtranscript: WebExpand<BulkDeleteFailure_Expand, conversationtranscript_Select, conversationtranscript_Filter, { regardingobjectid_conversationtranscript: conversationtranscript_Result }>;
  regardingobjectid_customapi: WebExpand<BulkDeleteFailure_Expand, CustomAPI_Select, CustomAPI_Filter, { regardingobjectid_customapi: CustomAPI_Result }>;
  regardingobjectid_customapirequestparameter: WebExpand<BulkDeleteFailure_Expand, CustomAPIRequestParameter_Select, CustomAPIRequestParameter_Filter, { regardingobjectid_customapirequestparameter: CustomAPIRequestParameter_Result }>;
  regardingobjectid_customapiresponseproperty: WebExpand<BulkDeleteFailure_Expand, CustomAPIResponseProperty_Select, CustomAPIResponseProperty_Filter, { regardingobjectid_customapiresponseproperty: CustomAPIResponseProperty_Result }>;
  regardingobjectid_customeraddress: WebExpand<BulkDeleteFailure_Expand, CustomerAddress_Select, CustomerAddress_Filter, { regardingobjectid_customeraddress: CustomerAddress_Result }>;
  regardingobjectid_customerrelationship: WebExpand<BulkDeleteFailure_Expand, CustomerRelationship_Select, CustomerRelationship_Filter, { regardingobjectid_customerrelationship: CustomerRelationship_Result }>;
  regardingobjectid_datalakefolder: WebExpand<BulkDeleteFailure_Expand, datalakefolder_Select, datalakefolder_Filter, { regardingobjectid_datalakefolder: datalakefolder_Result }>;
  regardingobjectid_datalakefolderpermission: WebExpand<BulkDeleteFailure_Expand, datalakefolderpermission_Select, datalakefolderpermission_Filter, { regardingobjectid_datalakefolderpermission: datalakefolderpermission_Result }>;
  regardingobjectid_datalakeworkspace: WebExpand<BulkDeleteFailure_Expand, datalakeworkspace_Select, datalakeworkspace_Filter, { regardingobjectid_datalakeworkspace: datalakeworkspace_Result }>;
  regardingobjectid_datalakeworkspacepermission: WebExpand<BulkDeleteFailure_Expand, datalakeworkspacepermission_Select, datalakeworkspacepermission_Filter, { regardingobjectid_datalakeworkspacepermission: datalakeworkspacepermission_Result }>;
  regardingobjectid_displaystring: WebExpand<BulkDeleteFailure_Expand, DisplayString_Select, DisplayString_Filter, { regardingobjectid_displaystring: DisplayString_Result }>;
  regardingobjectid_email: WebExpand<BulkDeleteFailure_Expand, Email_Select, Email_Filter, { regardingobjectid_email: Email_Result }>;
  regardingobjectid_emailserverprofile: WebExpand<BulkDeleteFailure_Expand, EmailServerProfile_Select, EmailServerProfile_Filter, { regardingobjectid_emailserverprofile: EmailServerProfile_Result }>;
  regardingobjectid_entityanalyticsconfig: WebExpand<BulkDeleteFailure_Expand, EntityAnalyticsConfig_Select, EntityAnalyticsConfig_Filter, { regardingobjectid_entityanalyticsconfig: EntityAnalyticsConfig_Result }>;
  regardingobjectid_entityimageconfig: WebExpand<BulkDeleteFailure_Expand, EntityImageConfig_Select, EntityImageConfig_Filter, { regardingobjectid_entityimageconfig: EntityImageConfig_Result }>;
  regardingobjectid_entityindex: WebExpand<BulkDeleteFailure_Expand, EntityIndex_Select, EntityIndex_Filter, { regardingobjectid_entityindex: EntityIndex_Result }>;
  regardingobjectid_entitymap: WebExpand<BulkDeleteFailure_Expand, EntityMap_Select, EntityMap_Filter, { regardingobjectid_entitymap: EntityMap_Result }>;
  regardingobjectid_environmentvariabledefinition: WebExpand<BulkDeleteFailure_Expand, EnvironmentVariableDefinition_Select, EnvironmentVariableDefinition_Filter, { regardingobjectid_environmentvariabledefinition: EnvironmentVariableDefinition_Result }>;
  regardingobjectid_environmentvariablevalue: WebExpand<BulkDeleteFailure_Expand, EnvironmentVariableValue_Select, EnvironmentVariableValue_Filter, { regardingobjectid_environmentvariablevalue: EnvironmentVariableValue_Result }>;
  regardingobjectid_exportsolutionupload: WebExpand<BulkDeleteFailure_Expand, ExportSolutionUpload_Select, ExportSolutionUpload_Filter, { regardingobjectid_exportsolutionupload: ExportSolutionUpload_Result }>;
  regardingobjectid_fax: WebExpand<BulkDeleteFailure_Expand, Fax_Select, Fax_Filter, { regardingobjectid_fax: Fax_Result }>;
  regardingobjectid_featurecontrolsetting: WebExpand<BulkDeleteFailure_Expand, featurecontrolsetting_Select, featurecontrolsetting_Filter, { regardingobjectid_featurecontrolsetting: featurecontrolsetting_Result }>;
  regardingobjectid_fixedmonthlyfiscalcalendar: WebExpand<BulkDeleteFailure_Expand, FixedMonthlyFiscalCalendar_Select, FixedMonthlyFiscalCalendar_Filter, { regardingobjectid_fixedmonthlyfiscalcalendar: FixedMonthlyFiscalCalendar_Result }>;
  regardingobjectid_flowmachine: WebExpand<BulkDeleteFailure_Expand, flowmachine_Select, flowmachine_Filter, { regardingobjectid_flowmachine: flowmachine_Result }>;
  regardingobjectid_flowmachinegroup: WebExpand<BulkDeleteFailure_Expand, flowmachinegroup_Select, flowmachinegroup_Filter, { regardingobjectid_flowmachinegroup: flowmachinegroup_Result }>;
  regardingobjectid_flowsession: WebExpand<BulkDeleteFailure_Expand, flowsession_Select, flowsession_Filter, { regardingobjectid_flowsession: flowsession_Result }>;
  regardingobjectid_holidaywrapper: WebExpand<BulkDeleteFailure_Expand, holidaywrapper_Select, holidaywrapper_Filter, { regardingobjectid_holidaywrapper: holidaywrapper_Result }>;
  regardingobjectid_import: WebExpand<BulkDeleteFailure_Expand, Import_Select, Import_Filter, { regardingobjectid_import: Import_Result }>;
  regardingobjectid_importdata: WebExpand<BulkDeleteFailure_Expand, ImportData_Select, ImportData_Filter, { regardingobjectid_importdata: ImportData_Result }>;
  regardingobjectid_importfile: WebExpand<BulkDeleteFailure_Expand, ImportFile_Select, ImportFile_Filter, { regardingobjectid_importfile: ImportFile_Result }>;
  regardingobjectid_importlog: WebExpand<BulkDeleteFailure_Expand, ImportLog_Select, ImportLog_Filter, { regardingobjectid_importlog: ImportLog_Result }>;
  regardingobjectid_importmap: WebExpand<BulkDeleteFailure_Expand, ImportMap_Select, ImportMap_Filter, { regardingobjectid_importmap: ImportMap_Result }>;
  regardingobjectid_indexattributes: WebExpand<BulkDeleteFailure_Expand, IndexAttributes_Select, IndexAttributes_Filter, { regardingobjectid_indexattributes: IndexAttributes_Result }>;
  regardingobjectid_internalcatalogassignment: WebExpand<BulkDeleteFailure_Expand, InternalCatalogAssignment_Select, InternalCatalogAssignment_Filter, { regardingobjectid_internalcatalogassignment: InternalCatalogAssignment_Result }>;
  regardingobjectid_isvconfig: WebExpand<BulkDeleteFailure_Expand, IsvConfig_Select, IsvConfig_Filter, { regardingobjectid_isvconfig: IsvConfig_Result }>;
  regardingobjectid_kbarticle: WebExpand<BulkDeleteFailure_Expand, KbArticle_Select, KbArticle_Filter, { regardingobjectid_kbarticle: KbArticle_Result }>;
  regardingobjectid_kbarticlecomment: WebExpand<BulkDeleteFailure_Expand, KbArticleComment_Select, KbArticleComment_Filter, { regardingobjectid_kbarticlecomment: KbArticleComment_Result }>;
  regardingobjectid_kbarticletemplate: WebExpand<BulkDeleteFailure_Expand, KbArticleTemplate_Select, KbArticleTemplate_Filter, { regardingobjectid_kbarticletemplate: KbArticleTemplate_Result }>;
  regardingobjectid_keyvaultreference: WebExpand<BulkDeleteFailure_Expand, KeyVaultReference_Select, KeyVaultReference_Filter, { regardingobjectid_keyvaultreference: KeyVaultReference_Result }>;
  regardingobjectid_knowledgearticle: WebExpand<BulkDeleteFailure_Expand, KnowledgeArticle_Select, KnowledgeArticle_Filter, { regardingobjectid_knowledgearticle: KnowledgeArticle_Result }>;
  regardingobjectid_knowledgebaserecord: WebExpand<BulkDeleteFailure_Expand, KnowledgeBaseRecord_Select, KnowledgeBaseRecord_Filter, { regardingobjectid_knowledgebaserecord: KnowledgeBaseRecord_Result }>;
  regardingobjectid_letter: WebExpand<BulkDeleteFailure_Expand, Letter_Select, Letter_Filter, { regardingobjectid_letter: Letter_Result }>;
  regardingobjectid_managedidentity: WebExpand<BulkDeleteFailure_Expand, ManagedIdentity_Select, ManagedIdentity_Filter, { regardingobjectid_managedidentity: ManagedIdentity_Result }>;
  regardingobjectid_mbs_pluginprofile: WebExpand<BulkDeleteFailure_Expand, mbs_pluginprofile_Select, mbs_pluginprofile_Filter, { regardingobjectid_mbs_pluginprofile: mbs_pluginprofile_Result }>;
  regardingobjectid_monthlyfiscalcalendar: WebExpand<BulkDeleteFailure_Expand, MonthlyFiscalCalendar_Select, MonthlyFiscalCalendar_Filter, { regardingobjectid_monthlyfiscalcalendar: MonthlyFiscalCalendar_Result }>;
  regardingobjectid_msdyn_aibdataset: WebExpand<BulkDeleteFailure_Expand, msdyn_AIBDataset_Select, msdyn_AIBDataset_Filter, { regardingobjectid_msdyn_aibdataset: msdyn_AIBDataset_Result }>;
  regardingobjectid_msdyn_aibdatasetfile: WebExpand<BulkDeleteFailure_Expand, msdyn_AIBDatasetFile_Select, msdyn_AIBDatasetFile_Filter, { regardingobjectid_msdyn_aibdatasetfile: msdyn_AIBDatasetFile_Result }>;
  regardingobjectid_msdyn_aibdatasetrecord: WebExpand<BulkDeleteFailure_Expand, msdyn_AIBDatasetRecord_Select, msdyn_AIBDatasetRecord_Filter, { regardingobjectid_msdyn_aibdatasetrecord: msdyn_AIBDatasetRecord_Result }>;
  regardingobjectid_msdyn_aibdatasetscontainer: WebExpand<BulkDeleteFailure_Expand, msdyn_AIBDatasetsContainer_Select, msdyn_AIBDatasetsContainer_Filter, { regardingobjectid_msdyn_aibdatasetscontainer: msdyn_AIBDatasetsContainer_Result }>;
  regardingobjectid_msdyn_aibfile: WebExpand<BulkDeleteFailure_Expand, msdyn_AIBFile_Select, msdyn_AIBFile_Filter, { regardingobjectid_msdyn_aibfile: msdyn_AIBFile_Result }>;
  regardingobjectid_msdyn_aibfileattacheddata: WebExpand<BulkDeleteFailure_Expand, msdyn_AIBFileAttachedData_Select, msdyn_AIBFileAttachedData_Filter, { regardingobjectid_msdyn_aibfileattacheddata: msdyn_AIBFileAttachedData_Result }>;
  regardingobjectid_msdyn_aiconfiguration: WebExpand<BulkDeleteFailure_Expand, msdyn_AIConfiguration_Select, msdyn_AIConfiguration_Filter, { regardingobjectid_msdyn_aiconfiguration: msdyn_AIConfiguration_Result }>;
  regardingobjectid_msdyn_aifptrainingdocument: WebExpand<BulkDeleteFailure_Expand, msdyn_AIFpTrainingDocument_Select, msdyn_AIFpTrainingDocument_Filter, { regardingobjectid_msdyn_aifptrainingdocument: msdyn_AIFpTrainingDocument_Result }>;
  regardingobjectid_msdyn_aimodel: WebExpand<BulkDeleteFailure_Expand, msdyn_AIModel_Select, msdyn_AIModel_Filter, { regardingobjectid_msdyn_aimodel: msdyn_AIModel_Result }>;
  regardingobjectid_msdyn_aiodimage: WebExpand<BulkDeleteFailure_Expand, msdyn_AIOdImage_Select, msdyn_AIOdImage_Filter, { regardingobjectid_msdyn_aiodimage: msdyn_AIOdImage_Result }>;
  regardingobjectid_msdyn_aiodlabel: WebExpand<BulkDeleteFailure_Expand, msdyn_AIOdLabel_Select, msdyn_AIOdLabel_Filter, { regardingobjectid_msdyn_aiodlabel: msdyn_AIOdLabel_Result }>;
  regardingobjectid_msdyn_aiodtrainingboundingbox: WebExpand<BulkDeleteFailure_Expand, msdyn_AIOdTrainingBoundingBox_Select, msdyn_AIOdTrainingBoundingBox_Filter, { regardingobjectid_msdyn_aiodtrainingboundingbox: msdyn_AIOdTrainingBoundingBox_Result }>;
  regardingobjectid_msdyn_aiodtrainingimage: WebExpand<BulkDeleteFailure_Expand, msdyn_AIOdTrainingImage_Select, msdyn_AIOdTrainingImage_Filter, { regardingobjectid_msdyn_aiodtrainingimage: msdyn_AIOdTrainingImage_Result }>;
  regardingobjectid_msdyn_aitemplate: WebExpand<BulkDeleteFailure_Expand, msdyn_AITemplate_Select, msdyn_AITemplate_Filter, { regardingobjectid_msdyn_aitemplate: msdyn_AITemplate_Result }>;
  regardingobjectid_msdyn_analysiscomponent: WebExpand<BulkDeleteFailure_Expand, msdyn_analysiscomponent_Select, msdyn_analysiscomponent_Filter, { regardingobjectid_msdyn_analysiscomponent: msdyn_analysiscomponent_Result }>;
  regardingobjectid_msdyn_analysisjob: WebExpand<BulkDeleteFailure_Expand, msdyn_analysisjob_Select, msdyn_analysisjob_Filter, { regardingobjectid_msdyn_analysisjob: msdyn_analysisjob_Result }>;
  regardingobjectid_msdyn_analysisresult: WebExpand<BulkDeleteFailure_Expand, msdyn_analysisresult_Select, msdyn_analysisresult_Filter, { regardingobjectid_msdyn_analysisresult: msdyn_analysisresult_Result }>;
  regardingobjectid_msdyn_analysisresultdetail: WebExpand<BulkDeleteFailure_Expand, msdyn_analysisresultdetail_Select, msdyn_analysisresultdetail_Filter, { regardingobjectid_msdyn_analysisresultdetail: msdyn_analysisresultdetail_Result }>;
  regardingobjectid_msdyn_dataflow: WebExpand<BulkDeleteFailure_Expand, msdyn_dataflow_Select, msdyn_dataflow_Filter, { regardingobjectid_msdyn_dataflow: msdyn_dataflow_Result }>;
  regardingobjectid_msdyn_federatedarticle: WebExpand<BulkDeleteFailure_Expand, msdyn_federatedarticle_Select, msdyn_federatedarticle_Filter, { regardingobjectid_msdyn_federatedarticle: msdyn_federatedarticle_Result }>;
  regardingobjectid_msdyn_federatedarticleincident: WebExpand<BulkDeleteFailure_Expand, msdyn_federatedarticleincident_Select, msdyn_federatedarticleincident_Filter, { regardingobjectid_msdyn_federatedarticleincident: msdyn_federatedarticleincident_Result }>;
  regardingobjectid_msdyn_helppage: WebExpand<BulkDeleteFailure_Expand, msdyn_helppage_Select, msdyn_helppage_Filter, { regardingobjectid_msdyn_helppage: msdyn_helppage_Result }>;
  regardingobjectid_msdyn_kalanguagesetting: WebExpand<BulkDeleteFailure_Expand, msdyn_kalanguagesetting_Select, msdyn_kalanguagesetting_Filter, { regardingobjectid_msdyn_kalanguagesetting: msdyn_kalanguagesetting_Result }>;
  regardingobjectid_msdyn_kmfederatedsearchconfig: WebExpand<BulkDeleteFailure_Expand, msdyn_kmfederatedsearchconfig_Select, msdyn_kmfederatedsearchconfig_Filter, { regardingobjectid_msdyn_kmfederatedsearchconfig: msdyn_kmfederatedsearchconfig_Result }>;
  regardingobjectid_msdyn_kmpersonalizationsetting: WebExpand<BulkDeleteFailure_Expand, msdyn_kmpersonalizationsetting_Select, msdyn_kmpersonalizationsetting_Filter, { regardingobjectid_msdyn_kmpersonalizationsetting: msdyn_kmpersonalizationsetting_Result }>;
  regardingobjectid_msdyn_knowledgearticleimage: WebExpand<BulkDeleteFailure_Expand, msdyn_knowledgearticleimage_Select, msdyn_knowledgearticleimage_Filter, { regardingobjectid_msdyn_knowledgearticleimage: msdyn_knowledgearticleimage_Result }>;
  regardingobjectid_msdyn_knowledgearticletemplate: WebExpand<BulkDeleteFailure_Expand, msdyn_knowledgearticletemplate_Select, msdyn_knowledgearticletemplate_Filter, { regardingobjectid_msdyn_knowledgearticletemplate: msdyn_knowledgearticletemplate_Result }>;
  regardingobjectid_msdyn_knowledgeinteractioninsight: WebExpand<BulkDeleteFailure_Expand, msdyn_knowledgeinteractioninsight_Select, msdyn_knowledgeinteractioninsight_Filter, { regardingobjectid_msdyn_knowledgeinteractioninsight: msdyn_knowledgeinteractioninsight_Result }>;
  regardingobjectid_msdyn_knowledgepersonalfilter: WebExpand<BulkDeleteFailure_Expand, msdyn_knowledgepersonalfilter_Select, msdyn_knowledgepersonalfilter_Filter, { regardingobjectid_msdyn_knowledgepersonalfilter: msdyn_knowledgepersonalfilter_Result }>;
  regardingobjectid_msdyn_knowledgesearchfilter: WebExpand<BulkDeleteFailure_Expand, msdyn_knowledgesearchfilter_Select, msdyn_knowledgesearchfilter_Filter, { regardingobjectid_msdyn_knowledgesearchfilter: msdyn_knowledgesearchfilter_Result }>;
  regardingobjectid_msdyn_knowledgesearchinsight: WebExpand<BulkDeleteFailure_Expand, msdyn_knowledgesearchinsight_Select, msdyn_knowledgesearchinsight_Filter, { regardingobjectid_msdyn_knowledgesearchinsight: msdyn_knowledgesearchinsight_Result }>;
  regardingobjectid_msdyn_pminferredtask: WebExpand<BulkDeleteFailure_Expand, msdyn_pminferredtask_Select, msdyn_pminferredtask_Filter, { regardingobjectid_msdyn_pminferredtask: msdyn_pminferredtask_Result }>;
  regardingobjectid_msdyn_pmrecording: WebExpand<BulkDeleteFailure_Expand, msdyn_pmrecording_Select, msdyn_pmrecording_Filter, { regardingobjectid_msdyn_pmrecording: msdyn_pmrecording_Result }>;
  regardingobjectid_msdyn_richtextfile: WebExpand<BulkDeleteFailure_Expand, msdyn_richtextfile_Select, msdyn_richtextfile_Filter, { regardingobjectid_msdyn_richtextfile: msdyn_richtextfile_Result }>;
  regardingobjectid_msdyn_serviceconfiguration: WebExpand<BulkDeleteFailure_Expand, msdyn_serviceconfiguration_Select, msdyn_serviceconfiguration_Filter, { regardingobjectid_msdyn_serviceconfiguration: msdyn_serviceconfiguration_Result }>;
  regardingobjectid_msdyn_slakpi: WebExpand<BulkDeleteFailure_Expand, msdyn_slakpi_Select, msdyn_slakpi_Filter, { regardingobjectid_msdyn_slakpi: msdyn_slakpi_Result }>;
  regardingobjectid_msdyn_solutionhealthrule: WebExpand<BulkDeleteFailure_Expand, msdyn_solutionhealthrule_Select, msdyn_solutionhealthrule_Filter, { regardingobjectid_msdyn_solutionhealthrule: msdyn_solutionhealthrule_Result }>;
  regardingobjectid_msdyn_solutionhealthruleargument: WebExpand<BulkDeleteFailure_Expand, msdyn_solutionhealthruleargument_Select, msdyn_solutionhealthruleargument_Filter, { regardingobjectid_msdyn_solutionhealthruleargument: msdyn_solutionhealthruleargument_Result }>;
  regardingobjectid_msdyn_solutionhealthruleset: WebExpand<BulkDeleteFailure_Expand, msdyn_solutionhealthruleset_Select, msdyn_solutionhealthruleset_Filter, { regardingobjectid_msdyn_solutionhealthruleset: msdyn_solutionhealthruleset_Result }>;
  regardingobjectid_msdyn_tour: WebExpand<BulkDeleteFailure_Expand, msdyn_tour_Select, msdyn_tour_Filter, { regardingobjectid_msdyn_tour: msdyn_tour_Result }>;
  regardingobjectid_msdynce_botcontent: WebExpand<BulkDeleteFailure_Expand, msdynce_botcontent_Select, msdynce_botcontent_Filter, { regardingobjectid_msdynce_botcontent: msdynce_botcontent_Result }>;
  regardingobjectid_organization: WebExpand<BulkDeleteFailure_Expand, Organization_Select, Organization_Filter, { regardingobjectid_organization: Organization_Result }>;
  regardingobjectid_organizationdatasyncsubscription: WebExpand<BulkDeleteFailure_Expand, organizationdatasyncsubscription_Select, organizationdatasyncsubscription_Filter, { regardingobjectid_organizationdatasyncsubscription: organizationdatasyncsubscription_Result }>;
  regardingobjectid_organizationdatasyncsubscriptionentity: WebExpand<BulkDeleteFailure_Expand, organizationdatasyncsubscriptionentity_Select, organizationdatasyncsubscriptionentity_Filter, { regardingobjectid_organizationdatasyncsubscriptionentity: organizationdatasyncsubscriptionentity_Result }>;
  regardingobjectid_organizationsetting: WebExpand<BulkDeleteFailure_Expand, OrganizationSetting_Select, OrganizationSetting_Filter, { regardingobjectid_organizationsetting: OrganizationSetting_Result }>;
  regardingobjectid_package: WebExpand<BulkDeleteFailure_Expand, package_Select, package_Filter, { regardingobjectid_package: package_Result }>;
  regardingobjectid_pc_bankaccount: WebExpand<BulkDeleteFailure_Expand, pc_BankAccount_Select, pc_BankAccount_Filter, { regardingobjectid_pc_bankaccount: pc_BankAccount_Result }>;
  regardingobjectid_pc_participation: WebExpand<BulkDeleteFailure_Expand, pc_Participation_Select, pc_Participation_Filter, { regardingobjectid_pc_participation: pc_Participation_Result }>;
  regardingobjectid_pc_participationfeeexemption: WebExpand<BulkDeleteFailure_Expand, pc_ParticipationFeeExemption_Select, pc_ParticipationFeeExemption_Filter, { regardingobjectid_pc_participationfeeexemption: pc_ParticipationFeeExemption_Result }>;
  regardingobjectid_pc_payment: WebExpand<BulkDeleteFailure_Expand, pc_Payment_Select, pc_Payment_Filter, { regardingobjectid_pc_payment: pc_Payment_Result }>;
  regardingobjectid_pc_scheduledjob: WebExpand<BulkDeleteFailure_Expand, pc_ScheduledJob_Select, pc_ScheduledJob_Filter, { regardingobjectid_pc_scheduledjob: pc_ScheduledJob_Result }>;
  regardingobjectid_pc_settings: WebExpand<BulkDeleteFailure_Expand, pc_Settings_Select, pc_Settings_Filter, { regardingobjectid_pc_settings: pc_Settings_Result }>;
  regardingobjectid_pc_transaction: WebExpand<BulkDeleteFailure_Expand, pc_Transaction_Select, pc_Transaction_Filter, { regardingobjectid_pc_transaction: pc_Transaction_Result }>;
  regardingobjectid_pdfsetting: WebExpand<BulkDeleteFailure_Expand, PDFSetting_Select, PDFSetting_Filter, { regardingobjectid_pdfsetting: PDFSetting_Result }>;
  regardingobjectid_phonecall: WebExpand<BulkDeleteFailure_Expand, PhoneCall_Select, PhoneCall_Filter, { regardingobjectid_phonecall: PhoneCall_Result }>;
  regardingobjectid_pluginpackage: WebExpand<BulkDeleteFailure_Expand, pluginpackage_Select, pluginpackage_Filter, { regardingobjectid_pluginpackage: pluginpackage_Result }>;
  regardingobjectid_post: WebExpand<BulkDeleteFailure_Expand, Post_Select, Post_Filter, { regardingobjectid_post: Post_Result }>;
  regardingobjectid_privilege: WebExpand<BulkDeleteFailure_Expand, Privilege_Select, Privilege_Filter, { regardingobjectid_privilege: Privilege_Result }>;
  regardingobjectid_processstageparameter: WebExpand<BulkDeleteFailure_Expand, processstageparameter_Select, processstageparameter_Filter, { regardingobjectid_processstageparameter: processstageparameter_Result }>;
  regardingobjectid_provisionlanguageforuser: WebExpand<BulkDeleteFailure_Expand, ProvisionLanguageForUser_Select, ProvisionLanguageForUser_Filter, { regardingobjectid_provisionlanguageforuser: ProvisionLanguageForUser_Result }>;
  regardingobjectid_quarterlyfiscalcalendar: WebExpand<BulkDeleteFailure_Expand, QuarterlyFiscalCalendar_Select, QuarterlyFiscalCalendar_Filter, { regardingobjectid_quarterlyfiscalcalendar: QuarterlyFiscalCalendar_Result }>;
  regardingobjectid_queue: WebExpand<BulkDeleteFailure_Expand, Queue_Select, Queue_Filter, { regardingobjectid_queue: Queue_Result }>;
  regardingobjectid_queueitem: WebExpand<BulkDeleteFailure_Expand, QueueItem_Select, QueueItem_Filter, { regardingobjectid_queueitem: QueueItem_Result }>;
  regardingobjectid_recurringappointmentmaster: WebExpand<BulkDeleteFailure_Expand, RecurringAppointmentMaster_Select, RecurringAppointmentMaster_Filter, { regardingobjectid_recurringappointmentmaster: RecurringAppointmentMaster_Result }>;
  regardingobjectid_relationshipattribute: WebExpand<BulkDeleteFailure_Expand, RelationshipAttribute_Select, RelationshipAttribute_Filter, { regardingobjectid_relationshipattribute: RelationshipAttribute_Result }>;
  regardingobjectid_relationshiprole: WebExpand<BulkDeleteFailure_Expand, RelationshipRole_Select, RelationshipRole_Filter, { regardingobjectid_relationshiprole: RelationshipRole_Result }>;
  regardingobjectid_relationshiprolemap: WebExpand<BulkDeleteFailure_Expand, RelationshipRoleMap_Select, RelationshipRoleMap_Filter, { regardingobjectid_relationshiprolemap: RelationshipRoleMap_Result }>;
  regardingobjectid_revokeinheritedaccessrecordstracker: WebExpand<BulkDeleteFailure_Expand, revokeinheritedaccessrecordstracker_Select, revokeinheritedaccessrecordstracker_Filter, { regardingobjectid_revokeinheritedaccessrecordstracker: revokeinheritedaccessrecordstracker_Result }>;
  regardingobjectid_role: WebExpand<BulkDeleteFailure_Expand, Role_Select, Role_Filter, { regardingobjectid_role: Role_Result }>;
  regardingobjectid_routingrule: WebExpand<BulkDeleteFailure_Expand, RoutingRule_Select, RoutingRule_Filter, { regardingobjectid_routingrule: RoutingRule_Result }>;
  regardingobjectid_routingruleitem: WebExpand<BulkDeleteFailure_Expand, RoutingRuleItem_Select, RoutingRuleItem_Filter, { regardingobjectid_routingruleitem: RoutingRuleItem_Result }>;
  regardingobjectid_savedquery: WebExpand<BulkDeleteFailure_Expand, SavedQuery_Select, SavedQuery_Filter, { regardingobjectid_savedquery: SavedQuery_Result }>;
  regardingobjectid_semiannualfiscalcalendar: WebExpand<BulkDeleteFailure_Expand, SemiAnnualFiscalCalendar_Select, SemiAnnualFiscalCalendar_Filter, { regardingobjectid_semiannualfiscalcalendar: SemiAnnualFiscalCalendar_Result }>;
  regardingobjectid_serviceplan: WebExpand<BulkDeleteFailure_Expand, ServicePlan_Select, ServicePlan_Filter, { regardingobjectid_serviceplan: ServicePlan_Result }>;
  regardingobjectid_serviceplanmapping: WebExpand<BulkDeleteFailure_Expand, ServicePlanMapping_Select, ServicePlanMapping_Filter, { regardingobjectid_serviceplanmapping: ServicePlanMapping_Result }>;
  regardingobjectid_settingdefinition: WebExpand<BulkDeleteFailure_Expand, SettingDefinition_Select, SettingDefinition_Filter, { regardingobjectid_settingdefinition: SettingDefinition_Result }>;
  regardingobjectid_sla: WebExpand<BulkDeleteFailure_Expand, SLA_Select, SLA_Filter, { regardingobjectid_sla: SLA_Result }>;
  regardingobjectid_socialactivity: WebExpand<BulkDeleteFailure_Expand, SocialActivity_Select, SocialActivity_Filter, { regardingobjectid_socialactivity: SocialActivity_Result }>;
  regardingobjectid_solutioncomponentattributeconfiguration: WebExpand<BulkDeleteFailure_Expand, solutioncomponentattributeconfiguration_Select, solutioncomponentattributeconfiguration_Filter, { regardingobjectid_solutioncomponentattributeconfiguration: solutioncomponentattributeconfiguration_Result }>;
  regardingobjectid_solutioncomponentbatchconfiguration: WebExpand<BulkDeleteFailure_Expand, solutioncomponentbatchconfiguration_Select, solutioncomponentbatchconfiguration_Filter, { regardingobjectid_solutioncomponentbatchconfiguration: solutioncomponentbatchconfiguration_Result }>;
  regardingobjectid_solutioncomponentconfiguration: WebExpand<BulkDeleteFailure_Expand, solutioncomponentconfiguration_Select, solutioncomponentconfiguration_Filter, { regardingobjectid_solutioncomponentconfiguration: solutioncomponentconfiguration_Result }>;
  regardingobjectid_solutioncomponentrelationshipconfiguration: WebExpand<BulkDeleteFailure_Expand, solutioncomponentrelationshipconfiguration_Select, solutioncomponentrelationshipconfiguration_Filter, { regardingobjectid_solutioncomponentrelationshipconfiguration: solutioncomponentrelationshipconfiguration_Result }>;
  regardingobjectid_stagesolutionupload: WebExpand<BulkDeleteFailure_Expand, StageSolutionUpload_Select, StageSolutionUpload_Filter, { regardingobjectid_stagesolutionupload: StageSolutionUpload_Result }>;
  regardingobjectid_subject: WebExpand<BulkDeleteFailure_Expand, Subject_Select, Subject_Filter, { regardingobjectid_subject: Subject_Result }>;
  regardingobjectid_systemform: WebExpand<BulkDeleteFailure_Expand, SystemForm_Select, SystemForm_Filter, { regardingobjectid_systemform: SystemForm_Result }>;
  regardingobjectid_systemuser: WebExpand<BulkDeleteFailure_Expand, SystemUser_Select, SystemUser_Filter, { regardingobjectid_systemuser: SystemUser_Result }>;
  regardingobjectid_systemuserauthorizationchangetracker: WebExpand<BulkDeleteFailure_Expand, SystemUserAuthorizationChangeTracker_Select, SystemUserAuthorizationChangeTracker_Filter, { regardingobjectid_systemuserauthorizationchangetracker: SystemUserAuthorizationChangeTracker_Result }>;
  regardingobjectid_task: WebExpand<BulkDeleteFailure_Expand, Task_Select, Task_Filter, { regardingobjectid_task: Task_Result }>;
  regardingobjectid_team: WebExpand<BulkDeleteFailure_Expand, Team_Select, Team_Filter, { regardingobjectid_team: Team_Result }>;
  regardingobjectid_teammobileofflineprofilemembership: WebExpand<BulkDeleteFailure_Expand, teammobileofflineprofilemembership_Select, teammobileofflineprofilemembership_Filter, { regardingobjectid_teammobileofflineprofilemembership: teammobileofflineprofilemembership_Result }>;
  regardingobjectid_template: WebExpand<BulkDeleteFailure_Expand, Template_Select, Template_Filter, { regardingobjectid_template: Template_Result }>;
  regardingobjectid_territory: WebExpand<BulkDeleteFailure_Expand, Territory_Select, Territory_Filter, { regardingobjectid_territory: Territory_Result }>;
  regardingobjectid_theme: WebExpand<BulkDeleteFailure_Expand, Theme_Select, Theme_Filter, { regardingobjectid_theme: Theme_Result }>;
  regardingobjectid_userform: WebExpand<BulkDeleteFailure_Expand, UserForm_Select, UserForm_Filter, { regardingobjectid_userform: UserForm_Result }>;
  regardingobjectid_usermapping: WebExpand<BulkDeleteFailure_Expand, UserMapping_Select, UserMapping_Filter, { regardingobjectid_usermapping: UserMapping_Result }>;
  regardingobjectid_usermobileofflineprofilemembership: WebExpand<BulkDeleteFailure_Expand, usermobileofflineprofilemembership_Select, usermobileofflineprofilemembership_Filter, { regardingobjectid_usermobileofflineprofilemembership: usermobileofflineprofilemembership_Result }>;
  regardingobjectid_userquery: WebExpand<BulkDeleteFailure_Expand, UserQuery_Select, UserQuery_Filter, { regardingobjectid_userquery: UserQuery_Result }>;
  regardingobjectid_virtualentitymetadata: WebExpand<BulkDeleteFailure_Expand, VirtualEntityMetadata_Select, VirtualEntityMetadata_Filter, { regardingobjectid_virtualentitymetadata: VirtualEntityMetadata_Result }>;
  regardingobjectid_workflowbinary: WebExpand<BulkDeleteFailure_Expand, workflowbinary_Select, workflowbinary_Filter, { regardingobjectid_workflowbinary: workflowbinary_Result }>;
  userentityinstancedata_bulkdeletefailure: WebExpand<BulkDeleteFailure_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { userentityinstancedata_bulkdeletefailure: UserEntityInstanceData_Result[] }>;
}
interface BulkDeleteFailure_FormattedResult {
  asyncoperationid_formatted?: string;
  bulkdeleteoperationid_formatted?: string;
  ownerid_formatted?: string;
  regardingobjectid_formatted?: string;
}
interface BulkDeleteFailure_Result extends BulkDeleteFailure_Base, BulkDeleteFailure_Relationships {
  "@odata.etag": string;
  asyncoperationid_guid: string | null;
  bulkdeleteoperationid_guid: string | null;
  ownerid_guid: string | null;
  regardingobjectid_guid: string | null;
}
interface BulkDeleteFailure_RelatedOne {
  bulkdeleteoperationid: WebMappingRetrieve<BulkDeleteOperation_Select,BulkDeleteOperation_Expand,BulkDeleteOperation_Filter,BulkDeleteOperation_Fixed,BulkDeleteOperation_Result,BulkDeleteOperation_FormattedResult>;
  channelaccessprofile_bulkdeletefailures: WebMappingRetrieve<ChannelAccessProfile_Select,ChannelAccessProfile_Expand,ChannelAccessProfile_Filter,ChannelAccessProfile_Fixed,ChannelAccessProfile_Result,ChannelAccessProfile_FormattedResult>;
  channelaccessprofileruleid: WebMappingRetrieve<ChannelAccessProfileRule_Select,ChannelAccessProfileRule_Expand,ChannelAccessProfileRule_Filter,ChannelAccessProfileRule_Fixed,ChannelAccessProfileRule_Result,ChannelAccessProfileRule_FormattedResult>;
  externalparty_bulkdeletefailures: WebMappingRetrieve<ExternalParty_Select,ExternalParty_Expand,ExternalParty_Filter,ExternalParty_Fixed,ExternalParty_Result,ExternalParty_FormattedResult>;
  externalpartyitem_bulkdeletefailures: WebMappingRetrieve<ExternalPartyItem_Select,ExternalPartyItem_Expand,ExternalPartyItem_Filter,ExternalPartyItem_Fixed,ExternalPartyItem_Result,ExternalPartyItem_FormattedResult>;
  regardingobjectid_account: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  regardingobjectid_activityfileattachment: WebMappingRetrieve<activityfileattachment_Select,activityfileattachment_Expand,activityfileattachment_Filter,activityfileattachment_Fixed,activityfileattachment_Result,activityfileattachment_FormattedResult>;
  regardingobjectid_activitymimeattachment: WebMappingRetrieve<ActivityMimeAttachment_Select,ActivityMimeAttachment_Expand,ActivityMimeAttachment_Filter,ActivityMimeAttachment_Fixed,ActivityMimeAttachment_Result,ActivityMimeAttachment_FormattedResult>;
  regardingobjectid_activitypointer: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  regardingobjectid_annotation: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  regardingobjectid_annualfiscalcalendar: WebMappingRetrieve<AnnualFiscalCalendar_Select,AnnualFiscalCalendar_Expand,AnnualFiscalCalendar_Filter,AnnualFiscalCalendar_Fixed,AnnualFiscalCalendar_Result,AnnualFiscalCalendar_FormattedResult>;
  regardingobjectid_appaction: WebMappingRetrieve<appaction_Select,appaction_Expand,appaction_Filter,appaction_Fixed,appaction_Result,appaction_FormattedResult>;
  regardingobjectid_appelement: WebMappingRetrieve<AppElement_Select,AppElement_Expand,AppElement_Filter,AppElement_Fixed,AppElement_Result,AppElement_FormattedResult>;
  regardingobjectid_applicationuser: WebMappingRetrieve<ApplicationUser_Select,ApplicationUser_Expand,ApplicationUser_Filter,ApplicationUser_Fixed,ApplicationUser_Result,ApplicationUser_FormattedResult>;
  regardingobjectid_appmodulecomponentedge: WebMappingRetrieve<AppModuleComponentEdge_Select,AppModuleComponentEdge_Expand,AppModuleComponentEdge_Filter,AppModuleComponentEdge_Fixed,AppModuleComponentEdge_Result,AppModuleComponentEdge_FormattedResult>;
  regardingobjectid_appmodulecomponentnode: WebMappingRetrieve<AppModuleComponentNode_Select,AppModuleComponentNode_Expand,AppModuleComponentNode_Filter,AppModuleComponentNode_Fixed,AppModuleComponentNode_Result,AppModuleComponentNode_FormattedResult>;
  regardingobjectid_appointment: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
  regardingobjectid_appsetting: WebMappingRetrieve<AppSetting_Select,AppSetting_Expand,AppSetting_Filter,AppSetting_Fixed,AppSetting_Result,AppSetting_FormattedResult>;
  regardingobjectid_appusersetting: WebMappingRetrieve<AppUserSetting_Select,AppUserSetting_Expand,AppUserSetting_Filter,AppUserSetting_Fixed,AppUserSetting_Result,AppUserSetting_FormattedResult>;
  regardingobjectid_attributeimageconfig: WebMappingRetrieve<AttributeImageConfig_Select,AttributeImageConfig_Expand,AttributeImageConfig_Filter,AttributeImageConfig_Fixed,AttributeImageConfig_Result,AttributeImageConfig_FormattedResult>;
  regardingobjectid_attributemap: WebMappingRetrieve<AttributeMap_Select,AttributeMap_Expand,AttributeMap_Filter,AttributeMap_Fixed,AttributeMap_Result,AttributeMap_FormattedResult>;
  regardingobjectid_bot: WebMappingRetrieve<bot_Select,bot_Expand,bot_Filter,bot_Fixed,bot_Result,bot_FormattedResult>;
  regardingobjectid_botcomponent: WebMappingRetrieve<botcomponent_Select,botcomponent_Expand,botcomponent_Filter,botcomponent_Fixed,botcomponent_Result,botcomponent_FormattedResult>;
  regardingobjectid_businessunit: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  regardingobjectid_businessunitnewsarticle: WebMappingRetrieve<BusinessUnitNewsArticle_Select,BusinessUnitNewsArticle_Expand,BusinessUnitNewsArticle_Filter,BusinessUnitNewsArticle_Fixed,BusinessUnitNewsArticle_Result,BusinessUnitNewsArticle_FormattedResult>;
  regardingobjectid_calendar: WebMappingRetrieve<Calendar_Select,Calendar_Expand,Calendar_Filter,Calendar_Fixed,Calendar_Result,Calendar_FormattedResult>;
  regardingobjectid_canvasappextendedmetadata: WebMappingRetrieve<CanvasAppExtendedMetadata_Select,CanvasAppExtendedMetadata_Expand,CanvasAppExtendedMetadata_Filter,CanvasAppExtendedMetadata_Fixed,CanvasAppExtendedMetadata_Result,CanvasAppExtendedMetadata_FormattedResult>;
  regardingobjectid_cascadegrantrevokeaccessrecordstracker: WebMappingRetrieve<cascadegrantrevokeaccessrecordstracker_Select,cascadegrantrevokeaccessrecordstracker_Expand,cascadegrantrevokeaccessrecordstracker_Filter,cascadegrantrevokeaccessrecordstracker_Fixed,cascadegrantrevokeaccessrecordstracker_Result,cascadegrantrevokeaccessrecordstracker_FormattedResult>;
  regardingobjectid_cascadegrantrevokeaccessversiontracker: WebMappingRetrieve<cascadegrantrevokeaccessversiontracker_Select,cascadegrantrevokeaccessversiontracker_Expand,cascadegrantrevokeaccessversiontracker_Filter,cascadegrantrevokeaccessversiontracker_Fixed,cascadegrantrevokeaccessversiontracker_Result,cascadegrantrevokeaccessversiontracker_FormattedResult>;
  regardingobjectid_catalog: WebMappingRetrieve<Catalog_Select,Catalog_Expand,Catalog_Filter,Catalog_Fixed,Catalog_Result,Catalog_FormattedResult>;
  regardingobjectid_catalogassignment: WebMappingRetrieve<CatalogAssignment_Select,CatalogAssignment_Expand,CatalogAssignment_Filter,CatalogAssignment_Fixed,CatalogAssignment_Result,CatalogAssignment_FormattedResult>;
  regardingobjectid_connectionreference: WebMappingRetrieve<connectionreference_Select,connectionreference_Expand,connectionreference_Filter,connectionreference_Fixed,connectionreference_Result,connectionreference_FormattedResult>;
  regardingobjectid_connector: WebMappingRetrieve<connector_Select,connector_Expand,connector_Filter,connector_Fixed,connector_Result,connector_FormattedResult>;
  regardingobjectid_contact: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  regardingobjectid_conversationtranscript: WebMappingRetrieve<conversationtranscript_Select,conversationtranscript_Expand,conversationtranscript_Filter,conversationtranscript_Fixed,conversationtranscript_Result,conversationtranscript_FormattedResult>;
  regardingobjectid_customapi: WebMappingRetrieve<CustomAPI_Select,CustomAPI_Expand,CustomAPI_Filter,CustomAPI_Fixed,CustomAPI_Result,CustomAPI_FormattedResult>;
  regardingobjectid_customapirequestparameter: WebMappingRetrieve<CustomAPIRequestParameter_Select,CustomAPIRequestParameter_Expand,CustomAPIRequestParameter_Filter,CustomAPIRequestParameter_Fixed,CustomAPIRequestParameter_Result,CustomAPIRequestParameter_FormattedResult>;
  regardingobjectid_customapiresponseproperty: WebMappingRetrieve<CustomAPIResponseProperty_Select,CustomAPIResponseProperty_Expand,CustomAPIResponseProperty_Filter,CustomAPIResponseProperty_Fixed,CustomAPIResponseProperty_Result,CustomAPIResponseProperty_FormattedResult>;
  regardingobjectid_customeraddress: WebMappingRetrieve<CustomerAddress_Select,CustomerAddress_Expand,CustomerAddress_Filter,CustomerAddress_Fixed,CustomerAddress_Result,CustomerAddress_FormattedResult>;
  regardingobjectid_customerrelationship: WebMappingRetrieve<CustomerRelationship_Select,CustomerRelationship_Expand,CustomerRelationship_Filter,CustomerRelationship_Fixed,CustomerRelationship_Result,CustomerRelationship_FormattedResult>;
  regardingobjectid_datalakefolder: WebMappingRetrieve<datalakefolder_Select,datalakefolder_Expand,datalakefolder_Filter,datalakefolder_Fixed,datalakefolder_Result,datalakefolder_FormattedResult>;
  regardingobjectid_datalakefolderpermission: WebMappingRetrieve<datalakefolderpermission_Select,datalakefolderpermission_Expand,datalakefolderpermission_Filter,datalakefolderpermission_Fixed,datalakefolderpermission_Result,datalakefolderpermission_FormattedResult>;
  regardingobjectid_datalakeworkspace: WebMappingRetrieve<datalakeworkspace_Select,datalakeworkspace_Expand,datalakeworkspace_Filter,datalakeworkspace_Fixed,datalakeworkspace_Result,datalakeworkspace_FormattedResult>;
  regardingobjectid_datalakeworkspacepermission: WebMappingRetrieve<datalakeworkspacepermission_Select,datalakeworkspacepermission_Expand,datalakeworkspacepermission_Filter,datalakeworkspacepermission_Fixed,datalakeworkspacepermission_Result,datalakeworkspacepermission_FormattedResult>;
  regardingobjectid_displaystring: WebMappingRetrieve<DisplayString_Select,DisplayString_Expand,DisplayString_Filter,DisplayString_Fixed,DisplayString_Result,DisplayString_FormattedResult>;
  regardingobjectid_email: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  regardingobjectid_emailserverprofile: WebMappingRetrieve<EmailServerProfile_Select,EmailServerProfile_Expand,EmailServerProfile_Filter,EmailServerProfile_Fixed,EmailServerProfile_Result,EmailServerProfile_FormattedResult>;
  regardingobjectid_entityanalyticsconfig: WebMappingRetrieve<EntityAnalyticsConfig_Select,EntityAnalyticsConfig_Expand,EntityAnalyticsConfig_Filter,EntityAnalyticsConfig_Fixed,EntityAnalyticsConfig_Result,EntityAnalyticsConfig_FormattedResult>;
  regardingobjectid_entityimageconfig: WebMappingRetrieve<EntityImageConfig_Select,EntityImageConfig_Expand,EntityImageConfig_Filter,EntityImageConfig_Fixed,EntityImageConfig_Result,EntityImageConfig_FormattedResult>;
  regardingobjectid_entityindex: WebMappingRetrieve<EntityIndex_Select,EntityIndex_Expand,EntityIndex_Filter,EntityIndex_Fixed,EntityIndex_Result,EntityIndex_FormattedResult>;
  regardingobjectid_entitymap: WebMappingRetrieve<EntityMap_Select,EntityMap_Expand,EntityMap_Filter,EntityMap_Fixed,EntityMap_Result,EntityMap_FormattedResult>;
  regardingobjectid_environmentvariabledefinition: WebMappingRetrieve<EnvironmentVariableDefinition_Select,EnvironmentVariableDefinition_Expand,EnvironmentVariableDefinition_Filter,EnvironmentVariableDefinition_Fixed,EnvironmentVariableDefinition_Result,EnvironmentVariableDefinition_FormattedResult>;
  regardingobjectid_environmentvariablevalue: WebMappingRetrieve<EnvironmentVariableValue_Select,EnvironmentVariableValue_Expand,EnvironmentVariableValue_Filter,EnvironmentVariableValue_Fixed,EnvironmentVariableValue_Result,EnvironmentVariableValue_FormattedResult>;
  regardingobjectid_exportsolutionupload: WebMappingRetrieve<ExportSolutionUpload_Select,ExportSolutionUpload_Expand,ExportSolutionUpload_Filter,ExportSolutionUpload_Fixed,ExportSolutionUpload_Result,ExportSolutionUpload_FormattedResult>;
  regardingobjectid_fax: WebMappingRetrieve<Fax_Select,Fax_Expand,Fax_Filter,Fax_Fixed,Fax_Result,Fax_FormattedResult>;
  regardingobjectid_featurecontrolsetting: WebMappingRetrieve<featurecontrolsetting_Select,featurecontrolsetting_Expand,featurecontrolsetting_Filter,featurecontrolsetting_Fixed,featurecontrolsetting_Result,featurecontrolsetting_FormattedResult>;
  regardingobjectid_fixedmonthlyfiscalcalendar: WebMappingRetrieve<FixedMonthlyFiscalCalendar_Select,FixedMonthlyFiscalCalendar_Expand,FixedMonthlyFiscalCalendar_Filter,FixedMonthlyFiscalCalendar_Fixed,FixedMonthlyFiscalCalendar_Result,FixedMonthlyFiscalCalendar_FormattedResult>;
  regardingobjectid_flowmachine: WebMappingRetrieve<flowmachine_Select,flowmachine_Expand,flowmachine_Filter,flowmachine_Fixed,flowmachine_Result,flowmachine_FormattedResult>;
  regardingobjectid_flowmachinegroup: WebMappingRetrieve<flowmachinegroup_Select,flowmachinegroup_Expand,flowmachinegroup_Filter,flowmachinegroup_Fixed,flowmachinegroup_Result,flowmachinegroup_FormattedResult>;
  regardingobjectid_flowsession: WebMappingRetrieve<flowsession_Select,flowsession_Expand,flowsession_Filter,flowsession_Fixed,flowsession_Result,flowsession_FormattedResult>;
  regardingobjectid_holidaywrapper: WebMappingRetrieve<holidaywrapper_Select,holidaywrapper_Expand,holidaywrapper_Filter,holidaywrapper_Fixed,holidaywrapper_Result,holidaywrapper_FormattedResult>;
  regardingobjectid_import: WebMappingRetrieve<Import_Select,Import_Expand,Import_Filter,Import_Fixed,Import_Result,Import_FormattedResult>;
  regardingobjectid_importdata: WebMappingRetrieve<ImportData_Select,ImportData_Expand,ImportData_Filter,ImportData_Fixed,ImportData_Result,ImportData_FormattedResult>;
  regardingobjectid_importfile: WebMappingRetrieve<ImportFile_Select,ImportFile_Expand,ImportFile_Filter,ImportFile_Fixed,ImportFile_Result,ImportFile_FormattedResult>;
  regardingobjectid_importlog: WebMappingRetrieve<ImportLog_Select,ImportLog_Expand,ImportLog_Filter,ImportLog_Fixed,ImportLog_Result,ImportLog_FormattedResult>;
  regardingobjectid_importmap: WebMappingRetrieve<ImportMap_Select,ImportMap_Expand,ImportMap_Filter,ImportMap_Fixed,ImportMap_Result,ImportMap_FormattedResult>;
  regardingobjectid_indexattributes: WebMappingRetrieve<IndexAttributes_Select,IndexAttributes_Expand,IndexAttributes_Filter,IndexAttributes_Fixed,IndexAttributes_Result,IndexAttributes_FormattedResult>;
  regardingobjectid_internalcatalogassignment: WebMappingRetrieve<InternalCatalogAssignment_Select,InternalCatalogAssignment_Expand,InternalCatalogAssignment_Filter,InternalCatalogAssignment_Fixed,InternalCatalogAssignment_Result,InternalCatalogAssignment_FormattedResult>;
  regardingobjectid_isvconfig: WebMappingRetrieve<IsvConfig_Select,IsvConfig_Expand,IsvConfig_Filter,IsvConfig_Fixed,IsvConfig_Result,IsvConfig_FormattedResult>;
  regardingobjectid_kbarticle: WebMappingRetrieve<KbArticle_Select,KbArticle_Expand,KbArticle_Filter,KbArticle_Fixed,KbArticle_Result,KbArticle_FormattedResult>;
  regardingobjectid_kbarticlecomment: WebMappingRetrieve<KbArticleComment_Select,KbArticleComment_Expand,KbArticleComment_Filter,KbArticleComment_Fixed,KbArticleComment_Result,KbArticleComment_FormattedResult>;
  regardingobjectid_kbarticletemplate: WebMappingRetrieve<KbArticleTemplate_Select,KbArticleTemplate_Expand,KbArticleTemplate_Filter,KbArticleTemplate_Fixed,KbArticleTemplate_Result,KbArticleTemplate_FormattedResult>;
  regardingobjectid_keyvaultreference: WebMappingRetrieve<KeyVaultReference_Select,KeyVaultReference_Expand,KeyVaultReference_Filter,KeyVaultReference_Fixed,KeyVaultReference_Result,KeyVaultReference_FormattedResult>;
  regardingobjectid_knowledgearticle: WebMappingRetrieve<KnowledgeArticle_Select,KnowledgeArticle_Expand,KnowledgeArticle_Filter,KnowledgeArticle_Fixed,KnowledgeArticle_Result,KnowledgeArticle_FormattedResult>;
  regardingobjectid_knowledgebaserecord: WebMappingRetrieve<KnowledgeBaseRecord_Select,KnowledgeBaseRecord_Expand,KnowledgeBaseRecord_Filter,KnowledgeBaseRecord_Fixed,KnowledgeBaseRecord_Result,KnowledgeBaseRecord_FormattedResult>;
  regardingobjectid_letter: WebMappingRetrieve<Letter_Select,Letter_Expand,Letter_Filter,Letter_Fixed,Letter_Result,Letter_FormattedResult>;
  regardingobjectid_managedidentity: WebMappingRetrieve<ManagedIdentity_Select,ManagedIdentity_Expand,ManagedIdentity_Filter,ManagedIdentity_Fixed,ManagedIdentity_Result,ManagedIdentity_FormattedResult>;
  regardingobjectid_mbs_pluginprofile: WebMappingRetrieve<mbs_pluginprofile_Select,mbs_pluginprofile_Expand,mbs_pluginprofile_Filter,mbs_pluginprofile_Fixed,mbs_pluginprofile_Result,mbs_pluginprofile_FormattedResult>;
  regardingobjectid_monthlyfiscalcalendar: WebMappingRetrieve<MonthlyFiscalCalendar_Select,MonthlyFiscalCalendar_Expand,MonthlyFiscalCalendar_Filter,MonthlyFiscalCalendar_Fixed,MonthlyFiscalCalendar_Result,MonthlyFiscalCalendar_FormattedResult>;
  regardingobjectid_msdyn_aibdataset: WebMappingRetrieve<msdyn_AIBDataset_Select,msdyn_AIBDataset_Expand,msdyn_AIBDataset_Filter,msdyn_AIBDataset_Fixed,msdyn_AIBDataset_Result,msdyn_AIBDataset_FormattedResult>;
  regardingobjectid_msdyn_aibdatasetfile: WebMappingRetrieve<msdyn_AIBDatasetFile_Select,msdyn_AIBDatasetFile_Expand,msdyn_AIBDatasetFile_Filter,msdyn_AIBDatasetFile_Fixed,msdyn_AIBDatasetFile_Result,msdyn_AIBDatasetFile_FormattedResult>;
  regardingobjectid_msdyn_aibdatasetrecord: WebMappingRetrieve<msdyn_AIBDatasetRecord_Select,msdyn_AIBDatasetRecord_Expand,msdyn_AIBDatasetRecord_Filter,msdyn_AIBDatasetRecord_Fixed,msdyn_AIBDatasetRecord_Result,msdyn_AIBDatasetRecord_FormattedResult>;
  regardingobjectid_msdyn_aibdatasetscontainer: WebMappingRetrieve<msdyn_AIBDatasetsContainer_Select,msdyn_AIBDatasetsContainer_Expand,msdyn_AIBDatasetsContainer_Filter,msdyn_AIBDatasetsContainer_Fixed,msdyn_AIBDatasetsContainer_Result,msdyn_AIBDatasetsContainer_FormattedResult>;
  regardingobjectid_msdyn_aibfile: WebMappingRetrieve<msdyn_AIBFile_Select,msdyn_AIBFile_Expand,msdyn_AIBFile_Filter,msdyn_AIBFile_Fixed,msdyn_AIBFile_Result,msdyn_AIBFile_FormattedResult>;
  regardingobjectid_msdyn_aibfileattacheddata: WebMappingRetrieve<msdyn_AIBFileAttachedData_Select,msdyn_AIBFileAttachedData_Expand,msdyn_AIBFileAttachedData_Filter,msdyn_AIBFileAttachedData_Fixed,msdyn_AIBFileAttachedData_Result,msdyn_AIBFileAttachedData_FormattedResult>;
  regardingobjectid_msdyn_aiconfiguration: WebMappingRetrieve<msdyn_AIConfiguration_Select,msdyn_AIConfiguration_Expand,msdyn_AIConfiguration_Filter,msdyn_AIConfiguration_Fixed,msdyn_AIConfiguration_Result,msdyn_AIConfiguration_FormattedResult>;
  regardingobjectid_msdyn_aifptrainingdocument: WebMappingRetrieve<msdyn_AIFpTrainingDocument_Select,msdyn_AIFpTrainingDocument_Expand,msdyn_AIFpTrainingDocument_Filter,msdyn_AIFpTrainingDocument_Fixed,msdyn_AIFpTrainingDocument_Result,msdyn_AIFpTrainingDocument_FormattedResult>;
  regardingobjectid_msdyn_aimodel: WebMappingRetrieve<msdyn_AIModel_Select,msdyn_AIModel_Expand,msdyn_AIModel_Filter,msdyn_AIModel_Fixed,msdyn_AIModel_Result,msdyn_AIModel_FormattedResult>;
  regardingobjectid_msdyn_aiodimage: WebMappingRetrieve<msdyn_AIOdImage_Select,msdyn_AIOdImage_Expand,msdyn_AIOdImage_Filter,msdyn_AIOdImage_Fixed,msdyn_AIOdImage_Result,msdyn_AIOdImage_FormattedResult>;
  regardingobjectid_msdyn_aiodlabel: WebMappingRetrieve<msdyn_AIOdLabel_Select,msdyn_AIOdLabel_Expand,msdyn_AIOdLabel_Filter,msdyn_AIOdLabel_Fixed,msdyn_AIOdLabel_Result,msdyn_AIOdLabel_FormattedResult>;
  regardingobjectid_msdyn_aiodtrainingboundingbox: WebMappingRetrieve<msdyn_AIOdTrainingBoundingBox_Select,msdyn_AIOdTrainingBoundingBox_Expand,msdyn_AIOdTrainingBoundingBox_Filter,msdyn_AIOdTrainingBoundingBox_Fixed,msdyn_AIOdTrainingBoundingBox_Result,msdyn_AIOdTrainingBoundingBox_FormattedResult>;
  regardingobjectid_msdyn_aiodtrainingimage: WebMappingRetrieve<msdyn_AIOdTrainingImage_Select,msdyn_AIOdTrainingImage_Expand,msdyn_AIOdTrainingImage_Filter,msdyn_AIOdTrainingImage_Fixed,msdyn_AIOdTrainingImage_Result,msdyn_AIOdTrainingImage_FormattedResult>;
  regardingobjectid_msdyn_aitemplate: WebMappingRetrieve<msdyn_AITemplate_Select,msdyn_AITemplate_Expand,msdyn_AITemplate_Filter,msdyn_AITemplate_Fixed,msdyn_AITemplate_Result,msdyn_AITemplate_FormattedResult>;
  regardingobjectid_msdyn_analysiscomponent: WebMappingRetrieve<msdyn_analysiscomponent_Select,msdyn_analysiscomponent_Expand,msdyn_analysiscomponent_Filter,msdyn_analysiscomponent_Fixed,msdyn_analysiscomponent_Result,msdyn_analysiscomponent_FormattedResult>;
  regardingobjectid_msdyn_analysisjob: WebMappingRetrieve<msdyn_analysisjob_Select,msdyn_analysisjob_Expand,msdyn_analysisjob_Filter,msdyn_analysisjob_Fixed,msdyn_analysisjob_Result,msdyn_analysisjob_FormattedResult>;
  regardingobjectid_msdyn_analysisresult: WebMappingRetrieve<msdyn_analysisresult_Select,msdyn_analysisresult_Expand,msdyn_analysisresult_Filter,msdyn_analysisresult_Fixed,msdyn_analysisresult_Result,msdyn_analysisresult_FormattedResult>;
  regardingobjectid_msdyn_analysisresultdetail: WebMappingRetrieve<msdyn_analysisresultdetail_Select,msdyn_analysisresultdetail_Expand,msdyn_analysisresultdetail_Filter,msdyn_analysisresultdetail_Fixed,msdyn_analysisresultdetail_Result,msdyn_analysisresultdetail_FormattedResult>;
  regardingobjectid_msdyn_dataflow: WebMappingRetrieve<msdyn_dataflow_Select,msdyn_dataflow_Expand,msdyn_dataflow_Filter,msdyn_dataflow_Fixed,msdyn_dataflow_Result,msdyn_dataflow_FormattedResult>;
  regardingobjectid_msdyn_federatedarticle: WebMappingRetrieve<msdyn_federatedarticle_Select,msdyn_federatedarticle_Expand,msdyn_federatedarticle_Filter,msdyn_federatedarticle_Fixed,msdyn_federatedarticle_Result,msdyn_federatedarticle_FormattedResult>;
  regardingobjectid_msdyn_federatedarticleincident: WebMappingRetrieve<msdyn_federatedarticleincident_Select,msdyn_federatedarticleincident_Expand,msdyn_federatedarticleincident_Filter,msdyn_federatedarticleincident_Fixed,msdyn_federatedarticleincident_Result,msdyn_federatedarticleincident_FormattedResult>;
  regardingobjectid_msdyn_helppage: WebMappingRetrieve<msdyn_helppage_Select,msdyn_helppage_Expand,msdyn_helppage_Filter,msdyn_helppage_Fixed,msdyn_helppage_Result,msdyn_helppage_FormattedResult>;
  regardingobjectid_msdyn_kalanguagesetting: WebMappingRetrieve<msdyn_kalanguagesetting_Select,msdyn_kalanguagesetting_Expand,msdyn_kalanguagesetting_Filter,msdyn_kalanguagesetting_Fixed,msdyn_kalanguagesetting_Result,msdyn_kalanguagesetting_FormattedResult>;
  regardingobjectid_msdyn_kmfederatedsearchconfig: WebMappingRetrieve<msdyn_kmfederatedsearchconfig_Select,msdyn_kmfederatedsearchconfig_Expand,msdyn_kmfederatedsearchconfig_Filter,msdyn_kmfederatedsearchconfig_Fixed,msdyn_kmfederatedsearchconfig_Result,msdyn_kmfederatedsearchconfig_FormattedResult>;
  regardingobjectid_msdyn_kmpersonalizationsetting: WebMappingRetrieve<msdyn_kmpersonalizationsetting_Select,msdyn_kmpersonalizationsetting_Expand,msdyn_kmpersonalizationsetting_Filter,msdyn_kmpersonalizationsetting_Fixed,msdyn_kmpersonalizationsetting_Result,msdyn_kmpersonalizationsetting_FormattedResult>;
  regardingobjectid_msdyn_knowledgearticleimage: WebMappingRetrieve<msdyn_knowledgearticleimage_Select,msdyn_knowledgearticleimage_Expand,msdyn_knowledgearticleimage_Filter,msdyn_knowledgearticleimage_Fixed,msdyn_knowledgearticleimage_Result,msdyn_knowledgearticleimage_FormattedResult>;
  regardingobjectid_msdyn_knowledgearticletemplate: WebMappingRetrieve<msdyn_knowledgearticletemplate_Select,msdyn_knowledgearticletemplate_Expand,msdyn_knowledgearticletemplate_Filter,msdyn_knowledgearticletemplate_Fixed,msdyn_knowledgearticletemplate_Result,msdyn_knowledgearticletemplate_FormattedResult>;
  regardingobjectid_msdyn_knowledgeinteractioninsight: WebMappingRetrieve<msdyn_knowledgeinteractioninsight_Select,msdyn_knowledgeinteractioninsight_Expand,msdyn_knowledgeinteractioninsight_Filter,msdyn_knowledgeinteractioninsight_Fixed,msdyn_knowledgeinteractioninsight_Result,msdyn_knowledgeinteractioninsight_FormattedResult>;
  regardingobjectid_msdyn_knowledgepersonalfilter: WebMappingRetrieve<msdyn_knowledgepersonalfilter_Select,msdyn_knowledgepersonalfilter_Expand,msdyn_knowledgepersonalfilter_Filter,msdyn_knowledgepersonalfilter_Fixed,msdyn_knowledgepersonalfilter_Result,msdyn_knowledgepersonalfilter_FormattedResult>;
  regardingobjectid_msdyn_knowledgesearchfilter: WebMappingRetrieve<msdyn_knowledgesearchfilter_Select,msdyn_knowledgesearchfilter_Expand,msdyn_knowledgesearchfilter_Filter,msdyn_knowledgesearchfilter_Fixed,msdyn_knowledgesearchfilter_Result,msdyn_knowledgesearchfilter_FormattedResult>;
  regardingobjectid_msdyn_knowledgesearchinsight: WebMappingRetrieve<msdyn_knowledgesearchinsight_Select,msdyn_knowledgesearchinsight_Expand,msdyn_knowledgesearchinsight_Filter,msdyn_knowledgesearchinsight_Fixed,msdyn_knowledgesearchinsight_Result,msdyn_knowledgesearchinsight_FormattedResult>;
  regardingobjectid_msdyn_pminferredtask: WebMappingRetrieve<msdyn_pminferredtask_Select,msdyn_pminferredtask_Expand,msdyn_pminferredtask_Filter,msdyn_pminferredtask_Fixed,msdyn_pminferredtask_Result,msdyn_pminferredtask_FormattedResult>;
  regardingobjectid_msdyn_pmrecording: WebMappingRetrieve<msdyn_pmrecording_Select,msdyn_pmrecording_Expand,msdyn_pmrecording_Filter,msdyn_pmrecording_Fixed,msdyn_pmrecording_Result,msdyn_pmrecording_FormattedResult>;
  regardingobjectid_msdyn_richtextfile: WebMappingRetrieve<msdyn_richtextfile_Select,msdyn_richtextfile_Expand,msdyn_richtextfile_Filter,msdyn_richtextfile_Fixed,msdyn_richtextfile_Result,msdyn_richtextfile_FormattedResult>;
  regardingobjectid_msdyn_serviceconfiguration: WebMappingRetrieve<msdyn_serviceconfiguration_Select,msdyn_serviceconfiguration_Expand,msdyn_serviceconfiguration_Filter,msdyn_serviceconfiguration_Fixed,msdyn_serviceconfiguration_Result,msdyn_serviceconfiguration_FormattedResult>;
  regardingobjectid_msdyn_slakpi: WebMappingRetrieve<msdyn_slakpi_Select,msdyn_slakpi_Expand,msdyn_slakpi_Filter,msdyn_slakpi_Fixed,msdyn_slakpi_Result,msdyn_slakpi_FormattedResult>;
  regardingobjectid_msdyn_solutionhealthrule: WebMappingRetrieve<msdyn_solutionhealthrule_Select,msdyn_solutionhealthrule_Expand,msdyn_solutionhealthrule_Filter,msdyn_solutionhealthrule_Fixed,msdyn_solutionhealthrule_Result,msdyn_solutionhealthrule_FormattedResult>;
  regardingobjectid_msdyn_solutionhealthruleargument: WebMappingRetrieve<msdyn_solutionhealthruleargument_Select,msdyn_solutionhealthruleargument_Expand,msdyn_solutionhealthruleargument_Filter,msdyn_solutionhealthruleargument_Fixed,msdyn_solutionhealthruleargument_Result,msdyn_solutionhealthruleargument_FormattedResult>;
  regardingobjectid_msdyn_solutionhealthruleset: WebMappingRetrieve<msdyn_solutionhealthruleset_Select,msdyn_solutionhealthruleset_Expand,msdyn_solutionhealthruleset_Filter,msdyn_solutionhealthruleset_Fixed,msdyn_solutionhealthruleset_Result,msdyn_solutionhealthruleset_FormattedResult>;
  regardingobjectid_msdyn_tour: WebMappingRetrieve<msdyn_tour_Select,msdyn_tour_Expand,msdyn_tour_Filter,msdyn_tour_Fixed,msdyn_tour_Result,msdyn_tour_FormattedResult>;
  regardingobjectid_msdynce_botcontent: WebMappingRetrieve<msdynce_botcontent_Select,msdynce_botcontent_Expand,msdynce_botcontent_Filter,msdynce_botcontent_Fixed,msdynce_botcontent_Result,msdynce_botcontent_FormattedResult>;
  regardingobjectid_organization: WebMappingRetrieve<Organization_Select,Organization_Expand,Organization_Filter,Organization_Fixed,Organization_Result,Organization_FormattedResult>;
  regardingobjectid_organizationdatasyncsubscription: WebMappingRetrieve<organizationdatasyncsubscription_Select,organizationdatasyncsubscription_Expand,organizationdatasyncsubscription_Filter,organizationdatasyncsubscription_Fixed,organizationdatasyncsubscription_Result,organizationdatasyncsubscription_FormattedResult>;
  regardingobjectid_organizationdatasyncsubscriptionentity: WebMappingRetrieve<organizationdatasyncsubscriptionentity_Select,organizationdatasyncsubscriptionentity_Expand,organizationdatasyncsubscriptionentity_Filter,organizationdatasyncsubscriptionentity_Fixed,organizationdatasyncsubscriptionentity_Result,organizationdatasyncsubscriptionentity_FormattedResult>;
  regardingobjectid_organizationsetting: WebMappingRetrieve<OrganizationSetting_Select,OrganizationSetting_Expand,OrganizationSetting_Filter,OrganizationSetting_Fixed,OrganizationSetting_Result,OrganizationSetting_FormattedResult>;
  regardingobjectid_package: WebMappingRetrieve<package_Select,package_Expand,package_Filter,package_Fixed,package_Result,package_FormattedResult>;
  regardingobjectid_pc_bankaccount: WebMappingRetrieve<pc_BankAccount_Select,pc_BankAccount_Expand,pc_BankAccount_Filter,pc_BankAccount_Fixed,pc_BankAccount_Result,pc_BankAccount_FormattedResult>;
  regardingobjectid_pc_participation: WebMappingRetrieve<pc_Participation_Select,pc_Participation_Expand,pc_Participation_Filter,pc_Participation_Fixed,pc_Participation_Result,pc_Participation_FormattedResult>;
  regardingobjectid_pc_participationfeeexemption: WebMappingRetrieve<pc_ParticipationFeeExemption_Select,pc_ParticipationFeeExemption_Expand,pc_ParticipationFeeExemption_Filter,pc_ParticipationFeeExemption_Fixed,pc_ParticipationFeeExemption_Result,pc_ParticipationFeeExemption_FormattedResult>;
  regardingobjectid_pc_payment: WebMappingRetrieve<pc_Payment_Select,pc_Payment_Expand,pc_Payment_Filter,pc_Payment_Fixed,pc_Payment_Result,pc_Payment_FormattedResult>;
  regardingobjectid_pc_scheduledjob: WebMappingRetrieve<pc_ScheduledJob_Select,pc_ScheduledJob_Expand,pc_ScheduledJob_Filter,pc_ScheduledJob_Fixed,pc_ScheduledJob_Result,pc_ScheduledJob_FormattedResult>;
  regardingobjectid_pc_settings: WebMappingRetrieve<pc_Settings_Select,pc_Settings_Expand,pc_Settings_Filter,pc_Settings_Fixed,pc_Settings_Result,pc_Settings_FormattedResult>;
  regardingobjectid_pc_transaction: WebMappingRetrieve<pc_Transaction_Select,pc_Transaction_Expand,pc_Transaction_Filter,pc_Transaction_Fixed,pc_Transaction_Result,pc_Transaction_FormattedResult>;
  regardingobjectid_pdfsetting: WebMappingRetrieve<PDFSetting_Select,PDFSetting_Expand,PDFSetting_Filter,PDFSetting_Fixed,PDFSetting_Result,PDFSetting_FormattedResult>;
  regardingobjectid_phonecall: WebMappingRetrieve<PhoneCall_Select,PhoneCall_Expand,PhoneCall_Filter,PhoneCall_Fixed,PhoneCall_Result,PhoneCall_FormattedResult>;
  regardingobjectid_pluginpackage: WebMappingRetrieve<pluginpackage_Select,pluginpackage_Expand,pluginpackage_Filter,pluginpackage_Fixed,pluginpackage_Result,pluginpackage_FormattedResult>;
  regardingobjectid_post: WebMappingRetrieve<Post_Select,Post_Expand,Post_Filter,Post_Fixed,Post_Result,Post_FormattedResult>;
  regardingobjectid_privilege: WebMappingRetrieve<Privilege_Select,Privilege_Expand,Privilege_Filter,Privilege_Fixed,Privilege_Result,Privilege_FormattedResult>;
  regardingobjectid_processstageparameter: WebMappingRetrieve<processstageparameter_Select,processstageparameter_Expand,processstageparameter_Filter,processstageparameter_Fixed,processstageparameter_Result,processstageparameter_FormattedResult>;
  regardingobjectid_provisionlanguageforuser: WebMappingRetrieve<ProvisionLanguageForUser_Select,ProvisionLanguageForUser_Expand,ProvisionLanguageForUser_Filter,ProvisionLanguageForUser_Fixed,ProvisionLanguageForUser_Result,ProvisionLanguageForUser_FormattedResult>;
  regardingobjectid_quarterlyfiscalcalendar: WebMappingRetrieve<QuarterlyFiscalCalendar_Select,QuarterlyFiscalCalendar_Expand,QuarterlyFiscalCalendar_Filter,QuarterlyFiscalCalendar_Fixed,QuarterlyFiscalCalendar_Result,QuarterlyFiscalCalendar_FormattedResult>;
  regardingobjectid_queue: WebMappingRetrieve<Queue_Select,Queue_Expand,Queue_Filter,Queue_Fixed,Queue_Result,Queue_FormattedResult>;
  regardingobjectid_queueitem: WebMappingRetrieve<QueueItem_Select,QueueItem_Expand,QueueItem_Filter,QueueItem_Fixed,QueueItem_Result,QueueItem_FormattedResult>;
  regardingobjectid_recurringappointmentmaster: WebMappingRetrieve<RecurringAppointmentMaster_Select,RecurringAppointmentMaster_Expand,RecurringAppointmentMaster_Filter,RecurringAppointmentMaster_Fixed,RecurringAppointmentMaster_Result,RecurringAppointmentMaster_FormattedResult>;
  regardingobjectid_relationshipattribute: WebMappingRetrieve<RelationshipAttribute_Select,RelationshipAttribute_Expand,RelationshipAttribute_Filter,RelationshipAttribute_Fixed,RelationshipAttribute_Result,RelationshipAttribute_FormattedResult>;
  regardingobjectid_relationshiprole: WebMappingRetrieve<RelationshipRole_Select,RelationshipRole_Expand,RelationshipRole_Filter,RelationshipRole_Fixed,RelationshipRole_Result,RelationshipRole_FormattedResult>;
  regardingobjectid_relationshiprolemap: WebMappingRetrieve<RelationshipRoleMap_Select,RelationshipRoleMap_Expand,RelationshipRoleMap_Filter,RelationshipRoleMap_Fixed,RelationshipRoleMap_Result,RelationshipRoleMap_FormattedResult>;
  regardingobjectid_revokeinheritedaccessrecordstracker: WebMappingRetrieve<revokeinheritedaccessrecordstracker_Select,revokeinheritedaccessrecordstracker_Expand,revokeinheritedaccessrecordstracker_Filter,revokeinheritedaccessrecordstracker_Fixed,revokeinheritedaccessrecordstracker_Result,revokeinheritedaccessrecordstracker_FormattedResult>;
  regardingobjectid_role: WebMappingRetrieve<Role_Select,Role_Expand,Role_Filter,Role_Fixed,Role_Result,Role_FormattedResult>;
  regardingobjectid_routingrule: WebMappingRetrieve<RoutingRule_Select,RoutingRule_Expand,RoutingRule_Filter,RoutingRule_Fixed,RoutingRule_Result,RoutingRule_FormattedResult>;
  regardingobjectid_routingruleitem: WebMappingRetrieve<RoutingRuleItem_Select,RoutingRuleItem_Expand,RoutingRuleItem_Filter,RoutingRuleItem_Fixed,RoutingRuleItem_Result,RoutingRuleItem_FormattedResult>;
  regardingobjectid_savedquery: WebMappingRetrieve<SavedQuery_Select,SavedQuery_Expand,SavedQuery_Filter,SavedQuery_Fixed,SavedQuery_Result,SavedQuery_FormattedResult>;
  regardingobjectid_semiannualfiscalcalendar: WebMappingRetrieve<SemiAnnualFiscalCalendar_Select,SemiAnnualFiscalCalendar_Expand,SemiAnnualFiscalCalendar_Filter,SemiAnnualFiscalCalendar_Fixed,SemiAnnualFiscalCalendar_Result,SemiAnnualFiscalCalendar_FormattedResult>;
  regardingobjectid_serviceplan: WebMappingRetrieve<ServicePlan_Select,ServicePlan_Expand,ServicePlan_Filter,ServicePlan_Fixed,ServicePlan_Result,ServicePlan_FormattedResult>;
  regardingobjectid_serviceplanmapping: WebMappingRetrieve<ServicePlanMapping_Select,ServicePlanMapping_Expand,ServicePlanMapping_Filter,ServicePlanMapping_Fixed,ServicePlanMapping_Result,ServicePlanMapping_FormattedResult>;
  regardingobjectid_settingdefinition: WebMappingRetrieve<SettingDefinition_Select,SettingDefinition_Expand,SettingDefinition_Filter,SettingDefinition_Fixed,SettingDefinition_Result,SettingDefinition_FormattedResult>;
  regardingobjectid_sla: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  regardingobjectid_socialactivity: WebMappingRetrieve<SocialActivity_Select,SocialActivity_Expand,SocialActivity_Filter,SocialActivity_Fixed,SocialActivity_Result,SocialActivity_FormattedResult>;
  regardingobjectid_solutioncomponentattributeconfiguration: WebMappingRetrieve<solutioncomponentattributeconfiguration_Select,solutioncomponentattributeconfiguration_Expand,solutioncomponentattributeconfiguration_Filter,solutioncomponentattributeconfiguration_Fixed,solutioncomponentattributeconfiguration_Result,solutioncomponentattributeconfiguration_FormattedResult>;
  regardingobjectid_solutioncomponentbatchconfiguration: WebMappingRetrieve<solutioncomponentbatchconfiguration_Select,solutioncomponentbatchconfiguration_Expand,solutioncomponentbatchconfiguration_Filter,solutioncomponentbatchconfiguration_Fixed,solutioncomponentbatchconfiguration_Result,solutioncomponentbatchconfiguration_FormattedResult>;
  regardingobjectid_solutioncomponentconfiguration: WebMappingRetrieve<solutioncomponentconfiguration_Select,solutioncomponentconfiguration_Expand,solutioncomponentconfiguration_Filter,solutioncomponentconfiguration_Fixed,solutioncomponentconfiguration_Result,solutioncomponentconfiguration_FormattedResult>;
  regardingobjectid_solutioncomponentrelationshipconfiguration: WebMappingRetrieve<solutioncomponentrelationshipconfiguration_Select,solutioncomponentrelationshipconfiguration_Expand,solutioncomponentrelationshipconfiguration_Filter,solutioncomponentrelationshipconfiguration_Fixed,solutioncomponentrelationshipconfiguration_Result,solutioncomponentrelationshipconfiguration_FormattedResult>;
  regardingobjectid_stagesolutionupload: WebMappingRetrieve<StageSolutionUpload_Select,StageSolutionUpload_Expand,StageSolutionUpload_Filter,StageSolutionUpload_Fixed,StageSolutionUpload_Result,StageSolutionUpload_FormattedResult>;
  regardingobjectid_subject: WebMappingRetrieve<Subject_Select,Subject_Expand,Subject_Filter,Subject_Fixed,Subject_Result,Subject_FormattedResult>;
  regardingobjectid_systemform: WebMappingRetrieve<SystemForm_Select,SystemForm_Expand,SystemForm_Filter,SystemForm_Fixed,SystemForm_Result,SystemForm_FormattedResult>;
  regardingobjectid_systemuser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  regardingobjectid_systemuserauthorizationchangetracker: WebMappingRetrieve<SystemUserAuthorizationChangeTracker_Select,SystemUserAuthorizationChangeTracker_Expand,SystemUserAuthorizationChangeTracker_Filter,SystemUserAuthorizationChangeTracker_Fixed,SystemUserAuthorizationChangeTracker_Result,SystemUserAuthorizationChangeTracker_FormattedResult>;
  regardingobjectid_task: WebMappingRetrieve<Task_Select,Task_Expand,Task_Filter,Task_Fixed,Task_Result,Task_FormattedResult>;
  regardingobjectid_team: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  regardingobjectid_teammobileofflineprofilemembership: WebMappingRetrieve<teammobileofflineprofilemembership_Select,teammobileofflineprofilemembership_Expand,teammobileofflineprofilemembership_Filter,teammobileofflineprofilemembership_Fixed,teammobileofflineprofilemembership_Result,teammobileofflineprofilemembership_FormattedResult>;
  regardingobjectid_template: WebMappingRetrieve<Template_Select,Template_Expand,Template_Filter,Template_Fixed,Template_Result,Template_FormattedResult>;
  regardingobjectid_territory: WebMappingRetrieve<Territory_Select,Territory_Expand,Territory_Filter,Territory_Fixed,Territory_Result,Territory_FormattedResult>;
  regardingobjectid_theme: WebMappingRetrieve<Theme_Select,Theme_Expand,Theme_Filter,Theme_Fixed,Theme_Result,Theme_FormattedResult>;
  regardingobjectid_userform: WebMappingRetrieve<UserForm_Select,UserForm_Expand,UserForm_Filter,UserForm_Fixed,UserForm_Result,UserForm_FormattedResult>;
  regardingobjectid_usermapping: WebMappingRetrieve<UserMapping_Select,UserMapping_Expand,UserMapping_Filter,UserMapping_Fixed,UserMapping_Result,UserMapping_FormattedResult>;
  regardingobjectid_usermobileofflineprofilemembership: WebMappingRetrieve<usermobileofflineprofilemembership_Select,usermobileofflineprofilemembership_Expand,usermobileofflineprofilemembership_Filter,usermobileofflineprofilemembership_Fixed,usermobileofflineprofilemembership_Result,usermobileofflineprofilemembership_FormattedResult>;
  regardingobjectid_userquery: WebMappingRetrieve<UserQuery_Select,UserQuery_Expand,UserQuery_Filter,UserQuery_Fixed,UserQuery_Result,UserQuery_FormattedResult>;
  regardingobjectid_virtualentitymetadata: WebMappingRetrieve<VirtualEntityMetadata_Select,VirtualEntityMetadata_Expand,VirtualEntityMetadata_Filter,VirtualEntityMetadata_Fixed,VirtualEntityMetadata_Result,VirtualEntityMetadata_FormattedResult>;
  regardingobjectid_workflowbinary: WebMappingRetrieve<workflowbinary_Select,workflowbinary_Expand,workflowbinary_Filter,workflowbinary_Fixed,workflowbinary_Result,workflowbinary_FormattedResult>;
}
interface BulkDeleteFailure_RelatedMany {
  userentityinstancedata_bulkdeletefailure: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
}
interface WebEntitiesRetrieve {
  bulkdeletefailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
}
interface WebEntitiesRelated {
  bulkdeletefailures: WebMappingRelated<BulkDeleteFailure_RelatedOne,BulkDeleteFailure_RelatedMany>;
}
interface WebEntitiesCUDA {
  bulkdeletefailures: WebMappingCUDA<BulkDeleteFailure_Create,BulkDeleteFailure_Update,BulkDeleteFailure_Select>;
}
