interface BusinessUnit_Base extends WebEntity {
  address1_addressid?: string | null;
  address1_addresstypecode?: businessunit_address1_addresstypecode | null;
  address1_city?: string | null;
  address1_country?: string | null;
  address1_county?: string | null;
  address1_fax?: string | null;
  address1_latitude?: number | null;
  address1_line1?: string | null;
  address1_line2?: string | null;
  address1_line3?: string | null;
  address1_longitude?: number | null;
  address1_name?: string | null;
  address1_postalcode?: string | null;
  address1_postofficebox?: string | null;
  address1_shippingmethodcode?: businessunit_address1_shippingmethodcode | null;
  address1_stateorprovince?: string | null;
  address1_telephone1?: string | null;
  address1_telephone2?: string | null;
  address1_telephone3?: string | null;
  address1_upszone?: string | null;
  address1_utcoffset?: number | null;
  address2_addressid?: string | null;
  address2_addresstypecode?: businessunit_address2_addresstypecode | null;
  address2_city?: string | null;
  address2_country?: string | null;
  address2_county?: string | null;
  address2_fax?: string | null;
  address2_latitude?: number | null;
  address2_line1?: string | null;
  address2_line2?: string | null;
  address2_line3?: string | null;
  address2_longitude?: number | null;
  address2_name?: string | null;
  address2_postalcode?: string | null;
  address2_postofficebox?: string | null;
  address2_shippingmethodcode?: businessunit_address2_shippingmethodcode | null;
  address2_stateorprovince?: string | null;
  address2_telephone1?: string | null;
  address2_telephone2?: string | null;
  address2_telephone3?: string | null;
  address2_upszone?: string | null;
  address2_utcoffset?: number | null;
  businessunitid?: string | null;
  costcenter?: string | null;
  createdon?: Date | null;
  creditlimit?: number | null;
  description?: string | null;
  disabledreason?: string | null;
  divisionname?: string | null;
  emailaddress?: string | null;
  exchangerate?: number | null;
  fileasname?: string | null;
  ftpsiteurl?: string | null;
  importsequencenumber?: number | null;
  inheritancemask?: number | null;
  isdisabled?: boolean | null;
  modifiedon?: Date | null;
  name?: string | null;
  overriddencreatedon?: Date | null;
  picture?: string | null;
  stockexchange?: string | null;
  tickersymbol?: string | null;
  usergroupid?: string | null;
  utcoffset?: number | null;
  versionnumber?: number | null;
  websiteurl?: string | null;
  workflowsuspended?: boolean | null;
}
interface BusinessUnit_Relationships {
  BulkDeleteOperation_BusinessUnit?: BulkDeleteOperation_Result[] | null;
  BusinessUnit_AsyncOperations?: AsyncOperation_Result[] | null;
  BusinessUnit_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  BusinessUnit_DuplicateRules?: DuplicateRule_Result[] | null;
  BusinessUnit_ImportData?: ImportData_Result[] | null;
  BusinessUnit_ImportFiles?: ImportFile_Result[] | null;
  BusinessUnit_ImportLogs?: ImportLog_Result[] | null;
  BusinessUnit_ImportMaps?: ImportMap_Result[] | null;
  BusinessUnit_Imports?: Import_Result[] | null;
  BusinessUnit_ProcessSessions?: ProcessSession_Result[] | null;
  BusinessUnit_SyncError?: SyncError_Result[] | null;
  BusinessUnit_SyncErrors?: SyncError_Result[] | null;
  Owning_businessunit_processsessions?: ProcessSession_Result[] | null;
  actioncardusersettings_businessunit?: ActionCardUserSettings_Result[] | null;
  bizmap_businessid_businessunit?: BusinessUnitMap_Result[] | null;
  bizmap_subbusinessid_businessunit?: BusinessUnitMap_Result[] | null;
  business_unit_PostRegarding?: PostRegarding_Result[] | null;
  business_unit_TraceRegarding?: TraceRegarding_Result[] | null;
  business_unit_accounts?: Account_Result[] | null;
  business_unit_actioncards?: ActionCard_Result[] | null;
  business_unit_activityfileattachment?: activityfileattachment_Result[] | null;
  business_unit_activitypointer?: ActivityPointer_Result[] | null;
  business_unit_annotations?: Annotation_Result[] | null;
  business_unit_applicationuser?: ApplicationUser_Result[] | null;
  business_unit_appnotification?: appnotification_Result[] | null;
  business_unit_appointment_activities?: Appointment_Result[] | null;
  business_unit_asyncoperation?: AsyncOperation_Result[] | null;
  business_unit_bot?: bot_Result[] | null;
  business_unit_botcomponent?: botcomponent_Result[] | null;
  business_unit_calendars?: Calendar_Result[] | null;
  business_unit_canvasappextendedmetadata?: CanvasAppExtendedMetadata_Result[] | null;
  business_unit_category?: Category_Result[] | null;
  business_unit_channelaccessprofile?: ChannelAccessProfile_Result[] | null;
  business_unit_connectionreference?: connectionreference_Result[] | null;
  business_unit_connections?: Connection_Result[] | null;
  business_unit_connector?: connector_Result[] | null;
  business_unit_contacts?: Contact_Result[] | null;
  business_unit_conversationtranscript?: conversationtranscript_Result[] | null;
  business_unit_convertrule?: ConvertRule_Result[] | null;
  business_unit_customapi?: CustomAPI_Result[] | null;
  business_unit_customapirequestparameter?: CustomAPIRequestParameter_Result[] | null;
  business_unit_customapiresponseproperty?: CustomAPIResponseProperty_Result[] | null;
  business_unit_customer_relationship?: CustomerRelationship_Result[] | null;
  business_unit_datalakefolder?: datalakefolder_Result[] | null;
  business_unit_datalakefolderpermission?: datalakefolderpermission_Result[] | null;
  business_unit_email_activities?: Email_Result[] | null;
  business_unit_emailserverprofile?: EmailServerProfile_Result[] | null;
  business_unit_emailsignatures?: EmailSignature_Result[] | null;
  business_unit_environmentvariabledefinition?: EnvironmentVariableDefinition_Result[] | null;
  business_unit_environmentvariablevalue?: EnvironmentVariableValue_Result[] | null;
  business_unit_exchangesyncidmapping?: ExchangeSyncIdMapping_Result[] | null;
  business_unit_exportsolutionupload?: ExportSolutionUpload_Result[] | null;
  business_unit_externalparty?: ExternalParty_Result[] | null;
  business_unit_fax_activities?: Fax_Result[] | null;
  business_unit_featurecontrolsetting?: featurecontrolsetting_Result[] | null;
  business_unit_feedback?: Feedback_Result[] | null;
  business_unit_flowmachine?: flowmachine_Result[] | null;
  business_unit_flowmachinegroup?: flowmachinegroup_Result[] | null;
  business_unit_flowsession?: flowsession_Result[] | null;
  business_unit_goal?: Goal_Result[] | null;
  business_unit_goalrollupquery?: GoalRollupQuery_Result[] | null;
  business_unit_keyvaultreference?: KeyVaultReference_Result[] | null;
  business_unit_knowledgearticle?: KnowledgeArticle_Result[] | null;
  business_unit_letter_activities?: Letter_Result[] | null;
  business_unit_mailbox?: Mailbox_Result[] | null;
  business_unit_mailmergetemplates?: MailMergeTemplate_Result[] | null;
  business_unit_managedidentity?: ManagedIdentity_Result[] | null;
  business_unit_msdyn_aibdataset?: msdyn_AIBDataset_Result[] | null;
  business_unit_msdyn_aibdatasetfile?: msdyn_AIBDatasetFile_Result[] | null;
  business_unit_msdyn_aibdatasetrecord?: msdyn_AIBDatasetRecord_Result[] | null;
  business_unit_msdyn_aibdatasetscontainer?: msdyn_AIBDatasetsContainer_Result[] | null;
  business_unit_msdyn_aibfile?: msdyn_AIBFile_Result[] | null;
  business_unit_msdyn_aibfileattacheddata?: msdyn_AIBFileAttachedData_Result[] | null;
  business_unit_msdyn_aiconfiguration?: msdyn_AIConfiguration_Result[] | null;
  business_unit_msdyn_aifptrainingdocument?: msdyn_AIFpTrainingDocument_Result[] | null;
  business_unit_msdyn_aimodel?: msdyn_AIModel_Result[] | null;
  business_unit_msdyn_aiodimage?: msdyn_AIOdImage_Result[] | null;
  business_unit_msdyn_aiodlabel?: msdyn_AIOdLabel_Result[] | null;
  business_unit_msdyn_aiodtrainingboundingbox?: msdyn_AIOdTrainingBoundingBox_Result[] | null;
  business_unit_msdyn_aiodtrainingimage?: msdyn_AIOdTrainingImage_Result[] | null;
  business_unit_msdyn_aitemplate?: msdyn_AITemplate_Result[] | null;
  business_unit_msdyn_analysiscomponent?: msdyn_analysiscomponent_Result[] | null;
  business_unit_msdyn_analysisjob?: msdyn_analysisjob_Result[] | null;
  business_unit_msdyn_analysisresult?: msdyn_analysisresult_Result[] | null;
  business_unit_msdyn_analysisresultdetail?: msdyn_analysisresultdetail_Result[] | null;
  business_unit_msdyn_dataflow?: msdyn_dataflow_Result[] | null;
  business_unit_msdyn_federatedarticle?: msdyn_federatedarticle_Result[] | null;
  business_unit_msdyn_kalanguagesetting?: msdyn_kalanguagesetting_Result[] | null;
  business_unit_msdyn_kmfederatedsearchconfig?: msdyn_kmfederatedsearchconfig_Result[] | null;
  business_unit_msdyn_knowledgearticleimage?: msdyn_knowledgearticleimage_Result[] | null;
  business_unit_msdyn_knowledgearticletemplate?: msdyn_knowledgearticletemplate_Result[] | null;
  business_unit_msdyn_knowledgeinteractioninsight?: msdyn_knowledgeinteractioninsight_Result[] | null;
  business_unit_msdyn_knowledgepersonalfilter?: msdyn_knowledgepersonalfilter_Result[] | null;
  business_unit_msdyn_knowledgesearchfilter?: msdyn_knowledgesearchfilter_Result[] | null;
  business_unit_msdyn_knowledgesearchinsight?: msdyn_knowledgesearchinsight_Result[] | null;
  business_unit_msdyn_pminferredtask?: msdyn_pminferredtask_Result[] | null;
  business_unit_msdyn_pmrecording?: msdyn_pmrecording_Result[] | null;
  business_unit_msdyn_richtextfile?: msdyn_richtextfile_Result[] | null;
  business_unit_msdyn_serviceconfiguration?: msdyn_serviceconfiguration_Result[] | null;
  business_unit_msdyn_slakpi?: msdyn_slakpi_Result[] | null;
  business_unit_msdyn_solutionhealthrule?: msdyn_solutionhealthrule_Result[] | null;
  business_unit_msdyn_solutionhealthruleargument?: msdyn_solutionhealthruleargument_Result[] | null;
  business_unit_msdynce_botcontent?: msdynce_botcontent_Result[] | null;
  business_unit_new_interactionforemail?: InteractionForEmail_Result[] | null;
  business_unit_parent_business_unit?: BusinessUnit_Result[] | null;
  business_unit_pdfsetting?: PDFSetting_Result[] | null;
  business_unit_personaldocumenttemplates?: PersonalDocumentTemplate_Result[] | null;
  business_unit_phone_call_activities?: PhoneCall_Result[] | null;
  business_unit_postfollows?: PostFollow_Result[] | null;
  business_unit_principalentitybusinessunitmap?: PrincipalEntityBusinessUnitMap_Result[] | null;
  business_unit_processstageparameter?: processstageparameter_Result[] | null;
  business_unit_profilerule?: ChannelAccessProfileRule_Result[] | null;
  business_unit_queues?: Queue_Result[] | null;
  business_unit_queues2?: Queue_Result[] | null;
  business_unit_recurrencerule?: RecurrenceRule_Result[] | null;
  business_unit_recurringappointmentmaster_activities?: RecurringAppointmentMaster_Result[] | null;
  business_unit_reports?: Report_Result[] | null;
  business_unit_revokeinheritedaccessrecordstracker?: revokeinheritedaccessrecordstracker_Result[] | null;
  business_unit_roles?: Role_Result[] | null;
  business_unit_routingrule?: RoutingRule_Result[] | null;
  business_unit_sharepointdocument?: SharePointDocument_Result[] | null;
  business_unit_sharepointdocument2?: SharePointDocument_Result[] | null;
  business_unit_sharepointdocumentlocation?: SharePointDocumentLocation_Result[] | null;
  business_unit_sharepointsites?: SharePointSite_Result[] | null;
  business_unit_slabase?: SLA_Result[] | null;
  business_unit_slakpiinstance?: SLAKPIInstance_Result[] | null;
  business_unit_socialactivity?: SocialActivity_Result[] | null;
  business_unit_socialprofiles?: SocialProfile_Result[] | null;
  business_unit_solutioncomponentbatchconfiguration?: solutioncomponentbatchconfiguration_Result[] | null;
  business_unit_stagesolutionupload?: StageSolutionUpload_Result[] | null;
  business_unit_system_users?: SystemUser_Result[] | null;
  business_unit_task_activities?: Task_Result[] | null;
  business_unit_teams?: Team_Result[] | null;
  business_unit_templates?: Template_Result[] | null;
  business_unit_untrackedemail_activities?: UntrackedEmail_Result[] | null;
  business_unit_user_settings?: UserSettings_Result[] | null;
  business_unit_userapplicationmetadata?: UserApplicationMetadata_Result[] | null;
  business_unit_userform?: UserForm_Result[] | null;
  business_unit_userquery?: UserQuery_Result[] | null;
  business_unit_userqueryvisualizations?: UserQueryVisualization_Result[] | null;
  business_unit_workflow?: Workflow_Result[] | null;
  business_unit_workflowbinary?: workflowbinary_Result[] | null;
  business_unit_workflowlogs?: WorkflowLog_Result[] | null;
  businessunit_callbackregistration?: CallbackRegistration_Result[] | null;
  businessunit_canvasapp?: CanvasApp_Result[] | null;
  businessunit_canvasappextendedmetadata?: CanvasAppExtendedMetadata_Result[] | null;
  businessunit_internal_addresses?: InternalAddress_Result[] | null;
  businessunit_mailboxtrackingcategory?: MailboxTrackingCategory_Result[] | null;
  businessunit_mailboxtrackingfolder?: MailboxTrackingFolder_Result[] | null;
  businessunit_principalobjectattributeaccess?: PrincipalObjectAttributeAccess_Result[] | null;
  lk_userfiscalcalendar_businessunit?: UserFiscalCalendar_Result[] | null;
  mbs_businessunit_mbs_pluginprofile?: mbs_pluginprofile_Result[] | null;
  systemuserbusinessunitentitymap_businessunitid_businessunit?: SystemUserBusinessUnitEntityMap_Result[] | null;
  userentityinstancedata_businessunit?: UserEntityInstanceData_Result[] | null;
  userentityuisettings_businessunit?: UserEntityUISettings_Result[] | null;
}
interface BusinessUnit extends BusinessUnit_Base, BusinessUnit_Relationships {
  calendarid_bind$calendars?: string | null;
  parentbusinessunitid_bind$businessunits?: string | null;
  transactioncurrencyid_bind$transactioncurrencies?: string | null;
}
interface BusinessUnit_Create extends BusinessUnit {
}
interface BusinessUnit_Update extends BusinessUnit {
}
interface BusinessUnit_Select {
  address1_addressid: WebAttribute<BusinessUnit_Select, { address1_addressid: string | null }, {  }>;
  address1_addresstypecode: WebAttribute<BusinessUnit_Select, { address1_addresstypecode: businessunit_address1_addresstypecode | null }, { address1_addresstypecode_formatted?: string }>;
  address1_city: WebAttribute<BusinessUnit_Select, { address1_city: string | null }, {  }>;
  address1_country: WebAttribute<BusinessUnit_Select, { address1_country: string | null }, {  }>;
  address1_county: WebAttribute<BusinessUnit_Select, { address1_county: string | null }, {  }>;
  address1_fax: WebAttribute<BusinessUnit_Select, { address1_fax: string | null }, {  }>;
  address1_latitude: WebAttribute<BusinessUnit_Select, { address1_latitude: number | null }, {  }>;
  address1_line1: WebAttribute<BusinessUnit_Select, { address1_line1: string | null }, {  }>;
  address1_line2: WebAttribute<BusinessUnit_Select, { address1_line2: string | null }, {  }>;
  address1_line3: WebAttribute<BusinessUnit_Select, { address1_line3: string | null }, {  }>;
  address1_longitude: WebAttribute<BusinessUnit_Select, { address1_longitude: number | null }, {  }>;
  address1_name: WebAttribute<BusinessUnit_Select, { address1_name: string | null }, {  }>;
  address1_postalcode: WebAttribute<BusinessUnit_Select, { address1_postalcode: string | null }, {  }>;
  address1_postofficebox: WebAttribute<BusinessUnit_Select, { address1_postofficebox: string | null }, {  }>;
  address1_shippingmethodcode: WebAttribute<BusinessUnit_Select, { address1_shippingmethodcode: businessunit_address1_shippingmethodcode | null }, { address1_shippingmethodcode_formatted?: string }>;
  address1_stateorprovince: WebAttribute<BusinessUnit_Select, { address1_stateorprovince: string | null }, {  }>;
  address1_telephone1: WebAttribute<BusinessUnit_Select, { address1_telephone1: string | null }, {  }>;
  address1_telephone2: WebAttribute<BusinessUnit_Select, { address1_telephone2: string | null }, {  }>;
  address1_telephone3: WebAttribute<BusinessUnit_Select, { address1_telephone3: string | null }, {  }>;
  address1_upszone: WebAttribute<BusinessUnit_Select, { address1_upszone: string | null }, {  }>;
  address1_utcoffset: WebAttribute<BusinessUnit_Select, { address1_utcoffset: number | null }, {  }>;
  address2_addressid: WebAttribute<BusinessUnit_Select, { address2_addressid: string | null }, {  }>;
  address2_addresstypecode: WebAttribute<BusinessUnit_Select, { address2_addresstypecode: businessunit_address2_addresstypecode | null }, { address2_addresstypecode_formatted?: string }>;
  address2_city: WebAttribute<BusinessUnit_Select, { address2_city: string | null }, {  }>;
  address2_country: WebAttribute<BusinessUnit_Select, { address2_country: string | null }, {  }>;
  address2_county: WebAttribute<BusinessUnit_Select, { address2_county: string | null }, {  }>;
  address2_fax: WebAttribute<BusinessUnit_Select, { address2_fax: string | null }, {  }>;
  address2_latitude: WebAttribute<BusinessUnit_Select, { address2_latitude: number | null }, {  }>;
  address2_line1: WebAttribute<BusinessUnit_Select, { address2_line1: string | null }, {  }>;
  address2_line2: WebAttribute<BusinessUnit_Select, { address2_line2: string | null }, {  }>;
  address2_line3: WebAttribute<BusinessUnit_Select, { address2_line3: string | null }, {  }>;
  address2_longitude: WebAttribute<BusinessUnit_Select, { address2_longitude: number | null }, {  }>;
  address2_name: WebAttribute<BusinessUnit_Select, { address2_name: string | null }, {  }>;
  address2_postalcode: WebAttribute<BusinessUnit_Select, { address2_postalcode: string | null }, {  }>;
  address2_postofficebox: WebAttribute<BusinessUnit_Select, { address2_postofficebox: string | null }, {  }>;
  address2_shippingmethodcode: WebAttribute<BusinessUnit_Select, { address2_shippingmethodcode: businessunit_address2_shippingmethodcode | null }, { address2_shippingmethodcode_formatted?: string }>;
  address2_stateorprovince: WebAttribute<BusinessUnit_Select, { address2_stateorprovince: string | null }, {  }>;
  address2_telephone1: WebAttribute<BusinessUnit_Select, { address2_telephone1: string | null }, {  }>;
  address2_telephone2: WebAttribute<BusinessUnit_Select, { address2_telephone2: string | null }, {  }>;
  address2_telephone3: WebAttribute<BusinessUnit_Select, { address2_telephone3: string | null }, {  }>;
  address2_upszone: WebAttribute<BusinessUnit_Select, { address2_upszone: string | null }, {  }>;
  address2_utcoffset: WebAttribute<BusinessUnit_Select, { address2_utcoffset: number | null }, {  }>;
  businessunitid: WebAttribute<BusinessUnit_Select, { businessunitid: string | null }, {  }>;
  calendarid_guid: WebAttribute<BusinessUnit_Select, { calendarid_guid: string | null }, { calendarid_formatted?: string }>;
  costcenter: WebAttribute<BusinessUnit_Select, { costcenter: string | null }, {  }>;
  createdby_guid: WebAttribute<BusinessUnit_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<BusinessUnit_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<BusinessUnit_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  creditlimit: WebAttribute<BusinessUnit_Select, { creditlimit: number | null }, {  }>;
  description: WebAttribute<BusinessUnit_Select, { description: string | null }, {  }>;
  disabledreason: WebAttribute<BusinessUnit_Select, { disabledreason: string | null }, {  }>;
  divisionname: WebAttribute<BusinessUnit_Select, { divisionname: string | null }, {  }>;
  emailaddress: WebAttribute<BusinessUnit_Select, { emailaddress: string | null }, {  }>;
  exchangerate: WebAttribute<BusinessUnit_Select, { exchangerate: number | null }, {  }>;
  fileasname: WebAttribute<BusinessUnit_Select, { fileasname: string | null }, {  }>;
  ftpsiteurl: WebAttribute<BusinessUnit_Select, { ftpsiteurl: string | null }, {  }>;
  importsequencenumber: WebAttribute<BusinessUnit_Select, { importsequencenumber: number | null }, {  }>;
  inheritancemask: WebAttribute<BusinessUnit_Select, { inheritancemask: number | null }, {  }>;
  isdisabled: WebAttribute<BusinessUnit_Select, { isdisabled: boolean | null }, {  }>;
  modifiedby_guid: WebAttribute<BusinessUnit_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<BusinessUnit_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<BusinessUnit_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  name: WebAttribute<BusinessUnit_Select, { name: string | null }, {  }>;
  organizationid_guid: WebAttribute<BusinessUnit_Select, { organizationid_guid: string | null }, { organizationid_formatted?: string }>;
  overriddencreatedon: WebAttribute<BusinessUnit_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  parentbusinessunitid_guid: WebAttribute<BusinessUnit_Select, { parentbusinessunitid_guid: string | null }, { parentbusinessunitid_formatted?: string }>;
  picture: WebAttribute<BusinessUnit_Select, { picture: string | null }, {  }>;
  stockexchange: WebAttribute<BusinessUnit_Select, { stockexchange: string | null }, {  }>;
  tickersymbol: WebAttribute<BusinessUnit_Select, { tickersymbol: string | null }, {  }>;
  transactioncurrencyid_guid: WebAttribute<BusinessUnit_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  usergroupid: WebAttribute<BusinessUnit_Select, { usergroupid: string | null }, {  }>;
  utcoffset: WebAttribute<BusinessUnit_Select, { utcoffset: number | null }, {  }>;
  versionnumber: WebAttribute<BusinessUnit_Select, { versionnumber: number | null }, {  }>;
  websiteurl: WebAttribute<BusinessUnit_Select, { websiteurl: string | null }, {  }>;
  workflowsuspended: WebAttribute<BusinessUnit_Select, { workflowsuspended: boolean | null }, {  }>;
}
interface BusinessUnit_Filter {
  address1_addressid: XQW.Guid;
  address1_addresstypecode: businessunit_address1_addresstypecode;
  address1_city: string;
  address1_country: string;
  address1_county: string;
  address1_fax: string;
  address1_latitude: number;
  address1_line1: string;
  address1_line2: string;
  address1_line3: string;
  address1_longitude: number;
  address1_name: string;
  address1_postalcode: string;
  address1_postofficebox: string;
  address1_shippingmethodcode: businessunit_address1_shippingmethodcode;
  address1_stateorprovince: string;
  address1_telephone1: string;
  address1_telephone2: string;
  address1_telephone3: string;
  address1_upszone: string;
  address1_utcoffset: number;
  address2_addressid: XQW.Guid;
  address2_addresstypecode: businessunit_address2_addresstypecode;
  address2_city: string;
  address2_country: string;
  address2_county: string;
  address2_fax: string;
  address2_latitude: number;
  address2_line1: string;
  address2_line2: string;
  address2_line3: string;
  address2_longitude: number;
  address2_name: string;
  address2_postalcode: string;
  address2_postofficebox: string;
  address2_shippingmethodcode: businessunit_address2_shippingmethodcode;
  address2_stateorprovince: string;
  address2_telephone1: string;
  address2_telephone2: string;
  address2_telephone3: string;
  address2_upszone: string;
  address2_utcoffset: number;
  businessunitid: XQW.Guid;
  calendarid_guid: XQW.Guid;
  costcenter: string;
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  creditlimit: number;
  description: string;
  disabledreason: string;
  divisionname: string;
  emailaddress: string;
  exchangerate: any;
  fileasname: string;
  ftpsiteurl: string;
  importsequencenumber: number;
  inheritancemask: number;
  isdisabled: boolean;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  name: string;
  organizationid_guid: XQW.Guid;
  overriddencreatedon: Date;
  parentbusinessunitid_guid: XQW.Guid;
  picture: string;
  stockexchange: string;
  tickersymbol: string;
  transactioncurrencyid_guid: XQW.Guid;
  usergroupid: XQW.Guid;
  utcoffset: number;
  versionnumber: number;
  websiteurl: string;
  workflowsuspended: boolean;
}
interface BusinessUnit_Expand {
  BulkDeleteOperation_BusinessUnit: WebExpand<BusinessUnit_Expand, BulkDeleteOperation_Select, BulkDeleteOperation_Filter, { BulkDeleteOperation_BusinessUnit: BulkDeleteOperation_Result[] }>;
  BusinessUnit_AsyncOperations: WebExpand<BusinessUnit_Expand, AsyncOperation_Select, AsyncOperation_Filter, { BusinessUnit_AsyncOperations: AsyncOperation_Result[] }>;
  BusinessUnit_BulkDeleteFailures: WebExpand<BusinessUnit_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { BusinessUnit_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  BusinessUnit_DuplicateRules: WebExpand<BusinessUnit_Expand, DuplicateRule_Select, DuplicateRule_Filter, { BusinessUnit_DuplicateRules: DuplicateRule_Result[] }>;
  BusinessUnit_ImportData: WebExpand<BusinessUnit_Expand, ImportData_Select, ImportData_Filter, { BusinessUnit_ImportData: ImportData_Result[] }>;
  BusinessUnit_ImportFiles: WebExpand<BusinessUnit_Expand, ImportFile_Select, ImportFile_Filter, { BusinessUnit_ImportFiles: ImportFile_Result[] }>;
  BusinessUnit_ImportLogs: WebExpand<BusinessUnit_Expand, ImportLog_Select, ImportLog_Filter, { BusinessUnit_ImportLogs: ImportLog_Result[] }>;
  BusinessUnit_ImportMaps: WebExpand<BusinessUnit_Expand, ImportMap_Select, ImportMap_Filter, { BusinessUnit_ImportMaps: ImportMap_Result[] }>;
  BusinessUnit_Imports: WebExpand<BusinessUnit_Expand, Import_Select, Import_Filter, { BusinessUnit_Imports: Import_Result[] }>;
  BusinessUnit_ProcessSessions: WebExpand<BusinessUnit_Expand, ProcessSession_Select, ProcessSession_Filter, { BusinessUnit_ProcessSessions: ProcessSession_Result[] }>;
  BusinessUnit_SyncError: WebExpand<BusinessUnit_Expand, SyncError_Select, SyncError_Filter, { BusinessUnit_SyncError: SyncError_Result[] }>;
  BusinessUnit_SyncErrors: WebExpand<BusinessUnit_Expand, SyncError_Select, SyncError_Filter, { BusinessUnit_SyncErrors: SyncError_Result[] }>;
  Owning_businessunit_processsessions: WebExpand<BusinessUnit_Expand, ProcessSession_Select, ProcessSession_Filter, { Owning_businessunit_processsessions: ProcessSession_Result[] }>;
  actioncardusersettings_businessunit: WebExpand<BusinessUnit_Expand, ActionCardUserSettings_Select, ActionCardUserSettings_Filter, { actioncardusersettings_businessunit: ActionCardUserSettings_Result[] }>;
  bizmap_businessid_businessunit: WebExpand<BusinessUnit_Expand, BusinessUnitMap_Select, BusinessUnitMap_Filter, { bizmap_businessid_businessunit: BusinessUnitMap_Result[] }>;
  bizmap_subbusinessid_businessunit: WebExpand<BusinessUnit_Expand, BusinessUnitMap_Select, BusinessUnitMap_Filter, { bizmap_subbusinessid_businessunit: BusinessUnitMap_Result[] }>;
  business_unit_PostRegarding: WebExpand<BusinessUnit_Expand, PostRegarding_Select, PostRegarding_Filter, { business_unit_PostRegarding: PostRegarding_Result[] }>;
  business_unit_TraceRegarding: WebExpand<BusinessUnit_Expand, TraceRegarding_Select, TraceRegarding_Filter, { business_unit_TraceRegarding: TraceRegarding_Result[] }>;
  business_unit_accounts: WebExpand<BusinessUnit_Expand, Account_Select, Account_Filter, { business_unit_accounts: Account_Result[] }>;
  business_unit_actioncards: WebExpand<BusinessUnit_Expand, ActionCard_Select, ActionCard_Filter, { business_unit_actioncards: ActionCard_Result[] }>;
  business_unit_activityfileattachment: WebExpand<BusinessUnit_Expand, activityfileattachment_Select, activityfileattachment_Filter, { business_unit_activityfileattachment: activityfileattachment_Result[] }>;
  business_unit_activitypointer: WebExpand<BusinessUnit_Expand, ActivityPointer_Select, ActivityPointer_Filter, { business_unit_activitypointer: ActivityPointer_Result[] }>;
  business_unit_annotations: WebExpand<BusinessUnit_Expand, Annotation_Select, Annotation_Filter, { business_unit_annotations: Annotation_Result[] }>;
  business_unit_applicationuser: WebExpand<BusinessUnit_Expand, ApplicationUser_Select, ApplicationUser_Filter, { business_unit_applicationuser: ApplicationUser_Result[] }>;
  business_unit_appnotification: WebExpand<BusinessUnit_Expand, appnotification_Select, appnotification_Filter, { business_unit_appnotification: appnotification_Result[] }>;
  business_unit_appointment_activities: WebExpand<BusinessUnit_Expand, Appointment_Select, Appointment_Filter, { business_unit_appointment_activities: Appointment_Result[] }>;
  business_unit_asyncoperation: WebExpand<BusinessUnit_Expand, AsyncOperation_Select, AsyncOperation_Filter, { business_unit_asyncoperation: AsyncOperation_Result[] }>;
  business_unit_bot: WebExpand<BusinessUnit_Expand, bot_Select, bot_Filter, { business_unit_bot: bot_Result[] }>;
  business_unit_botcomponent: WebExpand<BusinessUnit_Expand, botcomponent_Select, botcomponent_Filter, { business_unit_botcomponent: botcomponent_Result[] }>;
  business_unit_calendars: WebExpand<BusinessUnit_Expand, Calendar_Select, Calendar_Filter, { business_unit_calendars: Calendar_Result[] }>;
  business_unit_canvasappextendedmetadata: WebExpand<BusinessUnit_Expand, CanvasAppExtendedMetadata_Select, CanvasAppExtendedMetadata_Filter, { business_unit_canvasappextendedmetadata: CanvasAppExtendedMetadata_Result[] }>;
  business_unit_category: WebExpand<BusinessUnit_Expand, Category_Select, Category_Filter, { business_unit_category: Category_Result[] }>;
  business_unit_channelaccessprofile: WebExpand<BusinessUnit_Expand, ChannelAccessProfile_Select, ChannelAccessProfile_Filter, { business_unit_channelaccessprofile: ChannelAccessProfile_Result[] }>;
  business_unit_connectionreference: WebExpand<BusinessUnit_Expand, connectionreference_Select, connectionreference_Filter, { business_unit_connectionreference: connectionreference_Result[] }>;
  business_unit_connections: WebExpand<BusinessUnit_Expand, Connection_Select, Connection_Filter, { business_unit_connections: Connection_Result[] }>;
  business_unit_connector: WebExpand<BusinessUnit_Expand, connector_Select, connector_Filter, { business_unit_connector: connector_Result[] }>;
  business_unit_contacts: WebExpand<BusinessUnit_Expand, Contact_Select, Contact_Filter, { business_unit_contacts: Contact_Result[] }>;
  business_unit_conversationtranscript: WebExpand<BusinessUnit_Expand, conversationtranscript_Select, conversationtranscript_Filter, { business_unit_conversationtranscript: conversationtranscript_Result[] }>;
  business_unit_convertrule: WebExpand<BusinessUnit_Expand, ConvertRule_Select, ConvertRule_Filter, { business_unit_convertrule: ConvertRule_Result[] }>;
  business_unit_customapi: WebExpand<BusinessUnit_Expand, CustomAPI_Select, CustomAPI_Filter, { business_unit_customapi: CustomAPI_Result[] }>;
  business_unit_customapirequestparameter: WebExpand<BusinessUnit_Expand, CustomAPIRequestParameter_Select, CustomAPIRequestParameter_Filter, { business_unit_customapirequestparameter: CustomAPIRequestParameter_Result[] }>;
  business_unit_customapiresponseproperty: WebExpand<BusinessUnit_Expand, CustomAPIResponseProperty_Select, CustomAPIResponseProperty_Filter, { business_unit_customapiresponseproperty: CustomAPIResponseProperty_Result[] }>;
  business_unit_customer_relationship: WebExpand<BusinessUnit_Expand, CustomerRelationship_Select, CustomerRelationship_Filter, { business_unit_customer_relationship: CustomerRelationship_Result[] }>;
  business_unit_datalakefolder: WebExpand<BusinessUnit_Expand, datalakefolder_Select, datalakefolder_Filter, { business_unit_datalakefolder: datalakefolder_Result[] }>;
  business_unit_datalakefolderpermission: WebExpand<BusinessUnit_Expand, datalakefolderpermission_Select, datalakefolderpermission_Filter, { business_unit_datalakefolderpermission: datalakefolderpermission_Result[] }>;
  business_unit_email_activities: WebExpand<BusinessUnit_Expand, Email_Select, Email_Filter, { business_unit_email_activities: Email_Result[] }>;
  business_unit_emailserverprofile: WebExpand<BusinessUnit_Expand, EmailServerProfile_Select, EmailServerProfile_Filter, { business_unit_emailserverprofile: EmailServerProfile_Result[] }>;
  business_unit_emailsignatures: WebExpand<BusinessUnit_Expand, EmailSignature_Select, EmailSignature_Filter, { business_unit_emailsignatures: EmailSignature_Result[] }>;
  business_unit_environmentvariabledefinition: WebExpand<BusinessUnit_Expand, EnvironmentVariableDefinition_Select, EnvironmentVariableDefinition_Filter, { business_unit_environmentvariabledefinition: EnvironmentVariableDefinition_Result[] }>;
  business_unit_environmentvariablevalue: WebExpand<BusinessUnit_Expand, EnvironmentVariableValue_Select, EnvironmentVariableValue_Filter, { business_unit_environmentvariablevalue: EnvironmentVariableValue_Result[] }>;
  business_unit_exchangesyncidmapping: WebExpand<BusinessUnit_Expand, ExchangeSyncIdMapping_Select, ExchangeSyncIdMapping_Filter, { business_unit_exchangesyncidmapping: ExchangeSyncIdMapping_Result[] }>;
  business_unit_exportsolutionupload: WebExpand<BusinessUnit_Expand, ExportSolutionUpload_Select, ExportSolutionUpload_Filter, { business_unit_exportsolutionupload: ExportSolutionUpload_Result[] }>;
  business_unit_externalparty: WebExpand<BusinessUnit_Expand, ExternalParty_Select, ExternalParty_Filter, { business_unit_externalparty: ExternalParty_Result[] }>;
  business_unit_fax_activities: WebExpand<BusinessUnit_Expand, Fax_Select, Fax_Filter, { business_unit_fax_activities: Fax_Result[] }>;
  business_unit_featurecontrolsetting: WebExpand<BusinessUnit_Expand, featurecontrolsetting_Select, featurecontrolsetting_Filter, { business_unit_featurecontrolsetting: featurecontrolsetting_Result[] }>;
  business_unit_feedback: WebExpand<BusinessUnit_Expand, Feedback_Select, Feedback_Filter, { business_unit_feedback: Feedback_Result[] }>;
  business_unit_flowmachine: WebExpand<BusinessUnit_Expand, flowmachine_Select, flowmachine_Filter, { business_unit_flowmachine: flowmachine_Result[] }>;
  business_unit_flowmachinegroup: WebExpand<BusinessUnit_Expand, flowmachinegroup_Select, flowmachinegroup_Filter, { business_unit_flowmachinegroup: flowmachinegroup_Result[] }>;
  business_unit_flowsession: WebExpand<BusinessUnit_Expand, flowsession_Select, flowsession_Filter, { business_unit_flowsession: flowsession_Result[] }>;
  business_unit_goal: WebExpand<BusinessUnit_Expand, Goal_Select, Goal_Filter, { business_unit_goal: Goal_Result[] }>;
  business_unit_goalrollupquery: WebExpand<BusinessUnit_Expand, GoalRollupQuery_Select, GoalRollupQuery_Filter, { business_unit_goalrollupquery: GoalRollupQuery_Result[] }>;
  business_unit_keyvaultreference: WebExpand<BusinessUnit_Expand, KeyVaultReference_Select, KeyVaultReference_Filter, { business_unit_keyvaultreference: KeyVaultReference_Result[] }>;
  business_unit_knowledgearticle: WebExpand<BusinessUnit_Expand, KnowledgeArticle_Select, KnowledgeArticle_Filter, { business_unit_knowledgearticle: KnowledgeArticle_Result[] }>;
  business_unit_letter_activities: WebExpand<BusinessUnit_Expand, Letter_Select, Letter_Filter, { business_unit_letter_activities: Letter_Result[] }>;
  business_unit_mailbox: WebExpand<BusinessUnit_Expand, Mailbox_Select, Mailbox_Filter, { business_unit_mailbox: Mailbox_Result[] }>;
  business_unit_mailmergetemplates: WebExpand<BusinessUnit_Expand, MailMergeTemplate_Select, MailMergeTemplate_Filter, { business_unit_mailmergetemplates: MailMergeTemplate_Result[] }>;
  business_unit_managedidentity: WebExpand<BusinessUnit_Expand, ManagedIdentity_Select, ManagedIdentity_Filter, { business_unit_managedidentity: ManagedIdentity_Result[] }>;
  business_unit_msdyn_aibdataset: WebExpand<BusinessUnit_Expand, msdyn_AIBDataset_Select, msdyn_AIBDataset_Filter, { business_unit_msdyn_aibdataset: msdyn_AIBDataset_Result[] }>;
  business_unit_msdyn_aibdatasetfile: WebExpand<BusinessUnit_Expand, msdyn_AIBDatasetFile_Select, msdyn_AIBDatasetFile_Filter, { business_unit_msdyn_aibdatasetfile: msdyn_AIBDatasetFile_Result[] }>;
  business_unit_msdyn_aibdatasetrecord: WebExpand<BusinessUnit_Expand, msdyn_AIBDatasetRecord_Select, msdyn_AIBDatasetRecord_Filter, { business_unit_msdyn_aibdatasetrecord: msdyn_AIBDatasetRecord_Result[] }>;
  business_unit_msdyn_aibdatasetscontainer: WebExpand<BusinessUnit_Expand, msdyn_AIBDatasetsContainer_Select, msdyn_AIBDatasetsContainer_Filter, { business_unit_msdyn_aibdatasetscontainer: msdyn_AIBDatasetsContainer_Result[] }>;
  business_unit_msdyn_aibfile: WebExpand<BusinessUnit_Expand, msdyn_AIBFile_Select, msdyn_AIBFile_Filter, { business_unit_msdyn_aibfile: msdyn_AIBFile_Result[] }>;
  business_unit_msdyn_aibfileattacheddata: WebExpand<BusinessUnit_Expand, msdyn_AIBFileAttachedData_Select, msdyn_AIBFileAttachedData_Filter, { business_unit_msdyn_aibfileattacheddata: msdyn_AIBFileAttachedData_Result[] }>;
  business_unit_msdyn_aiconfiguration: WebExpand<BusinessUnit_Expand, msdyn_AIConfiguration_Select, msdyn_AIConfiguration_Filter, { business_unit_msdyn_aiconfiguration: msdyn_AIConfiguration_Result[] }>;
  business_unit_msdyn_aifptrainingdocument: WebExpand<BusinessUnit_Expand, msdyn_AIFpTrainingDocument_Select, msdyn_AIFpTrainingDocument_Filter, { business_unit_msdyn_aifptrainingdocument: msdyn_AIFpTrainingDocument_Result[] }>;
  business_unit_msdyn_aimodel: WebExpand<BusinessUnit_Expand, msdyn_AIModel_Select, msdyn_AIModel_Filter, { business_unit_msdyn_aimodel: msdyn_AIModel_Result[] }>;
  business_unit_msdyn_aiodimage: WebExpand<BusinessUnit_Expand, msdyn_AIOdImage_Select, msdyn_AIOdImage_Filter, { business_unit_msdyn_aiodimage: msdyn_AIOdImage_Result[] }>;
  business_unit_msdyn_aiodlabel: WebExpand<BusinessUnit_Expand, msdyn_AIOdLabel_Select, msdyn_AIOdLabel_Filter, { business_unit_msdyn_aiodlabel: msdyn_AIOdLabel_Result[] }>;
  business_unit_msdyn_aiodtrainingboundingbox: WebExpand<BusinessUnit_Expand, msdyn_AIOdTrainingBoundingBox_Select, msdyn_AIOdTrainingBoundingBox_Filter, { business_unit_msdyn_aiodtrainingboundingbox: msdyn_AIOdTrainingBoundingBox_Result[] }>;
  business_unit_msdyn_aiodtrainingimage: WebExpand<BusinessUnit_Expand, msdyn_AIOdTrainingImage_Select, msdyn_AIOdTrainingImage_Filter, { business_unit_msdyn_aiodtrainingimage: msdyn_AIOdTrainingImage_Result[] }>;
  business_unit_msdyn_aitemplate: WebExpand<BusinessUnit_Expand, msdyn_AITemplate_Select, msdyn_AITemplate_Filter, { business_unit_msdyn_aitemplate: msdyn_AITemplate_Result[] }>;
  business_unit_msdyn_analysiscomponent: WebExpand<BusinessUnit_Expand, msdyn_analysiscomponent_Select, msdyn_analysiscomponent_Filter, { business_unit_msdyn_analysiscomponent: msdyn_analysiscomponent_Result[] }>;
  business_unit_msdyn_analysisjob: WebExpand<BusinessUnit_Expand, msdyn_analysisjob_Select, msdyn_analysisjob_Filter, { business_unit_msdyn_analysisjob: msdyn_analysisjob_Result[] }>;
  business_unit_msdyn_analysisresult: WebExpand<BusinessUnit_Expand, msdyn_analysisresult_Select, msdyn_analysisresult_Filter, { business_unit_msdyn_analysisresult: msdyn_analysisresult_Result[] }>;
  business_unit_msdyn_analysisresultdetail: WebExpand<BusinessUnit_Expand, msdyn_analysisresultdetail_Select, msdyn_analysisresultdetail_Filter, { business_unit_msdyn_analysisresultdetail: msdyn_analysisresultdetail_Result[] }>;
  business_unit_msdyn_dataflow: WebExpand<BusinessUnit_Expand, msdyn_dataflow_Select, msdyn_dataflow_Filter, { business_unit_msdyn_dataflow: msdyn_dataflow_Result[] }>;
  business_unit_msdyn_federatedarticle: WebExpand<BusinessUnit_Expand, msdyn_federatedarticle_Select, msdyn_federatedarticle_Filter, { business_unit_msdyn_federatedarticle: msdyn_federatedarticle_Result[] }>;
  business_unit_msdyn_kalanguagesetting: WebExpand<BusinessUnit_Expand, msdyn_kalanguagesetting_Select, msdyn_kalanguagesetting_Filter, { business_unit_msdyn_kalanguagesetting: msdyn_kalanguagesetting_Result[] }>;
  business_unit_msdyn_kmfederatedsearchconfig: WebExpand<BusinessUnit_Expand, msdyn_kmfederatedsearchconfig_Select, msdyn_kmfederatedsearchconfig_Filter, { business_unit_msdyn_kmfederatedsearchconfig: msdyn_kmfederatedsearchconfig_Result[] }>;
  business_unit_msdyn_knowledgearticleimage: WebExpand<BusinessUnit_Expand, msdyn_knowledgearticleimage_Select, msdyn_knowledgearticleimage_Filter, { business_unit_msdyn_knowledgearticleimage: msdyn_knowledgearticleimage_Result[] }>;
  business_unit_msdyn_knowledgearticletemplate: WebExpand<BusinessUnit_Expand, msdyn_knowledgearticletemplate_Select, msdyn_knowledgearticletemplate_Filter, { business_unit_msdyn_knowledgearticletemplate: msdyn_knowledgearticletemplate_Result[] }>;
  business_unit_msdyn_knowledgeinteractioninsight: WebExpand<BusinessUnit_Expand, msdyn_knowledgeinteractioninsight_Select, msdyn_knowledgeinteractioninsight_Filter, { business_unit_msdyn_knowledgeinteractioninsight: msdyn_knowledgeinteractioninsight_Result[] }>;
  business_unit_msdyn_knowledgepersonalfilter: WebExpand<BusinessUnit_Expand, msdyn_knowledgepersonalfilter_Select, msdyn_knowledgepersonalfilter_Filter, { business_unit_msdyn_knowledgepersonalfilter: msdyn_knowledgepersonalfilter_Result[] }>;
  business_unit_msdyn_knowledgesearchfilter: WebExpand<BusinessUnit_Expand, msdyn_knowledgesearchfilter_Select, msdyn_knowledgesearchfilter_Filter, { business_unit_msdyn_knowledgesearchfilter: msdyn_knowledgesearchfilter_Result[] }>;
  business_unit_msdyn_knowledgesearchinsight: WebExpand<BusinessUnit_Expand, msdyn_knowledgesearchinsight_Select, msdyn_knowledgesearchinsight_Filter, { business_unit_msdyn_knowledgesearchinsight: msdyn_knowledgesearchinsight_Result[] }>;
  business_unit_msdyn_pminferredtask: WebExpand<BusinessUnit_Expand, msdyn_pminferredtask_Select, msdyn_pminferredtask_Filter, { business_unit_msdyn_pminferredtask: msdyn_pminferredtask_Result[] }>;
  business_unit_msdyn_pmrecording: WebExpand<BusinessUnit_Expand, msdyn_pmrecording_Select, msdyn_pmrecording_Filter, { business_unit_msdyn_pmrecording: msdyn_pmrecording_Result[] }>;
  business_unit_msdyn_richtextfile: WebExpand<BusinessUnit_Expand, msdyn_richtextfile_Select, msdyn_richtextfile_Filter, { business_unit_msdyn_richtextfile: msdyn_richtextfile_Result[] }>;
  business_unit_msdyn_serviceconfiguration: WebExpand<BusinessUnit_Expand, msdyn_serviceconfiguration_Select, msdyn_serviceconfiguration_Filter, { business_unit_msdyn_serviceconfiguration: msdyn_serviceconfiguration_Result[] }>;
  business_unit_msdyn_slakpi: WebExpand<BusinessUnit_Expand, msdyn_slakpi_Select, msdyn_slakpi_Filter, { business_unit_msdyn_slakpi: msdyn_slakpi_Result[] }>;
  business_unit_msdyn_solutionhealthrule: WebExpand<BusinessUnit_Expand, msdyn_solutionhealthrule_Select, msdyn_solutionhealthrule_Filter, { business_unit_msdyn_solutionhealthrule: msdyn_solutionhealthrule_Result[] }>;
  business_unit_msdyn_solutionhealthruleargument: WebExpand<BusinessUnit_Expand, msdyn_solutionhealthruleargument_Select, msdyn_solutionhealthruleargument_Filter, { business_unit_msdyn_solutionhealthruleargument: msdyn_solutionhealthruleargument_Result[] }>;
  business_unit_msdynce_botcontent: WebExpand<BusinessUnit_Expand, msdynce_botcontent_Select, msdynce_botcontent_Filter, { business_unit_msdynce_botcontent: msdynce_botcontent_Result[] }>;
  business_unit_new_interactionforemail: WebExpand<BusinessUnit_Expand, InteractionForEmail_Select, InteractionForEmail_Filter, { business_unit_new_interactionforemail: InteractionForEmail_Result[] }>;
  business_unit_parent_business_unit: WebExpand<BusinessUnit_Expand, BusinessUnit_Select, BusinessUnit_Filter, { business_unit_parent_business_unit: BusinessUnit_Result[] }>;
  business_unit_pdfsetting: WebExpand<BusinessUnit_Expand, PDFSetting_Select, PDFSetting_Filter, { business_unit_pdfsetting: PDFSetting_Result[] }>;
  business_unit_personaldocumenttemplates: WebExpand<BusinessUnit_Expand, PersonalDocumentTemplate_Select, PersonalDocumentTemplate_Filter, { business_unit_personaldocumenttemplates: PersonalDocumentTemplate_Result[] }>;
  business_unit_phone_call_activities: WebExpand<BusinessUnit_Expand, PhoneCall_Select, PhoneCall_Filter, { business_unit_phone_call_activities: PhoneCall_Result[] }>;
  business_unit_postfollows: WebExpand<BusinessUnit_Expand, PostFollow_Select, PostFollow_Filter, { business_unit_postfollows: PostFollow_Result[] }>;
  business_unit_principalentitybusinessunitmap: WebExpand<BusinessUnit_Expand, PrincipalEntityBusinessUnitMap_Select, PrincipalEntityBusinessUnitMap_Filter, { business_unit_principalentitybusinessunitmap: PrincipalEntityBusinessUnitMap_Result[] }>;
  business_unit_processstageparameter: WebExpand<BusinessUnit_Expand, processstageparameter_Select, processstageparameter_Filter, { business_unit_processstageparameter: processstageparameter_Result[] }>;
  business_unit_profilerule: WebExpand<BusinessUnit_Expand, ChannelAccessProfileRule_Select, ChannelAccessProfileRule_Filter, { business_unit_profilerule: ChannelAccessProfileRule_Result[] }>;
  business_unit_queues: WebExpand<BusinessUnit_Expand, Queue_Select, Queue_Filter, { business_unit_queues: Queue_Result[] }>;
  business_unit_queues2: WebExpand<BusinessUnit_Expand, Queue_Select, Queue_Filter, { business_unit_queues2: Queue_Result[] }>;
  business_unit_recurrencerule: WebExpand<BusinessUnit_Expand, RecurrenceRule_Select, RecurrenceRule_Filter, { business_unit_recurrencerule: RecurrenceRule_Result[] }>;
  business_unit_recurringappointmentmaster_activities: WebExpand<BusinessUnit_Expand, RecurringAppointmentMaster_Select, RecurringAppointmentMaster_Filter, { business_unit_recurringappointmentmaster_activities: RecurringAppointmentMaster_Result[] }>;
  business_unit_reports: WebExpand<BusinessUnit_Expand, Report_Select, Report_Filter, { business_unit_reports: Report_Result[] }>;
  business_unit_revokeinheritedaccessrecordstracker: WebExpand<BusinessUnit_Expand, revokeinheritedaccessrecordstracker_Select, revokeinheritedaccessrecordstracker_Filter, { business_unit_revokeinheritedaccessrecordstracker: revokeinheritedaccessrecordstracker_Result[] }>;
  business_unit_roles: WebExpand<BusinessUnit_Expand, Role_Select, Role_Filter, { business_unit_roles: Role_Result[] }>;
  business_unit_routingrule: WebExpand<BusinessUnit_Expand, RoutingRule_Select, RoutingRule_Filter, { business_unit_routingrule: RoutingRule_Result[] }>;
  business_unit_sharepointdocument: WebExpand<BusinessUnit_Expand, SharePointDocument_Select, SharePointDocument_Filter, { business_unit_sharepointdocument: SharePointDocument_Result[] }>;
  business_unit_sharepointdocument2: WebExpand<BusinessUnit_Expand, SharePointDocument_Select, SharePointDocument_Filter, { business_unit_sharepointdocument2: SharePointDocument_Result[] }>;
  business_unit_sharepointdocumentlocation: WebExpand<BusinessUnit_Expand, SharePointDocumentLocation_Select, SharePointDocumentLocation_Filter, { business_unit_sharepointdocumentlocation: SharePointDocumentLocation_Result[] }>;
  business_unit_sharepointsites: WebExpand<BusinessUnit_Expand, SharePointSite_Select, SharePointSite_Filter, { business_unit_sharepointsites: SharePointSite_Result[] }>;
  business_unit_slabase: WebExpand<BusinessUnit_Expand, SLA_Select, SLA_Filter, { business_unit_slabase: SLA_Result[] }>;
  business_unit_slakpiinstance: WebExpand<BusinessUnit_Expand, SLAKPIInstance_Select, SLAKPIInstance_Filter, { business_unit_slakpiinstance: SLAKPIInstance_Result[] }>;
  business_unit_socialactivity: WebExpand<BusinessUnit_Expand, SocialActivity_Select, SocialActivity_Filter, { business_unit_socialactivity: SocialActivity_Result[] }>;
  business_unit_socialprofiles: WebExpand<BusinessUnit_Expand, SocialProfile_Select, SocialProfile_Filter, { business_unit_socialprofiles: SocialProfile_Result[] }>;
  business_unit_solutioncomponentbatchconfiguration: WebExpand<BusinessUnit_Expand, solutioncomponentbatchconfiguration_Select, solutioncomponentbatchconfiguration_Filter, { business_unit_solutioncomponentbatchconfiguration: solutioncomponentbatchconfiguration_Result[] }>;
  business_unit_stagesolutionupload: WebExpand<BusinessUnit_Expand, StageSolutionUpload_Select, StageSolutionUpload_Filter, { business_unit_stagesolutionupload: StageSolutionUpload_Result[] }>;
  business_unit_system_users: WebExpand<BusinessUnit_Expand, SystemUser_Select, SystemUser_Filter, { business_unit_system_users: SystemUser_Result[] }>;
  business_unit_task_activities: WebExpand<BusinessUnit_Expand, Task_Select, Task_Filter, { business_unit_task_activities: Task_Result[] }>;
  business_unit_teams: WebExpand<BusinessUnit_Expand, Team_Select, Team_Filter, { business_unit_teams: Team_Result[] }>;
  business_unit_templates: WebExpand<BusinessUnit_Expand, Template_Select, Template_Filter, { business_unit_templates: Template_Result[] }>;
  business_unit_untrackedemail_activities: WebExpand<BusinessUnit_Expand, UntrackedEmail_Select, UntrackedEmail_Filter, { business_unit_untrackedemail_activities: UntrackedEmail_Result[] }>;
  business_unit_user_settings: WebExpand<BusinessUnit_Expand, UserSettings_Select, UserSettings_Filter, { business_unit_user_settings: UserSettings_Result[] }>;
  business_unit_userapplicationmetadata: WebExpand<BusinessUnit_Expand, UserApplicationMetadata_Select, UserApplicationMetadata_Filter, { business_unit_userapplicationmetadata: UserApplicationMetadata_Result[] }>;
  business_unit_userform: WebExpand<BusinessUnit_Expand, UserForm_Select, UserForm_Filter, { business_unit_userform: UserForm_Result[] }>;
  business_unit_userquery: WebExpand<BusinessUnit_Expand, UserQuery_Select, UserQuery_Filter, { business_unit_userquery: UserQuery_Result[] }>;
  business_unit_userqueryvisualizations: WebExpand<BusinessUnit_Expand, UserQueryVisualization_Select, UserQueryVisualization_Filter, { business_unit_userqueryvisualizations: UserQueryVisualization_Result[] }>;
  business_unit_workflow: WebExpand<BusinessUnit_Expand, Workflow_Select, Workflow_Filter, { business_unit_workflow: Workflow_Result[] }>;
  business_unit_workflowbinary: WebExpand<BusinessUnit_Expand, workflowbinary_Select, workflowbinary_Filter, { business_unit_workflowbinary: workflowbinary_Result[] }>;
  business_unit_workflowlogs: WebExpand<BusinessUnit_Expand, WorkflowLog_Select, WorkflowLog_Filter, { business_unit_workflowlogs: WorkflowLog_Result[] }>;
  businessunit_callbackregistration: WebExpand<BusinessUnit_Expand, CallbackRegistration_Select, CallbackRegistration_Filter, { businessunit_callbackregistration: CallbackRegistration_Result[] }>;
  businessunit_canvasapp: WebExpand<BusinessUnit_Expand, CanvasApp_Select, CanvasApp_Filter, { businessunit_canvasapp: CanvasApp_Result[] }>;
  businessunit_canvasappextendedmetadata: WebExpand<BusinessUnit_Expand, CanvasAppExtendedMetadata_Select, CanvasAppExtendedMetadata_Filter, { businessunit_canvasappextendedmetadata: CanvasAppExtendedMetadata_Result[] }>;
  businessunit_internal_addresses: WebExpand<BusinessUnit_Expand, InternalAddress_Select, InternalAddress_Filter, { businessunit_internal_addresses: InternalAddress_Result[] }>;
  businessunit_mailboxtrackingcategory: WebExpand<BusinessUnit_Expand, MailboxTrackingCategory_Select, MailboxTrackingCategory_Filter, { businessunit_mailboxtrackingcategory: MailboxTrackingCategory_Result[] }>;
  businessunit_mailboxtrackingfolder: WebExpand<BusinessUnit_Expand, MailboxTrackingFolder_Select, MailboxTrackingFolder_Filter, { businessunit_mailboxtrackingfolder: MailboxTrackingFolder_Result[] }>;
  businessunit_principalobjectattributeaccess: WebExpand<BusinessUnit_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { businessunit_principalobjectattributeaccess: PrincipalObjectAttributeAccess_Result[] }>;
  calendarid: WebExpand<BusinessUnit_Expand, Calendar_Select, Calendar_Filter, { calendarid: Calendar_Result }>;
  createdby: WebExpand<BusinessUnit_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<BusinessUnit_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  lk_userfiscalcalendar_businessunit: WebExpand<BusinessUnit_Expand, UserFiscalCalendar_Select, UserFiscalCalendar_Filter, { lk_userfiscalcalendar_businessunit: UserFiscalCalendar_Result[] }>;
  mbs_businessunit_mbs_pluginprofile: WebExpand<BusinessUnit_Expand, mbs_pluginprofile_Select, mbs_pluginprofile_Filter, { mbs_businessunit_mbs_pluginprofile: mbs_pluginprofile_Result[] }>;
  modifiedby: WebExpand<BusinessUnit_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<BusinessUnit_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  organizationid: WebExpand<BusinessUnit_Expand, Organization_Select, Organization_Filter, { organizationid: Organization_Result }>;
  parentbusinessunitid: WebExpand<BusinessUnit_Expand, BusinessUnit_Select, BusinessUnit_Filter, { parentbusinessunitid: BusinessUnit_Result }>;
  systemuserbusinessunitentitymap_businessunitid_businessunit: WebExpand<BusinessUnit_Expand, SystemUserBusinessUnitEntityMap_Select, SystemUserBusinessUnitEntityMap_Filter, { systemuserbusinessunitentitymap_businessunitid_businessunit: SystemUserBusinessUnitEntityMap_Result[] }>;
  transactioncurrencyid: WebExpand<BusinessUnit_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid: TransactionCurrency_Result }>;
  userentityinstancedata_businessunit: WebExpand<BusinessUnit_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { userentityinstancedata_businessunit: UserEntityInstanceData_Result[] }>;
  userentityuisettings_businessunit: WebExpand<BusinessUnit_Expand, UserEntityUISettings_Select, UserEntityUISettings_Filter, { userentityuisettings_businessunit: UserEntityUISettings_Result[] }>;
}
interface BusinessUnit_FormattedResult {
  address1_addresstypecode_formatted?: string;
  address1_shippingmethodcode_formatted?: string;
  address2_addresstypecode_formatted?: string;
  address2_shippingmethodcode_formatted?: string;
  calendarid_formatted?: string;
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  organizationid_formatted?: string;
  overriddencreatedon_formatted?: string;
  parentbusinessunitid_formatted?: string;
  transactioncurrencyid_formatted?: string;
}
interface BusinessUnit_Result extends BusinessUnit_Base, BusinessUnit_Relationships {
  "@odata.etag": string;
  calendarid_guid: string | null;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  organizationid_guid: string | null;
  parentbusinessunitid_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface BusinessUnit_RelatedOne {
  calendarid: WebMappingRetrieve<Calendar_Select,Calendar_Expand,Calendar_Filter,Calendar_Fixed,Calendar_Result,Calendar_FormattedResult>;
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  organizationid: WebMappingRetrieve<Organization_Select,Organization_Expand,Organization_Filter,Organization_Fixed,Organization_Result,Organization_FormattedResult>;
  parentbusinessunitid: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  transactioncurrencyid: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface BusinessUnit_RelatedMany {
  BulkDeleteOperation_BusinessUnit: WebMappingRetrieve<BulkDeleteOperation_Select,BulkDeleteOperation_Expand,BulkDeleteOperation_Filter,BulkDeleteOperation_Fixed,BulkDeleteOperation_Result,BulkDeleteOperation_FormattedResult>;
  BusinessUnit_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  BusinessUnit_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  BusinessUnit_DuplicateRules: WebMappingRetrieve<DuplicateRule_Select,DuplicateRule_Expand,DuplicateRule_Filter,DuplicateRule_Fixed,DuplicateRule_Result,DuplicateRule_FormattedResult>;
  BusinessUnit_ImportData: WebMappingRetrieve<ImportData_Select,ImportData_Expand,ImportData_Filter,ImportData_Fixed,ImportData_Result,ImportData_FormattedResult>;
  BusinessUnit_ImportFiles: WebMappingRetrieve<ImportFile_Select,ImportFile_Expand,ImportFile_Filter,ImportFile_Fixed,ImportFile_Result,ImportFile_FormattedResult>;
  BusinessUnit_ImportLogs: WebMappingRetrieve<ImportLog_Select,ImportLog_Expand,ImportLog_Filter,ImportLog_Fixed,ImportLog_Result,ImportLog_FormattedResult>;
  BusinessUnit_ImportMaps: WebMappingRetrieve<ImportMap_Select,ImportMap_Expand,ImportMap_Filter,ImportMap_Fixed,ImportMap_Result,ImportMap_FormattedResult>;
  BusinessUnit_Imports: WebMappingRetrieve<Import_Select,Import_Expand,Import_Filter,Import_Fixed,Import_Result,Import_FormattedResult>;
  BusinessUnit_ProcessSessions: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  BusinessUnit_SyncError: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  BusinessUnit_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  Owning_businessunit_processsessions: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  actioncardusersettings_businessunit: WebMappingRetrieve<ActionCardUserSettings_Select,ActionCardUserSettings_Expand,ActionCardUserSettings_Filter,ActionCardUserSettings_Fixed,ActionCardUserSettings_Result,ActionCardUserSettings_FormattedResult>;
  bizmap_businessid_businessunit: WebMappingRetrieve<BusinessUnitMap_Select,BusinessUnitMap_Expand,BusinessUnitMap_Filter,BusinessUnitMap_Fixed,BusinessUnitMap_Result,BusinessUnitMap_FormattedResult>;
  bizmap_subbusinessid_businessunit: WebMappingRetrieve<BusinessUnitMap_Select,BusinessUnitMap_Expand,BusinessUnitMap_Filter,BusinessUnitMap_Fixed,BusinessUnitMap_Result,BusinessUnitMap_FormattedResult>;
  business_unit_PostRegarding: WebMappingRetrieve<PostRegarding_Select,PostRegarding_Expand,PostRegarding_Filter,PostRegarding_Fixed,PostRegarding_Result,PostRegarding_FormattedResult>;
  business_unit_TraceRegarding: WebMappingRetrieve<TraceRegarding_Select,TraceRegarding_Expand,TraceRegarding_Filter,TraceRegarding_Fixed,TraceRegarding_Result,TraceRegarding_FormattedResult>;
  business_unit_accounts: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  business_unit_actioncards: WebMappingRetrieve<ActionCard_Select,ActionCard_Expand,ActionCard_Filter,ActionCard_Fixed,ActionCard_Result,ActionCard_FormattedResult>;
  business_unit_activityfileattachment: WebMappingRetrieve<activityfileattachment_Select,activityfileattachment_Expand,activityfileattachment_Filter,activityfileattachment_Fixed,activityfileattachment_Result,activityfileattachment_FormattedResult>;
  business_unit_activitypointer: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  business_unit_annotations: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  business_unit_applicationuser: WebMappingRetrieve<ApplicationUser_Select,ApplicationUser_Expand,ApplicationUser_Filter,ApplicationUser_Fixed,ApplicationUser_Result,ApplicationUser_FormattedResult>;
  business_unit_appnotification: WebMappingRetrieve<appnotification_Select,appnotification_Expand,appnotification_Filter,appnotification_Fixed,appnotification_Result,appnotification_FormattedResult>;
  business_unit_appointment_activities: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
  business_unit_asyncoperation: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  business_unit_bot: WebMappingRetrieve<bot_Select,bot_Expand,bot_Filter,bot_Fixed,bot_Result,bot_FormattedResult>;
  business_unit_botcomponent: WebMappingRetrieve<botcomponent_Select,botcomponent_Expand,botcomponent_Filter,botcomponent_Fixed,botcomponent_Result,botcomponent_FormattedResult>;
  business_unit_calendars: WebMappingRetrieve<Calendar_Select,Calendar_Expand,Calendar_Filter,Calendar_Fixed,Calendar_Result,Calendar_FormattedResult>;
  business_unit_canvasappextendedmetadata: WebMappingRetrieve<CanvasAppExtendedMetadata_Select,CanvasAppExtendedMetadata_Expand,CanvasAppExtendedMetadata_Filter,CanvasAppExtendedMetadata_Fixed,CanvasAppExtendedMetadata_Result,CanvasAppExtendedMetadata_FormattedResult>;
  business_unit_category: WebMappingRetrieve<Category_Select,Category_Expand,Category_Filter,Category_Fixed,Category_Result,Category_FormattedResult>;
  business_unit_channelaccessprofile: WebMappingRetrieve<ChannelAccessProfile_Select,ChannelAccessProfile_Expand,ChannelAccessProfile_Filter,ChannelAccessProfile_Fixed,ChannelAccessProfile_Result,ChannelAccessProfile_FormattedResult>;
  business_unit_connectionreference: WebMappingRetrieve<connectionreference_Select,connectionreference_Expand,connectionreference_Filter,connectionreference_Fixed,connectionreference_Result,connectionreference_FormattedResult>;
  business_unit_connections: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  business_unit_connector: WebMappingRetrieve<connector_Select,connector_Expand,connector_Filter,connector_Fixed,connector_Result,connector_FormattedResult>;
  business_unit_contacts: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  business_unit_conversationtranscript: WebMappingRetrieve<conversationtranscript_Select,conversationtranscript_Expand,conversationtranscript_Filter,conversationtranscript_Fixed,conversationtranscript_Result,conversationtranscript_FormattedResult>;
  business_unit_convertrule: WebMappingRetrieve<ConvertRule_Select,ConvertRule_Expand,ConvertRule_Filter,ConvertRule_Fixed,ConvertRule_Result,ConvertRule_FormattedResult>;
  business_unit_customapi: WebMappingRetrieve<CustomAPI_Select,CustomAPI_Expand,CustomAPI_Filter,CustomAPI_Fixed,CustomAPI_Result,CustomAPI_FormattedResult>;
  business_unit_customapirequestparameter: WebMappingRetrieve<CustomAPIRequestParameter_Select,CustomAPIRequestParameter_Expand,CustomAPIRequestParameter_Filter,CustomAPIRequestParameter_Fixed,CustomAPIRequestParameter_Result,CustomAPIRequestParameter_FormattedResult>;
  business_unit_customapiresponseproperty: WebMappingRetrieve<CustomAPIResponseProperty_Select,CustomAPIResponseProperty_Expand,CustomAPIResponseProperty_Filter,CustomAPIResponseProperty_Fixed,CustomAPIResponseProperty_Result,CustomAPIResponseProperty_FormattedResult>;
  business_unit_customer_relationship: WebMappingRetrieve<CustomerRelationship_Select,CustomerRelationship_Expand,CustomerRelationship_Filter,CustomerRelationship_Fixed,CustomerRelationship_Result,CustomerRelationship_FormattedResult>;
  business_unit_datalakefolder: WebMappingRetrieve<datalakefolder_Select,datalakefolder_Expand,datalakefolder_Filter,datalakefolder_Fixed,datalakefolder_Result,datalakefolder_FormattedResult>;
  business_unit_datalakefolderpermission: WebMappingRetrieve<datalakefolderpermission_Select,datalakefolderpermission_Expand,datalakefolderpermission_Filter,datalakefolderpermission_Fixed,datalakefolderpermission_Result,datalakefolderpermission_FormattedResult>;
  business_unit_email_activities: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  business_unit_emailserverprofile: WebMappingRetrieve<EmailServerProfile_Select,EmailServerProfile_Expand,EmailServerProfile_Filter,EmailServerProfile_Fixed,EmailServerProfile_Result,EmailServerProfile_FormattedResult>;
  business_unit_emailsignatures: WebMappingRetrieve<EmailSignature_Select,EmailSignature_Expand,EmailSignature_Filter,EmailSignature_Fixed,EmailSignature_Result,EmailSignature_FormattedResult>;
  business_unit_environmentvariabledefinition: WebMappingRetrieve<EnvironmentVariableDefinition_Select,EnvironmentVariableDefinition_Expand,EnvironmentVariableDefinition_Filter,EnvironmentVariableDefinition_Fixed,EnvironmentVariableDefinition_Result,EnvironmentVariableDefinition_FormattedResult>;
  business_unit_environmentvariablevalue: WebMappingRetrieve<EnvironmentVariableValue_Select,EnvironmentVariableValue_Expand,EnvironmentVariableValue_Filter,EnvironmentVariableValue_Fixed,EnvironmentVariableValue_Result,EnvironmentVariableValue_FormattedResult>;
  business_unit_exchangesyncidmapping: WebMappingRetrieve<ExchangeSyncIdMapping_Select,ExchangeSyncIdMapping_Expand,ExchangeSyncIdMapping_Filter,ExchangeSyncIdMapping_Fixed,ExchangeSyncIdMapping_Result,ExchangeSyncIdMapping_FormattedResult>;
  business_unit_exportsolutionupload: WebMappingRetrieve<ExportSolutionUpload_Select,ExportSolutionUpload_Expand,ExportSolutionUpload_Filter,ExportSolutionUpload_Fixed,ExportSolutionUpload_Result,ExportSolutionUpload_FormattedResult>;
  business_unit_externalparty: WebMappingRetrieve<ExternalParty_Select,ExternalParty_Expand,ExternalParty_Filter,ExternalParty_Fixed,ExternalParty_Result,ExternalParty_FormattedResult>;
  business_unit_fax_activities: WebMappingRetrieve<Fax_Select,Fax_Expand,Fax_Filter,Fax_Fixed,Fax_Result,Fax_FormattedResult>;
  business_unit_featurecontrolsetting: WebMappingRetrieve<featurecontrolsetting_Select,featurecontrolsetting_Expand,featurecontrolsetting_Filter,featurecontrolsetting_Fixed,featurecontrolsetting_Result,featurecontrolsetting_FormattedResult>;
  business_unit_feedback: WebMappingRetrieve<Feedback_Select,Feedback_Expand,Feedback_Filter,Feedback_Fixed,Feedback_Result,Feedback_FormattedResult>;
  business_unit_flowmachine: WebMappingRetrieve<flowmachine_Select,flowmachine_Expand,flowmachine_Filter,flowmachine_Fixed,flowmachine_Result,flowmachine_FormattedResult>;
  business_unit_flowmachinegroup: WebMappingRetrieve<flowmachinegroup_Select,flowmachinegroup_Expand,flowmachinegroup_Filter,flowmachinegroup_Fixed,flowmachinegroup_Result,flowmachinegroup_FormattedResult>;
  business_unit_flowsession: WebMappingRetrieve<flowsession_Select,flowsession_Expand,flowsession_Filter,flowsession_Fixed,flowsession_Result,flowsession_FormattedResult>;
  business_unit_goal: WebMappingRetrieve<Goal_Select,Goal_Expand,Goal_Filter,Goal_Fixed,Goal_Result,Goal_FormattedResult>;
  business_unit_goalrollupquery: WebMappingRetrieve<GoalRollupQuery_Select,GoalRollupQuery_Expand,GoalRollupQuery_Filter,GoalRollupQuery_Fixed,GoalRollupQuery_Result,GoalRollupQuery_FormattedResult>;
  business_unit_keyvaultreference: WebMappingRetrieve<KeyVaultReference_Select,KeyVaultReference_Expand,KeyVaultReference_Filter,KeyVaultReference_Fixed,KeyVaultReference_Result,KeyVaultReference_FormattedResult>;
  business_unit_knowledgearticle: WebMappingRetrieve<KnowledgeArticle_Select,KnowledgeArticle_Expand,KnowledgeArticle_Filter,KnowledgeArticle_Fixed,KnowledgeArticle_Result,KnowledgeArticle_FormattedResult>;
  business_unit_letter_activities: WebMappingRetrieve<Letter_Select,Letter_Expand,Letter_Filter,Letter_Fixed,Letter_Result,Letter_FormattedResult>;
  business_unit_mailbox: WebMappingRetrieve<Mailbox_Select,Mailbox_Expand,Mailbox_Filter,Mailbox_Fixed,Mailbox_Result,Mailbox_FormattedResult>;
  business_unit_mailmergetemplates: WebMappingRetrieve<MailMergeTemplate_Select,MailMergeTemplate_Expand,MailMergeTemplate_Filter,MailMergeTemplate_Fixed,MailMergeTemplate_Result,MailMergeTemplate_FormattedResult>;
  business_unit_managedidentity: WebMappingRetrieve<ManagedIdentity_Select,ManagedIdentity_Expand,ManagedIdentity_Filter,ManagedIdentity_Fixed,ManagedIdentity_Result,ManagedIdentity_FormattedResult>;
  business_unit_msdyn_aibdataset: WebMappingRetrieve<msdyn_AIBDataset_Select,msdyn_AIBDataset_Expand,msdyn_AIBDataset_Filter,msdyn_AIBDataset_Fixed,msdyn_AIBDataset_Result,msdyn_AIBDataset_FormattedResult>;
  business_unit_msdyn_aibdatasetfile: WebMappingRetrieve<msdyn_AIBDatasetFile_Select,msdyn_AIBDatasetFile_Expand,msdyn_AIBDatasetFile_Filter,msdyn_AIBDatasetFile_Fixed,msdyn_AIBDatasetFile_Result,msdyn_AIBDatasetFile_FormattedResult>;
  business_unit_msdyn_aibdatasetrecord: WebMappingRetrieve<msdyn_AIBDatasetRecord_Select,msdyn_AIBDatasetRecord_Expand,msdyn_AIBDatasetRecord_Filter,msdyn_AIBDatasetRecord_Fixed,msdyn_AIBDatasetRecord_Result,msdyn_AIBDatasetRecord_FormattedResult>;
  business_unit_msdyn_aibdatasetscontainer: WebMappingRetrieve<msdyn_AIBDatasetsContainer_Select,msdyn_AIBDatasetsContainer_Expand,msdyn_AIBDatasetsContainer_Filter,msdyn_AIBDatasetsContainer_Fixed,msdyn_AIBDatasetsContainer_Result,msdyn_AIBDatasetsContainer_FormattedResult>;
  business_unit_msdyn_aibfile: WebMappingRetrieve<msdyn_AIBFile_Select,msdyn_AIBFile_Expand,msdyn_AIBFile_Filter,msdyn_AIBFile_Fixed,msdyn_AIBFile_Result,msdyn_AIBFile_FormattedResult>;
  business_unit_msdyn_aibfileattacheddata: WebMappingRetrieve<msdyn_AIBFileAttachedData_Select,msdyn_AIBFileAttachedData_Expand,msdyn_AIBFileAttachedData_Filter,msdyn_AIBFileAttachedData_Fixed,msdyn_AIBFileAttachedData_Result,msdyn_AIBFileAttachedData_FormattedResult>;
  business_unit_msdyn_aiconfiguration: WebMappingRetrieve<msdyn_AIConfiguration_Select,msdyn_AIConfiguration_Expand,msdyn_AIConfiguration_Filter,msdyn_AIConfiguration_Fixed,msdyn_AIConfiguration_Result,msdyn_AIConfiguration_FormattedResult>;
  business_unit_msdyn_aifptrainingdocument: WebMappingRetrieve<msdyn_AIFpTrainingDocument_Select,msdyn_AIFpTrainingDocument_Expand,msdyn_AIFpTrainingDocument_Filter,msdyn_AIFpTrainingDocument_Fixed,msdyn_AIFpTrainingDocument_Result,msdyn_AIFpTrainingDocument_FormattedResult>;
  business_unit_msdyn_aimodel: WebMappingRetrieve<msdyn_AIModel_Select,msdyn_AIModel_Expand,msdyn_AIModel_Filter,msdyn_AIModel_Fixed,msdyn_AIModel_Result,msdyn_AIModel_FormattedResult>;
  business_unit_msdyn_aiodimage: WebMappingRetrieve<msdyn_AIOdImage_Select,msdyn_AIOdImage_Expand,msdyn_AIOdImage_Filter,msdyn_AIOdImage_Fixed,msdyn_AIOdImage_Result,msdyn_AIOdImage_FormattedResult>;
  business_unit_msdyn_aiodlabel: WebMappingRetrieve<msdyn_AIOdLabel_Select,msdyn_AIOdLabel_Expand,msdyn_AIOdLabel_Filter,msdyn_AIOdLabel_Fixed,msdyn_AIOdLabel_Result,msdyn_AIOdLabel_FormattedResult>;
  business_unit_msdyn_aiodtrainingboundingbox: WebMappingRetrieve<msdyn_AIOdTrainingBoundingBox_Select,msdyn_AIOdTrainingBoundingBox_Expand,msdyn_AIOdTrainingBoundingBox_Filter,msdyn_AIOdTrainingBoundingBox_Fixed,msdyn_AIOdTrainingBoundingBox_Result,msdyn_AIOdTrainingBoundingBox_FormattedResult>;
  business_unit_msdyn_aiodtrainingimage: WebMappingRetrieve<msdyn_AIOdTrainingImage_Select,msdyn_AIOdTrainingImage_Expand,msdyn_AIOdTrainingImage_Filter,msdyn_AIOdTrainingImage_Fixed,msdyn_AIOdTrainingImage_Result,msdyn_AIOdTrainingImage_FormattedResult>;
  business_unit_msdyn_aitemplate: WebMappingRetrieve<msdyn_AITemplate_Select,msdyn_AITemplate_Expand,msdyn_AITemplate_Filter,msdyn_AITemplate_Fixed,msdyn_AITemplate_Result,msdyn_AITemplate_FormattedResult>;
  business_unit_msdyn_analysiscomponent: WebMappingRetrieve<msdyn_analysiscomponent_Select,msdyn_analysiscomponent_Expand,msdyn_analysiscomponent_Filter,msdyn_analysiscomponent_Fixed,msdyn_analysiscomponent_Result,msdyn_analysiscomponent_FormattedResult>;
  business_unit_msdyn_analysisjob: WebMappingRetrieve<msdyn_analysisjob_Select,msdyn_analysisjob_Expand,msdyn_analysisjob_Filter,msdyn_analysisjob_Fixed,msdyn_analysisjob_Result,msdyn_analysisjob_FormattedResult>;
  business_unit_msdyn_analysisresult: WebMappingRetrieve<msdyn_analysisresult_Select,msdyn_analysisresult_Expand,msdyn_analysisresult_Filter,msdyn_analysisresult_Fixed,msdyn_analysisresult_Result,msdyn_analysisresult_FormattedResult>;
  business_unit_msdyn_analysisresultdetail: WebMappingRetrieve<msdyn_analysisresultdetail_Select,msdyn_analysisresultdetail_Expand,msdyn_analysisresultdetail_Filter,msdyn_analysisresultdetail_Fixed,msdyn_analysisresultdetail_Result,msdyn_analysisresultdetail_FormattedResult>;
  business_unit_msdyn_dataflow: WebMappingRetrieve<msdyn_dataflow_Select,msdyn_dataflow_Expand,msdyn_dataflow_Filter,msdyn_dataflow_Fixed,msdyn_dataflow_Result,msdyn_dataflow_FormattedResult>;
  business_unit_msdyn_federatedarticle: WebMappingRetrieve<msdyn_federatedarticle_Select,msdyn_federatedarticle_Expand,msdyn_federatedarticle_Filter,msdyn_federatedarticle_Fixed,msdyn_federatedarticle_Result,msdyn_federatedarticle_FormattedResult>;
  business_unit_msdyn_kalanguagesetting: WebMappingRetrieve<msdyn_kalanguagesetting_Select,msdyn_kalanguagesetting_Expand,msdyn_kalanguagesetting_Filter,msdyn_kalanguagesetting_Fixed,msdyn_kalanguagesetting_Result,msdyn_kalanguagesetting_FormattedResult>;
  business_unit_msdyn_kmfederatedsearchconfig: WebMappingRetrieve<msdyn_kmfederatedsearchconfig_Select,msdyn_kmfederatedsearchconfig_Expand,msdyn_kmfederatedsearchconfig_Filter,msdyn_kmfederatedsearchconfig_Fixed,msdyn_kmfederatedsearchconfig_Result,msdyn_kmfederatedsearchconfig_FormattedResult>;
  business_unit_msdyn_knowledgearticleimage: WebMappingRetrieve<msdyn_knowledgearticleimage_Select,msdyn_knowledgearticleimage_Expand,msdyn_knowledgearticleimage_Filter,msdyn_knowledgearticleimage_Fixed,msdyn_knowledgearticleimage_Result,msdyn_knowledgearticleimage_FormattedResult>;
  business_unit_msdyn_knowledgearticletemplate: WebMappingRetrieve<msdyn_knowledgearticletemplate_Select,msdyn_knowledgearticletemplate_Expand,msdyn_knowledgearticletemplate_Filter,msdyn_knowledgearticletemplate_Fixed,msdyn_knowledgearticletemplate_Result,msdyn_knowledgearticletemplate_FormattedResult>;
  business_unit_msdyn_knowledgeinteractioninsight: WebMappingRetrieve<msdyn_knowledgeinteractioninsight_Select,msdyn_knowledgeinteractioninsight_Expand,msdyn_knowledgeinteractioninsight_Filter,msdyn_knowledgeinteractioninsight_Fixed,msdyn_knowledgeinteractioninsight_Result,msdyn_knowledgeinteractioninsight_FormattedResult>;
  business_unit_msdyn_knowledgepersonalfilter: WebMappingRetrieve<msdyn_knowledgepersonalfilter_Select,msdyn_knowledgepersonalfilter_Expand,msdyn_knowledgepersonalfilter_Filter,msdyn_knowledgepersonalfilter_Fixed,msdyn_knowledgepersonalfilter_Result,msdyn_knowledgepersonalfilter_FormattedResult>;
  business_unit_msdyn_knowledgesearchfilter: WebMappingRetrieve<msdyn_knowledgesearchfilter_Select,msdyn_knowledgesearchfilter_Expand,msdyn_knowledgesearchfilter_Filter,msdyn_knowledgesearchfilter_Fixed,msdyn_knowledgesearchfilter_Result,msdyn_knowledgesearchfilter_FormattedResult>;
  business_unit_msdyn_knowledgesearchinsight: WebMappingRetrieve<msdyn_knowledgesearchinsight_Select,msdyn_knowledgesearchinsight_Expand,msdyn_knowledgesearchinsight_Filter,msdyn_knowledgesearchinsight_Fixed,msdyn_knowledgesearchinsight_Result,msdyn_knowledgesearchinsight_FormattedResult>;
  business_unit_msdyn_pminferredtask: WebMappingRetrieve<msdyn_pminferredtask_Select,msdyn_pminferredtask_Expand,msdyn_pminferredtask_Filter,msdyn_pminferredtask_Fixed,msdyn_pminferredtask_Result,msdyn_pminferredtask_FormattedResult>;
  business_unit_msdyn_pmrecording: WebMappingRetrieve<msdyn_pmrecording_Select,msdyn_pmrecording_Expand,msdyn_pmrecording_Filter,msdyn_pmrecording_Fixed,msdyn_pmrecording_Result,msdyn_pmrecording_FormattedResult>;
  business_unit_msdyn_richtextfile: WebMappingRetrieve<msdyn_richtextfile_Select,msdyn_richtextfile_Expand,msdyn_richtextfile_Filter,msdyn_richtextfile_Fixed,msdyn_richtextfile_Result,msdyn_richtextfile_FormattedResult>;
  business_unit_msdyn_serviceconfiguration: WebMappingRetrieve<msdyn_serviceconfiguration_Select,msdyn_serviceconfiguration_Expand,msdyn_serviceconfiguration_Filter,msdyn_serviceconfiguration_Fixed,msdyn_serviceconfiguration_Result,msdyn_serviceconfiguration_FormattedResult>;
  business_unit_msdyn_slakpi: WebMappingRetrieve<msdyn_slakpi_Select,msdyn_slakpi_Expand,msdyn_slakpi_Filter,msdyn_slakpi_Fixed,msdyn_slakpi_Result,msdyn_slakpi_FormattedResult>;
  business_unit_msdyn_solutionhealthrule: WebMappingRetrieve<msdyn_solutionhealthrule_Select,msdyn_solutionhealthrule_Expand,msdyn_solutionhealthrule_Filter,msdyn_solutionhealthrule_Fixed,msdyn_solutionhealthrule_Result,msdyn_solutionhealthrule_FormattedResult>;
  business_unit_msdyn_solutionhealthruleargument: WebMappingRetrieve<msdyn_solutionhealthruleargument_Select,msdyn_solutionhealthruleargument_Expand,msdyn_solutionhealthruleargument_Filter,msdyn_solutionhealthruleargument_Fixed,msdyn_solutionhealthruleargument_Result,msdyn_solutionhealthruleargument_FormattedResult>;
  business_unit_msdynce_botcontent: WebMappingRetrieve<msdynce_botcontent_Select,msdynce_botcontent_Expand,msdynce_botcontent_Filter,msdynce_botcontent_Fixed,msdynce_botcontent_Result,msdynce_botcontent_FormattedResult>;
  business_unit_new_interactionforemail: WebMappingRetrieve<InteractionForEmail_Select,InteractionForEmail_Expand,InteractionForEmail_Filter,InteractionForEmail_Fixed,InteractionForEmail_Result,InteractionForEmail_FormattedResult>;
  business_unit_parent_business_unit: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  business_unit_pdfsetting: WebMappingRetrieve<PDFSetting_Select,PDFSetting_Expand,PDFSetting_Filter,PDFSetting_Fixed,PDFSetting_Result,PDFSetting_FormattedResult>;
  business_unit_personaldocumenttemplates: WebMappingRetrieve<PersonalDocumentTemplate_Select,PersonalDocumentTemplate_Expand,PersonalDocumentTemplate_Filter,PersonalDocumentTemplate_Fixed,PersonalDocumentTemplate_Result,PersonalDocumentTemplate_FormattedResult>;
  business_unit_phone_call_activities: WebMappingRetrieve<PhoneCall_Select,PhoneCall_Expand,PhoneCall_Filter,PhoneCall_Fixed,PhoneCall_Result,PhoneCall_FormattedResult>;
  business_unit_postfollows: WebMappingRetrieve<PostFollow_Select,PostFollow_Expand,PostFollow_Filter,PostFollow_Fixed,PostFollow_Result,PostFollow_FormattedResult>;
  business_unit_principalentitybusinessunitmap: WebMappingRetrieve<PrincipalEntityBusinessUnitMap_Select,PrincipalEntityBusinessUnitMap_Expand,PrincipalEntityBusinessUnitMap_Filter,PrincipalEntityBusinessUnitMap_Fixed,PrincipalEntityBusinessUnitMap_Result,PrincipalEntityBusinessUnitMap_FormattedResult>;
  business_unit_processstageparameter: WebMappingRetrieve<processstageparameter_Select,processstageparameter_Expand,processstageparameter_Filter,processstageparameter_Fixed,processstageparameter_Result,processstageparameter_FormattedResult>;
  business_unit_profilerule: WebMappingRetrieve<ChannelAccessProfileRule_Select,ChannelAccessProfileRule_Expand,ChannelAccessProfileRule_Filter,ChannelAccessProfileRule_Fixed,ChannelAccessProfileRule_Result,ChannelAccessProfileRule_FormattedResult>;
  business_unit_queues: WebMappingRetrieve<Queue_Select,Queue_Expand,Queue_Filter,Queue_Fixed,Queue_Result,Queue_FormattedResult>;
  business_unit_queues2: WebMappingRetrieve<Queue_Select,Queue_Expand,Queue_Filter,Queue_Fixed,Queue_Result,Queue_FormattedResult>;
  business_unit_recurrencerule: WebMappingRetrieve<RecurrenceRule_Select,RecurrenceRule_Expand,RecurrenceRule_Filter,RecurrenceRule_Fixed,RecurrenceRule_Result,RecurrenceRule_FormattedResult>;
  business_unit_recurringappointmentmaster_activities: WebMappingRetrieve<RecurringAppointmentMaster_Select,RecurringAppointmentMaster_Expand,RecurringAppointmentMaster_Filter,RecurringAppointmentMaster_Fixed,RecurringAppointmentMaster_Result,RecurringAppointmentMaster_FormattedResult>;
  business_unit_reports: WebMappingRetrieve<Report_Select,Report_Expand,Report_Filter,Report_Fixed,Report_Result,Report_FormattedResult>;
  business_unit_revokeinheritedaccessrecordstracker: WebMappingRetrieve<revokeinheritedaccessrecordstracker_Select,revokeinheritedaccessrecordstracker_Expand,revokeinheritedaccessrecordstracker_Filter,revokeinheritedaccessrecordstracker_Fixed,revokeinheritedaccessrecordstracker_Result,revokeinheritedaccessrecordstracker_FormattedResult>;
  business_unit_roles: WebMappingRetrieve<Role_Select,Role_Expand,Role_Filter,Role_Fixed,Role_Result,Role_FormattedResult>;
  business_unit_routingrule: WebMappingRetrieve<RoutingRule_Select,RoutingRule_Expand,RoutingRule_Filter,RoutingRule_Fixed,RoutingRule_Result,RoutingRule_FormattedResult>;
  business_unit_sharepointdocument: WebMappingRetrieve<SharePointDocument_Select,SharePointDocument_Expand,SharePointDocument_Filter,SharePointDocument_Fixed,SharePointDocument_Result,SharePointDocument_FormattedResult>;
  business_unit_sharepointdocument2: WebMappingRetrieve<SharePointDocument_Select,SharePointDocument_Expand,SharePointDocument_Filter,SharePointDocument_Fixed,SharePointDocument_Result,SharePointDocument_FormattedResult>;
  business_unit_sharepointdocumentlocation: WebMappingRetrieve<SharePointDocumentLocation_Select,SharePointDocumentLocation_Expand,SharePointDocumentLocation_Filter,SharePointDocumentLocation_Fixed,SharePointDocumentLocation_Result,SharePointDocumentLocation_FormattedResult>;
  business_unit_sharepointsites: WebMappingRetrieve<SharePointSite_Select,SharePointSite_Expand,SharePointSite_Filter,SharePointSite_Fixed,SharePointSite_Result,SharePointSite_FormattedResult>;
  business_unit_slabase: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  business_unit_slakpiinstance: WebMappingRetrieve<SLAKPIInstance_Select,SLAKPIInstance_Expand,SLAKPIInstance_Filter,SLAKPIInstance_Fixed,SLAKPIInstance_Result,SLAKPIInstance_FormattedResult>;
  business_unit_socialactivity: WebMappingRetrieve<SocialActivity_Select,SocialActivity_Expand,SocialActivity_Filter,SocialActivity_Fixed,SocialActivity_Result,SocialActivity_FormattedResult>;
  business_unit_socialprofiles: WebMappingRetrieve<SocialProfile_Select,SocialProfile_Expand,SocialProfile_Filter,SocialProfile_Fixed,SocialProfile_Result,SocialProfile_FormattedResult>;
  business_unit_solutioncomponentbatchconfiguration: WebMappingRetrieve<solutioncomponentbatchconfiguration_Select,solutioncomponentbatchconfiguration_Expand,solutioncomponentbatchconfiguration_Filter,solutioncomponentbatchconfiguration_Fixed,solutioncomponentbatchconfiguration_Result,solutioncomponentbatchconfiguration_FormattedResult>;
  business_unit_stagesolutionupload: WebMappingRetrieve<StageSolutionUpload_Select,StageSolutionUpload_Expand,StageSolutionUpload_Filter,StageSolutionUpload_Fixed,StageSolutionUpload_Result,StageSolutionUpload_FormattedResult>;
  business_unit_system_users: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  business_unit_task_activities: WebMappingRetrieve<Task_Select,Task_Expand,Task_Filter,Task_Fixed,Task_Result,Task_FormattedResult>;
  business_unit_teams: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  business_unit_templates: WebMappingRetrieve<Template_Select,Template_Expand,Template_Filter,Template_Fixed,Template_Result,Template_FormattedResult>;
  business_unit_untrackedemail_activities: WebMappingRetrieve<UntrackedEmail_Select,UntrackedEmail_Expand,UntrackedEmail_Filter,UntrackedEmail_Fixed,UntrackedEmail_Result,UntrackedEmail_FormattedResult>;
  business_unit_user_settings: WebMappingRetrieve<UserSettings_Select,UserSettings_Expand,UserSettings_Filter,UserSettings_Fixed,UserSettings_Result,UserSettings_FormattedResult>;
  business_unit_userapplicationmetadata: WebMappingRetrieve<UserApplicationMetadata_Select,UserApplicationMetadata_Expand,UserApplicationMetadata_Filter,UserApplicationMetadata_Fixed,UserApplicationMetadata_Result,UserApplicationMetadata_FormattedResult>;
  business_unit_userform: WebMappingRetrieve<UserForm_Select,UserForm_Expand,UserForm_Filter,UserForm_Fixed,UserForm_Result,UserForm_FormattedResult>;
  business_unit_userquery: WebMappingRetrieve<UserQuery_Select,UserQuery_Expand,UserQuery_Filter,UserQuery_Fixed,UserQuery_Result,UserQuery_FormattedResult>;
  business_unit_userqueryvisualizations: WebMappingRetrieve<UserQueryVisualization_Select,UserQueryVisualization_Expand,UserQueryVisualization_Filter,UserQueryVisualization_Fixed,UserQueryVisualization_Result,UserQueryVisualization_FormattedResult>;
  business_unit_workflow: WebMappingRetrieve<Workflow_Select,Workflow_Expand,Workflow_Filter,Workflow_Fixed,Workflow_Result,Workflow_FormattedResult>;
  business_unit_workflowbinary: WebMappingRetrieve<workflowbinary_Select,workflowbinary_Expand,workflowbinary_Filter,workflowbinary_Fixed,workflowbinary_Result,workflowbinary_FormattedResult>;
  business_unit_workflowlogs: WebMappingRetrieve<WorkflowLog_Select,WorkflowLog_Expand,WorkflowLog_Filter,WorkflowLog_Fixed,WorkflowLog_Result,WorkflowLog_FormattedResult>;
  businessunit_callbackregistration: WebMappingRetrieve<CallbackRegistration_Select,CallbackRegistration_Expand,CallbackRegistration_Filter,CallbackRegistration_Fixed,CallbackRegistration_Result,CallbackRegistration_FormattedResult>;
  businessunit_canvasapp: WebMappingRetrieve<CanvasApp_Select,CanvasApp_Expand,CanvasApp_Filter,CanvasApp_Fixed,CanvasApp_Result,CanvasApp_FormattedResult>;
  businessunit_canvasappextendedmetadata: WebMappingRetrieve<CanvasAppExtendedMetadata_Select,CanvasAppExtendedMetadata_Expand,CanvasAppExtendedMetadata_Filter,CanvasAppExtendedMetadata_Fixed,CanvasAppExtendedMetadata_Result,CanvasAppExtendedMetadata_FormattedResult>;
  businessunit_internal_addresses: WebMappingRetrieve<InternalAddress_Select,InternalAddress_Expand,InternalAddress_Filter,InternalAddress_Fixed,InternalAddress_Result,InternalAddress_FormattedResult>;
  businessunit_mailboxtrackingcategory: WebMappingRetrieve<MailboxTrackingCategory_Select,MailboxTrackingCategory_Expand,MailboxTrackingCategory_Filter,MailboxTrackingCategory_Fixed,MailboxTrackingCategory_Result,MailboxTrackingCategory_FormattedResult>;
  businessunit_mailboxtrackingfolder: WebMappingRetrieve<MailboxTrackingFolder_Select,MailboxTrackingFolder_Expand,MailboxTrackingFolder_Filter,MailboxTrackingFolder_Fixed,MailboxTrackingFolder_Result,MailboxTrackingFolder_FormattedResult>;
  businessunit_principalobjectattributeaccess: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  lk_userfiscalcalendar_businessunit: WebMappingRetrieve<UserFiscalCalendar_Select,UserFiscalCalendar_Expand,UserFiscalCalendar_Filter,UserFiscalCalendar_Fixed,UserFiscalCalendar_Result,UserFiscalCalendar_FormattedResult>;
  mbs_businessunit_mbs_pluginprofile: WebMappingRetrieve<mbs_pluginprofile_Select,mbs_pluginprofile_Expand,mbs_pluginprofile_Filter,mbs_pluginprofile_Fixed,mbs_pluginprofile_Result,mbs_pluginprofile_FormattedResult>;
  systemuserbusinessunitentitymap_businessunitid_businessunit: WebMappingRetrieve<SystemUserBusinessUnitEntityMap_Select,SystemUserBusinessUnitEntityMap_Expand,SystemUserBusinessUnitEntityMap_Filter,SystemUserBusinessUnitEntityMap_Fixed,SystemUserBusinessUnitEntityMap_Result,SystemUserBusinessUnitEntityMap_FormattedResult>;
  userentityinstancedata_businessunit: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
  userentityuisettings_businessunit: WebMappingRetrieve<UserEntityUISettings_Select,UserEntityUISettings_Expand,UserEntityUISettings_Filter,UserEntityUISettings_Fixed,UserEntityUISettings_Result,UserEntityUISettings_FormattedResult>;
}
interface WebEntitiesRetrieve {
  businessunits: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
}
interface WebEntitiesRelated {
  businessunits: WebMappingRelated<BusinessUnit_RelatedOne,BusinessUnit_RelatedMany>;
}
interface WebEntitiesCUDA {
  businessunits: WebMappingCUDA<BusinessUnit_Create,BusinessUnit_Update,BusinessUnit_Select>;
}
