interface DuplicateRecord_Base extends WebEntity {
  createdon?: Date | null;
  duplicateid?: string | null;
  owningbusinessunit?: string | null;
  owninguser?: string | null;
}
interface DuplicateRecord_Relationships {
  baserecordid_account?: Account_Result | null;
  baserecordid_activityfileattachment?: activityfileattachment_Result | null;
  baserecordid_applicationuser?: ApplicationUser_Result | null;
  baserecordid_appointment?: Appointment_Result | null;
  baserecordid_canvasappextendedmetadata?: CanvasAppExtendedMetadata_Result | null;
  baserecordid_cascadegrantrevokeaccessrecordstracker?: cascadegrantrevokeaccessrecordstracker_Result | null;
  baserecordid_cascadegrantrevokeaccessversiontracker?: cascadegrantrevokeaccessversiontracker_Result | null;
  baserecordid_catalogassignment?: CatalogAssignment_Result | null;
  baserecordid_connector?: connector_Result | null;
  baserecordid_contact?: Contact_Result | null;
  baserecordid_conversationtranscript?: conversationtranscript_Result | null;
  baserecordid_datalakefolder?: datalakefolder_Result | null;
  baserecordid_datalakefolderpermission?: datalakefolderpermission_Result | null;
  baserecordid_datalakeworkspace?: datalakeworkspace_Result | null;
  baserecordid_datalakeworkspacepermission?: datalakeworkspacepermission_Result | null;
  baserecordid_email?: Email_Result | null;
  baserecordid_emailserverprofile?: EmailServerProfile_Result | null;
  baserecordid_environmentvariabledefinition?: EnvironmentVariableDefinition_Result | null;
  baserecordid_environmentvariablevalue?: EnvironmentVariableValue_Result | null;
  baserecordid_exportsolutionupload?: ExportSolutionUpload_Result | null;
  baserecordid_fax?: Fax_Result | null;
  baserecordid_featurecontrolsetting?: featurecontrolsetting_Result | null;
  baserecordid_feedback?: Feedback_Result | null;
  baserecordid_flowmachinegroup?: flowmachinegroup_Result | null;
  baserecordid_goal?: Goal_Result | null;
  baserecordid_goalrollupquery?: GoalRollupQuery_Result | null;
  baserecordid_kbarticle?: KbArticle_Result | null;
  baserecordid_keyvaultreference?: KeyVaultReference_Result | null;
  baserecordid_knowledgearticle?: KnowledgeArticle_Result | null;
  baserecordid_knowledgebaserecord?: KnowledgeBaseRecord_Result | null;
  baserecordid_letter?: Letter_Result | null;
  baserecordid_managedidentity?: ManagedIdentity_Result | null;
  baserecordid_msdyn_aibdataset?: msdyn_AIBDataset_Result | null;
  baserecordid_msdyn_aibdatasetfile?: msdyn_AIBDatasetFile_Result | null;
  baserecordid_msdyn_aibdatasetrecord?: msdyn_AIBDatasetRecord_Result | null;
  baserecordid_msdyn_aibdatasetscontainer?: msdyn_AIBDatasetsContainer_Result | null;
  baserecordid_msdyn_aibfile?: msdyn_AIBFile_Result | null;
  baserecordid_msdyn_aibfileattacheddata?: msdyn_AIBFileAttachedData_Result | null;
  baserecordid_msdyn_aiodimage?: msdyn_AIOdImage_Result | null;
  baserecordid_msdyn_aiodlabel?: msdyn_AIOdLabel_Result | null;
  baserecordid_msdyn_aiodtrainingboundingbox?: msdyn_AIOdTrainingBoundingBox_Result | null;
  baserecordid_msdyn_aiodtrainingimage?: msdyn_AIOdTrainingImage_Result | null;
  baserecordid_msdyn_analysiscomponent?: msdyn_analysiscomponent_Result | null;
  baserecordid_msdyn_analysisjob?: msdyn_analysisjob_Result | null;
  baserecordid_msdyn_analysisresult?: msdyn_analysisresult_Result | null;
  baserecordid_msdyn_analysisresultdetail?: msdyn_analysisresultdetail_Result | null;
  baserecordid_msdyn_dataflow?: msdyn_dataflow_Result | null;
  baserecordid_msdyn_federatedarticle?: msdyn_federatedarticle_Result | null;
  baserecordid_msdyn_federatedarticleincident?: msdyn_federatedarticleincident_Result | null;
  baserecordid_msdyn_kalanguagesetting?: msdyn_kalanguagesetting_Result | null;
  baserecordid_msdyn_kmfederatedsearchconfig?: msdyn_kmfederatedsearchconfig_Result | null;
  baserecordid_msdyn_knowledgearticleimage?: msdyn_knowledgearticleimage_Result | null;
  baserecordid_msdyn_knowledgearticletemplate?: msdyn_knowledgearticletemplate_Result | null;
  baserecordid_msdyn_knowledgeinteractioninsight?: msdyn_knowledgeinteractioninsight_Result | null;
  baserecordid_msdyn_knowledgepersonalfilter?: msdyn_knowledgepersonalfilter_Result | null;
  baserecordid_msdyn_knowledgesearchfilter?: msdyn_knowledgesearchfilter_Result | null;
  baserecordid_msdyn_knowledgesearchinsight?: msdyn_knowledgesearchinsight_Result | null;
  baserecordid_msdyn_pminferredtask?: msdyn_pminferredtask_Result | null;
  baserecordid_msdyn_pmrecording?: msdyn_pmrecording_Result | null;
  baserecordid_msdyn_serviceconfiguration?: msdyn_serviceconfiguration_Result | null;
  baserecordid_msdyn_slakpi?: msdyn_slakpi_Result | null;
  baserecordid_msdyn_solutionhealthrule?: msdyn_solutionhealthrule_Result | null;
  baserecordid_msdyn_solutionhealthruleargument?: msdyn_solutionhealthruleargument_Result | null;
  baserecordid_msdyn_solutionhealthruleset?: msdyn_solutionhealthruleset_Result | null;
  baserecordid_organizationdatasyncsubscription?: organizationdatasyncsubscription_Result | null;
  baserecordid_organizationdatasyncsubscriptionentity?: organizationdatasyncsubscriptionentity_Result | null;
  baserecordid_package?: package_Result | null;
  baserecordid_phonecall?: PhoneCall_Result | null;
  baserecordid_publisher?: Publisher_Result | null;
  baserecordid_queue?: Queue_Result | null;
  baserecordid_recurringappointmentmaster?: RecurringAppointmentMaster_Result | null;
  baserecordid_revokeinheritedaccessrecordstracker?: revokeinheritedaccessrecordstracker_Result | null;
  baserecordid_serviceplan?: ServicePlan_Result | null;
  baserecordid_serviceplanmapping?: ServicePlanMapping_Result | null;
  baserecordid_sharepointdocumentlocation?: SharePointDocumentLocation_Result | null;
  baserecordid_sharepointsite?: SharePointSite_Result | null;
  baserecordid_socialactivity?: SocialActivity_Result | null;
  baserecordid_socialprofile?: SocialProfile_Result | null;
  baserecordid_solutioncomponentattributeconfiguration?: solutioncomponentattributeconfiguration_Result | null;
  baserecordid_solutioncomponentbatchconfiguration?: solutioncomponentbatchconfiguration_Result | null;
  baserecordid_solutioncomponentconfiguration?: solutioncomponentconfiguration_Result | null;
  baserecordid_solutioncomponentrelationshipconfiguration?: solutioncomponentrelationshipconfiguration_Result | null;
  baserecordid_stagesolutionupload?: StageSolutionUpload_Result | null;
  baserecordid_systemuser?: SystemUser_Result | null;
  baserecordid_task?: Task_Result | null;
  baserecordid_team?: Team_Result | null;
  baserecordid_transactioncurrency?: TransactionCurrency_Result | null;
  channelaccessprofile_duplicatebaserecord?: ChannelAccessProfile_Result | null;
  channelaccessprofile_duplicatematchingrecord?: ChannelAccessProfile_Result | null;
  duplicaterecordid_account?: Account_Result | null;
  duplicaterecordid_activityfileattachment?: activityfileattachment_Result | null;
  duplicaterecordid_applicationuser?: ApplicationUser_Result | null;
  duplicaterecordid_appointment?: Appointment_Result | null;
  duplicaterecordid_canvasappextendedmetadata?: CanvasAppExtendedMetadata_Result | null;
  duplicaterecordid_cascadegrantrevokeaccessrecordstracker?: cascadegrantrevokeaccessrecordstracker_Result | null;
  duplicaterecordid_cascadegrantrevokeaccessversiontracker?: cascadegrantrevokeaccessversiontracker_Result | null;
  duplicaterecordid_catalogassignment?: CatalogAssignment_Result | null;
  duplicaterecordid_connector?: connector_Result | null;
  duplicaterecordid_contact?: Contact_Result | null;
  duplicaterecordid_conversationtranscript?: conversationtranscript_Result | null;
  duplicaterecordid_datalakefolder?: datalakefolder_Result | null;
  duplicaterecordid_datalakefolderpermission?: datalakefolderpermission_Result | null;
  duplicaterecordid_datalakeworkspace?: datalakeworkspace_Result | null;
  duplicaterecordid_datalakeworkspacepermission?: datalakeworkspacepermission_Result | null;
  duplicaterecordid_email?: Email_Result | null;
  duplicaterecordid_emailserverprofile?: EmailServerProfile_Result | null;
  duplicaterecordid_environmentvariabledefinition?: EnvironmentVariableDefinition_Result | null;
  duplicaterecordid_environmentvariablevalue?: EnvironmentVariableValue_Result | null;
  duplicaterecordid_exportsolutionupload?: ExportSolutionUpload_Result | null;
  duplicaterecordid_fax?: Fax_Result | null;
  duplicaterecordid_featurecontrolsetting?: featurecontrolsetting_Result | null;
  duplicaterecordid_feedback?: Feedback_Result | null;
  duplicaterecordid_flowmachinegroup?: flowmachinegroup_Result | null;
  duplicaterecordid_goal?: Goal_Result | null;
  duplicaterecordid_goalrollupquery?: GoalRollupQuery_Result | null;
  duplicaterecordid_kbarticle?: KbArticle_Result | null;
  duplicaterecordid_keyvaultreference?: KeyVaultReference_Result | null;
  duplicaterecordid_knowledgearticle?: KnowledgeArticle_Result | null;
  duplicaterecordid_knowledgebaserecord?: KnowledgeBaseRecord_Result | null;
  duplicaterecordid_letter?: Letter_Result | null;
  duplicaterecordid_managedidentity?: ManagedIdentity_Result | null;
  duplicaterecordid_msdyn_aibdataset?: msdyn_AIBDataset_Result | null;
  duplicaterecordid_msdyn_aibdatasetfile?: msdyn_AIBDatasetFile_Result | null;
  duplicaterecordid_msdyn_aibdatasetrecord?: msdyn_AIBDatasetRecord_Result | null;
  duplicaterecordid_msdyn_aibdatasetscontainer?: msdyn_AIBDatasetsContainer_Result | null;
  duplicaterecordid_msdyn_aibfile?: msdyn_AIBFile_Result | null;
  duplicaterecordid_msdyn_aibfileattacheddata?: msdyn_AIBFileAttachedData_Result | null;
  duplicaterecordid_msdyn_aiodimage?: msdyn_AIOdImage_Result | null;
  duplicaterecordid_msdyn_aiodlabel?: msdyn_AIOdLabel_Result | null;
  duplicaterecordid_msdyn_aiodtrainingboundingbox?: msdyn_AIOdTrainingBoundingBox_Result | null;
  duplicaterecordid_msdyn_aiodtrainingimage?: msdyn_AIOdTrainingImage_Result | null;
  duplicaterecordid_msdyn_analysiscomponent?: msdyn_analysiscomponent_Result | null;
  duplicaterecordid_msdyn_analysisjob?: msdyn_analysisjob_Result | null;
  duplicaterecordid_msdyn_analysisresult?: msdyn_analysisresult_Result | null;
  duplicaterecordid_msdyn_analysisresultdetail?: msdyn_analysisresultdetail_Result | null;
  duplicaterecordid_msdyn_dataflow?: msdyn_dataflow_Result | null;
  duplicaterecordid_msdyn_federatedarticle?: msdyn_federatedarticle_Result | null;
  duplicaterecordid_msdyn_federatedarticleincident?: msdyn_federatedarticleincident_Result | null;
  duplicaterecordid_msdyn_kalanguagesetting?: msdyn_kalanguagesetting_Result | null;
  duplicaterecordid_msdyn_kmfederatedsearchconfig?: msdyn_kmfederatedsearchconfig_Result | null;
  duplicaterecordid_msdyn_knowledgearticleimage?: msdyn_knowledgearticleimage_Result | null;
  duplicaterecordid_msdyn_knowledgearticletemplate?: msdyn_knowledgearticletemplate_Result | null;
  duplicaterecordid_msdyn_knowledgeinteractioninsight?: msdyn_knowledgeinteractioninsight_Result | null;
  duplicaterecordid_msdyn_knowledgepersonalfilter?: msdyn_knowledgepersonalfilter_Result | null;
  duplicaterecordid_msdyn_knowledgesearchfilter?: msdyn_knowledgesearchfilter_Result | null;
  duplicaterecordid_msdyn_knowledgesearchinsight?: msdyn_knowledgesearchinsight_Result | null;
  duplicaterecordid_msdyn_pminferredtask?: msdyn_pminferredtask_Result | null;
  duplicaterecordid_msdyn_pmrecording?: msdyn_pmrecording_Result | null;
  duplicaterecordid_msdyn_serviceconfiguration?: msdyn_serviceconfiguration_Result | null;
  duplicaterecordid_msdyn_slakpi?: msdyn_slakpi_Result | null;
  duplicaterecordid_msdyn_solutionhealthrule?: msdyn_solutionhealthrule_Result | null;
  duplicaterecordid_msdyn_solutionhealthruleargument?: msdyn_solutionhealthruleargument_Result | null;
  duplicaterecordid_msdyn_solutionhealthruleset?: msdyn_solutionhealthruleset_Result | null;
  duplicaterecordid_organizationdatasyncsubscription?: organizationdatasyncsubscription_Result | null;
  duplicaterecordid_organizationdatasyncsubscriptionentity?: organizationdatasyncsubscriptionentity_Result | null;
  duplicaterecordid_package?: package_Result | null;
  duplicaterecordid_phonecall?: PhoneCall_Result | null;
  duplicaterecordid_publisher?: Publisher_Result | null;
  duplicaterecordid_queue?: Queue_Result | null;
  duplicaterecordid_recurringappointmentmaster?: RecurringAppointmentMaster_Result | null;
  duplicaterecordid_revokeinheritedaccessrecordstracker?: revokeinheritedaccessrecordstracker_Result | null;
  duplicaterecordid_serviceplan?: ServicePlan_Result | null;
  duplicaterecordid_serviceplanmapping?: ServicePlanMapping_Result | null;
  duplicaterecordid_sharepointdocumentlocation?: SharePointDocumentLocation_Result | null;
  duplicaterecordid_sharepointsite?: SharePointSite_Result | null;
  duplicaterecordid_socialactivity?: SocialActivity_Result | null;
  duplicaterecordid_socialprofile?: SocialProfile_Result | null;
  duplicaterecordid_solutioncomponentattributeconfiguration?: solutioncomponentattributeconfiguration_Result | null;
  duplicaterecordid_solutioncomponentbatchconfiguration?: solutioncomponentbatchconfiguration_Result | null;
  duplicaterecordid_solutioncomponentconfiguration?: solutioncomponentconfiguration_Result | null;
  duplicaterecordid_solutioncomponentrelationshipconfiguration?: solutioncomponentrelationshipconfiguration_Result | null;
  duplicaterecordid_stagesolutionupload?: StageSolutionUpload_Result | null;
  duplicaterecordid_systemuser?: SystemUser_Result | null;
  duplicaterecordid_task?: Task_Result | null;
  duplicaterecordid_team?: Team_Result | null;
  duplicaterecordid_transactioncurrency?: TransactionCurrency_Result | null;
  userentityinstancedata_duplicaterecord?: UserEntityInstanceData_Result[] | null;
}
interface DuplicateRecord extends DuplicateRecord_Base, DuplicateRecord_Relationships {
}
interface DuplicateRecord_Create extends DuplicateRecord {
}
interface DuplicateRecord_Update extends DuplicateRecord {
}
interface DuplicateRecord_Select {
  asyncoperationid_guid: WebAttribute<DuplicateRecord_Select, { asyncoperationid_guid: string | null }, { asyncoperationid_formatted?: string }>;
  baserecordid_guid: WebAttribute<DuplicateRecord_Select, { baserecordid_guid: string | null }, { baserecordid_formatted?: string }>;
  createdon: WebAttribute<DuplicateRecord_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  duplicateid: WebAttribute<DuplicateRecord_Select, { duplicateid: string | null }, {  }>;
  duplicaterecordid_guid: WebAttribute<DuplicateRecord_Select, { duplicaterecordid_guid: string | null }, { duplicaterecordid_formatted?: string }>;
  duplicateruleid_guid: WebAttribute<DuplicateRecord_Select, { duplicateruleid_guid: string | null }, { duplicateruleid_formatted?: string }>;
  ownerid_guid: WebAttribute<DuplicateRecord_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit: WebAttribute<DuplicateRecord_Select, { owningbusinessunit: string | null }, {  }>;
  owninguser: WebAttribute<DuplicateRecord_Select, { owninguser: string | null }, {  }>;
}
interface DuplicateRecord_Filter {
  asyncoperationid_guid: XQW.Guid;
  baserecordid_guid: XQW.Guid;
  createdon: Date;
  duplicateid: XQW.Guid;
  duplicaterecordid_guid: XQW.Guid;
  duplicateruleid_guid: XQW.Guid;
  ownerid_guid: XQW.Guid;
  owningbusinessunit: XQW.Guid;
  owninguser: XQW.Guid;
}
interface DuplicateRecord_Expand {
  asyncoperationid: WebExpand<DuplicateRecord_Expand, AsyncOperation_Select, AsyncOperation_Filter, { asyncoperationid: AsyncOperation_Result }>;
  baserecordid_account: WebExpand<DuplicateRecord_Expand, Account_Select, Account_Filter, { baserecordid_account: Account_Result }>;
  baserecordid_activityfileattachment: WebExpand<DuplicateRecord_Expand, activityfileattachment_Select, activityfileattachment_Filter, { baserecordid_activityfileattachment: activityfileattachment_Result }>;
  baserecordid_applicationuser: WebExpand<DuplicateRecord_Expand, ApplicationUser_Select, ApplicationUser_Filter, { baserecordid_applicationuser: ApplicationUser_Result }>;
  baserecordid_appointment: WebExpand<DuplicateRecord_Expand, Appointment_Select, Appointment_Filter, { baserecordid_appointment: Appointment_Result }>;
  baserecordid_canvasappextendedmetadata: WebExpand<DuplicateRecord_Expand, CanvasAppExtendedMetadata_Select, CanvasAppExtendedMetadata_Filter, { baserecordid_canvasappextendedmetadata: CanvasAppExtendedMetadata_Result }>;
  baserecordid_cascadegrantrevokeaccessrecordstracker: WebExpand<DuplicateRecord_Expand, cascadegrantrevokeaccessrecordstracker_Select, cascadegrantrevokeaccessrecordstracker_Filter, { baserecordid_cascadegrantrevokeaccessrecordstracker: cascadegrantrevokeaccessrecordstracker_Result }>;
  baserecordid_cascadegrantrevokeaccessversiontracker: WebExpand<DuplicateRecord_Expand, cascadegrantrevokeaccessversiontracker_Select, cascadegrantrevokeaccessversiontracker_Filter, { baserecordid_cascadegrantrevokeaccessversiontracker: cascadegrantrevokeaccessversiontracker_Result }>;
  baserecordid_catalogassignment: WebExpand<DuplicateRecord_Expand, CatalogAssignment_Select, CatalogAssignment_Filter, { baserecordid_catalogassignment: CatalogAssignment_Result }>;
  baserecordid_connector: WebExpand<DuplicateRecord_Expand, connector_Select, connector_Filter, { baserecordid_connector: connector_Result }>;
  baserecordid_contact: WebExpand<DuplicateRecord_Expand, Contact_Select, Contact_Filter, { baserecordid_contact: Contact_Result }>;
  baserecordid_conversationtranscript: WebExpand<DuplicateRecord_Expand, conversationtranscript_Select, conversationtranscript_Filter, { baserecordid_conversationtranscript: conversationtranscript_Result }>;
  baserecordid_datalakefolder: WebExpand<DuplicateRecord_Expand, datalakefolder_Select, datalakefolder_Filter, { baserecordid_datalakefolder: datalakefolder_Result }>;
  baserecordid_datalakefolderpermission: WebExpand<DuplicateRecord_Expand, datalakefolderpermission_Select, datalakefolderpermission_Filter, { baserecordid_datalakefolderpermission: datalakefolderpermission_Result }>;
  baserecordid_datalakeworkspace: WebExpand<DuplicateRecord_Expand, datalakeworkspace_Select, datalakeworkspace_Filter, { baserecordid_datalakeworkspace: datalakeworkspace_Result }>;
  baserecordid_datalakeworkspacepermission: WebExpand<DuplicateRecord_Expand, datalakeworkspacepermission_Select, datalakeworkspacepermission_Filter, { baserecordid_datalakeworkspacepermission: datalakeworkspacepermission_Result }>;
  baserecordid_email: WebExpand<DuplicateRecord_Expand, Email_Select, Email_Filter, { baserecordid_email: Email_Result }>;
  baserecordid_emailserverprofile: WebExpand<DuplicateRecord_Expand, EmailServerProfile_Select, EmailServerProfile_Filter, { baserecordid_emailserverprofile: EmailServerProfile_Result }>;
  baserecordid_environmentvariabledefinition: WebExpand<DuplicateRecord_Expand, EnvironmentVariableDefinition_Select, EnvironmentVariableDefinition_Filter, { baserecordid_environmentvariabledefinition: EnvironmentVariableDefinition_Result }>;
  baserecordid_environmentvariablevalue: WebExpand<DuplicateRecord_Expand, EnvironmentVariableValue_Select, EnvironmentVariableValue_Filter, { baserecordid_environmentvariablevalue: EnvironmentVariableValue_Result }>;
  baserecordid_exportsolutionupload: WebExpand<DuplicateRecord_Expand, ExportSolutionUpload_Select, ExportSolutionUpload_Filter, { baserecordid_exportsolutionupload: ExportSolutionUpload_Result }>;
  baserecordid_fax: WebExpand<DuplicateRecord_Expand, Fax_Select, Fax_Filter, { baserecordid_fax: Fax_Result }>;
  baserecordid_featurecontrolsetting: WebExpand<DuplicateRecord_Expand, featurecontrolsetting_Select, featurecontrolsetting_Filter, { baserecordid_featurecontrolsetting: featurecontrolsetting_Result }>;
  baserecordid_feedback: WebExpand<DuplicateRecord_Expand, Feedback_Select, Feedback_Filter, { baserecordid_feedback: Feedback_Result }>;
  baserecordid_flowmachinegroup: WebExpand<DuplicateRecord_Expand, flowmachinegroup_Select, flowmachinegroup_Filter, { baserecordid_flowmachinegroup: flowmachinegroup_Result }>;
  baserecordid_goal: WebExpand<DuplicateRecord_Expand, Goal_Select, Goal_Filter, { baserecordid_goal: Goal_Result }>;
  baserecordid_goalrollupquery: WebExpand<DuplicateRecord_Expand, GoalRollupQuery_Select, GoalRollupQuery_Filter, { baserecordid_goalrollupquery: GoalRollupQuery_Result }>;
  baserecordid_kbarticle: WebExpand<DuplicateRecord_Expand, KbArticle_Select, KbArticle_Filter, { baserecordid_kbarticle: KbArticle_Result }>;
  baserecordid_keyvaultreference: WebExpand<DuplicateRecord_Expand, KeyVaultReference_Select, KeyVaultReference_Filter, { baserecordid_keyvaultreference: KeyVaultReference_Result }>;
  baserecordid_knowledgearticle: WebExpand<DuplicateRecord_Expand, KnowledgeArticle_Select, KnowledgeArticle_Filter, { baserecordid_knowledgearticle: KnowledgeArticle_Result }>;
  baserecordid_knowledgebaserecord: WebExpand<DuplicateRecord_Expand, KnowledgeBaseRecord_Select, KnowledgeBaseRecord_Filter, { baserecordid_knowledgebaserecord: KnowledgeBaseRecord_Result }>;
  baserecordid_letter: WebExpand<DuplicateRecord_Expand, Letter_Select, Letter_Filter, { baserecordid_letter: Letter_Result }>;
  baserecordid_managedidentity: WebExpand<DuplicateRecord_Expand, ManagedIdentity_Select, ManagedIdentity_Filter, { baserecordid_managedidentity: ManagedIdentity_Result }>;
  baserecordid_msdyn_aibdataset: WebExpand<DuplicateRecord_Expand, msdyn_AIBDataset_Select, msdyn_AIBDataset_Filter, { baserecordid_msdyn_aibdataset: msdyn_AIBDataset_Result }>;
  baserecordid_msdyn_aibdatasetfile: WebExpand<DuplicateRecord_Expand, msdyn_AIBDatasetFile_Select, msdyn_AIBDatasetFile_Filter, { baserecordid_msdyn_aibdatasetfile: msdyn_AIBDatasetFile_Result }>;
  baserecordid_msdyn_aibdatasetrecord: WebExpand<DuplicateRecord_Expand, msdyn_AIBDatasetRecord_Select, msdyn_AIBDatasetRecord_Filter, { baserecordid_msdyn_aibdatasetrecord: msdyn_AIBDatasetRecord_Result }>;
  baserecordid_msdyn_aibdatasetscontainer: WebExpand<DuplicateRecord_Expand, msdyn_AIBDatasetsContainer_Select, msdyn_AIBDatasetsContainer_Filter, { baserecordid_msdyn_aibdatasetscontainer: msdyn_AIBDatasetsContainer_Result }>;
  baserecordid_msdyn_aibfile: WebExpand<DuplicateRecord_Expand, msdyn_AIBFile_Select, msdyn_AIBFile_Filter, { baserecordid_msdyn_aibfile: msdyn_AIBFile_Result }>;
  baserecordid_msdyn_aibfileattacheddata: WebExpand<DuplicateRecord_Expand, msdyn_AIBFileAttachedData_Select, msdyn_AIBFileAttachedData_Filter, { baserecordid_msdyn_aibfileattacheddata: msdyn_AIBFileAttachedData_Result }>;
  baserecordid_msdyn_aiodimage: WebExpand<DuplicateRecord_Expand, msdyn_AIOdImage_Select, msdyn_AIOdImage_Filter, { baserecordid_msdyn_aiodimage: msdyn_AIOdImage_Result }>;
  baserecordid_msdyn_aiodlabel: WebExpand<DuplicateRecord_Expand, msdyn_AIOdLabel_Select, msdyn_AIOdLabel_Filter, { baserecordid_msdyn_aiodlabel: msdyn_AIOdLabel_Result }>;
  baserecordid_msdyn_aiodtrainingboundingbox: WebExpand<DuplicateRecord_Expand, msdyn_AIOdTrainingBoundingBox_Select, msdyn_AIOdTrainingBoundingBox_Filter, { baserecordid_msdyn_aiodtrainingboundingbox: msdyn_AIOdTrainingBoundingBox_Result }>;
  baserecordid_msdyn_aiodtrainingimage: WebExpand<DuplicateRecord_Expand, msdyn_AIOdTrainingImage_Select, msdyn_AIOdTrainingImage_Filter, { baserecordid_msdyn_aiodtrainingimage: msdyn_AIOdTrainingImage_Result }>;
  baserecordid_msdyn_analysiscomponent: WebExpand<DuplicateRecord_Expand, msdyn_analysiscomponent_Select, msdyn_analysiscomponent_Filter, { baserecordid_msdyn_analysiscomponent: msdyn_analysiscomponent_Result }>;
  baserecordid_msdyn_analysisjob: WebExpand<DuplicateRecord_Expand, msdyn_analysisjob_Select, msdyn_analysisjob_Filter, { baserecordid_msdyn_analysisjob: msdyn_analysisjob_Result }>;
  baserecordid_msdyn_analysisresult: WebExpand<DuplicateRecord_Expand, msdyn_analysisresult_Select, msdyn_analysisresult_Filter, { baserecordid_msdyn_analysisresult: msdyn_analysisresult_Result }>;
  baserecordid_msdyn_analysisresultdetail: WebExpand<DuplicateRecord_Expand, msdyn_analysisresultdetail_Select, msdyn_analysisresultdetail_Filter, { baserecordid_msdyn_analysisresultdetail: msdyn_analysisresultdetail_Result }>;
  baserecordid_msdyn_dataflow: WebExpand<DuplicateRecord_Expand, msdyn_dataflow_Select, msdyn_dataflow_Filter, { baserecordid_msdyn_dataflow: msdyn_dataflow_Result }>;
  baserecordid_msdyn_federatedarticle: WebExpand<DuplicateRecord_Expand, msdyn_federatedarticle_Select, msdyn_federatedarticle_Filter, { baserecordid_msdyn_federatedarticle: msdyn_federatedarticle_Result }>;
  baserecordid_msdyn_federatedarticleincident: WebExpand<DuplicateRecord_Expand, msdyn_federatedarticleincident_Select, msdyn_federatedarticleincident_Filter, { baserecordid_msdyn_federatedarticleincident: msdyn_federatedarticleincident_Result }>;
  baserecordid_msdyn_kalanguagesetting: WebExpand<DuplicateRecord_Expand, msdyn_kalanguagesetting_Select, msdyn_kalanguagesetting_Filter, { baserecordid_msdyn_kalanguagesetting: msdyn_kalanguagesetting_Result }>;
  baserecordid_msdyn_kmfederatedsearchconfig: WebExpand<DuplicateRecord_Expand, msdyn_kmfederatedsearchconfig_Select, msdyn_kmfederatedsearchconfig_Filter, { baserecordid_msdyn_kmfederatedsearchconfig: msdyn_kmfederatedsearchconfig_Result }>;
  baserecordid_msdyn_knowledgearticleimage: WebExpand<DuplicateRecord_Expand, msdyn_knowledgearticleimage_Select, msdyn_knowledgearticleimage_Filter, { baserecordid_msdyn_knowledgearticleimage: msdyn_knowledgearticleimage_Result }>;
  baserecordid_msdyn_knowledgearticletemplate: WebExpand<DuplicateRecord_Expand, msdyn_knowledgearticletemplate_Select, msdyn_knowledgearticletemplate_Filter, { baserecordid_msdyn_knowledgearticletemplate: msdyn_knowledgearticletemplate_Result }>;
  baserecordid_msdyn_knowledgeinteractioninsight: WebExpand<DuplicateRecord_Expand, msdyn_knowledgeinteractioninsight_Select, msdyn_knowledgeinteractioninsight_Filter, { baserecordid_msdyn_knowledgeinteractioninsight: msdyn_knowledgeinteractioninsight_Result }>;
  baserecordid_msdyn_knowledgepersonalfilter: WebExpand<DuplicateRecord_Expand, msdyn_knowledgepersonalfilter_Select, msdyn_knowledgepersonalfilter_Filter, { baserecordid_msdyn_knowledgepersonalfilter: msdyn_knowledgepersonalfilter_Result }>;
  baserecordid_msdyn_knowledgesearchfilter: WebExpand<DuplicateRecord_Expand, msdyn_knowledgesearchfilter_Select, msdyn_knowledgesearchfilter_Filter, { baserecordid_msdyn_knowledgesearchfilter: msdyn_knowledgesearchfilter_Result }>;
  baserecordid_msdyn_knowledgesearchinsight: WebExpand<DuplicateRecord_Expand, msdyn_knowledgesearchinsight_Select, msdyn_knowledgesearchinsight_Filter, { baserecordid_msdyn_knowledgesearchinsight: msdyn_knowledgesearchinsight_Result }>;
  baserecordid_msdyn_pminferredtask: WebExpand<DuplicateRecord_Expand, msdyn_pminferredtask_Select, msdyn_pminferredtask_Filter, { baserecordid_msdyn_pminferredtask: msdyn_pminferredtask_Result }>;
  baserecordid_msdyn_pmrecording: WebExpand<DuplicateRecord_Expand, msdyn_pmrecording_Select, msdyn_pmrecording_Filter, { baserecordid_msdyn_pmrecording: msdyn_pmrecording_Result }>;
  baserecordid_msdyn_serviceconfiguration: WebExpand<DuplicateRecord_Expand, msdyn_serviceconfiguration_Select, msdyn_serviceconfiguration_Filter, { baserecordid_msdyn_serviceconfiguration: msdyn_serviceconfiguration_Result }>;
  baserecordid_msdyn_slakpi: WebExpand<DuplicateRecord_Expand, msdyn_slakpi_Select, msdyn_slakpi_Filter, { baserecordid_msdyn_slakpi: msdyn_slakpi_Result }>;
  baserecordid_msdyn_solutionhealthrule: WebExpand<DuplicateRecord_Expand, msdyn_solutionhealthrule_Select, msdyn_solutionhealthrule_Filter, { baserecordid_msdyn_solutionhealthrule: msdyn_solutionhealthrule_Result }>;
  baserecordid_msdyn_solutionhealthruleargument: WebExpand<DuplicateRecord_Expand, msdyn_solutionhealthruleargument_Select, msdyn_solutionhealthruleargument_Filter, { baserecordid_msdyn_solutionhealthruleargument: msdyn_solutionhealthruleargument_Result }>;
  baserecordid_msdyn_solutionhealthruleset: WebExpand<DuplicateRecord_Expand, msdyn_solutionhealthruleset_Select, msdyn_solutionhealthruleset_Filter, { baserecordid_msdyn_solutionhealthruleset: msdyn_solutionhealthruleset_Result }>;
  baserecordid_organizationdatasyncsubscription: WebExpand<DuplicateRecord_Expand, organizationdatasyncsubscription_Select, organizationdatasyncsubscription_Filter, { baserecordid_organizationdatasyncsubscription: organizationdatasyncsubscription_Result }>;
  baserecordid_organizationdatasyncsubscriptionentity: WebExpand<DuplicateRecord_Expand, organizationdatasyncsubscriptionentity_Select, organizationdatasyncsubscriptionentity_Filter, { baserecordid_organizationdatasyncsubscriptionentity: organizationdatasyncsubscriptionentity_Result }>;
  baserecordid_package: WebExpand<DuplicateRecord_Expand, package_Select, package_Filter, { baserecordid_package: package_Result }>;
  baserecordid_phonecall: WebExpand<DuplicateRecord_Expand, PhoneCall_Select, PhoneCall_Filter, { baserecordid_phonecall: PhoneCall_Result }>;
  baserecordid_publisher: WebExpand<DuplicateRecord_Expand, Publisher_Select, Publisher_Filter, { baserecordid_publisher: Publisher_Result }>;
  baserecordid_queue: WebExpand<DuplicateRecord_Expand, Queue_Select, Queue_Filter, { baserecordid_queue: Queue_Result }>;
  baserecordid_recurringappointmentmaster: WebExpand<DuplicateRecord_Expand, RecurringAppointmentMaster_Select, RecurringAppointmentMaster_Filter, { baserecordid_recurringappointmentmaster: RecurringAppointmentMaster_Result }>;
  baserecordid_revokeinheritedaccessrecordstracker: WebExpand<DuplicateRecord_Expand, revokeinheritedaccessrecordstracker_Select, revokeinheritedaccessrecordstracker_Filter, { baserecordid_revokeinheritedaccessrecordstracker: revokeinheritedaccessrecordstracker_Result }>;
  baserecordid_serviceplan: WebExpand<DuplicateRecord_Expand, ServicePlan_Select, ServicePlan_Filter, { baserecordid_serviceplan: ServicePlan_Result }>;
  baserecordid_serviceplanmapping: WebExpand<DuplicateRecord_Expand, ServicePlanMapping_Select, ServicePlanMapping_Filter, { baserecordid_serviceplanmapping: ServicePlanMapping_Result }>;
  baserecordid_sharepointdocumentlocation: WebExpand<DuplicateRecord_Expand, SharePointDocumentLocation_Select, SharePointDocumentLocation_Filter, { baserecordid_sharepointdocumentlocation: SharePointDocumentLocation_Result }>;
  baserecordid_sharepointsite: WebExpand<DuplicateRecord_Expand, SharePointSite_Select, SharePointSite_Filter, { baserecordid_sharepointsite: SharePointSite_Result }>;
  baserecordid_socialactivity: WebExpand<DuplicateRecord_Expand, SocialActivity_Select, SocialActivity_Filter, { baserecordid_socialactivity: SocialActivity_Result }>;
  baserecordid_socialprofile: WebExpand<DuplicateRecord_Expand, SocialProfile_Select, SocialProfile_Filter, { baserecordid_socialprofile: SocialProfile_Result }>;
  baserecordid_solutioncomponentattributeconfiguration: WebExpand<DuplicateRecord_Expand, solutioncomponentattributeconfiguration_Select, solutioncomponentattributeconfiguration_Filter, { baserecordid_solutioncomponentattributeconfiguration: solutioncomponentattributeconfiguration_Result }>;
  baserecordid_solutioncomponentbatchconfiguration: WebExpand<DuplicateRecord_Expand, solutioncomponentbatchconfiguration_Select, solutioncomponentbatchconfiguration_Filter, { baserecordid_solutioncomponentbatchconfiguration: solutioncomponentbatchconfiguration_Result }>;
  baserecordid_solutioncomponentconfiguration: WebExpand<DuplicateRecord_Expand, solutioncomponentconfiguration_Select, solutioncomponentconfiguration_Filter, { baserecordid_solutioncomponentconfiguration: solutioncomponentconfiguration_Result }>;
  baserecordid_solutioncomponentrelationshipconfiguration: WebExpand<DuplicateRecord_Expand, solutioncomponentrelationshipconfiguration_Select, solutioncomponentrelationshipconfiguration_Filter, { baserecordid_solutioncomponentrelationshipconfiguration: solutioncomponentrelationshipconfiguration_Result }>;
  baserecordid_stagesolutionupload: WebExpand<DuplicateRecord_Expand, StageSolutionUpload_Select, StageSolutionUpload_Filter, { baserecordid_stagesolutionupload: StageSolutionUpload_Result }>;
  baserecordid_systemuser: WebExpand<DuplicateRecord_Expand, SystemUser_Select, SystemUser_Filter, { baserecordid_systemuser: SystemUser_Result }>;
  baserecordid_task: WebExpand<DuplicateRecord_Expand, Task_Select, Task_Filter, { baserecordid_task: Task_Result }>;
  baserecordid_team: WebExpand<DuplicateRecord_Expand, Team_Select, Team_Filter, { baserecordid_team: Team_Result }>;
  baserecordid_transactioncurrency: WebExpand<DuplicateRecord_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { baserecordid_transactioncurrency: TransactionCurrency_Result }>;
  channelaccessprofile_duplicatebaserecord: WebExpand<DuplicateRecord_Expand, ChannelAccessProfile_Select, ChannelAccessProfile_Filter, { channelaccessprofile_duplicatebaserecord: ChannelAccessProfile_Result }>;
  channelaccessprofile_duplicatematchingrecord: WebExpand<DuplicateRecord_Expand, ChannelAccessProfile_Select, ChannelAccessProfile_Filter, { channelaccessprofile_duplicatematchingrecord: ChannelAccessProfile_Result }>;
  duplicaterecordid_account: WebExpand<DuplicateRecord_Expand, Account_Select, Account_Filter, { duplicaterecordid_account: Account_Result }>;
  duplicaterecordid_activityfileattachment: WebExpand<DuplicateRecord_Expand, activityfileattachment_Select, activityfileattachment_Filter, { duplicaterecordid_activityfileattachment: activityfileattachment_Result }>;
  duplicaterecordid_applicationuser: WebExpand<DuplicateRecord_Expand, ApplicationUser_Select, ApplicationUser_Filter, { duplicaterecordid_applicationuser: ApplicationUser_Result }>;
  duplicaterecordid_appointment: WebExpand<DuplicateRecord_Expand, Appointment_Select, Appointment_Filter, { duplicaterecordid_appointment: Appointment_Result }>;
  duplicaterecordid_canvasappextendedmetadata: WebExpand<DuplicateRecord_Expand, CanvasAppExtendedMetadata_Select, CanvasAppExtendedMetadata_Filter, { duplicaterecordid_canvasappextendedmetadata: CanvasAppExtendedMetadata_Result }>;
  duplicaterecordid_cascadegrantrevokeaccessrecordstracker: WebExpand<DuplicateRecord_Expand, cascadegrantrevokeaccessrecordstracker_Select, cascadegrantrevokeaccessrecordstracker_Filter, { duplicaterecordid_cascadegrantrevokeaccessrecordstracker: cascadegrantrevokeaccessrecordstracker_Result }>;
  duplicaterecordid_cascadegrantrevokeaccessversiontracker: WebExpand<DuplicateRecord_Expand, cascadegrantrevokeaccessversiontracker_Select, cascadegrantrevokeaccessversiontracker_Filter, { duplicaterecordid_cascadegrantrevokeaccessversiontracker: cascadegrantrevokeaccessversiontracker_Result }>;
  duplicaterecordid_catalogassignment: WebExpand<DuplicateRecord_Expand, CatalogAssignment_Select, CatalogAssignment_Filter, { duplicaterecordid_catalogassignment: CatalogAssignment_Result }>;
  duplicaterecordid_connector: WebExpand<DuplicateRecord_Expand, connector_Select, connector_Filter, { duplicaterecordid_connector: connector_Result }>;
  duplicaterecordid_contact: WebExpand<DuplicateRecord_Expand, Contact_Select, Contact_Filter, { duplicaterecordid_contact: Contact_Result }>;
  duplicaterecordid_conversationtranscript: WebExpand<DuplicateRecord_Expand, conversationtranscript_Select, conversationtranscript_Filter, { duplicaterecordid_conversationtranscript: conversationtranscript_Result }>;
  duplicaterecordid_datalakefolder: WebExpand<DuplicateRecord_Expand, datalakefolder_Select, datalakefolder_Filter, { duplicaterecordid_datalakefolder: datalakefolder_Result }>;
  duplicaterecordid_datalakefolderpermission: WebExpand<DuplicateRecord_Expand, datalakefolderpermission_Select, datalakefolderpermission_Filter, { duplicaterecordid_datalakefolderpermission: datalakefolderpermission_Result }>;
  duplicaterecordid_datalakeworkspace: WebExpand<DuplicateRecord_Expand, datalakeworkspace_Select, datalakeworkspace_Filter, { duplicaterecordid_datalakeworkspace: datalakeworkspace_Result }>;
  duplicaterecordid_datalakeworkspacepermission: WebExpand<DuplicateRecord_Expand, datalakeworkspacepermission_Select, datalakeworkspacepermission_Filter, { duplicaterecordid_datalakeworkspacepermission: datalakeworkspacepermission_Result }>;
  duplicaterecordid_email: WebExpand<DuplicateRecord_Expand, Email_Select, Email_Filter, { duplicaterecordid_email: Email_Result }>;
  duplicaterecordid_emailserverprofile: WebExpand<DuplicateRecord_Expand, EmailServerProfile_Select, EmailServerProfile_Filter, { duplicaterecordid_emailserverprofile: EmailServerProfile_Result }>;
  duplicaterecordid_environmentvariabledefinition: WebExpand<DuplicateRecord_Expand, EnvironmentVariableDefinition_Select, EnvironmentVariableDefinition_Filter, { duplicaterecordid_environmentvariabledefinition: EnvironmentVariableDefinition_Result }>;
  duplicaterecordid_environmentvariablevalue: WebExpand<DuplicateRecord_Expand, EnvironmentVariableValue_Select, EnvironmentVariableValue_Filter, { duplicaterecordid_environmentvariablevalue: EnvironmentVariableValue_Result }>;
  duplicaterecordid_exportsolutionupload: WebExpand<DuplicateRecord_Expand, ExportSolutionUpload_Select, ExportSolutionUpload_Filter, { duplicaterecordid_exportsolutionupload: ExportSolutionUpload_Result }>;
  duplicaterecordid_fax: WebExpand<DuplicateRecord_Expand, Fax_Select, Fax_Filter, { duplicaterecordid_fax: Fax_Result }>;
  duplicaterecordid_featurecontrolsetting: WebExpand<DuplicateRecord_Expand, featurecontrolsetting_Select, featurecontrolsetting_Filter, { duplicaterecordid_featurecontrolsetting: featurecontrolsetting_Result }>;
  duplicaterecordid_feedback: WebExpand<DuplicateRecord_Expand, Feedback_Select, Feedback_Filter, { duplicaterecordid_feedback: Feedback_Result }>;
  duplicaterecordid_flowmachinegroup: WebExpand<DuplicateRecord_Expand, flowmachinegroup_Select, flowmachinegroup_Filter, { duplicaterecordid_flowmachinegroup: flowmachinegroup_Result }>;
  duplicaterecordid_goal: WebExpand<DuplicateRecord_Expand, Goal_Select, Goal_Filter, { duplicaterecordid_goal: Goal_Result }>;
  duplicaterecordid_goalrollupquery: WebExpand<DuplicateRecord_Expand, GoalRollupQuery_Select, GoalRollupQuery_Filter, { duplicaterecordid_goalrollupquery: GoalRollupQuery_Result }>;
  duplicaterecordid_kbarticle: WebExpand<DuplicateRecord_Expand, KbArticle_Select, KbArticle_Filter, { duplicaterecordid_kbarticle: KbArticle_Result }>;
  duplicaterecordid_keyvaultreference: WebExpand<DuplicateRecord_Expand, KeyVaultReference_Select, KeyVaultReference_Filter, { duplicaterecordid_keyvaultreference: KeyVaultReference_Result }>;
  duplicaterecordid_knowledgearticle: WebExpand<DuplicateRecord_Expand, KnowledgeArticle_Select, KnowledgeArticle_Filter, { duplicaterecordid_knowledgearticle: KnowledgeArticle_Result }>;
  duplicaterecordid_knowledgebaserecord: WebExpand<DuplicateRecord_Expand, KnowledgeBaseRecord_Select, KnowledgeBaseRecord_Filter, { duplicaterecordid_knowledgebaserecord: KnowledgeBaseRecord_Result }>;
  duplicaterecordid_letter: WebExpand<DuplicateRecord_Expand, Letter_Select, Letter_Filter, { duplicaterecordid_letter: Letter_Result }>;
  duplicaterecordid_managedidentity: WebExpand<DuplicateRecord_Expand, ManagedIdentity_Select, ManagedIdentity_Filter, { duplicaterecordid_managedidentity: ManagedIdentity_Result }>;
  duplicaterecordid_msdyn_aibdataset: WebExpand<DuplicateRecord_Expand, msdyn_AIBDataset_Select, msdyn_AIBDataset_Filter, { duplicaterecordid_msdyn_aibdataset: msdyn_AIBDataset_Result }>;
  duplicaterecordid_msdyn_aibdatasetfile: WebExpand<DuplicateRecord_Expand, msdyn_AIBDatasetFile_Select, msdyn_AIBDatasetFile_Filter, { duplicaterecordid_msdyn_aibdatasetfile: msdyn_AIBDatasetFile_Result }>;
  duplicaterecordid_msdyn_aibdatasetrecord: WebExpand<DuplicateRecord_Expand, msdyn_AIBDatasetRecord_Select, msdyn_AIBDatasetRecord_Filter, { duplicaterecordid_msdyn_aibdatasetrecord: msdyn_AIBDatasetRecord_Result }>;
  duplicaterecordid_msdyn_aibdatasetscontainer: WebExpand<DuplicateRecord_Expand, msdyn_AIBDatasetsContainer_Select, msdyn_AIBDatasetsContainer_Filter, { duplicaterecordid_msdyn_aibdatasetscontainer: msdyn_AIBDatasetsContainer_Result }>;
  duplicaterecordid_msdyn_aibfile: WebExpand<DuplicateRecord_Expand, msdyn_AIBFile_Select, msdyn_AIBFile_Filter, { duplicaterecordid_msdyn_aibfile: msdyn_AIBFile_Result }>;
  duplicaterecordid_msdyn_aibfileattacheddata: WebExpand<DuplicateRecord_Expand, msdyn_AIBFileAttachedData_Select, msdyn_AIBFileAttachedData_Filter, { duplicaterecordid_msdyn_aibfileattacheddata: msdyn_AIBFileAttachedData_Result }>;
  duplicaterecordid_msdyn_aiodimage: WebExpand<DuplicateRecord_Expand, msdyn_AIOdImage_Select, msdyn_AIOdImage_Filter, { duplicaterecordid_msdyn_aiodimage: msdyn_AIOdImage_Result }>;
  duplicaterecordid_msdyn_aiodlabel: WebExpand<DuplicateRecord_Expand, msdyn_AIOdLabel_Select, msdyn_AIOdLabel_Filter, { duplicaterecordid_msdyn_aiodlabel: msdyn_AIOdLabel_Result }>;
  duplicaterecordid_msdyn_aiodtrainingboundingbox: WebExpand<DuplicateRecord_Expand, msdyn_AIOdTrainingBoundingBox_Select, msdyn_AIOdTrainingBoundingBox_Filter, { duplicaterecordid_msdyn_aiodtrainingboundingbox: msdyn_AIOdTrainingBoundingBox_Result }>;
  duplicaterecordid_msdyn_aiodtrainingimage: WebExpand<DuplicateRecord_Expand, msdyn_AIOdTrainingImage_Select, msdyn_AIOdTrainingImage_Filter, { duplicaterecordid_msdyn_aiodtrainingimage: msdyn_AIOdTrainingImage_Result }>;
  duplicaterecordid_msdyn_analysiscomponent: WebExpand<DuplicateRecord_Expand, msdyn_analysiscomponent_Select, msdyn_analysiscomponent_Filter, { duplicaterecordid_msdyn_analysiscomponent: msdyn_analysiscomponent_Result }>;
  duplicaterecordid_msdyn_analysisjob: WebExpand<DuplicateRecord_Expand, msdyn_analysisjob_Select, msdyn_analysisjob_Filter, { duplicaterecordid_msdyn_analysisjob: msdyn_analysisjob_Result }>;
  duplicaterecordid_msdyn_analysisresult: WebExpand<DuplicateRecord_Expand, msdyn_analysisresult_Select, msdyn_analysisresult_Filter, { duplicaterecordid_msdyn_analysisresult: msdyn_analysisresult_Result }>;
  duplicaterecordid_msdyn_analysisresultdetail: WebExpand<DuplicateRecord_Expand, msdyn_analysisresultdetail_Select, msdyn_analysisresultdetail_Filter, { duplicaterecordid_msdyn_analysisresultdetail: msdyn_analysisresultdetail_Result }>;
  duplicaterecordid_msdyn_dataflow: WebExpand<DuplicateRecord_Expand, msdyn_dataflow_Select, msdyn_dataflow_Filter, { duplicaterecordid_msdyn_dataflow: msdyn_dataflow_Result }>;
  duplicaterecordid_msdyn_federatedarticle: WebExpand<DuplicateRecord_Expand, msdyn_federatedarticle_Select, msdyn_federatedarticle_Filter, { duplicaterecordid_msdyn_federatedarticle: msdyn_federatedarticle_Result }>;
  duplicaterecordid_msdyn_federatedarticleincident: WebExpand<DuplicateRecord_Expand, msdyn_federatedarticleincident_Select, msdyn_federatedarticleincident_Filter, { duplicaterecordid_msdyn_federatedarticleincident: msdyn_federatedarticleincident_Result }>;
  duplicaterecordid_msdyn_kalanguagesetting: WebExpand<DuplicateRecord_Expand, msdyn_kalanguagesetting_Select, msdyn_kalanguagesetting_Filter, { duplicaterecordid_msdyn_kalanguagesetting: msdyn_kalanguagesetting_Result }>;
  duplicaterecordid_msdyn_kmfederatedsearchconfig: WebExpand<DuplicateRecord_Expand, msdyn_kmfederatedsearchconfig_Select, msdyn_kmfederatedsearchconfig_Filter, { duplicaterecordid_msdyn_kmfederatedsearchconfig: msdyn_kmfederatedsearchconfig_Result }>;
  duplicaterecordid_msdyn_knowledgearticleimage: WebExpand<DuplicateRecord_Expand, msdyn_knowledgearticleimage_Select, msdyn_knowledgearticleimage_Filter, { duplicaterecordid_msdyn_knowledgearticleimage: msdyn_knowledgearticleimage_Result }>;
  duplicaterecordid_msdyn_knowledgearticletemplate: WebExpand<DuplicateRecord_Expand, msdyn_knowledgearticletemplate_Select, msdyn_knowledgearticletemplate_Filter, { duplicaterecordid_msdyn_knowledgearticletemplate: msdyn_knowledgearticletemplate_Result }>;
  duplicaterecordid_msdyn_knowledgeinteractioninsight: WebExpand<DuplicateRecord_Expand, msdyn_knowledgeinteractioninsight_Select, msdyn_knowledgeinteractioninsight_Filter, { duplicaterecordid_msdyn_knowledgeinteractioninsight: msdyn_knowledgeinteractioninsight_Result }>;
  duplicaterecordid_msdyn_knowledgepersonalfilter: WebExpand<DuplicateRecord_Expand, msdyn_knowledgepersonalfilter_Select, msdyn_knowledgepersonalfilter_Filter, { duplicaterecordid_msdyn_knowledgepersonalfilter: msdyn_knowledgepersonalfilter_Result }>;
  duplicaterecordid_msdyn_knowledgesearchfilter: WebExpand<DuplicateRecord_Expand, msdyn_knowledgesearchfilter_Select, msdyn_knowledgesearchfilter_Filter, { duplicaterecordid_msdyn_knowledgesearchfilter: msdyn_knowledgesearchfilter_Result }>;
  duplicaterecordid_msdyn_knowledgesearchinsight: WebExpand<DuplicateRecord_Expand, msdyn_knowledgesearchinsight_Select, msdyn_knowledgesearchinsight_Filter, { duplicaterecordid_msdyn_knowledgesearchinsight: msdyn_knowledgesearchinsight_Result }>;
  duplicaterecordid_msdyn_pminferredtask: WebExpand<DuplicateRecord_Expand, msdyn_pminferredtask_Select, msdyn_pminferredtask_Filter, { duplicaterecordid_msdyn_pminferredtask: msdyn_pminferredtask_Result }>;
  duplicaterecordid_msdyn_pmrecording: WebExpand<DuplicateRecord_Expand, msdyn_pmrecording_Select, msdyn_pmrecording_Filter, { duplicaterecordid_msdyn_pmrecording: msdyn_pmrecording_Result }>;
  duplicaterecordid_msdyn_serviceconfiguration: WebExpand<DuplicateRecord_Expand, msdyn_serviceconfiguration_Select, msdyn_serviceconfiguration_Filter, { duplicaterecordid_msdyn_serviceconfiguration: msdyn_serviceconfiguration_Result }>;
  duplicaterecordid_msdyn_slakpi: WebExpand<DuplicateRecord_Expand, msdyn_slakpi_Select, msdyn_slakpi_Filter, { duplicaterecordid_msdyn_slakpi: msdyn_slakpi_Result }>;
  duplicaterecordid_msdyn_solutionhealthrule: WebExpand<DuplicateRecord_Expand, msdyn_solutionhealthrule_Select, msdyn_solutionhealthrule_Filter, { duplicaterecordid_msdyn_solutionhealthrule: msdyn_solutionhealthrule_Result }>;
  duplicaterecordid_msdyn_solutionhealthruleargument: WebExpand<DuplicateRecord_Expand, msdyn_solutionhealthruleargument_Select, msdyn_solutionhealthruleargument_Filter, { duplicaterecordid_msdyn_solutionhealthruleargument: msdyn_solutionhealthruleargument_Result }>;
  duplicaterecordid_msdyn_solutionhealthruleset: WebExpand<DuplicateRecord_Expand, msdyn_solutionhealthruleset_Select, msdyn_solutionhealthruleset_Filter, { duplicaterecordid_msdyn_solutionhealthruleset: msdyn_solutionhealthruleset_Result }>;
  duplicaterecordid_organizationdatasyncsubscription: WebExpand<DuplicateRecord_Expand, organizationdatasyncsubscription_Select, organizationdatasyncsubscription_Filter, { duplicaterecordid_organizationdatasyncsubscription: organizationdatasyncsubscription_Result }>;
  duplicaterecordid_organizationdatasyncsubscriptionentity: WebExpand<DuplicateRecord_Expand, organizationdatasyncsubscriptionentity_Select, organizationdatasyncsubscriptionentity_Filter, { duplicaterecordid_organizationdatasyncsubscriptionentity: organizationdatasyncsubscriptionentity_Result }>;
  duplicaterecordid_package: WebExpand<DuplicateRecord_Expand, package_Select, package_Filter, { duplicaterecordid_package: package_Result }>;
  duplicaterecordid_phonecall: WebExpand<DuplicateRecord_Expand, PhoneCall_Select, PhoneCall_Filter, { duplicaterecordid_phonecall: PhoneCall_Result }>;
  duplicaterecordid_publisher: WebExpand<DuplicateRecord_Expand, Publisher_Select, Publisher_Filter, { duplicaterecordid_publisher: Publisher_Result }>;
  duplicaterecordid_queue: WebExpand<DuplicateRecord_Expand, Queue_Select, Queue_Filter, { duplicaterecordid_queue: Queue_Result }>;
  duplicaterecordid_recurringappointmentmaster: WebExpand<DuplicateRecord_Expand, RecurringAppointmentMaster_Select, RecurringAppointmentMaster_Filter, { duplicaterecordid_recurringappointmentmaster: RecurringAppointmentMaster_Result }>;
  duplicaterecordid_revokeinheritedaccessrecordstracker: WebExpand<DuplicateRecord_Expand, revokeinheritedaccessrecordstracker_Select, revokeinheritedaccessrecordstracker_Filter, { duplicaterecordid_revokeinheritedaccessrecordstracker: revokeinheritedaccessrecordstracker_Result }>;
  duplicaterecordid_serviceplan: WebExpand<DuplicateRecord_Expand, ServicePlan_Select, ServicePlan_Filter, { duplicaterecordid_serviceplan: ServicePlan_Result }>;
  duplicaterecordid_serviceplanmapping: WebExpand<DuplicateRecord_Expand, ServicePlanMapping_Select, ServicePlanMapping_Filter, { duplicaterecordid_serviceplanmapping: ServicePlanMapping_Result }>;
  duplicaterecordid_sharepointdocumentlocation: WebExpand<DuplicateRecord_Expand, SharePointDocumentLocation_Select, SharePointDocumentLocation_Filter, { duplicaterecordid_sharepointdocumentlocation: SharePointDocumentLocation_Result }>;
  duplicaterecordid_sharepointsite: WebExpand<DuplicateRecord_Expand, SharePointSite_Select, SharePointSite_Filter, { duplicaterecordid_sharepointsite: SharePointSite_Result }>;
  duplicaterecordid_socialactivity: WebExpand<DuplicateRecord_Expand, SocialActivity_Select, SocialActivity_Filter, { duplicaterecordid_socialactivity: SocialActivity_Result }>;
  duplicaterecordid_socialprofile: WebExpand<DuplicateRecord_Expand, SocialProfile_Select, SocialProfile_Filter, { duplicaterecordid_socialprofile: SocialProfile_Result }>;
  duplicaterecordid_solutioncomponentattributeconfiguration: WebExpand<DuplicateRecord_Expand, solutioncomponentattributeconfiguration_Select, solutioncomponentattributeconfiguration_Filter, { duplicaterecordid_solutioncomponentattributeconfiguration: solutioncomponentattributeconfiguration_Result }>;
  duplicaterecordid_solutioncomponentbatchconfiguration: WebExpand<DuplicateRecord_Expand, solutioncomponentbatchconfiguration_Select, solutioncomponentbatchconfiguration_Filter, { duplicaterecordid_solutioncomponentbatchconfiguration: solutioncomponentbatchconfiguration_Result }>;
  duplicaterecordid_solutioncomponentconfiguration: WebExpand<DuplicateRecord_Expand, solutioncomponentconfiguration_Select, solutioncomponentconfiguration_Filter, { duplicaterecordid_solutioncomponentconfiguration: solutioncomponentconfiguration_Result }>;
  duplicaterecordid_solutioncomponentrelationshipconfiguration: WebExpand<DuplicateRecord_Expand, solutioncomponentrelationshipconfiguration_Select, solutioncomponentrelationshipconfiguration_Filter, { duplicaterecordid_solutioncomponentrelationshipconfiguration: solutioncomponentrelationshipconfiguration_Result }>;
  duplicaterecordid_stagesolutionupload: WebExpand<DuplicateRecord_Expand, StageSolutionUpload_Select, StageSolutionUpload_Filter, { duplicaterecordid_stagesolutionupload: StageSolutionUpload_Result }>;
  duplicaterecordid_systemuser: WebExpand<DuplicateRecord_Expand, SystemUser_Select, SystemUser_Filter, { duplicaterecordid_systemuser: SystemUser_Result }>;
  duplicaterecordid_task: WebExpand<DuplicateRecord_Expand, Task_Select, Task_Filter, { duplicaterecordid_task: Task_Result }>;
  duplicaterecordid_team: WebExpand<DuplicateRecord_Expand, Team_Select, Team_Filter, { duplicaterecordid_team: Team_Result }>;
  duplicaterecordid_transactioncurrency: WebExpand<DuplicateRecord_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { duplicaterecordid_transactioncurrency: TransactionCurrency_Result }>;
  duplicateruleid: WebExpand<DuplicateRecord_Expand, DuplicateRule_Select, DuplicateRule_Filter, { duplicateruleid: DuplicateRule_Result }>;
  userentityinstancedata_duplicaterecord: WebExpand<DuplicateRecord_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { userentityinstancedata_duplicaterecord: UserEntityInstanceData_Result[] }>;
}
interface DuplicateRecord_FormattedResult {
  asyncoperationid_formatted?: string;
  baserecordid_formatted?: string;
  createdon_formatted?: string;
  duplicaterecordid_formatted?: string;
  duplicateruleid_formatted?: string;
  ownerid_formatted?: string;
}
interface DuplicateRecord_Result extends DuplicateRecord_Base, DuplicateRecord_Relationships {
  "@odata.etag": string;
  asyncoperationid_guid: string | null;
  baserecordid_guid: string | null;
  duplicaterecordid_guid: string | null;
  duplicateruleid_guid: string | null;
  ownerid_guid: string | null;
}
interface DuplicateRecord_RelatedOne {
  asyncoperationid: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  baserecordid_account: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  baserecordid_activityfileattachment: WebMappingRetrieve<activityfileattachment_Select,activityfileattachment_Expand,activityfileattachment_Filter,activityfileattachment_Fixed,activityfileattachment_Result,activityfileattachment_FormattedResult>;
  baserecordid_applicationuser: WebMappingRetrieve<ApplicationUser_Select,ApplicationUser_Expand,ApplicationUser_Filter,ApplicationUser_Fixed,ApplicationUser_Result,ApplicationUser_FormattedResult>;
  baserecordid_appointment: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
  baserecordid_canvasappextendedmetadata: WebMappingRetrieve<CanvasAppExtendedMetadata_Select,CanvasAppExtendedMetadata_Expand,CanvasAppExtendedMetadata_Filter,CanvasAppExtendedMetadata_Fixed,CanvasAppExtendedMetadata_Result,CanvasAppExtendedMetadata_FormattedResult>;
  baserecordid_cascadegrantrevokeaccessrecordstracker: WebMappingRetrieve<cascadegrantrevokeaccessrecordstracker_Select,cascadegrantrevokeaccessrecordstracker_Expand,cascadegrantrevokeaccessrecordstracker_Filter,cascadegrantrevokeaccessrecordstracker_Fixed,cascadegrantrevokeaccessrecordstracker_Result,cascadegrantrevokeaccessrecordstracker_FormattedResult>;
  baserecordid_cascadegrantrevokeaccessversiontracker: WebMappingRetrieve<cascadegrantrevokeaccessversiontracker_Select,cascadegrantrevokeaccessversiontracker_Expand,cascadegrantrevokeaccessversiontracker_Filter,cascadegrantrevokeaccessversiontracker_Fixed,cascadegrantrevokeaccessversiontracker_Result,cascadegrantrevokeaccessversiontracker_FormattedResult>;
  baserecordid_catalogassignment: WebMappingRetrieve<CatalogAssignment_Select,CatalogAssignment_Expand,CatalogAssignment_Filter,CatalogAssignment_Fixed,CatalogAssignment_Result,CatalogAssignment_FormattedResult>;
  baserecordid_connector: WebMappingRetrieve<connector_Select,connector_Expand,connector_Filter,connector_Fixed,connector_Result,connector_FormattedResult>;
  baserecordid_contact: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  baserecordid_conversationtranscript: WebMappingRetrieve<conversationtranscript_Select,conversationtranscript_Expand,conversationtranscript_Filter,conversationtranscript_Fixed,conversationtranscript_Result,conversationtranscript_FormattedResult>;
  baserecordid_datalakefolder: WebMappingRetrieve<datalakefolder_Select,datalakefolder_Expand,datalakefolder_Filter,datalakefolder_Fixed,datalakefolder_Result,datalakefolder_FormattedResult>;
  baserecordid_datalakefolderpermission: WebMappingRetrieve<datalakefolderpermission_Select,datalakefolderpermission_Expand,datalakefolderpermission_Filter,datalakefolderpermission_Fixed,datalakefolderpermission_Result,datalakefolderpermission_FormattedResult>;
  baserecordid_datalakeworkspace: WebMappingRetrieve<datalakeworkspace_Select,datalakeworkspace_Expand,datalakeworkspace_Filter,datalakeworkspace_Fixed,datalakeworkspace_Result,datalakeworkspace_FormattedResult>;
  baserecordid_datalakeworkspacepermission: WebMappingRetrieve<datalakeworkspacepermission_Select,datalakeworkspacepermission_Expand,datalakeworkspacepermission_Filter,datalakeworkspacepermission_Fixed,datalakeworkspacepermission_Result,datalakeworkspacepermission_FormattedResult>;
  baserecordid_email: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  baserecordid_emailserverprofile: WebMappingRetrieve<EmailServerProfile_Select,EmailServerProfile_Expand,EmailServerProfile_Filter,EmailServerProfile_Fixed,EmailServerProfile_Result,EmailServerProfile_FormattedResult>;
  baserecordid_environmentvariabledefinition: WebMappingRetrieve<EnvironmentVariableDefinition_Select,EnvironmentVariableDefinition_Expand,EnvironmentVariableDefinition_Filter,EnvironmentVariableDefinition_Fixed,EnvironmentVariableDefinition_Result,EnvironmentVariableDefinition_FormattedResult>;
  baserecordid_environmentvariablevalue: WebMappingRetrieve<EnvironmentVariableValue_Select,EnvironmentVariableValue_Expand,EnvironmentVariableValue_Filter,EnvironmentVariableValue_Fixed,EnvironmentVariableValue_Result,EnvironmentVariableValue_FormattedResult>;
  baserecordid_exportsolutionupload: WebMappingRetrieve<ExportSolutionUpload_Select,ExportSolutionUpload_Expand,ExportSolutionUpload_Filter,ExportSolutionUpload_Fixed,ExportSolutionUpload_Result,ExportSolutionUpload_FormattedResult>;
  baserecordid_fax: WebMappingRetrieve<Fax_Select,Fax_Expand,Fax_Filter,Fax_Fixed,Fax_Result,Fax_FormattedResult>;
  baserecordid_featurecontrolsetting: WebMappingRetrieve<featurecontrolsetting_Select,featurecontrolsetting_Expand,featurecontrolsetting_Filter,featurecontrolsetting_Fixed,featurecontrolsetting_Result,featurecontrolsetting_FormattedResult>;
  baserecordid_feedback: WebMappingRetrieve<Feedback_Select,Feedback_Expand,Feedback_Filter,Feedback_Fixed,Feedback_Result,Feedback_FormattedResult>;
  baserecordid_flowmachinegroup: WebMappingRetrieve<flowmachinegroup_Select,flowmachinegroup_Expand,flowmachinegroup_Filter,flowmachinegroup_Fixed,flowmachinegroup_Result,flowmachinegroup_FormattedResult>;
  baserecordid_goal: WebMappingRetrieve<Goal_Select,Goal_Expand,Goal_Filter,Goal_Fixed,Goal_Result,Goal_FormattedResult>;
  baserecordid_goalrollupquery: WebMappingRetrieve<GoalRollupQuery_Select,GoalRollupQuery_Expand,GoalRollupQuery_Filter,GoalRollupQuery_Fixed,GoalRollupQuery_Result,GoalRollupQuery_FormattedResult>;
  baserecordid_kbarticle: WebMappingRetrieve<KbArticle_Select,KbArticle_Expand,KbArticle_Filter,KbArticle_Fixed,KbArticle_Result,KbArticle_FormattedResult>;
  baserecordid_keyvaultreference: WebMappingRetrieve<KeyVaultReference_Select,KeyVaultReference_Expand,KeyVaultReference_Filter,KeyVaultReference_Fixed,KeyVaultReference_Result,KeyVaultReference_FormattedResult>;
  baserecordid_knowledgearticle: WebMappingRetrieve<KnowledgeArticle_Select,KnowledgeArticle_Expand,KnowledgeArticle_Filter,KnowledgeArticle_Fixed,KnowledgeArticle_Result,KnowledgeArticle_FormattedResult>;
  baserecordid_knowledgebaserecord: WebMappingRetrieve<KnowledgeBaseRecord_Select,KnowledgeBaseRecord_Expand,KnowledgeBaseRecord_Filter,KnowledgeBaseRecord_Fixed,KnowledgeBaseRecord_Result,KnowledgeBaseRecord_FormattedResult>;
  baserecordid_letter: WebMappingRetrieve<Letter_Select,Letter_Expand,Letter_Filter,Letter_Fixed,Letter_Result,Letter_FormattedResult>;
  baserecordid_managedidentity: WebMappingRetrieve<ManagedIdentity_Select,ManagedIdentity_Expand,ManagedIdentity_Filter,ManagedIdentity_Fixed,ManagedIdentity_Result,ManagedIdentity_FormattedResult>;
  baserecordid_msdyn_aibdataset: WebMappingRetrieve<msdyn_AIBDataset_Select,msdyn_AIBDataset_Expand,msdyn_AIBDataset_Filter,msdyn_AIBDataset_Fixed,msdyn_AIBDataset_Result,msdyn_AIBDataset_FormattedResult>;
  baserecordid_msdyn_aibdatasetfile: WebMappingRetrieve<msdyn_AIBDatasetFile_Select,msdyn_AIBDatasetFile_Expand,msdyn_AIBDatasetFile_Filter,msdyn_AIBDatasetFile_Fixed,msdyn_AIBDatasetFile_Result,msdyn_AIBDatasetFile_FormattedResult>;
  baserecordid_msdyn_aibdatasetrecord: WebMappingRetrieve<msdyn_AIBDatasetRecord_Select,msdyn_AIBDatasetRecord_Expand,msdyn_AIBDatasetRecord_Filter,msdyn_AIBDatasetRecord_Fixed,msdyn_AIBDatasetRecord_Result,msdyn_AIBDatasetRecord_FormattedResult>;
  baserecordid_msdyn_aibdatasetscontainer: WebMappingRetrieve<msdyn_AIBDatasetsContainer_Select,msdyn_AIBDatasetsContainer_Expand,msdyn_AIBDatasetsContainer_Filter,msdyn_AIBDatasetsContainer_Fixed,msdyn_AIBDatasetsContainer_Result,msdyn_AIBDatasetsContainer_FormattedResult>;
  baserecordid_msdyn_aibfile: WebMappingRetrieve<msdyn_AIBFile_Select,msdyn_AIBFile_Expand,msdyn_AIBFile_Filter,msdyn_AIBFile_Fixed,msdyn_AIBFile_Result,msdyn_AIBFile_FormattedResult>;
  baserecordid_msdyn_aibfileattacheddata: WebMappingRetrieve<msdyn_AIBFileAttachedData_Select,msdyn_AIBFileAttachedData_Expand,msdyn_AIBFileAttachedData_Filter,msdyn_AIBFileAttachedData_Fixed,msdyn_AIBFileAttachedData_Result,msdyn_AIBFileAttachedData_FormattedResult>;
  baserecordid_msdyn_aiodimage: WebMappingRetrieve<msdyn_AIOdImage_Select,msdyn_AIOdImage_Expand,msdyn_AIOdImage_Filter,msdyn_AIOdImage_Fixed,msdyn_AIOdImage_Result,msdyn_AIOdImage_FormattedResult>;
  baserecordid_msdyn_aiodlabel: WebMappingRetrieve<msdyn_AIOdLabel_Select,msdyn_AIOdLabel_Expand,msdyn_AIOdLabel_Filter,msdyn_AIOdLabel_Fixed,msdyn_AIOdLabel_Result,msdyn_AIOdLabel_FormattedResult>;
  baserecordid_msdyn_aiodtrainingboundingbox: WebMappingRetrieve<msdyn_AIOdTrainingBoundingBox_Select,msdyn_AIOdTrainingBoundingBox_Expand,msdyn_AIOdTrainingBoundingBox_Filter,msdyn_AIOdTrainingBoundingBox_Fixed,msdyn_AIOdTrainingBoundingBox_Result,msdyn_AIOdTrainingBoundingBox_FormattedResult>;
  baserecordid_msdyn_aiodtrainingimage: WebMappingRetrieve<msdyn_AIOdTrainingImage_Select,msdyn_AIOdTrainingImage_Expand,msdyn_AIOdTrainingImage_Filter,msdyn_AIOdTrainingImage_Fixed,msdyn_AIOdTrainingImage_Result,msdyn_AIOdTrainingImage_FormattedResult>;
  baserecordid_msdyn_analysiscomponent: WebMappingRetrieve<msdyn_analysiscomponent_Select,msdyn_analysiscomponent_Expand,msdyn_analysiscomponent_Filter,msdyn_analysiscomponent_Fixed,msdyn_analysiscomponent_Result,msdyn_analysiscomponent_FormattedResult>;
  baserecordid_msdyn_analysisjob: WebMappingRetrieve<msdyn_analysisjob_Select,msdyn_analysisjob_Expand,msdyn_analysisjob_Filter,msdyn_analysisjob_Fixed,msdyn_analysisjob_Result,msdyn_analysisjob_FormattedResult>;
  baserecordid_msdyn_analysisresult: WebMappingRetrieve<msdyn_analysisresult_Select,msdyn_analysisresult_Expand,msdyn_analysisresult_Filter,msdyn_analysisresult_Fixed,msdyn_analysisresult_Result,msdyn_analysisresult_FormattedResult>;
  baserecordid_msdyn_analysisresultdetail: WebMappingRetrieve<msdyn_analysisresultdetail_Select,msdyn_analysisresultdetail_Expand,msdyn_analysisresultdetail_Filter,msdyn_analysisresultdetail_Fixed,msdyn_analysisresultdetail_Result,msdyn_analysisresultdetail_FormattedResult>;
  baserecordid_msdyn_dataflow: WebMappingRetrieve<msdyn_dataflow_Select,msdyn_dataflow_Expand,msdyn_dataflow_Filter,msdyn_dataflow_Fixed,msdyn_dataflow_Result,msdyn_dataflow_FormattedResult>;
  baserecordid_msdyn_federatedarticle: WebMappingRetrieve<msdyn_federatedarticle_Select,msdyn_federatedarticle_Expand,msdyn_federatedarticle_Filter,msdyn_federatedarticle_Fixed,msdyn_federatedarticle_Result,msdyn_federatedarticle_FormattedResult>;
  baserecordid_msdyn_federatedarticleincident: WebMappingRetrieve<msdyn_federatedarticleincident_Select,msdyn_federatedarticleincident_Expand,msdyn_federatedarticleincident_Filter,msdyn_federatedarticleincident_Fixed,msdyn_federatedarticleincident_Result,msdyn_federatedarticleincident_FormattedResult>;
  baserecordid_msdyn_kalanguagesetting: WebMappingRetrieve<msdyn_kalanguagesetting_Select,msdyn_kalanguagesetting_Expand,msdyn_kalanguagesetting_Filter,msdyn_kalanguagesetting_Fixed,msdyn_kalanguagesetting_Result,msdyn_kalanguagesetting_FormattedResult>;
  baserecordid_msdyn_kmfederatedsearchconfig: WebMappingRetrieve<msdyn_kmfederatedsearchconfig_Select,msdyn_kmfederatedsearchconfig_Expand,msdyn_kmfederatedsearchconfig_Filter,msdyn_kmfederatedsearchconfig_Fixed,msdyn_kmfederatedsearchconfig_Result,msdyn_kmfederatedsearchconfig_FormattedResult>;
  baserecordid_msdyn_knowledgearticleimage: WebMappingRetrieve<msdyn_knowledgearticleimage_Select,msdyn_knowledgearticleimage_Expand,msdyn_knowledgearticleimage_Filter,msdyn_knowledgearticleimage_Fixed,msdyn_knowledgearticleimage_Result,msdyn_knowledgearticleimage_FormattedResult>;
  baserecordid_msdyn_knowledgearticletemplate: WebMappingRetrieve<msdyn_knowledgearticletemplate_Select,msdyn_knowledgearticletemplate_Expand,msdyn_knowledgearticletemplate_Filter,msdyn_knowledgearticletemplate_Fixed,msdyn_knowledgearticletemplate_Result,msdyn_knowledgearticletemplate_FormattedResult>;
  baserecordid_msdyn_knowledgeinteractioninsight: WebMappingRetrieve<msdyn_knowledgeinteractioninsight_Select,msdyn_knowledgeinteractioninsight_Expand,msdyn_knowledgeinteractioninsight_Filter,msdyn_knowledgeinteractioninsight_Fixed,msdyn_knowledgeinteractioninsight_Result,msdyn_knowledgeinteractioninsight_FormattedResult>;
  baserecordid_msdyn_knowledgepersonalfilter: WebMappingRetrieve<msdyn_knowledgepersonalfilter_Select,msdyn_knowledgepersonalfilter_Expand,msdyn_knowledgepersonalfilter_Filter,msdyn_knowledgepersonalfilter_Fixed,msdyn_knowledgepersonalfilter_Result,msdyn_knowledgepersonalfilter_FormattedResult>;
  baserecordid_msdyn_knowledgesearchfilter: WebMappingRetrieve<msdyn_knowledgesearchfilter_Select,msdyn_knowledgesearchfilter_Expand,msdyn_knowledgesearchfilter_Filter,msdyn_knowledgesearchfilter_Fixed,msdyn_knowledgesearchfilter_Result,msdyn_knowledgesearchfilter_FormattedResult>;
  baserecordid_msdyn_knowledgesearchinsight: WebMappingRetrieve<msdyn_knowledgesearchinsight_Select,msdyn_knowledgesearchinsight_Expand,msdyn_knowledgesearchinsight_Filter,msdyn_knowledgesearchinsight_Fixed,msdyn_knowledgesearchinsight_Result,msdyn_knowledgesearchinsight_FormattedResult>;
  baserecordid_msdyn_pminferredtask: WebMappingRetrieve<msdyn_pminferredtask_Select,msdyn_pminferredtask_Expand,msdyn_pminferredtask_Filter,msdyn_pminferredtask_Fixed,msdyn_pminferredtask_Result,msdyn_pminferredtask_FormattedResult>;
  baserecordid_msdyn_pmrecording: WebMappingRetrieve<msdyn_pmrecording_Select,msdyn_pmrecording_Expand,msdyn_pmrecording_Filter,msdyn_pmrecording_Fixed,msdyn_pmrecording_Result,msdyn_pmrecording_FormattedResult>;
  baserecordid_msdyn_serviceconfiguration: WebMappingRetrieve<msdyn_serviceconfiguration_Select,msdyn_serviceconfiguration_Expand,msdyn_serviceconfiguration_Filter,msdyn_serviceconfiguration_Fixed,msdyn_serviceconfiguration_Result,msdyn_serviceconfiguration_FormattedResult>;
  baserecordid_msdyn_slakpi: WebMappingRetrieve<msdyn_slakpi_Select,msdyn_slakpi_Expand,msdyn_slakpi_Filter,msdyn_slakpi_Fixed,msdyn_slakpi_Result,msdyn_slakpi_FormattedResult>;
  baserecordid_msdyn_solutionhealthrule: WebMappingRetrieve<msdyn_solutionhealthrule_Select,msdyn_solutionhealthrule_Expand,msdyn_solutionhealthrule_Filter,msdyn_solutionhealthrule_Fixed,msdyn_solutionhealthrule_Result,msdyn_solutionhealthrule_FormattedResult>;
  baserecordid_msdyn_solutionhealthruleargument: WebMappingRetrieve<msdyn_solutionhealthruleargument_Select,msdyn_solutionhealthruleargument_Expand,msdyn_solutionhealthruleargument_Filter,msdyn_solutionhealthruleargument_Fixed,msdyn_solutionhealthruleargument_Result,msdyn_solutionhealthruleargument_FormattedResult>;
  baserecordid_msdyn_solutionhealthruleset: WebMappingRetrieve<msdyn_solutionhealthruleset_Select,msdyn_solutionhealthruleset_Expand,msdyn_solutionhealthruleset_Filter,msdyn_solutionhealthruleset_Fixed,msdyn_solutionhealthruleset_Result,msdyn_solutionhealthruleset_FormattedResult>;
  baserecordid_organizationdatasyncsubscription: WebMappingRetrieve<organizationdatasyncsubscription_Select,organizationdatasyncsubscription_Expand,organizationdatasyncsubscription_Filter,organizationdatasyncsubscription_Fixed,organizationdatasyncsubscription_Result,organizationdatasyncsubscription_FormattedResult>;
  baserecordid_organizationdatasyncsubscriptionentity: WebMappingRetrieve<organizationdatasyncsubscriptionentity_Select,organizationdatasyncsubscriptionentity_Expand,organizationdatasyncsubscriptionentity_Filter,organizationdatasyncsubscriptionentity_Fixed,organizationdatasyncsubscriptionentity_Result,organizationdatasyncsubscriptionentity_FormattedResult>;
  baserecordid_package: WebMappingRetrieve<package_Select,package_Expand,package_Filter,package_Fixed,package_Result,package_FormattedResult>;
  baserecordid_phonecall: WebMappingRetrieve<PhoneCall_Select,PhoneCall_Expand,PhoneCall_Filter,PhoneCall_Fixed,PhoneCall_Result,PhoneCall_FormattedResult>;
  baserecordid_publisher: WebMappingRetrieve<Publisher_Select,Publisher_Expand,Publisher_Filter,Publisher_Fixed,Publisher_Result,Publisher_FormattedResult>;
  baserecordid_queue: WebMappingRetrieve<Queue_Select,Queue_Expand,Queue_Filter,Queue_Fixed,Queue_Result,Queue_FormattedResult>;
  baserecordid_recurringappointmentmaster: WebMappingRetrieve<RecurringAppointmentMaster_Select,RecurringAppointmentMaster_Expand,RecurringAppointmentMaster_Filter,RecurringAppointmentMaster_Fixed,RecurringAppointmentMaster_Result,RecurringAppointmentMaster_FormattedResult>;
  baserecordid_revokeinheritedaccessrecordstracker: WebMappingRetrieve<revokeinheritedaccessrecordstracker_Select,revokeinheritedaccessrecordstracker_Expand,revokeinheritedaccessrecordstracker_Filter,revokeinheritedaccessrecordstracker_Fixed,revokeinheritedaccessrecordstracker_Result,revokeinheritedaccessrecordstracker_FormattedResult>;
  baserecordid_serviceplan: WebMappingRetrieve<ServicePlan_Select,ServicePlan_Expand,ServicePlan_Filter,ServicePlan_Fixed,ServicePlan_Result,ServicePlan_FormattedResult>;
  baserecordid_serviceplanmapping: WebMappingRetrieve<ServicePlanMapping_Select,ServicePlanMapping_Expand,ServicePlanMapping_Filter,ServicePlanMapping_Fixed,ServicePlanMapping_Result,ServicePlanMapping_FormattedResult>;
  baserecordid_sharepointdocumentlocation: WebMappingRetrieve<SharePointDocumentLocation_Select,SharePointDocumentLocation_Expand,SharePointDocumentLocation_Filter,SharePointDocumentLocation_Fixed,SharePointDocumentLocation_Result,SharePointDocumentLocation_FormattedResult>;
  baserecordid_sharepointsite: WebMappingRetrieve<SharePointSite_Select,SharePointSite_Expand,SharePointSite_Filter,SharePointSite_Fixed,SharePointSite_Result,SharePointSite_FormattedResult>;
  baserecordid_socialactivity: WebMappingRetrieve<SocialActivity_Select,SocialActivity_Expand,SocialActivity_Filter,SocialActivity_Fixed,SocialActivity_Result,SocialActivity_FormattedResult>;
  baserecordid_socialprofile: WebMappingRetrieve<SocialProfile_Select,SocialProfile_Expand,SocialProfile_Filter,SocialProfile_Fixed,SocialProfile_Result,SocialProfile_FormattedResult>;
  baserecordid_solutioncomponentattributeconfiguration: WebMappingRetrieve<solutioncomponentattributeconfiguration_Select,solutioncomponentattributeconfiguration_Expand,solutioncomponentattributeconfiguration_Filter,solutioncomponentattributeconfiguration_Fixed,solutioncomponentattributeconfiguration_Result,solutioncomponentattributeconfiguration_FormattedResult>;
  baserecordid_solutioncomponentbatchconfiguration: WebMappingRetrieve<solutioncomponentbatchconfiguration_Select,solutioncomponentbatchconfiguration_Expand,solutioncomponentbatchconfiguration_Filter,solutioncomponentbatchconfiguration_Fixed,solutioncomponentbatchconfiguration_Result,solutioncomponentbatchconfiguration_FormattedResult>;
  baserecordid_solutioncomponentconfiguration: WebMappingRetrieve<solutioncomponentconfiguration_Select,solutioncomponentconfiguration_Expand,solutioncomponentconfiguration_Filter,solutioncomponentconfiguration_Fixed,solutioncomponentconfiguration_Result,solutioncomponentconfiguration_FormattedResult>;
  baserecordid_solutioncomponentrelationshipconfiguration: WebMappingRetrieve<solutioncomponentrelationshipconfiguration_Select,solutioncomponentrelationshipconfiguration_Expand,solutioncomponentrelationshipconfiguration_Filter,solutioncomponentrelationshipconfiguration_Fixed,solutioncomponentrelationshipconfiguration_Result,solutioncomponentrelationshipconfiguration_FormattedResult>;
  baserecordid_stagesolutionupload: WebMappingRetrieve<StageSolutionUpload_Select,StageSolutionUpload_Expand,StageSolutionUpload_Filter,StageSolutionUpload_Fixed,StageSolutionUpload_Result,StageSolutionUpload_FormattedResult>;
  baserecordid_systemuser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  baserecordid_task: WebMappingRetrieve<Task_Select,Task_Expand,Task_Filter,Task_Fixed,Task_Result,Task_FormattedResult>;
  baserecordid_team: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  baserecordid_transactioncurrency: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
  channelaccessprofile_duplicatebaserecord: WebMappingRetrieve<ChannelAccessProfile_Select,ChannelAccessProfile_Expand,ChannelAccessProfile_Filter,ChannelAccessProfile_Fixed,ChannelAccessProfile_Result,ChannelAccessProfile_FormattedResult>;
  channelaccessprofile_duplicatematchingrecord: WebMappingRetrieve<ChannelAccessProfile_Select,ChannelAccessProfile_Expand,ChannelAccessProfile_Filter,ChannelAccessProfile_Fixed,ChannelAccessProfile_Result,ChannelAccessProfile_FormattedResult>;
  duplicaterecordid_account: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  duplicaterecordid_activityfileattachment: WebMappingRetrieve<activityfileattachment_Select,activityfileattachment_Expand,activityfileattachment_Filter,activityfileattachment_Fixed,activityfileattachment_Result,activityfileattachment_FormattedResult>;
  duplicaterecordid_applicationuser: WebMappingRetrieve<ApplicationUser_Select,ApplicationUser_Expand,ApplicationUser_Filter,ApplicationUser_Fixed,ApplicationUser_Result,ApplicationUser_FormattedResult>;
  duplicaterecordid_appointment: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
  duplicaterecordid_canvasappextendedmetadata: WebMappingRetrieve<CanvasAppExtendedMetadata_Select,CanvasAppExtendedMetadata_Expand,CanvasAppExtendedMetadata_Filter,CanvasAppExtendedMetadata_Fixed,CanvasAppExtendedMetadata_Result,CanvasAppExtendedMetadata_FormattedResult>;
  duplicaterecordid_cascadegrantrevokeaccessrecordstracker: WebMappingRetrieve<cascadegrantrevokeaccessrecordstracker_Select,cascadegrantrevokeaccessrecordstracker_Expand,cascadegrantrevokeaccessrecordstracker_Filter,cascadegrantrevokeaccessrecordstracker_Fixed,cascadegrantrevokeaccessrecordstracker_Result,cascadegrantrevokeaccessrecordstracker_FormattedResult>;
  duplicaterecordid_cascadegrantrevokeaccessversiontracker: WebMappingRetrieve<cascadegrantrevokeaccessversiontracker_Select,cascadegrantrevokeaccessversiontracker_Expand,cascadegrantrevokeaccessversiontracker_Filter,cascadegrantrevokeaccessversiontracker_Fixed,cascadegrantrevokeaccessversiontracker_Result,cascadegrantrevokeaccessversiontracker_FormattedResult>;
  duplicaterecordid_catalogassignment: WebMappingRetrieve<CatalogAssignment_Select,CatalogAssignment_Expand,CatalogAssignment_Filter,CatalogAssignment_Fixed,CatalogAssignment_Result,CatalogAssignment_FormattedResult>;
  duplicaterecordid_connector: WebMappingRetrieve<connector_Select,connector_Expand,connector_Filter,connector_Fixed,connector_Result,connector_FormattedResult>;
  duplicaterecordid_contact: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  duplicaterecordid_conversationtranscript: WebMappingRetrieve<conversationtranscript_Select,conversationtranscript_Expand,conversationtranscript_Filter,conversationtranscript_Fixed,conversationtranscript_Result,conversationtranscript_FormattedResult>;
  duplicaterecordid_datalakefolder: WebMappingRetrieve<datalakefolder_Select,datalakefolder_Expand,datalakefolder_Filter,datalakefolder_Fixed,datalakefolder_Result,datalakefolder_FormattedResult>;
  duplicaterecordid_datalakefolderpermission: WebMappingRetrieve<datalakefolderpermission_Select,datalakefolderpermission_Expand,datalakefolderpermission_Filter,datalakefolderpermission_Fixed,datalakefolderpermission_Result,datalakefolderpermission_FormattedResult>;
  duplicaterecordid_datalakeworkspace: WebMappingRetrieve<datalakeworkspace_Select,datalakeworkspace_Expand,datalakeworkspace_Filter,datalakeworkspace_Fixed,datalakeworkspace_Result,datalakeworkspace_FormattedResult>;
  duplicaterecordid_datalakeworkspacepermission: WebMappingRetrieve<datalakeworkspacepermission_Select,datalakeworkspacepermission_Expand,datalakeworkspacepermission_Filter,datalakeworkspacepermission_Fixed,datalakeworkspacepermission_Result,datalakeworkspacepermission_FormattedResult>;
  duplicaterecordid_email: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  duplicaterecordid_emailserverprofile: WebMappingRetrieve<EmailServerProfile_Select,EmailServerProfile_Expand,EmailServerProfile_Filter,EmailServerProfile_Fixed,EmailServerProfile_Result,EmailServerProfile_FormattedResult>;
  duplicaterecordid_environmentvariabledefinition: WebMappingRetrieve<EnvironmentVariableDefinition_Select,EnvironmentVariableDefinition_Expand,EnvironmentVariableDefinition_Filter,EnvironmentVariableDefinition_Fixed,EnvironmentVariableDefinition_Result,EnvironmentVariableDefinition_FormattedResult>;
  duplicaterecordid_environmentvariablevalue: WebMappingRetrieve<EnvironmentVariableValue_Select,EnvironmentVariableValue_Expand,EnvironmentVariableValue_Filter,EnvironmentVariableValue_Fixed,EnvironmentVariableValue_Result,EnvironmentVariableValue_FormattedResult>;
  duplicaterecordid_exportsolutionupload: WebMappingRetrieve<ExportSolutionUpload_Select,ExportSolutionUpload_Expand,ExportSolutionUpload_Filter,ExportSolutionUpload_Fixed,ExportSolutionUpload_Result,ExportSolutionUpload_FormattedResult>;
  duplicaterecordid_fax: WebMappingRetrieve<Fax_Select,Fax_Expand,Fax_Filter,Fax_Fixed,Fax_Result,Fax_FormattedResult>;
  duplicaterecordid_featurecontrolsetting: WebMappingRetrieve<featurecontrolsetting_Select,featurecontrolsetting_Expand,featurecontrolsetting_Filter,featurecontrolsetting_Fixed,featurecontrolsetting_Result,featurecontrolsetting_FormattedResult>;
  duplicaterecordid_feedback: WebMappingRetrieve<Feedback_Select,Feedback_Expand,Feedback_Filter,Feedback_Fixed,Feedback_Result,Feedback_FormattedResult>;
  duplicaterecordid_flowmachinegroup: WebMappingRetrieve<flowmachinegroup_Select,flowmachinegroup_Expand,flowmachinegroup_Filter,flowmachinegroup_Fixed,flowmachinegroup_Result,flowmachinegroup_FormattedResult>;
  duplicaterecordid_goal: WebMappingRetrieve<Goal_Select,Goal_Expand,Goal_Filter,Goal_Fixed,Goal_Result,Goal_FormattedResult>;
  duplicaterecordid_goalrollupquery: WebMappingRetrieve<GoalRollupQuery_Select,GoalRollupQuery_Expand,GoalRollupQuery_Filter,GoalRollupQuery_Fixed,GoalRollupQuery_Result,GoalRollupQuery_FormattedResult>;
  duplicaterecordid_kbarticle: WebMappingRetrieve<KbArticle_Select,KbArticle_Expand,KbArticle_Filter,KbArticle_Fixed,KbArticle_Result,KbArticle_FormattedResult>;
  duplicaterecordid_keyvaultreference: WebMappingRetrieve<KeyVaultReference_Select,KeyVaultReference_Expand,KeyVaultReference_Filter,KeyVaultReference_Fixed,KeyVaultReference_Result,KeyVaultReference_FormattedResult>;
  duplicaterecordid_knowledgearticle: WebMappingRetrieve<KnowledgeArticle_Select,KnowledgeArticle_Expand,KnowledgeArticle_Filter,KnowledgeArticle_Fixed,KnowledgeArticle_Result,KnowledgeArticle_FormattedResult>;
  duplicaterecordid_knowledgebaserecord: WebMappingRetrieve<KnowledgeBaseRecord_Select,KnowledgeBaseRecord_Expand,KnowledgeBaseRecord_Filter,KnowledgeBaseRecord_Fixed,KnowledgeBaseRecord_Result,KnowledgeBaseRecord_FormattedResult>;
  duplicaterecordid_letter: WebMappingRetrieve<Letter_Select,Letter_Expand,Letter_Filter,Letter_Fixed,Letter_Result,Letter_FormattedResult>;
  duplicaterecordid_managedidentity: WebMappingRetrieve<ManagedIdentity_Select,ManagedIdentity_Expand,ManagedIdentity_Filter,ManagedIdentity_Fixed,ManagedIdentity_Result,ManagedIdentity_FormattedResult>;
  duplicaterecordid_msdyn_aibdataset: WebMappingRetrieve<msdyn_AIBDataset_Select,msdyn_AIBDataset_Expand,msdyn_AIBDataset_Filter,msdyn_AIBDataset_Fixed,msdyn_AIBDataset_Result,msdyn_AIBDataset_FormattedResult>;
  duplicaterecordid_msdyn_aibdatasetfile: WebMappingRetrieve<msdyn_AIBDatasetFile_Select,msdyn_AIBDatasetFile_Expand,msdyn_AIBDatasetFile_Filter,msdyn_AIBDatasetFile_Fixed,msdyn_AIBDatasetFile_Result,msdyn_AIBDatasetFile_FormattedResult>;
  duplicaterecordid_msdyn_aibdatasetrecord: WebMappingRetrieve<msdyn_AIBDatasetRecord_Select,msdyn_AIBDatasetRecord_Expand,msdyn_AIBDatasetRecord_Filter,msdyn_AIBDatasetRecord_Fixed,msdyn_AIBDatasetRecord_Result,msdyn_AIBDatasetRecord_FormattedResult>;
  duplicaterecordid_msdyn_aibdatasetscontainer: WebMappingRetrieve<msdyn_AIBDatasetsContainer_Select,msdyn_AIBDatasetsContainer_Expand,msdyn_AIBDatasetsContainer_Filter,msdyn_AIBDatasetsContainer_Fixed,msdyn_AIBDatasetsContainer_Result,msdyn_AIBDatasetsContainer_FormattedResult>;
  duplicaterecordid_msdyn_aibfile: WebMappingRetrieve<msdyn_AIBFile_Select,msdyn_AIBFile_Expand,msdyn_AIBFile_Filter,msdyn_AIBFile_Fixed,msdyn_AIBFile_Result,msdyn_AIBFile_FormattedResult>;
  duplicaterecordid_msdyn_aibfileattacheddata: WebMappingRetrieve<msdyn_AIBFileAttachedData_Select,msdyn_AIBFileAttachedData_Expand,msdyn_AIBFileAttachedData_Filter,msdyn_AIBFileAttachedData_Fixed,msdyn_AIBFileAttachedData_Result,msdyn_AIBFileAttachedData_FormattedResult>;
  duplicaterecordid_msdyn_aiodimage: WebMappingRetrieve<msdyn_AIOdImage_Select,msdyn_AIOdImage_Expand,msdyn_AIOdImage_Filter,msdyn_AIOdImage_Fixed,msdyn_AIOdImage_Result,msdyn_AIOdImage_FormattedResult>;
  duplicaterecordid_msdyn_aiodlabel: WebMappingRetrieve<msdyn_AIOdLabel_Select,msdyn_AIOdLabel_Expand,msdyn_AIOdLabel_Filter,msdyn_AIOdLabel_Fixed,msdyn_AIOdLabel_Result,msdyn_AIOdLabel_FormattedResult>;
  duplicaterecordid_msdyn_aiodtrainingboundingbox: WebMappingRetrieve<msdyn_AIOdTrainingBoundingBox_Select,msdyn_AIOdTrainingBoundingBox_Expand,msdyn_AIOdTrainingBoundingBox_Filter,msdyn_AIOdTrainingBoundingBox_Fixed,msdyn_AIOdTrainingBoundingBox_Result,msdyn_AIOdTrainingBoundingBox_FormattedResult>;
  duplicaterecordid_msdyn_aiodtrainingimage: WebMappingRetrieve<msdyn_AIOdTrainingImage_Select,msdyn_AIOdTrainingImage_Expand,msdyn_AIOdTrainingImage_Filter,msdyn_AIOdTrainingImage_Fixed,msdyn_AIOdTrainingImage_Result,msdyn_AIOdTrainingImage_FormattedResult>;
  duplicaterecordid_msdyn_analysiscomponent: WebMappingRetrieve<msdyn_analysiscomponent_Select,msdyn_analysiscomponent_Expand,msdyn_analysiscomponent_Filter,msdyn_analysiscomponent_Fixed,msdyn_analysiscomponent_Result,msdyn_analysiscomponent_FormattedResult>;
  duplicaterecordid_msdyn_analysisjob: WebMappingRetrieve<msdyn_analysisjob_Select,msdyn_analysisjob_Expand,msdyn_analysisjob_Filter,msdyn_analysisjob_Fixed,msdyn_analysisjob_Result,msdyn_analysisjob_FormattedResult>;
  duplicaterecordid_msdyn_analysisresult: WebMappingRetrieve<msdyn_analysisresult_Select,msdyn_analysisresult_Expand,msdyn_analysisresult_Filter,msdyn_analysisresult_Fixed,msdyn_analysisresult_Result,msdyn_analysisresult_FormattedResult>;
  duplicaterecordid_msdyn_analysisresultdetail: WebMappingRetrieve<msdyn_analysisresultdetail_Select,msdyn_analysisresultdetail_Expand,msdyn_analysisresultdetail_Filter,msdyn_analysisresultdetail_Fixed,msdyn_analysisresultdetail_Result,msdyn_analysisresultdetail_FormattedResult>;
  duplicaterecordid_msdyn_dataflow: WebMappingRetrieve<msdyn_dataflow_Select,msdyn_dataflow_Expand,msdyn_dataflow_Filter,msdyn_dataflow_Fixed,msdyn_dataflow_Result,msdyn_dataflow_FormattedResult>;
  duplicaterecordid_msdyn_federatedarticle: WebMappingRetrieve<msdyn_federatedarticle_Select,msdyn_federatedarticle_Expand,msdyn_federatedarticle_Filter,msdyn_federatedarticle_Fixed,msdyn_federatedarticle_Result,msdyn_federatedarticle_FormattedResult>;
  duplicaterecordid_msdyn_federatedarticleincident: WebMappingRetrieve<msdyn_federatedarticleincident_Select,msdyn_federatedarticleincident_Expand,msdyn_federatedarticleincident_Filter,msdyn_federatedarticleincident_Fixed,msdyn_federatedarticleincident_Result,msdyn_federatedarticleincident_FormattedResult>;
  duplicaterecordid_msdyn_kalanguagesetting: WebMappingRetrieve<msdyn_kalanguagesetting_Select,msdyn_kalanguagesetting_Expand,msdyn_kalanguagesetting_Filter,msdyn_kalanguagesetting_Fixed,msdyn_kalanguagesetting_Result,msdyn_kalanguagesetting_FormattedResult>;
  duplicaterecordid_msdyn_kmfederatedsearchconfig: WebMappingRetrieve<msdyn_kmfederatedsearchconfig_Select,msdyn_kmfederatedsearchconfig_Expand,msdyn_kmfederatedsearchconfig_Filter,msdyn_kmfederatedsearchconfig_Fixed,msdyn_kmfederatedsearchconfig_Result,msdyn_kmfederatedsearchconfig_FormattedResult>;
  duplicaterecordid_msdyn_knowledgearticleimage: WebMappingRetrieve<msdyn_knowledgearticleimage_Select,msdyn_knowledgearticleimage_Expand,msdyn_knowledgearticleimage_Filter,msdyn_knowledgearticleimage_Fixed,msdyn_knowledgearticleimage_Result,msdyn_knowledgearticleimage_FormattedResult>;
  duplicaterecordid_msdyn_knowledgearticletemplate: WebMappingRetrieve<msdyn_knowledgearticletemplate_Select,msdyn_knowledgearticletemplate_Expand,msdyn_knowledgearticletemplate_Filter,msdyn_knowledgearticletemplate_Fixed,msdyn_knowledgearticletemplate_Result,msdyn_knowledgearticletemplate_FormattedResult>;
  duplicaterecordid_msdyn_knowledgeinteractioninsight: WebMappingRetrieve<msdyn_knowledgeinteractioninsight_Select,msdyn_knowledgeinteractioninsight_Expand,msdyn_knowledgeinteractioninsight_Filter,msdyn_knowledgeinteractioninsight_Fixed,msdyn_knowledgeinteractioninsight_Result,msdyn_knowledgeinteractioninsight_FormattedResult>;
  duplicaterecordid_msdyn_knowledgepersonalfilter: WebMappingRetrieve<msdyn_knowledgepersonalfilter_Select,msdyn_knowledgepersonalfilter_Expand,msdyn_knowledgepersonalfilter_Filter,msdyn_knowledgepersonalfilter_Fixed,msdyn_knowledgepersonalfilter_Result,msdyn_knowledgepersonalfilter_FormattedResult>;
  duplicaterecordid_msdyn_knowledgesearchfilter: WebMappingRetrieve<msdyn_knowledgesearchfilter_Select,msdyn_knowledgesearchfilter_Expand,msdyn_knowledgesearchfilter_Filter,msdyn_knowledgesearchfilter_Fixed,msdyn_knowledgesearchfilter_Result,msdyn_knowledgesearchfilter_FormattedResult>;
  duplicaterecordid_msdyn_knowledgesearchinsight: WebMappingRetrieve<msdyn_knowledgesearchinsight_Select,msdyn_knowledgesearchinsight_Expand,msdyn_knowledgesearchinsight_Filter,msdyn_knowledgesearchinsight_Fixed,msdyn_knowledgesearchinsight_Result,msdyn_knowledgesearchinsight_FormattedResult>;
  duplicaterecordid_msdyn_pminferredtask: WebMappingRetrieve<msdyn_pminferredtask_Select,msdyn_pminferredtask_Expand,msdyn_pminferredtask_Filter,msdyn_pminferredtask_Fixed,msdyn_pminferredtask_Result,msdyn_pminferredtask_FormattedResult>;
  duplicaterecordid_msdyn_pmrecording: WebMappingRetrieve<msdyn_pmrecording_Select,msdyn_pmrecording_Expand,msdyn_pmrecording_Filter,msdyn_pmrecording_Fixed,msdyn_pmrecording_Result,msdyn_pmrecording_FormattedResult>;
  duplicaterecordid_msdyn_serviceconfiguration: WebMappingRetrieve<msdyn_serviceconfiguration_Select,msdyn_serviceconfiguration_Expand,msdyn_serviceconfiguration_Filter,msdyn_serviceconfiguration_Fixed,msdyn_serviceconfiguration_Result,msdyn_serviceconfiguration_FormattedResult>;
  duplicaterecordid_msdyn_slakpi: WebMappingRetrieve<msdyn_slakpi_Select,msdyn_slakpi_Expand,msdyn_slakpi_Filter,msdyn_slakpi_Fixed,msdyn_slakpi_Result,msdyn_slakpi_FormattedResult>;
  duplicaterecordid_msdyn_solutionhealthrule: WebMappingRetrieve<msdyn_solutionhealthrule_Select,msdyn_solutionhealthrule_Expand,msdyn_solutionhealthrule_Filter,msdyn_solutionhealthrule_Fixed,msdyn_solutionhealthrule_Result,msdyn_solutionhealthrule_FormattedResult>;
  duplicaterecordid_msdyn_solutionhealthruleargument: WebMappingRetrieve<msdyn_solutionhealthruleargument_Select,msdyn_solutionhealthruleargument_Expand,msdyn_solutionhealthruleargument_Filter,msdyn_solutionhealthruleargument_Fixed,msdyn_solutionhealthruleargument_Result,msdyn_solutionhealthruleargument_FormattedResult>;
  duplicaterecordid_msdyn_solutionhealthruleset: WebMappingRetrieve<msdyn_solutionhealthruleset_Select,msdyn_solutionhealthruleset_Expand,msdyn_solutionhealthruleset_Filter,msdyn_solutionhealthruleset_Fixed,msdyn_solutionhealthruleset_Result,msdyn_solutionhealthruleset_FormattedResult>;
  duplicaterecordid_organizationdatasyncsubscription: WebMappingRetrieve<organizationdatasyncsubscription_Select,organizationdatasyncsubscription_Expand,organizationdatasyncsubscription_Filter,organizationdatasyncsubscription_Fixed,organizationdatasyncsubscription_Result,organizationdatasyncsubscription_FormattedResult>;
  duplicaterecordid_organizationdatasyncsubscriptionentity: WebMappingRetrieve<organizationdatasyncsubscriptionentity_Select,organizationdatasyncsubscriptionentity_Expand,organizationdatasyncsubscriptionentity_Filter,organizationdatasyncsubscriptionentity_Fixed,organizationdatasyncsubscriptionentity_Result,organizationdatasyncsubscriptionentity_FormattedResult>;
  duplicaterecordid_package: WebMappingRetrieve<package_Select,package_Expand,package_Filter,package_Fixed,package_Result,package_FormattedResult>;
  duplicaterecordid_phonecall: WebMappingRetrieve<PhoneCall_Select,PhoneCall_Expand,PhoneCall_Filter,PhoneCall_Fixed,PhoneCall_Result,PhoneCall_FormattedResult>;
  duplicaterecordid_publisher: WebMappingRetrieve<Publisher_Select,Publisher_Expand,Publisher_Filter,Publisher_Fixed,Publisher_Result,Publisher_FormattedResult>;
  duplicaterecordid_queue: WebMappingRetrieve<Queue_Select,Queue_Expand,Queue_Filter,Queue_Fixed,Queue_Result,Queue_FormattedResult>;
  duplicaterecordid_recurringappointmentmaster: WebMappingRetrieve<RecurringAppointmentMaster_Select,RecurringAppointmentMaster_Expand,RecurringAppointmentMaster_Filter,RecurringAppointmentMaster_Fixed,RecurringAppointmentMaster_Result,RecurringAppointmentMaster_FormattedResult>;
  duplicaterecordid_revokeinheritedaccessrecordstracker: WebMappingRetrieve<revokeinheritedaccessrecordstracker_Select,revokeinheritedaccessrecordstracker_Expand,revokeinheritedaccessrecordstracker_Filter,revokeinheritedaccessrecordstracker_Fixed,revokeinheritedaccessrecordstracker_Result,revokeinheritedaccessrecordstracker_FormattedResult>;
  duplicaterecordid_serviceplan: WebMappingRetrieve<ServicePlan_Select,ServicePlan_Expand,ServicePlan_Filter,ServicePlan_Fixed,ServicePlan_Result,ServicePlan_FormattedResult>;
  duplicaterecordid_serviceplanmapping: WebMappingRetrieve<ServicePlanMapping_Select,ServicePlanMapping_Expand,ServicePlanMapping_Filter,ServicePlanMapping_Fixed,ServicePlanMapping_Result,ServicePlanMapping_FormattedResult>;
  duplicaterecordid_sharepointdocumentlocation: WebMappingRetrieve<SharePointDocumentLocation_Select,SharePointDocumentLocation_Expand,SharePointDocumentLocation_Filter,SharePointDocumentLocation_Fixed,SharePointDocumentLocation_Result,SharePointDocumentLocation_FormattedResult>;
  duplicaterecordid_sharepointsite: WebMappingRetrieve<SharePointSite_Select,SharePointSite_Expand,SharePointSite_Filter,SharePointSite_Fixed,SharePointSite_Result,SharePointSite_FormattedResult>;
  duplicaterecordid_socialactivity: WebMappingRetrieve<SocialActivity_Select,SocialActivity_Expand,SocialActivity_Filter,SocialActivity_Fixed,SocialActivity_Result,SocialActivity_FormattedResult>;
  duplicaterecordid_socialprofile: WebMappingRetrieve<SocialProfile_Select,SocialProfile_Expand,SocialProfile_Filter,SocialProfile_Fixed,SocialProfile_Result,SocialProfile_FormattedResult>;
  duplicaterecordid_solutioncomponentattributeconfiguration: WebMappingRetrieve<solutioncomponentattributeconfiguration_Select,solutioncomponentattributeconfiguration_Expand,solutioncomponentattributeconfiguration_Filter,solutioncomponentattributeconfiguration_Fixed,solutioncomponentattributeconfiguration_Result,solutioncomponentattributeconfiguration_FormattedResult>;
  duplicaterecordid_solutioncomponentbatchconfiguration: WebMappingRetrieve<solutioncomponentbatchconfiguration_Select,solutioncomponentbatchconfiguration_Expand,solutioncomponentbatchconfiguration_Filter,solutioncomponentbatchconfiguration_Fixed,solutioncomponentbatchconfiguration_Result,solutioncomponentbatchconfiguration_FormattedResult>;
  duplicaterecordid_solutioncomponentconfiguration: WebMappingRetrieve<solutioncomponentconfiguration_Select,solutioncomponentconfiguration_Expand,solutioncomponentconfiguration_Filter,solutioncomponentconfiguration_Fixed,solutioncomponentconfiguration_Result,solutioncomponentconfiguration_FormattedResult>;
  duplicaterecordid_solutioncomponentrelationshipconfiguration: WebMappingRetrieve<solutioncomponentrelationshipconfiguration_Select,solutioncomponentrelationshipconfiguration_Expand,solutioncomponentrelationshipconfiguration_Filter,solutioncomponentrelationshipconfiguration_Fixed,solutioncomponentrelationshipconfiguration_Result,solutioncomponentrelationshipconfiguration_FormattedResult>;
  duplicaterecordid_stagesolutionupload: WebMappingRetrieve<StageSolutionUpload_Select,StageSolutionUpload_Expand,StageSolutionUpload_Filter,StageSolutionUpload_Fixed,StageSolutionUpload_Result,StageSolutionUpload_FormattedResult>;
  duplicaterecordid_systemuser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  duplicaterecordid_task: WebMappingRetrieve<Task_Select,Task_Expand,Task_Filter,Task_Fixed,Task_Result,Task_FormattedResult>;
  duplicaterecordid_team: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  duplicaterecordid_transactioncurrency: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
  duplicateruleid: WebMappingRetrieve<DuplicateRule_Select,DuplicateRule_Expand,DuplicateRule_Filter,DuplicateRule_Fixed,DuplicateRule_Result,DuplicateRule_FormattedResult>;
}
interface DuplicateRecord_RelatedMany {
  userentityinstancedata_duplicaterecord: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
}
interface WebEntitiesRetrieve {
  duplicaterecords: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
}
interface WebEntitiesRelated {
  duplicaterecords: WebMappingRelated<DuplicateRecord_RelatedOne,DuplicateRecord_RelatedMany>;
}
interface WebEntitiesCUDA {
  duplicaterecords: WebMappingCUDA<DuplicateRecord_Create,DuplicateRecord_Update,DuplicateRecord_Select>;
}
