interface MailboxTrackingFolder_Base extends WebEntity {
  createdon?: Date | null;
  exchangefolderid?: string | null;
  exchangefoldername?: string | null;
  folderonboardingstatus?: number | null;
  mailboxtrackingfolderid?: string | null;
  modifiedon?: Date | null;
  versionnumber?: number | null;
}
interface MailboxTrackingFolder_Relationships {
  regardingobjectid_account?: Account_Result | null;
  regardingobjectid_activityfileattachment?: activityfileattachment_Result | null;
  regardingobjectid_appaction?: appaction_Result | null;
  regardingobjectid_appelement?: AppElement_Result | null;
  regardingobjectid_applicationuser?: ApplicationUser_Result | null;
  regardingobjectid_appmodulecomponentedge?: AppModuleComponentEdge_Result | null;
  regardingobjectid_appmodulecomponentnode?: AppModuleComponentNode_Result | null;
  regardingobjectid_appsetting?: AppSetting_Result | null;
  regardingobjectid_appusersetting?: AppUserSetting_Result | null;
  regardingobjectid_asyncoperation?: AsyncOperation_Result | null;
  regardingobjectid_attributeimageconfig?: AttributeImageConfig_Result | null;
  regardingobjectid_bot?: bot_Result | null;
  regardingobjectid_botcomponent?: botcomponent_Result | null;
  regardingobjectid_canvasappextendedmetadata?: CanvasAppExtendedMetadata_Result | null;
  regardingobjectid_cascadegrantrevokeaccessrecordstracker?: cascadegrantrevokeaccessrecordstracker_Result | null;
  regardingobjectid_cascadegrantrevokeaccessversiontracker?: cascadegrantrevokeaccessversiontracker_Result | null;
  regardingobjectid_catalog?: Catalog_Result | null;
  regardingobjectid_catalogassignment?: CatalogAssignment_Result | null;
  regardingobjectid_connectionreference?: connectionreference_Result | null;
  regardingobjectid_connector?: connector_Result | null;
  regardingobjectid_contact?: Contact_Result | null;
  regardingobjectid_conversationtranscript?: conversationtranscript_Result | null;
  regardingobjectid_customapi?: CustomAPI_Result | null;
  regardingobjectid_customapirequestparameter?: CustomAPIRequestParameter_Result | null;
  regardingobjectid_customapiresponseproperty?: CustomAPIResponseProperty_Result | null;
  regardingobjectid_datalakefolder?: datalakefolder_Result | null;
  regardingobjectid_datalakefolderpermission?: datalakefolderpermission_Result | null;
  regardingobjectid_datalakeworkspace?: datalakeworkspace_Result | null;
  regardingobjectid_datalakeworkspacepermission?: datalakeworkspacepermission_Result | null;
  regardingobjectid_entityanalyticsconfig?: EntityAnalyticsConfig_Result | null;
  regardingobjectid_entityimageconfig?: EntityImageConfig_Result | null;
  regardingobjectid_entityindex?: EntityIndex_Result | null;
  regardingobjectid_environmentvariabledefinition?: EnvironmentVariableDefinition_Result | null;
  regardingobjectid_environmentvariablevalue?: EnvironmentVariableValue_Result | null;
  regardingobjectid_exportsolutionupload?: ExportSolutionUpload_Result | null;
  regardingobjectid_featurecontrolsetting?: featurecontrolsetting_Result | null;
  regardingobjectid_flowmachine?: flowmachine_Result | null;
  regardingobjectid_flowmachinegroup?: flowmachinegroup_Result | null;
  regardingobjectid_flowsession?: flowsession_Result | null;
  regardingobjectid_holidaywrapper?: holidaywrapper_Result | null;
  regardingobjectid_indexattributes?: IndexAttributes_Result | null;
  regardingobjectid_internalcatalogassignment?: InternalCatalogAssignment_Result | null;
  regardingobjectid_keyvaultreference?: KeyVaultReference_Result | null;
  regardingobjectid_managedidentity?: ManagedIdentity_Result | null;
  regardingobjectid_mbs_pluginprofile?: mbs_pluginprofile_Result | null;
  regardingobjectid_msdyn_aibdataset?: msdyn_AIBDataset_Result | null;
  regardingobjectid_msdyn_aibdatasetfile?: msdyn_AIBDatasetFile_Result | null;
  regardingobjectid_msdyn_aibdatasetrecord?: msdyn_AIBDatasetRecord_Result | null;
  regardingobjectid_msdyn_aibdatasetscontainer?: msdyn_AIBDatasetsContainer_Result | null;
  regardingobjectid_msdyn_aibfile?: msdyn_AIBFile_Result | null;
  regardingobjectid_msdyn_aibfileattacheddata?: msdyn_AIBFileAttachedData_Result | null;
  regardingobjectid_msdyn_aiconfiguration?: msdyn_AIConfiguration_Result | null;
  regardingobjectid_msdyn_aifptrainingdocument?: msdyn_AIFpTrainingDocument_Result | null;
  regardingobjectid_msdyn_aimodel?: msdyn_AIModel_Result | null;
  regardingobjectid_msdyn_aiodimage?: msdyn_AIOdImage_Result | null;
  regardingobjectid_msdyn_aiodlabel?: msdyn_AIOdLabel_Result | null;
  regardingobjectid_msdyn_aiodtrainingboundingbox?: msdyn_AIOdTrainingBoundingBox_Result | null;
  regardingobjectid_msdyn_aiodtrainingimage?: msdyn_AIOdTrainingImage_Result | null;
  regardingobjectid_msdyn_aitemplate?: msdyn_AITemplate_Result | null;
  regardingobjectid_msdyn_analysiscomponent?: msdyn_analysiscomponent_Result | null;
  regardingobjectid_msdyn_analysisjob?: msdyn_analysisjob_Result | null;
  regardingobjectid_msdyn_analysisresult?: msdyn_analysisresult_Result | null;
  regardingobjectid_msdyn_analysisresultdetail?: msdyn_analysisresultdetail_Result | null;
  regardingobjectid_msdyn_dataflow?: msdyn_dataflow_Result | null;
  regardingobjectid_msdyn_federatedarticle?: msdyn_federatedarticle_Result | null;
  regardingobjectid_msdyn_federatedarticleincident?: msdyn_federatedarticleincident_Result | null;
  regardingobjectid_msdyn_helppage?: msdyn_helppage_Result | null;
  regardingobjectid_msdyn_kalanguagesetting?: msdyn_kalanguagesetting_Result | null;
  regardingobjectid_msdyn_kmfederatedsearchconfig?: msdyn_kmfederatedsearchconfig_Result | null;
  regardingobjectid_msdyn_kmpersonalizationsetting?: msdyn_kmpersonalizationsetting_Result | null;
  regardingobjectid_msdyn_knowledgearticleimage?: msdyn_knowledgearticleimage_Result | null;
  regardingobjectid_msdyn_knowledgearticletemplate?: msdyn_knowledgearticletemplate_Result | null;
  regardingobjectid_msdyn_knowledgeinteractioninsight?: msdyn_knowledgeinteractioninsight_Result | null;
  regardingobjectid_msdyn_knowledgepersonalfilter?: msdyn_knowledgepersonalfilter_Result | null;
  regardingobjectid_msdyn_knowledgesearchfilter?: msdyn_knowledgesearchfilter_Result | null;
  regardingobjectid_msdyn_knowledgesearchinsight?: msdyn_knowledgesearchinsight_Result | null;
  regardingobjectid_msdyn_pminferredtask?: msdyn_pminferredtask_Result | null;
  regardingobjectid_msdyn_pmrecording?: msdyn_pmrecording_Result | null;
  regardingobjectid_msdyn_richtextfile?: msdyn_richtextfile_Result | null;
  regardingobjectid_msdyn_serviceconfiguration?: msdyn_serviceconfiguration_Result | null;
  regardingobjectid_msdyn_slakpi?: msdyn_slakpi_Result | null;
  regardingobjectid_msdyn_solutionhealthrule?: msdyn_solutionhealthrule_Result | null;
  regardingobjectid_msdyn_solutionhealthruleargument?: msdyn_solutionhealthruleargument_Result | null;
  regardingobjectid_msdyn_solutionhealthruleset?: msdyn_solutionhealthruleset_Result | null;
  regardingobjectid_msdyn_tour?: msdyn_tour_Result | null;
  regardingobjectid_msdynce_botcontent?: msdynce_botcontent_Result | null;
  regardingobjectid_organizationdatasyncsubscription?: organizationdatasyncsubscription_Result | null;
  regardingobjectid_organizationdatasyncsubscriptionentity?: organizationdatasyncsubscriptionentity_Result | null;
  regardingobjectid_organizationsetting?: OrganizationSetting_Result | null;
  regardingobjectid_package?: package_Result | null;
  regardingobjectid_pc_bankaccount?: pc_BankAccount_Result | null;
  regardingobjectid_pc_participation?: pc_Participation_Result | null;
  regardingobjectid_pc_participationfeeexemption?: pc_ParticipationFeeExemption_Result | null;
  regardingobjectid_pc_payment?: pc_Payment_Result | null;
  regardingobjectid_pc_scheduledjob?: pc_ScheduledJob_Result | null;
  regardingobjectid_pc_settings?: pc_Settings_Result | null;
  regardingobjectid_pc_transaction?: pc_Transaction_Result | null;
  regardingobjectid_pdfsetting?: PDFSetting_Result | null;
  regardingobjectid_pluginpackage?: pluginpackage_Result | null;
  regardingobjectid_processstageparameter?: processstageparameter_Result | null;
  regardingobjectid_provisionlanguageforuser?: ProvisionLanguageForUser_Result | null;
  regardingobjectid_relationshipattribute?: RelationshipAttribute_Result | null;
  regardingobjectid_revokeinheritedaccessrecordstracker?: revokeinheritedaccessrecordstracker_Result | null;
  regardingobjectid_serviceplan?: ServicePlan_Result | null;
  regardingobjectid_serviceplanmapping?: ServicePlanMapping_Result | null;
  regardingobjectid_settingdefinition?: SettingDefinition_Result | null;
  regardingobjectid_solutioncomponentattributeconfiguration?: solutioncomponentattributeconfiguration_Result | null;
  regardingobjectid_solutioncomponentbatchconfiguration?: solutioncomponentbatchconfiguration_Result | null;
  regardingobjectid_solutioncomponentconfiguration?: solutioncomponentconfiguration_Result | null;
  regardingobjectid_solutioncomponentrelationshipconfiguration?: solutioncomponentrelationshipconfiguration_Result | null;
  regardingobjectid_stagesolutionupload?: StageSolutionUpload_Result | null;
  regardingobjectid_systemuserauthorizationchangetracker?: SystemUserAuthorizationChangeTracker_Result | null;
  regardingobjectid_teammobileofflineprofilemembership?: teammobileofflineprofilemembership_Result | null;
  regardingobjectid_territory?: Territory_Result | null;
  regardingobjectid_usermobileofflineprofilemembership?: usermobileofflineprofilemembership_Result | null;
  regardingobjectid_virtualentitymetadata?: VirtualEntityMetadata_Result | null;
  regardingobjectid_workflowbinary?: workflowbinary_Result | null;
}
interface MailboxTrackingFolder extends MailboxTrackingFolder_Base, MailboxTrackingFolder_Relationships {
  mailboxid_bind$mailboxes?: string | null;
  ownerid_bind$systemusers?: string | null;
  ownerid_bind$teams?: string | null;
  regardingobjectid_account_bind$accounts?: string | null;
  regardingobjectid_activityfileattachment_bind$activityfileattachments?: string | null;
  regardingobjectid_appaction_bind$appactions?: string | null;
  regardingobjectid_appelement_bind$appelements?: string | null;
  regardingobjectid_applicationuser_bind$applicationusers?: string | null;
  regardingobjectid_appmodulecomponentedge_bind$appmodulecomponentedges?: string | null;
  regardingobjectid_appmodulecomponentnode_bind$appmodulecomponentnodes?: string | null;
  regardingobjectid_appsetting_bind$appsettings?: string | null;
  regardingobjectid_appusersetting_bind$appusersettings?: string | null;
  regardingobjectid_asyncoperation_bind$asyncoperations?: string | null;
  regardingobjectid_attributeimageconfig_bind$attributeimageconfigs?: string | null;
  regardingobjectid_bot_bind$bots?: string | null;
  regardingobjectid_botcomponent_bind$botcomponents?: string | null;
  regardingobjectid_canvasappextendedmetadata_bind$canvasappextendedmetadata?: string | null;
  regardingobjectid_cascadegrantrevokeaccessrecordstracker_bind$cascadegrantrevokeaccessrecordstrackers?: string | null;
  regardingobjectid_cascadegrantrevokeaccessversiontracker_bind$cascadegrantrevokeaccessversiontrackers?: string | null;
  regardingobjectid_catalog_bind$catalogs?: string | null;
  regardingobjectid_catalogassignment_bind$catalogassignments?: string | null;
  regardingobjectid_connectionreference_bind$connectionreferences?: string | null;
  regardingobjectid_connector_bind$connectors?: string | null;
  regardingobjectid_contact_bind$contacts?: string | null;
  regardingobjectid_conversationtranscript_bind$conversationtranscripts?: string | null;
  regardingobjectid_customapi_bind$customapis?: string | null;
  regardingobjectid_customapirequestparameter_bind$customapirequestparameters?: string | null;
  regardingobjectid_customapiresponseproperty_bind$customapiresponseproperties?: string | null;
  regardingobjectid_datalakefolder_bind$datalakefolders?: string | null;
  regardingobjectid_datalakefolderpermission_bind$datalakefolderpermissions?: string | null;
  regardingobjectid_datalakeworkspace_bind$datalakeworkspaces?: string | null;
  regardingobjectid_datalakeworkspacepermission_bind$datalakeworkspacepermissions?: string | null;
  regardingobjectid_entityanalyticsconfig_bind$entityanalyticsconfigs?: string | null;
  regardingobjectid_entityimageconfig_bind$entityimageconfigs?: string | null;
  regardingobjectid_entityindex_bind$entityindexes?: string | null;
  regardingobjectid_environmentvariabledefinition_bind$environmentvariabledefinitions?: string | null;
  regardingobjectid_environmentvariablevalue_bind$environmentvariablevalues?: string | null;
  regardingobjectid_exportsolutionupload_bind$exportsolutionuploads?: string | null;
  regardingobjectid_featurecontrolsetting_bind$featurecontrolsettings?: string | null;
  regardingobjectid_flowmachine_bind$flowmachines?: string | null;
  regardingobjectid_flowmachinegroup_bind$flowmachinegroups?: string | null;
  regardingobjectid_flowsession_bind$flowsessions?: string | null;
  regardingobjectid_holidaywrapper_bind$holidaywrappers?: string | null;
  regardingobjectid_indexattributes_bind$indexattributes?: string | null;
  regardingobjectid_internalcatalogassignment_bind$internalcatalogassignments?: string | null;
  regardingobjectid_keyvaultreference_bind$keyvaultreferences?: string | null;
  regardingobjectid_managedidentity_bind$managedidentities?: string | null;
  regardingobjectid_mbs_pluginprofile_bind$mbs_pluginprofiles?: string | null;
  regardingobjectid_msdyn_aibdataset_bind$msdyn_aibdatasets?: string | null;
  regardingobjectid_msdyn_aibdatasetfile_bind$msdyn_aibdatasetfiles?: string | null;
  regardingobjectid_msdyn_aibdatasetrecord_bind$msdyn_aibdatasetrecords?: string | null;
  regardingobjectid_msdyn_aibdatasetscontainer_bind$msdyn_aibdatasetscontainers?: string | null;
  regardingobjectid_msdyn_aibfile_bind$msdyn_aibfiles?: string | null;
  regardingobjectid_msdyn_aibfileattacheddata_bind$msdyn_aibfileattacheddatas?: string | null;
  regardingobjectid_msdyn_aiconfiguration_bind$msdyn_aiconfigurations?: string | null;
  regardingobjectid_msdyn_aifptrainingdocument_bind$msdyn_aifptrainingdocuments?: string | null;
  regardingobjectid_msdyn_aimodel_bind$msdyn_aimodels?: string | null;
  regardingobjectid_msdyn_aiodimage_bind$msdyn_aiodimages?: string | null;
  regardingobjectid_msdyn_aiodlabel_bind$msdyn_aiodlabels?: string | null;
  regardingobjectid_msdyn_aiodtrainingboundingbox_bind$msdyn_aiodtrainingboundingboxes?: string | null;
  regardingobjectid_msdyn_aiodtrainingimage_bind$msdyn_aiodtrainingimages?: string | null;
  regardingobjectid_msdyn_aitemplate_bind$msdyn_aitemplates?: string | null;
  regardingobjectid_msdyn_analysiscomponent_bind$msdyn_analysiscomponents?: string | null;
  regardingobjectid_msdyn_analysisjob_bind$msdyn_analysisjobs?: string | null;
  regardingobjectid_msdyn_analysisresult_bind$msdyn_analysisresults?: string | null;
  regardingobjectid_msdyn_analysisresultdetail_bind$msdyn_analysisresultdetails?: string | null;
  regardingobjectid_msdyn_dataflow_bind$msdyn_dataflows?: string | null;
  regardingobjectid_msdyn_federatedarticle_bind$msdyn_federatedarticles?: string | null;
  regardingobjectid_msdyn_federatedarticleincident_bind$msdyn_federatedarticleincidents?: string | null;
  regardingobjectid_msdyn_helppage_bind$msdyn_helppages?: string | null;
  regardingobjectid_msdyn_kalanguagesetting_bind$msdyn_kalanguagesettings?: string | null;
  regardingobjectid_msdyn_kmfederatedsearchconfig_bind$msdyn_kmfederatedsearchconfigs?: string | null;
  regardingobjectid_msdyn_kmpersonalizationsetting_bind$msdyn_kmpersonalizationsettings?: string | null;
  regardingobjectid_msdyn_knowledgearticleimage_bind$msdyn_knowledgearticleimages?: string | null;
  regardingobjectid_msdyn_knowledgearticletemplate_bind$msdyn_knowledgearticletemplates?: string | null;
  regardingobjectid_msdyn_knowledgeinteractioninsight_bind$msdyn_knowledgeinteractioninsights?: string | null;
  regardingobjectid_msdyn_knowledgepersonalfilter_bind$msdyn_knowledgepersonalfilters?: string | null;
  regardingobjectid_msdyn_knowledgesearchfilter_bind$msdyn_knowledgesearchfilters?: string | null;
  regardingobjectid_msdyn_knowledgesearchinsight_bind$msdyn_knowledgesearchinsights?: string | null;
  regardingobjectid_msdyn_pminferredtask_bind$msdyn_pminferredtasks?: string | null;
  regardingobjectid_msdyn_pmrecording_bind$msdyn_pmrecordings?: string | null;
  regardingobjectid_msdyn_richtextfile_bind$msdyn_richtextfiles?: string | null;
  regardingobjectid_msdyn_serviceconfiguration_bind$msdyn_serviceconfigurations?: string | null;
  regardingobjectid_msdyn_slakpi_bind$msdyn_slakpis?: string | null;
  regardingobjectid_msdyn_solutionhealthrule_bind$msdyn_solutionhealthrules?: string | null;
  regardingobjectid_msdyn_solutionhealthruleargument_bind$msdyn_solutionhealthrulearguments?: string | null;
  regardingobjectid_msdyn_solutionhealthruleset_bind$msdyn_solutionhealthrulesets?: string | null;
  regardingobjectid_msdyn_tour_bind$msdyn_tours?: string | null;
  regardingobjectid_msdynce_botcontent_bind$msdynce_botcontents?: string | null;
  regardingobjectid_organizationdatasyncsubscription_bind$organizationdatasyncsubscriptions?: string | null;
  regardingobjectid_organizationdatasyncsubscriptionentity_bind$organizationdatasyncsubscriptionentities?: string | null;
  regardingobjectid_organizationsetting_bind$organizationsettings?: string | null;
  regardingobjectid_package_bind$packages?: string | null;
  regardingobjectid_pc_bankaccount_bind$pc_bankaccounts?: string | null;
  regardingobjectid_pc_participation_bind$pc_participations?: string | null;
  regardingobjectid_pc_participationfeeexemption_bind$pc_participationfeeexemptions?: string | null;
  regardingobjectid_pc_payment_bind$pc_payments?: string | null;
  regardingobjectid_pc_scheduledjob_bind$pc_scheduledjobs?: string | null;
  regardingobjectid_pc_settings_bind$pc_settingses?: string | null;
  regardingobjectid_pc_transaction_bind$pc_transactions?: string | null;
  regardingobjectid_pdfsetting_bind$pdfsettings?: string | null;
  regardingobjectid_pluginpackage_bind$pluginpackages?: string | null;
  regardingobjectid_processstageparameter_bind$processstageparameters?: string | null;
  regardingobjectid_provisionlanguageforuser_bind$provisionlanguageforusers?: string | null;
  regardingobjectid_relationshipattribute_bind$relationshipattributes?: string | null;
  regardingobjectid_revokeinheritedaccessrecordstracker_bind$revokeinheritedaccessrecordstrackers?: string | null;
  regardingobjectid_serviceplan_bind$serviceplans?: string | null;
  regardingobjectid_serviceplanmapping_bind$serviceplanmappings?: string | null;
  regardingobjectid_settingdefinition_bind$settingdefinitions?: string | null;
  regardingobjectid_solutioncomponentattributeconfiguration_bind$solutioncomponentattributeconfigurations?: string | null;
  regardingobjectid_solutioncomponentbatchconfiguration_bind$solutioncomponentbatchconfigurations?: string | null;
  regardingobjectid_solutioncomponentconfiguration_bind$solutioncomponentconfigurations?: string | null;
  regardingobjectid_solutioncomponentrelationshipconfiguration_bind$solutioncomponentrelationshipconfigurations?: string | null;
  regardingobjectid_stagesolutionupload_bind$stagesolutionuploads?: string | null;
  regardingobjectid_systemuserauthorizationchangetracker_bind$systemuserauthorizationchangetrackers?: string | null;
  regardingobjectid_teammobileofflineprofilemembership_bind$teammobileofflineprofilememberships?: string | null;
  regardingobjectid_territory_bind$territories?: string | null;
  regardingobjectid_usermobileofflineprofilemembership_bind$usermobileofflineprofilememberships?: string | null;
  regardingobjectid_virtualentitymetadata_bind$virtualentitymetadatas?: string | null;
  regardingobjectid_workflowbinary_bind$workflowbinaries?: string | null;
}
interface MailboxTrackingFolder_Create extends MailboxTrackingFolder {
}
interface MailboxTrackingFolder_Update extends MailboxTrackingFolder {
}
interface MailboxTrackingFolder_Select {
  createdby_guid: WebAttribute<MailboxTrackingFolder_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<MailboxTrackingFolder_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<MailboxTrackingFolder_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  exchangefolderid: WebAttribute<MailboxTrackingFolder_Select, { exchangefolderid: string | null }, {  }>;
  exchangefoldername: WebAttribute<MailboxTrackingFolder_Select, { exchangefoldername: string | null }, {  }>;
  folderonboardingstatus: WebAttribute<MailboxTrackingFolder_Select, { folderonboardingstatus: number | null }, {  }>;
  mailboxid_guid: WebAttribute<MailboxTrackingFolder_Select, { mailboxid_guid: string | null }, { mailboxid_formatted?: string }>;
  mailboxtrackingfolderid: WebAttribute<MailboxTrackingFolder_Select, { mailboxtrackingfolderid: string | null }, {  }>;
  modifiedby_guid: WebAttribute<MailboxTrackingFolder_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<MailboxTrackingFolder_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<MailboxTrackingFolder_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  organizationid_guid: WebAttribute<MailboxTrackingFolder_Select, { organizationid_guid: string | null }, { organizationid_formatted?: string }>;
  ownerid_guid: WebAttribute<MailboxTrackingFolder_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<MailboxTrackingFolder_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<MailboxTrackingFolder_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<MailboxTrackingFolder_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  regardingobjectid_guid: WebAttribute<MailboxTrackingFolder_Select, { regardingobjectid_guid: string | null }, { regardingobjectid_formatted?: string }>;
  versionnumber: WebAttribute<MailboxTrackingFolder_Select, { versionnumber: number | null }, {  }>;
}
interface MailboxTrackingFolder_Filter {
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  exchangefolderid: string;
  exchangefoldername: string;
  folderonboardingstatus: number;
  mailboxid_guid: XQW.Guid;
  mailboxtrackingfolderid: XQW.Guid;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  organizationid_guid: XQW.Guid;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  regardingobjectid_guid: XQW.Guid;
  versionnumber: number;
}
interface MailboxTrackingFolder_Expand {
  createdby: WebExpand<MailboxTrackingFolder_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<MailboxTrackingFolder_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  mailboxid: WebExpand<MailboxTrackingFolder_Expand, Mailbox_Select, Mailbox_Filter, { mailboxid: Mailbox_Result }>;
  modifiedby: WebExpand<MailboxTrackingFolder_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<MailboxTrackingFolder_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  organizationid: WebExpand<MailboxTrackingFolder_Expand, Organization_Select, Organization_Filter, { organizationid: Organization_Result }>;
  ownerid: WebExpand<MailboxTrackingFolder_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid: SystemUser_Result } & { ownerid: Team_Result }>;
  owningbusinessunit: WebExpand<MailboxTrackingFolder_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit: BusinessUnit_Result }>;
  owningteam: WebExpand<MailboxTrackingFolder_Expand, Team_Select, Team_Filter, { owningteam: Team_Result }>;
  regardingobjectid_account: WebExpand<MailboxTrackingFolder_Expand, Account_Select, Account_Filter, { regardingobjectid_account: Account_Result }>;
  regardingobjectid_activityfileattachment: WebExpand<MailboxTrackingFolder_Expand, activityfileattachment_Select, activityfileattachment_Filter, { regardingobjectid_activityfileattachment: activityfileattachment_Result }>;
  regardingobjectid_appaction: WebExpand<MailboxTrackingFolder_Expand, appaction_Select, appaction_Filter, { regardingobjectid_appaction: appaction_Result }>;
  regardingobjectid_appelement: WebExpand<MailboxTrackingFolder_Expand, AppElement_Select, AppElement_Filter, { regardingobjectid_appelement: AppElement_Result }>;
  regardingobjectid_applicationuser: WebExpand<MailboxTrackingFolder_Expand, ApplicationUser_Select, ApplicationUser_Filter, { regardingobjectid_applicationuser: ApplicationUser_Result }>;
  regardingobjectid_appmodulecomponentedge: WebExpand<MailboxTrackingFolder_Expand, AppModuleComponentEdge_Select, AppModuleComponentEdge_Filter, { regardingobjectid_appmodulecomponentedge: AppModuleComponentEdge_Result }>;
  regardingobjectid_appmodulecomponentnode: WebExpand<MailboxTrackingFolder_Expand, AppModuleComponentNode_Select, AppModuleComponentNode_Filter, { regardingobjectid_appmodulecomponentnode: AppModuleComponentNode_Result }>;
  regardingobjectid_appsetting: WebExpand<MailboxTrackingFolder_Expand, AppSetting_Select, AppSetting_Filter, { regardingobjectid_appsetting: AppSetting_Result }>;
  regardingobjectid_appusersetting: WebExpand<MailboxTrackingFolder_Expand, AppUserSetting_Select, AppUserSetting_Filter, { regardingobjectid_appusersetting: AppUserSetting_Result }>;
  regardingobjectid_asyncoperation: WebExpand<MailboxTrackingFolder_Expand, AsyncOperation_Select, AsyncOperation_Filter, { regardingobjectid_asyncoperation: AsyncOperation_Result }>;
  regardingobjectid_attributeimageconfig: WebExpand<MailboxTrackingFolder_Expand, AttributeImageConfig_Select, AttributeImageConfig_Filter, { regardingobjectid_attributeimageconfig: AttributeImageConfig_Result }>;
  regardingobjectid_bot: WebExpand<MailboxTrackingFolder_Expand, bot_Select, bot_Filter, { regardingobjectid_bot: bot_Result }>;
  regardingobjectid_botcomponent: WebExpand<MailboxTrackingFolder_Expand, botcomponent_Select, botcomponent_Filter, { regardingobjectid_botcomponent: botcomponent_Result }>;
  regardingobjectid_canvasappextendedmetadata: WebExpand<MailboxTrackingFolder_Expand, CanvasAppExtendedMetadata_Select, CanvasAppExtendedMetadata_Filter, { regardingobjectid_canvasappextendedmetadata: CanvasAppExtendedMetadata_Result }>;
  regardingobjectid_cascadegrantrevokeaccessrecordstracker: WebExpand<MailboxTrackingFolder_Expand, cascadegrantrevokeaccessrecordstracker_Select, cascadegrantrevokeaccessrecordstracker_Filter, { regardingobjectid_cascadegrantrevokeaccessrecordstracker: cascadegrantrevokeaccessrecordstracker_Result }>;
  regardingobjectid_cascadegrantrevokeaccessversiontracker: WebExpand<MailboxTrackingFolder_Expand, cascadegrantrevokeaccessversiontracker_Select, cascadegrantrevokeaccessversiontracker_Filter, { regardingobjectid_cascadegrantrevokeaccessversiontracker: cascadegrantrevokeaccessversiontracker_Result }>;
  regardingobjectid_catalog: WebExpand<MailboxTrackingFolder_Expand, Catalog_Select, Catalog_Filter, { regardingobjectid_catalog: Catalog_Result }>;
  regardingobjectid_catalogassignment: WebExpand<MailboxTrackingFolder_Expand, CatalogAssignment_Select, CatalogAssignment_Filter, { regardingobjectid_catalogassignment: CatalogAssignment_Result }>;
  regardingobjectid_connectionreference: WebExpand<MailboxTrackingFolder_Expand, connectionreference_Select, connectionreference_Filter, { regardingobjectid_connectionreference: connectionreference_Result }>;
  regardingobjectid_connector: WebExpand<MailboxTrackingFolder_Expand, connector_Select, connector_Filter, { regardingobjectid_connector: connector_Result }>;
  regardingobjectid_contact: WebExpand<MailboxTrackingFolder_Expand, Contact_Select, Contact_Filter, { regardingobjectid_contact: Contact_Result }>;
  regardingobjectid_conversationtranscript: WebExpand<MailboxTrackingFolder_Expand, conversationtranscript_Select, conversationtranscript_Filter, { regardingobjectid_conversationtranscript: conversationtranscript_Result }>;
  regardingobjectid_customapi: WebExpand<MailboxTrackingFolder_Expand, CustomAPI_Select, CustomAPI_Filter, { regardingobjectid_customapi: CustomAPI_Result }>;
  regardingobjectid_customapirequestparameter: WebExpand<MailboxTrackingFolder_Expand, CustomAPIRequestParameter_Select, CustomAPIRequestParameter_Filter, { regardingobjectid_customapirequestparameter: CustomAPIRequestParameter_Result }>;
  regardingobjectid_customapiresponseproperty: WebExpand<MailboxTrackingFolder_Expand, CustomAPIResponseProperty_Select, CustomAPIResponseProperty_Filter, { regardingobjectid_customapiresponseproperty: CustomAPIResponseProperty_Result }>;
  regardingobjectid_datalakefolder: WebExpand<MailboxTrackingFolder_Expand, datalakefolder_Select, datalakefolder_Filter, { regardingobjectid_datalakefolder: datalakefolder_Result }>;
  regardingobjectid_datalakefolderpermission: WebExpand<MailboxTrackingFolder_Expand, datalakefolderpermission_Select, datalakefolderpermission_Filter, { regardingobjectid_datalakefolderpermission: datalakefolderpermission_Result }>;
  regardingobjectid_datalakeworkspace: WebExpand<MailboxTrackingFolder_Expand, datalakeworkspace_Select, datalakeworkspace_Filter, { regardingobjectid_datalakeworkspace: datalakeworkspace_Result }>;
  regardingobjectid_datalakeworkspacepermission: WebExpand<MailboxTrackingFolder_Expand, datalakeworkspacepermission_Select, datalakeworkspacepermission_Filter, { regardingobjectid_datalakeworkspacepermission: datalakeworkspacepermission_Result }>;
  regardingobjectid_entityanalyticsconfig: WebExpand<MailboxTrackingFolder_Expand, EntityAnalyticsConfig_Select, EntityAnalyticsConfig_Filter, { regardingobjectid_entityanalyticsconfig: EntityAnalyticsConfig_Result }>;
  regardingobjectid_entityimageconfig: WebExpand<MailboxTrackingFolder_Expand, EntityImageConfig_Select, EntityImageConfig_Filter, { regardingobjectid_entityimageconfig: EntityImageConfig_Result }>;
  regardingobjectid_entityindex: WebExpand<MailboxTrackingFolder_Expand, EntityIndex_Select, EntityIndex_Filter, { regardingobjectid_entityindex: EntityIndex_Result }>;
  regardingobjectid_environmentvariabledefinition: WebExpand<MailboxTrackingFolder_Expand, EnvironmentVariableDefinition_Select, EnvironmentVariableDefinition_Filter, { regardingobjectid_environmentvariabledefinition: EnvironmentVariableDefinition_Result }>;
  regardingobjectid_environmentvariablevalue: WebExpand<MailboxTrackingFolder_Expand, EnvironmentVariableValue_Select, EnvironmentVariableValue_Filter, { regardingobjectid_environmentvariablevalue: EnvironmentVariableValue_Result }>;
  regardingobjectid_exportsolutionupload: WebExpand<MailboxTrackingFolder_Expand, ExportSolutionUpload_Select, ExportSolutionUpload_Filter, { regardingobjectid_exportsolutionupload: ExportSolutionUpload_Result }>;
  regardingobjectid_featurecontrolsetting: WebExpand<MailboxTrackingFolder_Expand, featurecontrolsetting_Select, featurecontrolsetting_Filter, { regardingobjectid_featurecontrolsetting: featurecontrolsetting_Result }>;
  regardingobjectid_flowmachine: WebExpand<MailboxTrackingFolder_Expand, flowmachine_Select, flowmachine_Filter, { regardingobjectid_flowmachine: flowmachine_Result }>;
  regardingobjectid_flowmachinegroup: WebExpand<MailboxTrackingFolder_Expand, flowmachinegroup_Select, flowmachinegroup_Filter, { regardingobjectid_flowmachinegroup: flowmachinegroup_Result }>;
  regardingobjectid_flowsession: WebExpand<MailboxTrackingFolder_Expand, flowsession_Select, flowsession_Filter, { regardingobjectid_flowsession: flowsession_Result }>;
  regardingobjectid_holidaywrapper: WebExpand<MailboxTrackingFolder_Expand, holidaywrapper_Select, holidaywrapper_Filter, { regardingobjectid_holidaywrapper: holidaywrapper_Result }>;
  regardingobjectid_indexattributes: WebExpand<MailboxTrackingFolder_Expand, IndexAttributes_Select, IndexAttributes_Filter, { regardingobjectid_indexattributes: IndexAttributes_Result }>;
  regardingobjectid_internalcatalogassignment: WebExpand<MailboxTrackingFolder_Expand, InternalCatalogAssignment_Select, InternalCatalogAssignment_Filter, { regardingobjectid_internalcatalogassignment: InternalCatalogAssignment_Result }>;
  regardingobjectid_keyvaultreference: WebExpand<MailboxTrackingFolder_Expand, KeyVaultReference_Select, KeyVaultReference_Filter, { regardingobjectid_keyvaultreference: KeyVaultReference_Result }>;
  regardingobjectid_managedidentity: WebExpand<MailboxTrackingFolder_Expand, ManagedIdentity_Select, ManagedIdentity_Filter, { regardingobjectid_managedidentity: ManagedIdentity_Result }>;
  regardingobjectid_mbs_pluginprofile: WebExpand<MailboxTrackingFolder_Expand, mbs_pluginprofile_Select, mbs_pluginprofile_Filter, { regardingobjectid_mbs_pluginprofile: mbs_pluginprofile_Result }>;
  regardingobjectid_msdyn_aibdataset: WebExpand<MailboxTrackingFolder_Expand, msdyn_AIBDataset_Select, msdyn_AIBDataset_Filter, { regardingobjectid_msdyn_aibdataset: msdyn_AIBDataset_Result }>;
  regardingobjectid_msdyn_aibdatasetfile: WebExpand<MailboxTrackingFolder_Expand, msdyn_AIBDatasetFile_Select, msdyn_AIBDatasetFile_Filter, { regardingobjectid_msdyn_aibdatasetfile: msdyn_AIBDatasetFile_Result }>;
  regardingobjectid_msdyn_aibdatasetrecord: WebExpand<MailboxTrackingFolder_Expand, msdyn_AIBDatasetRecord_Select, msdyn_AIBDatasetRecord_Filter, { regardingobjectid_msdyn_aibdatasetrecord: msdyn_AIBDatasetRecord_Result }>;
  regardingobjectid_msdyn_aibdatasetscontainer: WebExpand<MailboxTrackingFolder_Expand, msdyn_AIBDatasetsContainer_Select, msdyn_AIBDatasetsContainer_Filter, { regardingobjectid_msdyn_aibdatasetscontainer: msdyn_AIBDatasetsContainer_Result }>;
  regardingobjectid_msdyn_aibfile: WebExpand<MailboxTrackingFolder_Expand, msdyn_AIBFile_Select, msdyn_AIBFile_Filter, { regardingobjectid_msdyn_aibfile: msdyn_AIBFile_Result }>;
  regardingobjectid_msdyn_aibfileattacheddata: WebExpand<MailboxTrackingFolder_Expand, msdyn_AIBFileAttachedData_Select, msdyn_AIBFileAttachedData_Filter, { regardingobjectid_msdyn_aibfileattacheddata: msdyn_AIBFileAttachedData_Result }>;
  regardingobjectid_msdyn_aiconfiguration: WebExpand<MailboxTrackingFolder_Expand, msdyn_AIConfiguration_Select, msdyn_AIConfiguration_Filter, { regardingobjectid_msdyn_aiconfiguration: msdyn_AIConfiguration_Result }>;
  regardingobjectid_msdyn_aifptrainingdocument: WebExpand<MailboxTrackingFolder_Expand, msdyn_AIFpTrainingDocument_Select, msdyn_AIFpTrainingDocument_Filter, { regardingobjectid_msdyn_aifptrainingdocument: msdyn_AIFpTrainingDocument_Result }>;
  regardingobjectid_msdyn_aimodel: WebExpand<MailboxTrackingFolder_Expand, msdyn_AIModel_Select, msdyn_AIModel_Filter, { regardingobjectid_msdyn_aimodel: msdyn_AIModel_Result }>;
  regardingobjectid_msdyn_aiodimage: WebExpand<MailboxTrackingFolder_Expand, msdyn_AIOdImage_Select, msdyn_AIOdImage_Filter, { regardingobjectid_msdyn_aiodimage: msdyn_AIOdImage_Result }>;
  regardingobjectid_msdyn_aiodlabel: WebExpand<MailboxTrackingFolder_Expand, msdyn_AIOdLabel_Select, msdyn_AIOdLabel_Filter, { regardingobjectid_msdyn_aiodlabel: msdyn_AIOdLabel_Result }>;
  regardingobjectid_msdyn_aiodtrainingboundingbox: WebExpand<MailboxTrackingFolder_Expand, msdyn_AIOdTrainingBoundingBox_Select, msdyn_AIOdTrainingBoundingBox_Filter, { regardingobjectid_msdyn_aiodtrainingboundingbox: msdyn_AIOdTrainingBoundingBox_Result }>;
  regardingobjectid_msdyn_aiodtrainingimage: WebExpand<MailboxTrackingFolder_Expand, msdyn_AIOdTrainingImage_Select, msdyn_AIOdTrainingImage_Filter, { regardingobjectid_msdyn_aiodtrainingimage: msdyn_AIOdTrainingImage_Result }>;
  regardingobjectid_msdyn_aitemplate: WebExpand<MailboxTrackingFolder_Expand, msdyn_AITemplate_Select, msdyn_AITemplate_Filter, { regardingobjectid_msdyn_aitemplate: msdyn_AITemplate_Result }>;
  regardingobjectid_msdyn_analysiscomponent: WebExpand<MailboxTrackingFolder_Expand, msdyn_analysiscomponent_Select, msdyn_analysiscomponent_Filter, { regardingobjectid_msdyn_analysiscomponent: msdyn_analysiscomponent_Result }>;
  regardingobjectid_msdyn_analysisjob: WebExpand<MailboxTrackingFolder_Expand, msdyn_analysisjob_Select, msdyn_analysisjob_Filter, { regardingobjectid_msdyn_analysisjob: msdyn_analysisjob_Result }>;
  regardingobjectid_msdyn_analysisresult: WebExpand<MailboxTrackingFolder_Expand, msdyn_analysisresult_Select, msdyn_analysisresult_Filter, { regardingobjectid_msdyn_analysisresult: msdyn_analysisresult_Result }>;
  regardingobjectid_msdyn_analysisresultdetail: WebExpand<MailboxTrackingFolder_Expand, msdyn_analysisresultdetail_Select, msdyn_analysisresultdetail_Filter, { regardingobjectid_msdyn_analysisresultdetail: msdyn_analysisresultdetail_Result }>;
  regardingobjectid_msdyn_dataflow: WebExpand<MailboxTrackingFolder_Expand, msdyn_dataflow_Select, msdyn_dataflow_Filter, { regardingobjectid_msdyn_dataflow: msdyn_dataflow_Result }>;
  regardingobjectid_msdyn_federatedarticle: WebExpand<MailboxTrackingFolder_Expand, msdyn_federatedarticle_Select, msdyn_federatedarticle_Filter, { regardingobjectid_msdyn_federatedarticle: msdyn_federatedarticle_Result }>;
  regardingobjectid_msdyn_federatedarticleincident: WebExpand<MailboxTrackingFolder_Expand, msdyn_federatedarticleincident_Select, msdyn_federatedarticleincident_Filter, { regardingobjectid_msdyn_federatedarticleincident: msdyn_federatedarticleincident_Result }>;
  regardingobjectid_msdyn_helppage: WebExpand<MailboxTrackingFolder_Expand, msdyn_helppage_Select, msdyn_helppage_Filter, { regardingobjectid_msdyn_helppage: msdyn_helppage_Result }>;
  regardingobjectid_msdyn_kalanguagesetting: WebExpand<MailboxTrackingFolder_Expand, msdyn_kalanguagesetting_Select, msdyn_kalanguagesetting_Filter, { regardingobjectid_msdyn_kalanguagesetting: msdyn_kalanguagesetting_Result }>;
  regardingobjectid_msdyn_kmfederatedsearchconfig: WebExpand<MailboxTrackingFolder_Expand, msdyn_kmfederatedsearchconfig_Select, msdyn_kmfederatedsearchconfig_Filter, { regardingobjectid_msdyn_kmfederatedsearchconfig: msdyn_kmfederatedsearchconfig_Result }>;
  regardingobjectid_msdyn_kmpersonalizationsetting: WebExpand<MailboxTrackingFolder_Expand, msdyn_kmpersonalizationsetting_Select, msdyn_kmpersonalizationsetting_Filter, { regardingobjectid_msdyn_kmpersonalizationsetting: msdyn_kmpersonalizationsetting_Result }>;
  regardingobjectid_msdyn_knowledgearticleimage: WebExpand<MailboxTrackingFolder_Expand, msdyn_knowledgearticleimage_Select, msdyn_knowledgearticleimage_Filter, { regardingobjectid_msdyn_knowledgearticleimage: msdyn_knowledgearticleimage_Result }>;
  regardingobjectid_msdyn_knowledgearticletemplate: WebExpand<MailboxTrackingFolder_Expand, msdyn_knowledgearticletemplate_Select, msdyn_knowledgearticletemplate_Filter, { regardingobjectid_msdyn_knowledgearticletemplate: msdyn_knowledgearticletemplate_Result }>;
  regardingobjectid_msdyn_knowledgeinteractioninsight: WebExpand<MailboxTrackingFolder_Expand, msdyn_knowledgeinteractioninsight_Select, msdyn_knowledgeinteractioninsight_Filter, { regardingobjectid_msdyn_knowledgeinteractioninsight: msdyn_knowledgeinteractioninsight_Result }>;
  regardingobjectid_msdyn_knowledgepersonalfilter: WebExpand<MailboxTrackingFolder_Expand, msdyn_knowledgepersonalfilter_Select, msdyn_knowledgepersonalfilter_Filter, { regardingobjectid_msdyn_knowledgepersonalfilter: msdyn_knowledgepersonalfilter_Result }>;
  regardingobjectid_msdyn_knowledgesearchfilter: WebExpand<MailboxTrackingFolder_Expand, msdyn_knowledgesearchfilter_Select, msdyn_knowledgesearchfilter_Filter, { regardingobjectid_msdyn_knowledgesearchfilter: msdyn_knowledgesearchfilter_Result }>;
  regardingobjectid_msdyn_knowledgesearchinsight: WebExpand<MailboxTrackingFolder_Expand, msdyn_knowledgesearchinsight_Select, msdyn_knowledgesearchinsight_Filter, { regardingobjectid_msdyn_knowledgesearchinsight: msdyn_knowledgesearchinsight_Result }>;
  regardingobjectid_msdyn_pminferredtask: WebExpand<MailboxTrackingFolder_Expand, msdyn_pminferredtask_Select, msdyn_pminferredtask_Filter, { regardingobjectid_msdyn_pminferredtask: msdyn_pminferredtask_Result }>;
  regardingobjectid_msdyn_pmrecording: WebExpand<MailboxTrackingFolder_Expand, msdyn_pmrecording_Select, msdyn_pmrecording_Filter, { regardingobjectid_msdyn_pmrecording: msdyn_pmrecording_Result }>;
  regardingobjectid_msdyn_richtextfile: WebExpand<MailboxTrackingFolder_Expand, msdyn_richtextfile_Select, msdyn_richtextfile_Filter, { regardingobjectid_msdyn_richtextfile: msdyn_richtextfile_Result }>;
  regardingobjectid_msdyn_serviceconfiguration: WebExpand<MailboxTrackingFolder_Expand, msdyn_serviceconfiguration_Select, msdyn_serviceconfiguration_Filter, { regardingobjectid_msdyn_serviceconfiguration: msdyn_serviceconfiguration_Result }>;
  regardingobjectid_msdyn_slakpi: WebExpand<MailboxTrackingFolder_Expand, msdyn_slakpi_Select, msdyn_slakpi_Filter, { regardingobjectid_msdyn_slakpi: msdyn_slakpi_Result }>;
  regardingobjectid_msdyn_solutionhealthrule: WebExpand<MailboxTrackingFolder_Expand, msdyn_solutionhealthrule_Select, msdyn_solutionhealthrule_Filter, { regardingobjectid_msdyn_solutionhealthrule: msdyn_solutionhealthrule_Result }>;
  regardingobjectid_msdyn_solutionhealthruleargument: WebExpand<MailboxTrackingFolder_Expand, msdyn_solutionhealthruleargument_Select, msdyn_solutionhealthruleargument_Filter, { regardingobjectid_msdyn_solutionhealthruleargument: msdyn_solutionhealthruleargument_Result }>;
  regardingobjectid_msdyn_solutionhealthruleset: WebExpand<MailboxTrackingFolder_Expand, msdyn_solutionhealthruleset_Select, msdyn_solutionhealthruleset_Filter, { regardingobjectid_msdyn_solutionhealthruleset: msdyn_solutionhealthruleset_Result }>;
  regardingobjectid_msdyn_tour: WebExpand<MailboxTrackingFolder_Expand, msdyn_tour_Select, msdyn_tour_Filter, { regardingobjectid_msdyn_tour: msdyn_tour_Result }>;
  regardingobjectid_msdynce_botcontent: WebExpand<MailboxTrackingFolder_Expand, msdynce_botcontent_Select, msdynce_botcontent_Filter, { regardingobjectid_msdynce_botcontent: msdynce_botcontent_Result }>;
  regardingobjectid_organizationdatasyncsubscription: WebExpand<MailboxTrackingFolder_Expand, organizationdatasyncsubscription_Select, organizationdatasyncsubscription_Filter, { regardingobjectid_organizationdatasyncsubscription: organizationdatasyncsubscription_Result }>;
  regardingobjectid_organizationdatasyncsubscriptionentity: WebExpand<MailboxTrackingFolder_Expand, organizationdatasyncsubscriptionentity_Select, organizationdatasyncsubscriptionentity_Filter, { regardingobjectid_organizationdatasyncsubscriptionentity: organizationdatasyncsubscriptionentity_Result }>;
  regardingobjectid_organizationsetting: WebExpand<MailboxTrackingFolder_Expand, OrganizationSetting_Select, OrganizationSetting_Filter, { regardingobjectid_organizationsetting: OrganizationSetting_Result }>;
  regardingobjectid_package: WebExpand<MailboxTrackingFolder_Expand, package_Select, package_Filter, { regardingobjectid_package: package_Result }>;
  regardingobjectid_pc_bankaccount: WebExpand<MailboxTrackingFolder_Expand, pc_BankAccount_Select, pc_BankAccount_Filter, { regardingobjectid_pc_bankaccount: pc_BankAccount_Result }>;
  regardingobjectid_pc_participation: WebExpand<MailboxTrackingFolder_Expand, pc_Participation_Select, pc_Participation_Filter, { regardingobjectid_pc_participation: pc_Participation_Result }>;
  regardingobjectid_pc_participationfeeexemption: WebExpand<MailboxTrackingFolder_Expand, pc_ParticipationFeeExemption_Select, pc_ParticipationFeeExemption_Filter, { regardingobjectid_pc_participationfeeexemption: pc_ParticipationFeeExemption_Result }>;
  regardingobjectid_pc_payment: WebExpand<MailboxTrackingFolder_Expand, pc_Payment_Select, pc_Payment_Filter, { regardingobjectid_pc_payment: pc_Payment_Result }>;
  regardingobjectid_pc_scheduledjob: WebExpand<MailboxTrackingFolder_Expand, pc_ScheduledJob_Select, pc_ScheduledJob_Filter, { regardingobjectid_pc_scheduledjob: pc_ScheduledJob_Result }>;
  regardingobjectid_pc_settings: WebExpand<MailboxTrackingFolder_Expand, pc_Settings_Select, pc_Settings_Filter, { regardingobjectid_pc_settings: pc_Settings_Result }>;
  regardingobjectid_pc_transaction: WebExpand<MailboxTrackingFolder_Expand, pc_Transaction_Select, pc_Transaction_Filter, { regardingobjectid_pc_transaction: pc_Transaction_Result }>;
  regardingobjectid_pdfsetting: WebExpand<MailboxTrackingFolder_Expand, PDFSetting_Select, PDFSetting_Filter, { regardingobjectid_pdfsetting: PDFSetting_Result }>;
  regardingobjectid_pluginpackage: WebExpand<MailboxTrackingFolder_Expand, pluginpackage_Select, pluginpackage_Filter, { regardingobjectid_pluginpackage: pluginpackage_Result }>;
  regardingobjectid_processstageparameter: WebExpand<MailboxTrackingFolder_Expand, processstageparameter_Select, processstageparameter_Filter, { regardingobjectid_processstageparameter: processstageparameter_Result }>;
  regardingobjectid_provisionlanguageforuser: WebExpand<MailboxTrackingFolder_Expand, ProvisionLanguageForUser_Select, ProvisionLanguageForUser_Filter, { regardingobjectid_provisionlanguageforuser: ProvisionLanguageForUser_Result }>;
  regardingobjectid_relationshipattribute: WebExpand<MailboxTrackingFolder_Expand, RelationshipAttribute_Select, RelationshipAttribute_Filter, { regardingobjectid_relationshipattribute: RelationshipAttribute_Result }>;
  regardingobjectid_revokeinheritedaccessrecordstracker: WebExpand<MailboxTrackingFolder_Expand, revokeinheritedaccessrecordstracker_Select, revokeinheritedaccessrecordstracker_Filter, { regardingobjectid_revokeinheritedaccessrecordstracker: revokeinheritedaccessrecordstracker_Result }>;
  regardingobjectid_serviceplan: WebExpand<MailboxTrackingFolder_Expand, ServicePlan_Select, ServicePlan_Filter, { regardingobjectid_serviceplan: ServicePlan_Result }>;
  regardingobjectid_serviceplanmapping: WebExpand<MailboxTrackingFolder_Expand, ServicePlanMapping_Select, ServicePlanMapping_Filter, { regardingobjectid_serviceplanmapping: ServicePlanMapping_Result }>;
  regardingobjectid_settingdefinition: WebExpand<MailboxTrackingFolder_Expand, SettingDefinition_Select, SettingDefinition_Filter, { regardingobjectid_settingdefinition: SettingDefinition_Result }>;
  regardingobjectid_solutioncomponentattributeconfiguration: WebExpand<MailboxTrackingFolder_Expand, solutioncomponentattributeconfiguration_Select, solutioncomponentattributeconfiguration_Filter, { regardingobjectid_solutioncomponentattributeconfiguration: solutioncomponentattributeconfiguration_Result }>;
  regardingobjectid_solutioncomponentbatchconfiguration: WebExpand<MailboxTrackingFolder_Expand, solutioncomponentbatchconfiguration_Select, solutioncomponentbatchconfiguration_Filter, { regardingobjectid_solutioncomponentbatchconfiguration: solutioncomponentbatchconfiguration_Result }>;
  regardingobjectid_solutioncomponentconfiguration: WebExpand<MailboxTrackingFolder_Expand, solutioncomponentconfiguration_Select, solutioncomponentconfiguration_Filter, { regardingobjectid_solutioncomponentconfiguration: solutioncomponentconfiguration_Result }>;
  regardingobjectid_solutioncomponentrelationshipconfiguration: WebExpand<MailboxTrackingFolder_Expand, solutioncomponentrelationshipconfiguration_Select, solutioncomponentrelationshipconfiguration_Filter, { regardingobjectid_solutioncomponentrelationshipconfiguration: solutioncomponentrelationshipconfiguration_Result }>;
  regardingobjectid_stagesolutionupload: WebExpand<MailboxTrackingFolder_Expand, StageSolutionUpload_Select, StageSolutionUpload_Filter, { regardingobjectid_stagesolutionupload: StageSolutionUpload_Result }>;
  regardingobjectid_systemuserauthorizationchangetracker: WebExpand<MailboxTrackingFolder_Expand, SystemUserAuthorizationChangeTracker_Select, SystemUserAuthorizationChangeTracker_Filter, { regardingobjectid_systemuserauthorizationchangetracker: SystemUserAuthorizationChangeTracker_Result }>;
  regardingobjectid_teammobileofflineprofilemembership: WebExpand<MailboxTrackingFolder_Expand, teammobileofflineprofilemembership_Select, teammobileofflineprofilemembership_Filter, { regardingobjectid_teammobileofflineprofilemembership: teammobileofflineprofilemembership_Result }>;
  regardingobjectid_territory: WebExpand<MailboxTrackingFolder_Expand, Territory_Select, Territory_Filter, { regardingobjectid_territory: Territory_Result }>;
  regardingobjectid_usermobileofflineprofilemembership: WebExpand<MailboxTrackingFolder_Expand, usermobileofflineprofilemembership_Select, usermobileofflineprofilemembership_Filter, { regardingobjectid_usermobileofflineprofilemembership: usermobileofflineprofilemembership_Result }>;
  regardingobjectid_virtualentitymetadata: WebExpand<MailboxTrackingFolder_Expand, VirtualEntityMetadata_Select, VirtualEntityMetadata_Filter, { regardingobjectid_virtualentitymetadata: VirtualEntityMetadata_Result }>;
  regardingobjectid_workflowbinary: WebExpand<MailboxTrackingFolder_Expand, workflowbinary_Select, workflowbinary_Filter, { regardingobjectid_workflowbinary: workflowbinary_Result }>;
}
interface MailboxTrackingFolder_FormattedResult {
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  mailboxid_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  organizationid_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  regardingobjectid_formatted?: string;
}
interface MailboxTrackingFolder_Result extends MailboxTrackingFolder_Base, MailboxTrackingFolder_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  mailboxid_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  organizationid_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  regardingobjectid_guid: string | null;
}
interface MailboxTrackingFolder_RelatedOne {
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  mailboxid: WebMappingRetrieve<Mailbox_Select,Mailbox_Expand,Mailbox_Filter,Mailbox_Fixed,Mailbox_Result,Mailbox_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  organizationid: WebMappingRetrieve<Organization_Select,Organization_Expand,Organization_Filter,Organization_Fixed,Organization_Result,Organization_FormattedResult>;
  ownerid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult> & WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owningbusinessunit: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  regardingobjectid_account: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  regardingobjectid_activityfileattachment: WebMappingRetrieve<activityfileattachment_Select,activityfileattachment_Expand,activityfileattachment_Filter,activityfileattachment_Fixed,activityfileattachment_Result,activityfileattachment_FormattedResult>;
  regardingobjectid_appaction: WebMappingRetrieve<appaction_Select,appaction_Expand,appaction_Filter,appaction_Fixed,appaction_Result,appaction_FormattedResult>;
  regardingobjectid_appelement: WebMappingRetrieve<AppElement_Select,AppElement_Expand,AppElement_Filter,AppElement_Fixed,AppElement_Result,AppElement_FormattedResult>;
  regardingobjectid_applicationuser: WebMappingRetrieve<ApplicationUser_Select,ApplicationUser_Expand,ApplicationUser_Filter,ApplicationUser_Fixed,ApplicationUser_Result,ApplicationUser_FormattedResult>;
  regardingobjectid_appmodulecomponentedge: WebMappingRetrieve<AppModuleComponentEdge_Select,AppModuleComponentEdge_Expand,AppModuleComponentEdge_Filter,AppModuleComponentEdge_Fixed,AppModuleComponentEdge_Result,AppModuleComponentEdge_FormattedResult>;
  regardingobjectid_appmodulecomponentnode: WebMappingRetrieve<AppModuleComponentNode_Select,AppModuleComponentNode_Expand,AppModuleComponentNode_Filter,AppModuleComponentNode_Fixed,AppModuleComponentNode_Result,AppModuleComponentNode_FormattedResult>;
  regardingobjectid_appsetting: WebMappingRetrieve<AppSetting_Select,AppSetting_Expand,AppSetting_Filter,AppSetting_Fixed,AppSetting_Result,AppSetting_FormattedResult>;
  regardingobjectid_appusersetting: WebMappingRetrieve<AppUserSetting_Select,AppUserSetting_Expand,AppUserSetting_Filter,AppUserSetting_Fixed,AppUserSetting_Result,AppUserSetting_FormattedResult>;
  regardingobjectid_asyncoperation: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  regardingobjectid_attributeimageconfig: WebMappingRetrieve<AttributeImageConfig_Select,AttributeImageConfig_Expand,AttributeImageConfig_Filter,AttributeImageConfig_Fixed,AttributeImageConfig_Result,AttributeImageConfig_FormattedResult>;
  regardingobjectid_bot: WebMappingRetrieve<bot_Select,bot_Expand,bot_Filter,bot_Fixed,bot_Result,bot_FormattedResult>;
  regardingobjectid_botcomponent: WebMappingRetrieve<botcomponent_Select,botcomponent_Expand,botcomponent_Filter,botcomponent_Fixed,botcomponent_Result,botcomponent_FormattedResult>;
  regardingobjectid_canvasappextendedmetadata: WebMappingRetrieve<CanvasAppExtendedMetadata_Select,CanvasAppExtendedMetadata_Expand,CanvasAppExtendedMetadata_Filter,CanvasAppExtendedMetadata_Fixed,CanvasAppExtendedMetadata_Result,CanvasAppExtendedMetadata_FormattedResult>;
  regardingobjectid_cascadegrantrevokeaccessrecordstracker: WebMappingRetrieve<cascadegrantrevokeaccessrecordstracker_Select,cascadegrantrevokeaccessrecordstracker_Expand,cascadegrantrevokeaccessrecordstracker_Filter,cascadegrantrevokeaccessrecordstracker_Fixed,cascadegrantrevokeaccessrecordstracker_Result,cascadegrantrevokeaccessrecordstracker_FormattedResult>;
  regardingobjectid_cascadegrantrevokeaccessversiontracker: WebMappingRetrieve<cascadegrantrevokeaccessversiontracker_Select,cascadegrantrevokeaccessversiontracker_Expand,cascadegrantrevokeaccessversiontracker_Filter,cascadegrantrevokeaccessversiontracker_Fixed,cascadegrantrevokeaccessversiontracker_Result,cascadegrantrevokeaccessversiontracker_FormattedResult>;
  regardingobjectid_catalog: WebMappingRetrieve<Catalog_Select,Catalog_Expand,Catalog_Filter,Catalog_Fixed,Catalog_Result,Catalog_FormattedResult>;
  regardingobjectid_catalogassignment: WebMappingRetrieve<CatalogAssignment_Select,CatalogAssignment_Expand,CatalogAssignment_Filter,CatalogAssignment_Fixed,CatalogAssignment_Result,CatalogAssignment_FormattedResult>;
  regardingobjectid_connectionreference: WebMappingRetrieve<connectionreference_Select,connectionreference_Expand,connectionreference_Filter,connectionreference_Fixed,connectionreference_Result,connectionreference_FormattedResult>;
  regardingobjectid_connector: WebMappingRetrieve<connector_Select,connector_Expand,connector_Filter,connector_Fixed,connector_Result,connector_FormattedResult>;
  regardingobjectid_contact: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  regardingobjectid_conversationtranscript: WebMappingRetrieve<conversationtranscript_Select,conversationtranscript_Expand,conversationtranscript_Filter,conversationtranscript_Fixed,conversationtranscript_Result,conversationtranscript_FormattedResult>;
  regardingobjectid_customapi: WebMappingRetrieve<CustomAPI_Select,CustomAPI_Expand,CustomAPI_Filter,CustomAPI_Fixed,CustomAPI_Result,CustomAPI_FormattedResult>;
  regardingobjectid_customapirequestparameter: WebMappingRetrieve<CustomAPIRequestParameter_Select,CustomAPIRequestParameter_Expand,CustomAPIRequestParameter_Filter,CustomAPIRequestParameter_Fixed,CustomAPIRequestParameter_Result,CustomAPIRequestParameter_FormattedResult>;
  regardingobjectid_customapiresponseproperty: WebMappingRetrieve<CustomAPIResponseProperty_Select,CustomAPIResponseProperty_Expand,CustomAPIResponseProperty_Filter,CustomAPIResponseProperty_Fixed,CustomAPIResponseProperty_Result,CustomAPIResponseProperty_FormattedResult>;
  regardingobjectid_datalakefolder: WebMappingRetrieve<datalakefolder_Select,datalakefolder_Expand,datalakefolder_Filter,datalakefolder_Fixed,datalakefolder_Result,datalakefolder_FormattedResult>;
  regardingobjectid_datalakefolderpermission: WebMappingRetrieve<datalakefolderpermission_Select,datalakefolderpermission_Expand,datalakefolderpermission_Filter,datalakefolderpermission_Fixed,datalakefolderpermission_Result,datalakefolderpermission_FormattedResult>;
  regardingobjectid_datalakeworkspace: WebMappingRetrieve<datalakeworkspace_Select,datalakeworkspace_Expand,datalakeworkspace_Filter,datalakeworkspace_Fixed,datalakeworkspace_Result,datalakeworkspace_FormattedResult>;
  regardingobjectid_datalakeworkspacepermission: WebMappingRetrieve<datalakeworkspacepermission_Select,datalakeworkspacepermission_Expand,datalakeworkspacepermission_Filter,datalakeworkspacepermission_Fixed,datalakeworkspacepermission_Result,datalakeworkspacepermission_FormattedResult>;
  regardingobjectid_entityanalyticsconfig: WebMappingRetrieve<EntityAnalyticsConfig_Select,EntityAnalyticsConfig_Expand,EntityAnalyticsConfig_Filter,EntityAnalyticsConfig_Fixed,EntityAnalyticsConfig_Result,EntityAnalyticsConfig_FormattedResult>;
  regardingobjectid_entityimageconfig: WebMappingRetrieve<EntityImageConfig_Select,EntityImageConfig_Expand,EntityImageConfig_Filter,EntityImageConfig_Fixed,EntityImageConfig_Result,EntityImageConfig_FormattedResult>;
  regardingobjectid_entityindex: WebMappingRetrieve<EntityIndex_Select,EntityIndex_Expand,EntityIndex_Filter,EntityIndex_Fixed,EntityIndex_Result,EntityIndex_FormattedResult>;
  regardingobjectid_environmentvariabledefinition: WebMappingRetrieve<EnvironmentVariableDefinition_Select,EnvironmentVariableDefinition_Expand,EnvironmentVariableDefinition_Filter,EnvironmentVariableDefinition_Fixed,EnvironmentVariableDefinition_Result,EnvironmentVariableDefinition_FormattedResult>;
  regardingobjectid_environmentvariablevalue: WebMappingRetrieve<EnvironmentVariableValue_Select,EnvironmentVariableValue_Expand,EnvironmentVariableValue_Filter,EnvironmentVariableValue_Fixed,EnvironmentVariableValue_Result,EnvironmentVariableValue_FormattedResult>;
  regardingobjectid_exportsolutionupload: WebMappingRetrieve<ExportSolutionUpload_Select,ExportSolutionUpload_Expand,ExportSolutionUpload_Filter,ExportSolutionUpload_Fixed,ExportSolutionUpload_Result,ExportSolutionUpload_FormattedResult>;
  regardingobjectid_featurecontrolsetting: WebMappingRetrieve<featurecontrolsetting_Select,featurecontrolsetting_Expand,featurecontrolsetting_Filter,featurecontrolsetting_Fixed,featurecontrolsetting_Result,featurecontrolsetting_FormattedResult>;
  regardingobjectid_flowmachine: WebMappingRetrieve<flowmachine_Select,flowmachine_Expand,flowmachine_Filter,flowmachine_Fixed,flowmachine_Result,flowmachine_FormattedResult>;
  regardingobjectid_flowmachinegroup: WebMappingRetrieve<flowmachinegroup_Select,flowmachinegroup_Expand,flowmachinegroup_Filter,flowmachinegroup_Fixed,flowmachinegroup_Result,flowmachinegroup_FormattedResult>;
  regardingobjectid_flowsession: WebMappingRetrieve<flowsession_Select,flowsession_Expand,flowsession_Filter,flowsession_Fixed,flowsession_Result,flowsession_FormattedResult>;
  regardingobjectid_holidaywrapper: WebMappingRetrieve<holidaywrapper_Select,holidaywrapper_Expand,holidaywrapper_Filter,holidaywrapper_Fixed,holidaywrapper_Result,holidaywrapper_FormattedResult>;
  regardingobjectid_indexattributes: WebMappingRetrieve<IndexAttributes_Select,IndexAttributes_Expand,IndexAttributes_Filter,IndexAttributes_Fixed,IndexAttributes_Result,IndexAttributes_FormattedResult>;
  regardingobjectid_internalcatalogassignment: WebMappingRetrieve<InternalCatalogAssignment_Select,InternalCatalogAssignment_Expand,InternalCatalogAssignment_Filter,InternalCatalogAssignment_Fixed,InternalCatalogAssignment_Result,InternalCatalogAssignment_FormattedResult>;
  regardingobjectid_keyvaultreference: WebMappingRetrieve<KeyVaultReference_Select,KeyVaultReference_Expand,KeyVaultReference_Filter,KeyVaultReference_Fixed,KeyVaultReference_Result,KeyVaultReference_FormattedResult>;
  regardingobjectid_managedidentity: WebMappingRetrieve<ManagedIdentity_Select,ManagedIdentity_Expand,ManagedIdentity_Filter,ManagedIdentity_Fixed,ManagedIdentity_Result,ManagedIdentity_FormattedResult>;
  regardingobjectid_mbs_pluginprofile: WebMappingRetrieve<mbs_pluginprofile_Select,mbs_pluginprofile_Expand,mbs_pluginprofile_Filter,mbs_pluginprofile_Fixed,mbs_pluginprofile_Result,mbs_pluginprofile_FormattedResult>;
  regardingobjectid_msdyn_aibdataset: WebMappingRetrieve<msdyn_AIBDataset_Select,msdyn_AIBDataset_Expand,msdyn_AIBDataset_Filter,msdyn_AIBDataset_Fixed,msdyn_AIBDataset_Result,msdyn_AIBDataset_FormattedResult>;
  regardingobjectid_msdyn_aibdatasetfile: WebMappingRetrieve<msdyn_AIBDatasetFile_Select,msdyn_AIBDatasetFile_Expand,msdyn_AIBDatasetFile_Filter,msdyn_AIBDatasetFile_Fixed,msdyn_AIBDatasetFile_Result,msdyn_AIBDatasetFile_FormattedResult>;
  regardingobjectid_msdyn_aibdatasetrecord: WebMappingRetrieve<msdyn_AIBDatasetRecord_Select,msdyn_AIBDatasetRecord_Expand,msdyn_AIBDatasetRecord_Filter,msdyn_AIBDatasetRecord_Fixed,msdyn_AIBDatasetRecord_Result,msdyn_AIBDatasetRecord_FormattedResult>;
  regardingobjectid_msdyn_aibdatasetscontainer: WebMappingRetrieve<msdyn_AIBDatasetsContainer_Select,msdyn_AIBDatasetsContainer_Expand,msdyn_AIBDatasetsContainer_Filter,msdyn_AIBDatasetsContainer_Fixed,msdyn_AIBDatasetsContainer_Result,msdyn_AIBDatasetsContainer_FormattedResult>;
  regardingobjectid_msdyn_aibfile: WebMappingRetrieve<msdyn_AIBFile_Select,msdyn_AIBFile_Expand,msdyn_AIBFile_Filter,msdyn_AIBFile_Fixed,msdyn_AIBFile_Result,msdyn_AIBFile_FormattedResult>;
  regardingobjectid_msdyn_aibfileattacheddata: WebMappingRetrieve<msdyn_AIBFileAttachedData_Select,msdyn_AIBFileAttachedData_Expand,msdyn_AIBFileAttachedData_Filter,msdyn_AIBFileAttachedData_Fixed,msdyn_AIBFileAttachedData_Result,msdyn_AIBFileAttachedData_FormattedResult>;
  regardingobjectid_msdyn_aiconfiguration: WebMappingRetrieve<msdyn_AIConfiguration_Select,msdyn_AIConfiguration_Expand,msdyn_AIConfiguration_Filter,msdyn_AIConfiguration_Fixed,msdyn_AIConfiguration_Result,msdyn_AIConfiguration_FormattedResult>;
  regardingobjectid_msdyn_aifptrainingdocument: WebMappingRetrieve<msdyn_AIFpTrainingDocument_Select,msdyn_AIFpTrainingDocument_Expand,msdyn_AIFpTrainingDocument_Filter,msdyn_AIFpTrainingDocument_Fixed,msdyn_AIFpTrainingDocument_Result,msdyn_AIFpTrainingDocument_FormattedResult>;
  regardingobjectid_msdyn_aimodel: WebMappingRetrieve<msdyn_AIModel_Select,msdyn_AIModel_Expand,msdyn_AIModel_Filter,msdyn_AIModel_Fixed,msdyn_AIModel_Result,msdyn_AIModel_FormattedResult>;
  regardingobjectid_msdyn_aiodimage: WebMappingRetrieve<msdyn_AIOdImage_Select,msdyn_AIOdImage_Expand,msdyn_AIOdImage_Filter,msdyn_AIOdImage_Fixed,msdyn_AIOdImage_Result,msdyn_AIOdImage_FormattedResult>;
  regardingobjectid_msdyn_aiodlabel: WebMappingRetrieve<msdyn_AIOdLabel_Select,msdyn_AIOdLabel_Expand,msdyn_AIOdLabel_Filter,msdyn_AIOdLabel_Fixed,msdyn_AIOdLabel_Result,msdyn_AIOdLabel_FormattedResult>;
  regardingobjectid_msdyn_aiodtrainingboundingbox: WebMappingRetrieve<msdyn_AIOdTrainingBoundingBox_Select,msdyn_AIOdTrainingBoundingBox_Expand,msdyn_AIOdTrainingBoundingBox_Filter,msdyn_AIOdTrainingBoundingBox_Fixed,msdyn_AIOdTrainingBoundingBox_Result,msdyn_AIOdTrainingBoundingBox_FormattedResult>;
  regardingobjectid_msdyn_aiodtrainingimage: WebMappingRetrieve<msdyn_AIOdTrainingImage_Select,msdyn_AIOdTrainingImage_Expand,msdyn_AIOdTrainingImage_Filter,msdyn_AIOdTrainingImage_Fixed,msdyn_AIOdTrainingImage_Result,msdyn_AIOdTrainingImage_FormattedResult>;
  regardingobjectid_msdyn_aitemplate: WebMappingRetrieve<msdyn_AITemplate_Select,msdyn_AITemplate_Expand,msdyn_AITemplate_Filter,msdyn_AITemplate_Fixed,msdyn_AITemplate_Result,msdyn_AITemplate_FormattedResult>;
  regardingobjectid_msdyn_analysiscomponent: WebMappingRetrieve<msdyn_analysiscomponent_Select,msdyn_analysiscomponent_Expand,msdyn_analysiscomponent_Filter,msdyn_analysiscomponent_Fixed,msdyn_analysiscomponent_Result,msdyn_analysiscomponent_FormattedResult>;
  regardingobjectid_msdyn_analysisjob: WebMappingRetrieve<msdyn_analysisjob_Select,msdyn_analysisjob_Expand,msdyn_analysisjob_Filter,msdyn_analysisjob_Fixed,msdyn_analysisjob_Result,msdyn_analysisjob_FormattedResult>;
  regardingobjectid_msdyn_analysisresult: WebMappingRetrieve<msdyn_analysisresult_Select,msdyn_analysisresult_Expand,msdyn_analysisresult_Filter,msdyn_analysisresult_Fixed,msdyn_analysisresult_Result,msdyn_analysisresult_FormattedResult>;
  regardingobjectid_msdyn_analysisresultdetail: WebMappingRetrieve<msdyn_analysisresultdetail_Select,msdyn_analysisresultdetail_Expand,msdyn_analysisresultdetail_Filter,msdyn_analysisresultdetail_Fixed,msdyn_analysisresultdetail_Result,msdyn_analysisresultdetail_FormattedResult>;
  regardingobjectid_msdyn_dataflow: WebMappingRetrieve<msdyn_dataflow_Select,msdyn_dataflow_Expand,msdyn_dataflow_Filter,msdyn_dataflow_Fixed,msdyn_dataflow_Result,msdyn_dataflow_FormattedResult>;
  regardingobjectid_msdyn_federatedarticle: WebMappingRetrieve<msdyn_federatedarticle_Select,msdyn_federatedarticle_Expand,msdyn_federatedarticle_Filter,msdyn_federatedarticle_Fixed,msdyn_federatedarticle_Result,msdyn_federatedarticle_FormattedResult>;
  regardingobjectid_msdyn_federatedarticleincident: WebMappingRetrieve<msdyn_federatedarticleincident_Select,msdyn_federatedarticleincident_Expand,msdyn_federatedarticleincident_Filter,msdyn_federatedarticleincident_Fixed,msdyn_federatedarticleincident_Result,msdyn_federatedarticleincident_FormattedResult>;
  regardingobjectid_msdyn_helppage: WebMappingRetrieve<msdyn_helppage_Select,msdyn_helppage_Expand,msdyn_helppage_Filter,msdyn_helppage_Fixed,msdyn_helppage_Result,msdyn_helppage_FormattedResult>;
  regardingobjectid_msdyn_kalanguagesetting: WebMappingRetrieve<msdyn_kalanguagesetting_Select,msdyn_kalanguagesetting_Expand,msdyn_kalanguagesetting_Filter,msdyn_kalanguagesetting_Fixed,msdyn_kalanguagesetting_Result,msdyn_kalanguagesetting_FormattedResult>;
  regardingobjectid_msdyn_kmfederatedsearchconfig: WebMappingRetrieve<msdyn_kmfederatedsearchconfig_Select,msdyn_kmfederatedsearchconfig_Expand,msdyn_kmfederatedsearchconfig_Filter,msdyn_kmfederatedsearchconfig_Fixed,msdyn_kmfederatedsearchconfig_Result,msdyn_kmfederatedsearchconfig_FormattedResult>;
  regardingobjectid_msdyn_kmpersonalizationsetting: WebMappingRetrieve<msdyn_kmpersonalizationsetting_Select,msdyn_kmpersonalizationsetting_Expand,msdyn_kmpersonalizationsetting_Filter,msdyn_kmpersonalizationsetting_Fixed,msdyn_kmpersonalizationsetting_Result,msdyn_kmpersonalizationsetting_FormattedResult>;
  regardingobjectid_msdyn_knowledgearticleimage: WebMappingRetrieve<msdyn_knowledgearticleimage_Select,msdyn_knowledgearticleimage_Expand,msdyn_knowledgearticleimage_Filter,msdyn_knowledgearticleimage_Fixed,msdyn_knowledgearticleimage_Result,msdyn_knowledgearticleimage_FormattedResult>;
  regardingobjectid_msdyn_knowledgearticletemplate: WebMappingRetrieve<msdyn_knowledgearticletemplate_Select,msdyn_knowledgearticletemplate_Expand,msdyn_knowledgearticletemplate_Filter,msdyn_knowledgearticletemplate_Fixed,msdyn_knowledgearticletemplate_Result,msdyn_knowledgearticletemplate_FormattedResult>;
  regardingobjectid_msdyn_knowledgeinteractioninsight: WebMappingRetrieve<msdyn_knowledgeinteractioninsight_Select,msdyn_knowledgeinteractioninsight_Expand,msdyn_knowledgeinteractioninsight_Filter,msdyn_knowledgeinteractioninsight_Fixed,msdyn_knowledgeinteractioninsight_Result,msdyn_knowledgeinteractioninsight_FormattedResult>;
  regardingobjectid_msdyn_knowledgepersonalfilter: WebMappingRetrieve<msdyn_knowledgepersonalfilter_Select,msdyn_knowledgepersonalfilter_Expand,msdyn_knowledgepersonalfilter_Filter,msdyn_knowledgepersonalfilter_Fixed,msdyn_knowledgepersonalfilter_Result,msdyn_knowledgepersonalfilter_FormattedResult>;
  regardingobjectid_msdyn_knowledgesearchfilter: WebMappingRetrieve<msdyn_knowledgesearchfilter_Select,msdyn_knowledgesearchfilter_Expand,msdyn_knowledgesearchfilter_Filter,msdyn_knowledgesearchfilter_Fixed,msdyn_knowledgesearchfilter_Result,msdyn_knowledgesearchfilter_FormattedResult>;
  regardingobjectid_msdyn_knowledgesearchinsight: WebMappingRetrieve<msdyn_knowledgesearchinsight_Select,msdyn_knowledgesearchinsight_Expand,msdyn_knowledgesearchinsight_Filter,msdyn_knowledgesearchinsight_Fixed,msdyn_knowledgesearchinsight_Result,msdyn_knowledgesearchinsight_FormattedResult>;
  regardingobjectid_msdyn_pminferredtask: WebMappingRetrieve<msdyn_pminferredtask_Select,msdyn_pminferredtask_Expand,msdyn_pminferredtask_Filter,msdyn_pminferredtask_Fixed,msdyn_pminferredtask_Result,msdyn_pminferredtask_FormattedResult>;
  regardingobjectid_msdyn_pmrecording: WebMappingRetrieve<msdyn_pmrecording_Select,msdyn_pmrecording_Expand,msdyn_pmrecording_Filter,msdyn_pmrecording_Fixed,msdyn_pmrecording_Result,msdyn_pmrecording_FormattedResult>;
  regardingobjectid_msdyn_richtextfile: WebMappingRetrieve<msdyn_richtextfile_Select,msdyn_richtextfile_Expand,msdyn_richtextfile_Filter,msdyn_richtextfile_Fixed,msdyn_richtextfile_Result,msdyn_richtextfile_FormattedResult>;
  regardingobjectid_msdyn_serviceconfiguration: WebMappingRetrieve<msdyn_serviceconfiguration_Select,msdyn_serviceconfiguration_Expand,msdyn_serviceconfiguration_Filter,msdyn_serviceconfiguration_Fixed,msdyn_serviceconfiguration_Result,msdyn_serviceconfiguration_FormattedResult>;
  regardingobjectid_msdyn_slakpi: WebMappingRetrieve<msdyn_slakpi_Select,msdyn_slakpi_Expand,msdyn_slakpi_Filter,msdyn_slakpi_Fixed,msdyn_slakpi_Result,msdyn_slakpi_FormattedResult>;
  regardingobjectid_msdyn_solutionhealthrule: WebMappingRetrieve<msdyn_solutionhealthrule_Select,msdyn_solutionhealthrule_Expand,msdyn_solutionhealthrule_Filter,msdyn_solutionhealthrule_Fixed,msdyn_solutionhealthrule_Result,msdyn_solutionhealthrule_FormattedResult>;
  regardingobjectid_msdyn_solutionhealthruleargument: WebMappingRetrieve<msdyn_solutionhealthruleargument_Select,msdyn_solutionhealthruleargument_Expand,msdyn_solutionhealthruleargument_Filter,msdyn_solutionhealthruleargument_Fixed,msdyn_solutionhealthruleargument_Result,msdyn_solutionhealthruleargument_FormattedResult>;
  regardingobjectid_msdyn_solutionhealthruleset: WebMappingRetrieve<msdyn_solutionhealthruleset_Select,msdyn_solutionhealthruleset_Expand,msdyn_solutionhealthruleset_Filter,msdyn_solutionhealthruleset_Fixed,msdyn_solutionhealthruleset_Result,msdyn_solutionhealthruleset_FormattedResult>;
  regardingobjectid_msdyn_tour: WebMappingRetrieve<msdyn_tour_Select,msdyn_tour_Expand,msdyn_tour_Filter,msdyn_tour_Fixed,msdyn_tour_Result,msdyn_tour_FormattedResult>;
  regardingobjectid_msdynce_botcontent: WebMappingRetrieve<msdynce_botcontent_Select,msdynce_botcontent_Expand,msdynce_botcontent_Filter,msdynce_botcontent_Fixed,msdynce_botcontent_Result,msdynce_botcontent_FormattedResult>;
  regardingobjectid_organizationdatasyncsubscription: WebMappingRetrieve<organizationdatasyncsubscription_Select,organizationdatasyncsubscription_Expand,organizationdatasyncsubscription_Filter,organizationdatasyncsubscription_Fixed,organizationdatasyncsubscription_Result,organizationdatasyncsubscription_FormattedResult>;
  regardingobjectid_organizationdatasyncsubscriptionentity: WebMappingRetrieve<organizationdatasyncsubscriptionentity_Select,organizationdatasyncsubscriptionentity_Expand,organizationdatasyncsubscriptionentity_Filter,organizationdatasyncsubscriptionentity_Fixed,organizationdatasyncsubscriptionentity_Result,organizationdatasyncsubscriptionentity_FormattedResult>;
  regardingobjectid_organizationsetting: WebMappingRetrieve<OrganizationSetting_Select,OrganizationSetting_Expand,OrganizationSetting_Filter,OrganizationSetting_Fixed,OrganizationSetting_Result,OrganizationSetting_FormattedResult>;
  regardingobjectid_package: WebMappingRetrieve<package_Select,package_Expand,package_Filter,package_Fixed,package_Result,package_FormattedResult>;
  regardingobjectid_pc_bankaccount: WebMappingRetrieve<pc_BankAccount_Select,pc_BankAccount_Expand,pc_BankAccount_Filter,pc_BankAccount_Fixed,pc_BankAccount_Result,pc_BankAccount_FormattedResult>;
  regardingobjectid_pc_participation: WebMappingRetrieve<pc_Participation_Select,pc_Participation_Expand,pc_Participation_Filter,pc_Participation_Fixed,pc_Participation_Result,pc_Participation_FormattedResult>;
  regardingobjectid_pc_participationfeeexemption: WebMappingRetrieve<pc_ParticipationFeeExemption_Select,pc_ParticipationFeeExemption_Expand,pc_ParticipationFeeExemption_Filter,pc_ParticipationFeeExemption_Fixed,pc_ParticipationFeeExemption_Result,pc_ParticipationFeeExemption_FormattedResult>;
  regardingobjectid_pc_payment: WebMappingRetrieve<pc_Payment_Select,pc_Payment_Expand,pc_Payment_Filter,pc_Payment_Fixed,pc_Payment_Result,pc_Payment_FormattedResult>;
  regardingobjectid_pc_scheduledjob: WebMappingRetrieve<pc_ScheduledJob_Select,pc_ScheduledJob_Expand,pc_ScheduledJob_Filter,pc_ScheduledJob_Fixed,pc_ScheduledJob_Result,pc_ScheduledJob_FormattedResult>;
  regardingobjectid_pc_settings: WebMappingRetrieve<pc_Settings_Select,pc_Settings_Expand,pc_Settings_Filter,pc_Settings_Fixed,pc_Settings_Result,pc_Settings_FormattedResult>;
  regardingobjectid_pc_transaction: WebMappingRetrieve<pc_Transaction_Select,pc_Transaction_Expand,pc_Transaction_Filter,pc_Transaction_Fixed,pc_Transaction_Result,pc_Transaction_FormattedResult>;
  regardingobjectid_pdfsetting: WebMappingRetrieve<PDFSetting_Select,PDFSetting_Expand,PDFSetting_Filter,PDFSetting_Fixed,PDFSetting_Result,PDFSetting_FormattedResult>;
  regardingobjectid_pluginpackage: WebMappingRetrieve<pluginpackage_Select,pluginpackage_Expand,pluginpackage_Filter,pluginpackage_Fixed,pluginpackage_Result,pluginpackage_FormattedResult>;
  regardingobjectid_processstageparameter: WebMappingRetrieve<processstageparameter_Select,processstageparameter_Expand,processstageparameter_Filter,processstageparameter_Fixed,processstageparameter_Result,processstageparameter_FormattedResult>;
  regardingobjectid_provisionlanguageforuser: WebMappingRetrieve<ProvisionLanguageForUser_Select,ProvisionLanguageForUser_Expand,ProvisionLanguageForUser_Filter,ProvisionLanguageForUser_Fixed,ProvisionLanguageForUser_Result,ProvisionLanguageForUser_FormattedResult>;
  regardingobjectid_relationshipattribute: WebMappingRetrieve<RelationshipAttribute_Select,RelationshipAttribute_Expand,RelationshipAttribute_Filter,RelationshipAttribute_Fixed,RelationshipAttribute_Result,RelationshipAttribute_FormattedResult>;
  regardingobjectid_revokeinheritedaccessrecordstracker: WebMappingRetrieve<revokeinheritedaccessrecordstracker_Select,revokeinheritedaccessrecordstracker_Expand,revokeinheritedaccessrecordstracker_Filter,revokeinheritedaccessrecordstracker_Fixed,revokeinheritedaccessrecordstracker_Result,revokeinheritedaccessrecordstracker_FormattedResult>;
  regardingobjectid_serviceplan: WebMappingRetrieve<ServicePlan_Select,ServicePlan_Expand,ServicePlan_Filter,ServicePlan_Fixed,ServicePlan_Result,ServicePlan_FormattedResult>;
  regardingobjectid_serviceplanmapping: WebMappingRetrieve<ServicePlanMapping_Select,ServicePlanMapping_Expand,ServicePlanMapping_Filter,ServicePlanMapping_Fixed,ServicePlanMapping_Result,ServicePlanMapping_FormattedResult>;
  regardingobjectid_settingdefinition: WebMappingRetrieve<SettingDefinition_Select,SettingDefinition_Expand,SettingDefinition_Filter,SettingDefinition_Fixed,SettingDefinition_Result,SettingDefinition_FormattedResult>;
  regardingobjectid_solutioncomponentattributeconfiguration: WebMappingRetrieve<solutioncomponentattributeconfiguration_Select,solutioncomponentattributeconfiguration_Expand,solutioncomponentattributeconfiguration_Filter,solutioncomponentattributeconfiguration_Fixed,solutioncomponentattributeconfiguration_Result,solutioncomponentattributeconfiguration_FormattedResult>;
  regardingobjectid_solutioncomponentbatchconfiguration: WebMappingRetrieve<solutioncomponentbatchconfiguration_Select,solutioncomponentbatchconfiguration_Expand,solutioncomponentbatchconfiguration_Filter,solutioncomponentbatchconfiguration_Fixed,solutioncomponentbatchconfiguration_Result,solutioncomponentbatchconfiguration_FormattedResult>;
  regardingobjectid_solutioncomponentconfiguration: WebMappingRetrieve<solutioncomponentconfiguration_Select,solutioncomponentconfiguration_Expand,solutioncomponentconfiguration_Filter,solutioncomponentconfiguration_Fixed,solutioncomponentconfiguration_Result,solutioncomponentconfiguration_FormattedResult>;
  regardingobjectid_solutioncomponentrelationshipconfiguration: WebMappingRetrieve<solutioncomponentrelationshipconfiguration_Select,solutioncomponentrelationshipconfiguration_Expand,solutioncomponentrelationshipconfiguration_Filter,solutioncomponentrelationshipconfiguration_Fixed,solutioncomponentrelationshipconfiguration_Result,solutioncomponentrelationshipconfiguration_FormattedResult>;
  regardingobjectid_stagesolutionupload: WebMappingRetrieve<StageSolutionUpload_Select,StageSolutionUpload_Expand,StageSolutionUpload_Filter,StageSolutionUpload_Fixed,StageSolutionUpload_Result,StageSolutionUpload_FormattedResult>;
  regardingobjectid_systemuserauthorizationchangetracker: WebMappingRetrieve<SystemUserAuthorizationChangeTracker_Select,SystemUserAuthorizationChangeTracker_Expand,SystemUserAuthorizationChangeTracker_Filter,SystemUserAuthorizationChangeTracker_Fixed,SystemUserAuthorizationChangeTracker_Result,SystemUserAuthorizationChangeTracker_FormattedResult>;
  regardingobjectid_teammobileofflineprofilemembership: WebMappingRetrieve<teammobileofflineprofilemembership_Select,teammobileofflineprofilemembership_Expand,teammobileofflineprofilemembership_Filter,teammobileofflineprofilemembership_Fixed,teammobileofflineprofilemembership_Result,teammobileofflineprofilemembership_FormattedResult>;
  regardingobjectid_territory: WebMappingRetrieve<Territory_Select,Territory_Expand,Territory_Filter,Territory_Fixed,Territory_Result,Territory_FormattedResult>;
  regardingobjectid_usermobileofflineprofilemembership: WebMappingRetrieve<usermobileofflineprofilemembership_Select,usermobileofflineprofilemembership_Expand,usermobileofflineprofilemembership_Filter,usermobileofflineprofilemembership_Fixed,usermobileofflineprofilemembership_Result,usermobileofflineprofilemembership_FormattedResult>;
  regardingobjectid_virtualentitymetadata: WebMappingRetrieve<VirtualEntityMetadata_Select,VirtualEntityMetadata_Expand,VirtualEntityMetadata_Filter,VirtualEntityMetadata_Fixed,VirtualEntityMetadata_Result,VirtualEntityMetadata_FormattedResult>;
  regardingobjectid_workflowbinary: WebMappingRetrieve<workflowbinary_Select,workflowbinary_Expand,workflowbinary_Filter,workflowbinary_Fixed,workflowbinary_Result,workflowbinary_FormattedResult>;
}
interface MailboxTrackingFolder_RelatedMany {
}
interface WebEntitiesRetrieve {
  mailboxtrackingfolders: WebMappingRetrieve<MailboxTrackingFolder_Select,MailboxTrackingFolder_Expand,MailboxTrackingFolder_Filter,MailboxTrackingFolder_Fixed,MailboxTrackingFolder_Result,MailboxTrackingFolder_FormattedResult>;
}
interface WebEntitiesRelated {
  mailboxtrackingfolders: WebMappingRelated<MailboxTrackingFolder_RelatedOne,MailboxTrackingFolder_RelatedMany>;
}
interface WebEntitiesCUDA {
  mailboxtrackingfolders: WebMappingCUDA<MailboxTrackingFolder_Create,MailboxTrackingFolder_Update,MailboxTrackingFolder_Select>;
}
