interface PrincipalObjectAttributeAccess_Base extends WebEntity {
  attributeid?: string | null;
  principalobjectattributeaccessid?: string | null;
  readaccess?: boolean | null;
  updateaccess?: boolean | null;
  versionnumber?: number | null;
}
interface PrincipalObjectAttributeAccess_Relationships {
  channelaccessprofile_principalobjectattributeaccess?: ChannelAccessProfile_Result | null;
  objectid_account?: Account_Result | null;
  objectid_activityfileattachment?: activityfileattachment_Result | null;
  objectid_appaction?: appaction_Result | null;
  objectid_appelement?: AppElement_Result | null;
  objectid_applicationuser?: ApplicationUser_Result | null;
  objectid_appmodulecomponentedge?: AppModuleComponentEdge_Result | null;
  objectid_appmodulecomponentnode?: AppModuleComponentNode_Result | null;
  objectid_appointment?: Appointment_Result | null;
  objectid_appsetting?: AppSetting_Result | null;
  objectid_appusersetting?: AppUserSetting_Result | null;
  objectid_attributeimageconfig?: AttributeImageConfig_Result | null;
  objectid_bot?: bot_Result | null;
  objectid_botcomponent?: botcomponent_Result | null;
  objectid_businessunit?: BusinessUnit_Result | null;
  objectid_canvasappextendedmetadata?: CanvasAppExtendedMetadata_Result | null;
  objectid_cascadegrantrevokeaccessrecordstracker?: cascadegrantrevokeaccessrecordstracker_Result | null;
  objectid_cascadegrantrevokeaccessversiontracker?: cascadegrantrevokeaccessversiontracker_Result | null;
  objectid_catalog?: Catalog_Result | null;
  objectid_catalogassignment?: CatalogAssignment_Result | null;
  objectid_connection?: Connection_Result | null;
  objectid_connectionreference?: connectionreference_Result | null;
  objectid_connector?: connector_Result | null;
  objectid_contact?: Contact_Result | null;
  objectid_conversationtranscript?: conversationtranscript_Result | null;
  objectid_customapi?: CustomAPI_Result | null;
  objectid_customapirequestparameter?: CustomAPIRequestParameter_Result | null;
  objectid_customapiresponseproperty?: CustomAPIResponseProperty_Result | null;
  objectid_customeraddress?: CustomerAddress_Result | null;
  objectid_datalakefolder?: datalakefolder_Result | null;
  objectid_datalakefolderpermission?: datalakefolderpermission_Result | null;
  objectid_datalakeworkspace?: datalakeworkspace_Result | null;
  objectid_datalakeworkspacepermission?: datalakeworkspacepermission_Result | null;
  objectid_email?: Email_Result | null;
  objectid_entityanalyticsconfig?: EntityAnalyticsConfig_Result | null;
  objectid_entityimageconfig?: EntityImageConfig_Result | null;
  objectid_entityindex?: EntityIndex_Result | null;
  objectid_environmentvariabledefinition?: EnvironmentVariableDefinition_Result | null;
  objectid_environmentvariablevalue?: EnvironmentVariableValue_Result | null;
  objectid_exportsolutionupload?: ExportSolutionUpload_Result | null;
  objectid_fax?: Fax_Result | null;
  objectid_featurecontrolsetting?: featurecontrolsetting_Result | null;
  objectid_feedback?: Feedback_Result | null;
  objectid_flowmachine?: flowmachine_Result | null;
  objectid_flowmachinegroup?: flowmachinegroup_Result | null;
  objectid_flowsession?: flowsession_Result | null;
  objectid_goal?: Goal_Result | null;
  objectid_holidaywrapper?: holidaywrapper_Result | null;
  objectid_indexattributes?: IndexAttributes_Result | null;
  objectid_internalcatalogassignment?: InternalCatalogAssignment_Result | null;
  objectid_kbarticle?: KbArticle_Result | null;
  objectid_keyvaultreference?: KeyVaultReference_Result | null;
  objectid_knowledgearticle?: KnowledgeArticle_Result | null;
  objectid_knowledgearticleviews?: KnowledgeArticleViews_Result | null;
  objectid_knowledgebaserecord?: KnowledgeBaseRecord_Result | null;
  objectid_letter?: Letter_Result | null;
  objectid_mailmergetemplate?: MailMergeTemplate_Result | null;
  objectid_managedidentity?: ManagedIdentity_Result | null;
  objectid_mbs_pluginprofile?: mbs_pluginprofile_Result | null;
  objectid_msdyn_aibdataset?: msdyn_AIBDataset_Result | null;
  objectid_msdyn_aibdatasetfile?: msdyn_AIBDatasetFile_Result | null;
  objectid_msdyn_aibdatasetrecord?: msdyn_AIBDatasetRecord_Result | null;
  objectid_msdyn_aibdatasetscontainer?: msdyn_AIBDatasetsContainer_Result | null;
  objectid_msdyn_aibfile?: msdyn_AIBFile_Result | null;
  objectid_msdyn_aibfileattacheddata?: msdyn_AIBFileAttachedData_Result | null;
  objectid_msdyn_aiconfiguration?: msdyn_AIConfiguration_Result | null;
  objectid_msdyn_aifptrainingdocument?: msdyn_AIFpTrainingDocument_Result | null;
  objectid_msdyn_aimodel?: msdyn_AIModel_Result | null;
  objectid_msdyn_aiodimage?: msdyn_AIOdImage_Result | null;
  objectid_msdyn_aiodlabel?: msdyn_AIOdLabel_Result | null;
  objectid_msdyn_aiodtrainingboundingbox?: msdyn_AIOdTrainingBoundingBox_Result | null;
  objectid_msdyn_aiodtrainingimage?: msdyn_AIOdTrainingImage_Result | null;
  objectid_msdyn_aitemplate?: msdyn_AITemplate_Result | null;
  objectid_msdyn_analysiscomponent?: msdyn_analysiscomponent_Result | null;
  objectid_msdyn_analysisjob?: msdyn_analysisjob_Result | null;
  objectid_msdyn_analysisresult?: msdyn_analysisresult_Result | null;
  objectid_msdyn_analysisresultdetail?: msdyn_analysisresultdetail_Result | null;
  objectid_msdyn_dataflow?: msdyn_dataflow_Result | null;
  objectid_msdyn_federatedarticle?: msdyn_federatedarticle_Result | null;
  objectid_msdyn_federatedarticleincident?: msdyn_federatedarticleincident_Result | null;
  objectid_msdyn_helppage?: msdyn_helppage_Result | null;
  objectid_msdyn_kalanguagesetting?: msdyn_kalanguagesetting_Result | null;
  objectid_msdyn_kmfederatedsearchconfig?: msdyn_kmfederatedsearchconfig_Result | null;
  objectid_msdyn_kmpersonalizationsetting?: msdyn_kmpersonalizationsetting_Result | null;
  objectid_msdyn_knowledgearticleimage?: msdyn_knowledgearticleimage_Result | null;
  objectid_msdyn_knowledgearticletemplate?: msdyn_knowledgearticletemplate_Result | null;
  objectid_msdyn_knowledgeinteractioninsight?: msdyn_knowledgeinteractioninsight_Result | null;
  objectid_msdyn_knowledgepersonalfilter?: msdyn_knowledgepersonalfilter_Result | null;
  objectid_msdyn_knowledgesearchfilter?: msdyn_knowledgesearchfilter_Result | null;
  objectid_msdyn_knowledgesearchinsight?: msdyn_knowledgesearchinsight_Result | null;
  objectid_msdyn_pminferredtask?: msdyn_pminferredtask_Result | null;
  objectid_msdyn_pmrecording?: msdyn_pmrecording_Result | null;
  objectid_msdyn_richtextfile?: msdyn_richtextfile_Result | null;
  objectid_msdyn_serviceconfiguration?: msdyn_serviceconfiguration_Result | null;
  objectid_msdyn_slakpi?: msdyn_slakpi_Result | null;
  objectid_msdyn_solutionhealthrule?: msdyn_solutionhealthrule_Result | null;
  objectid_msdyn_solutionhealthruleargument?: msdyn_solutionhealthruleargument_Result | null;
  objectid_msdyn_solutionhealthruleset?: msdyn_solutionhealthruleset_Result | null;
  objectid_msdyn_tour?: msdyn_tour_Result | null;
  objectid_msdynce_botcontent?: msdynce_botcontent_Result | null;
  objectid_organizationdatasyncsubscription?: organizationdatasyncsubscription_Result | null;
  objectid_organizationdatasyncsubscriptionentity?: organizationdatasyncsubscriptionentity_Result | null;
  objectid_organizationsetting?: OrganizationSetting_Result | null;
  objectid_package?: package_Result | null;
  objectid_pc_bankaccount?: pc_BankAccount_Result | null;
  objectid_pc_participation?: pc_Participation_Result | null;
  objectid_pc_participationfeeexemption?: pc_ParticipationFeeExemption_Result | null;
  objectid_pc_payment?: pc_Payment_Result | null;
  objectid_pc_scheduledjob?: pc_ScheduledJob_Result | null;
  objectid_pc_settings?: pc_Settings_Result | null;
  objectid_pc_transaction?: pc_Transaction_Result | null;
  objectid_pdfsetting?: PDFSetting_Result | null;
  objectid_phonecall?: PhoneCall_Result | null;
  objectid_pluginpackage?: pluginpackage_Result | null;
  objectid_position?: Position_Result | null;
  objectid_processstageparameter?: processstageparameter_Result | null;
  objectid_provisionlanguageforuser?: ProvisionLanguageForUser_Result | null;
  objectid_queue?: Queue_Result | null;
  objectid_queueitem?: QueueItem_Result | null;
  objectid_recurringappointmentmaster?: RecurringAppointmentMaster_Result | null;
  objectid_relationshipattribute?: RelationshipAttribute_Result | null;
  objectid_reportcategory?: ReportCategory_Result | null;
  objectid_revokeinheritedaccessrecordstracker?: revokeinheritedaccessrecordstracker_Result | null;
  objectid_serviceplan?: ServicePlan_Result | null;
  objectid_serviceplanmapping?: ServicePlanMapping_Result | null;
  objectid_settingdefinition?: SettingDefinition_Result | null;
  objectid_sharepointdocumentlocation?: SharePointDocumentLocation_Result | null;
  objectid_sharepointsite?: SharePointSite_Result | null;
  objectid_socialactivity?: SocialActivity_Result | null;
  objectid_socialprofile?: SocialProfile_Result | null;
  objectid_solutioncomponentattributeconfiguration?: solutioncomponentattributeconfiguration_Result | null;
  objectid_solutioncomponentbatchconfiguration?: solutioncomponentbatchconfiguration_Result | null;
  objectid_solutioncomponentconfiguration?: solutioncomponentconfiguration_Result | null;
  objectid_solutioncomponentrelationshipconfiguration?: solutioncomponentrelationshipconfiguration_Result | null;
  objectid_stagesolutionupload?: StageSolutionUpload_Result | null;
  objectid_systemuser?: SystemUser_Result | null;
  objectid_systemuserauthorizationchangetracker?: SystemUserAuthorizationChangeTracker_Result | null;
  objectid_task?: Task_Result | null;
  objectid_team?: Team_Result | null;
  objectid_teammobileofflineprofilemembership?: teammobileofflineprofilemembership_Result | null;
  objectid_territory?: Territory_Result | null;
  objectid_usermobileofflineprofilemembership?: usermobileofflineprofilemembership_Result | null;
  objectid_virtualentitymetadata?: VirtualEntityMetadata_Result | null;
  objectid_workflowbinary?: workflowbinary_Result | null;
  principalid_systemuser?: SystemUser_Result | null;
  principalid_team?: Team_Result | null;
  userentityinstancedata_principalobjectattributeaccess?: UserEntityInstanceData_Result[] | null;
}
interface PrincipalObjectAttributeAccess extends PrincipalObjectAttributeAccess_Base, PrincipalObjectAttributeAccess_Relationships {
}
interface PrincipalObjectAttributeAccess_Create extends PrincipalObjectAttributeAccess {
  channelaccessprofile_principalobjectattributeaccess_bind$channelaccessprofiles?: string | null;
  objectid_account_bind$accounts?: string | null;
  objectid_activityfileattachment_bind$activityfileattachments?: string | null;
  objectid_appaction_bind$appactions?: string | null;
  objectid_appelement_bind$appelements?: string | null;
  objectid_applicationuser_bind$applicationusers?: string | null;
  objectid_appmodulecomponentedge_bind$appmodulecomponentedges?: string | null;
  objectid_appmodulecomponentnode_bind$appmodulecomponentnodes?: string | null;
  objectid_appointment_bind$appointments?: string | null;
  objectid_appsetting_bind$appsettings?: string | null;
  objectid_appusersetting_bind$appusersettings?: string | null;
  objectid_attributeimageconfig_bind$attributeimageconfigs?: string | null;
  objectid_bot_bind$bots?: string | null;
  objectid_botcomponent_bind$botcomponents?: string | null;
  objectid_businessunit_bind$businessunits?: string | null;
  objectid_canvasappextendedmetadata_bind$canvasappextendedmetadata?: string | null;
  objectid_cascadegrantrevokeaccessrecordstracker_bind$cascadegrantrevokeaccessrecordstrackers?: string | null;
  objectid_cascadegrantrevokeaccessversiontracker_bind$cascadegrantrevokeaccessversiontrackers?: string | null;
  objectid_catalog_bind$catalogs?: string | null;
  objectid_catalogassignment_bind$catalogassignments?: string | null;
  objectid_connection_bind$connections?: string | null;
  objectid_connectionreference_bind$connectionreferences?: string | null;
  objectid_connector_bind$connectors?: string | null;
  objectid_contact_bind$contacts?: string | null;
  objectid_conversationtranscript_bind$conversationtranscripts?: string | null;
  objectid_customapi_bind$customapis?: string | null;
  objectid_customapirequestparameter_bind$customapirequestparameters?: string | null;
  objectid_customapiresponseproperty_bind$customapiresponseproperties?: string | null;
  objectid_customeraddress_bind$customeraddresses?: string | null;
  objectid_datalakefolder_bind$datalakefolders?: string | null;
  objectid_datalakefolderpermission_bind$datalakefolderpermissions?: string | null;
  objectid_datalakeworkspace_bind$datalakeworkspaces?: string | null;
  objectid_datalakeworkspacepermission_bind$datalakeworkspacepermissions?: string | null;
  objectid_email_bind$emails?: string | null;
  objectid_entityanalyticsconfig_bind$entityanalyticsconfigs?: string | null;
  objectid_entityimageconfig_bind$entityimageconfigs?: string | null;
  objectid_entityindex_bind$entityindexes?: string | null;
  objectid_environmentvariabledefinition_bind$environmentvariabledefinitions?: string | null;
  objectid_environmentvariablevalue_bind$environmentvariablevalues?: string | null;
  objectid_exportsolutionupload_bind$exportsolutionuploads?: string | null;
  objectid_fax_bind$faxes?: string | null;
  objectid_featurecontrolsetting_bind$featurecontrolsettings?: string | null;
  objectid_feedback_bind$feedback?: string | null;
  objectid_flowmachine_bind$flowmachines?: string | null;
  objectid_flowmachinegroup_bind$flowmachinegroups?: string | null;
  objectid_flowsession_bind$flowsessions?: string | null;
  objectid_goal_bind$goals?: string | null;
  objectid_holidaywrapper_bind$holidaywrappers?: string | null;
  objectid_indexattributes_bind$indexattributes?: string | null;
  objectid_internalcatalogassignment_bind$internalcatalogassignments?: string | null;
  objectid_kbarticle_bind$kbarticles?: string | null;
  objectid_keyvaultreference_bind$keyvaultreferences?: string | null;
  objectid_knowledgearticle_bind$knowledgearticles?: string | null;
  objectid_knowledgearticleviews_bind$knowledgearticleviews?: string | null;
  objectid_knowledgebaserecord_bind$knowledgebaserecords?: string | null;
  objectid_letter_bind$letters?: string | null;
  objectid_mailmergetemplate_bind$mailmergetemplates?: string | null;
  objectid_managedidentity_bind$managedidentities?: string | null;
  objectid_mbs_pluginprofile_bind$mbs_pluginprofiles?: string | null;
  objectid_msdyn_aibdataset_bind$msdyn_aibdatasets?: string | null;
  objectid_msdyn_aibdatasetfile_bind$msdyn_aibdatasetfiles?: string | null;
  objectid_msdyn_aibdatasetrecord_bind$msdyn_aibdatasetrecords?: string | null;
  objectid_msdyn_aibdatasetscontainer_bind$msdyn_aibdatasetscontainers?: string | null;
  objectid_msdyn_aibfile_bind$msdyn_aibfiles?: string | null;
  objectid_msdyn_aibfileattacheddata_bind$msdyn_aibfileattacheddatas?: string | null;
  objectid_msdyn_aiconfiguration_bind$msdyn_aiconfigurations?: string | null;
  objectid_msdyn_aifptrainingdocument_bind$msdyn_aifptrainingdocuments?: string | null;
  objectid_msdyn_aimodel_bind$msdyn_aimodels?: string | null;
  objectid_msdyn_aiodimage_bind$msdyn_aiodimages?: string | null;
  objectid_msdyn_aiodlabel_bind$msdyn_aiodlabels?: string | null;
  objectid_msdyn_aiodtrainingboundingbox_bind$msdyn_aiodtrainingboundingboxes?: string | null;
  objectid_msdyn_aiodtrainingimage_bind$msdyn_aiodtrainingimages?: string | null;
  objectid_msdyn_aitemplate_bind$msdyn_aitemplates?: string | null;
  objectid_msdyn_analysiscomponent_bind$msdyn_analysiscomponents?: string | null;
  objectid_msdyn_analysisjob_bind$msdyn_analysisjobs?: string | null;
  objectid_msdyn_analysisresult_bind$msdyn_analysisresults?: string | null;
  objectid_msdyn_analysisresultdetail_bind$msdyn_analysisresultdetails?: string | null;
  objectid_msdyn_dataflow_bind$msdyn_dataflows?: string | null;
  objectid_msdyn_federatedarticle_bind$msdyn_federatedarticles?: string | null;
  objectid_msdyn_federatedarticleincident_bind$msdyn_federatedarticleincidents?: string | null;
  objectid_msdyn_helppage_bind$msdyn_helppages?: string | null;
  objectid_msdyn_kalanguagesetting_bind$msdyn_kalanguagesettings?: string | null;
  objectid_msdyn_kmfederatedsearchconfig_bind$msdyn_kmfederatedsearchconfigs?: string | null;
  objectid_msdyn_kmpersonalizationsetting_bind$msdyn_kmpersonalizationsettings?: string | null;
  objectid_msdyn_knowledgearticleimage_bind$msdyn_knowledgearticleimages?: string | null;
  objectid_msdyn_knowledgearticletemplate_bind$msdyn_knowledgearticletemplates?: string | null;
  objectid_msdyn_knowledgeinteractioninsight_bind$msdyn_knowledgeinteractioninsights?: string | null;
  objectid_msdyn_knowledgepersonalfilter_bind$msdyn_knowledgepersonalfilters?: string | null;
  objectid_msdyn_knowledgesearchfilter_bind$msdyn_knowledgesearchfilters?: string | null;
  objectid_msdyn_knowledgesearchinsight_bind$msdyn_knowledgesearchinsights?: string | null;
  objectid_msdyn_pminferredtask_bind$msdyn_pminferredtasks?: string | null;
  objectid_msdyn_pmrecording_bind$msdyn_pmrecordings?: string | null;
  objectid_msdyn_richtextfile_bind$msdyn_richtextfiles?: string | null;
  objectid_msdyn_serviceconfiguration_bind$msdyn_serviceconfigurations?: string | null;
  objectid_msdyn_slakpi_bind$msdyn_slakpis?: string | null;
  objectid_msdyn_solutionhealthrule_bind$msdyn_solutionhealthrules?: string | null;
  objectid_msdyn_solutionhealthruleargument_bind$msdyn_solutionhealthrulearguments?: string | null;
  objectid_msdyn_solutionhealthruleset_bind$msdyn_solutionhealthrulesets?: string | null;
  objectid_msdyn_tour_bind$msdyn_tours?: string | null;
  objectid_msdynce_botcontent_bind$msdynce_botcontents?: string | null;
  objectid_organizationdatasyncsubscription_bind$organizationdatasyncsubscriptions?: string | null;
  objectid_organizationdatasyncsubscriptionentity_bind$organizationdatasyncsubscriptionentities?: string | null;
  objectid_organizationsetting_bind$organizationsettings?: string | null;
  objectid_package_bind$packages?: string | null;
  objectid_pc_bankaccount_bind$pc_bankaccounts?: string | null;
  objectid_pc_participation_bind$pc_participations?: string | null;
  objectid_pc_participationfeeexemption_bind$pc_participationfeeexemptions?: string | null;
  objectid_pc_payment_bind$pc_payments?: string | null;
  objectid_pc_scheduledjob_bind$pc_scheduledjobs?: string | null;
  objectid_pc_settings_bind$pc_settingses?: string | null;
  objectid_pc_transaction_bind$pc_transactions?: string | null;
  objectid_pdfsetting_bind$pdfsettings?: string | null;
  objectid_phonecall_bind$phonecalls?: string | null;
  objectid_pluginpackage_bind$pluginpackages?: string | null;
  objectid_position_bind$positions?: string | null;
  objectid_processstageparameter_bind$processstageparameters?: string | null;
  objectid_provisionlanguageforuser_bind$provisionlanguageforusers?: string | null;
  objectid_queue_bind$queues?: string | null;
  objectid_queueitem_bind$queueitems?: string | null;
  objectid_recurringappointmentmaster_bind$recurringappointmentmasters?: string | null;
  objectid_relationshipattribute_bind$relationshipattributes?: string | null;
  objectid_reportcategory_bind$reportcategories?: string | null;
  objectid_revokeinheritedaccessrecordstracker_bind$revokeinheritedaccessrecordstrackers?: string | null;
  objectid_serviceplan_bind$serviceplans?: string | null;
  objectid_serviceplanmapping_bind$serviceplanmappings?: string | null;
  objectid_settingdefinition_bind$settingdefinitions?: string | null;
  objectid_sharepointdocumentlocation_bind$sharepointdocumentlocations?: string | null;
  objectid_sharepointsite_bind$sharepointsites?: string | null;
  objectid_socialactivity_bind$socialactivities?: string | null;
  objectid_socialprofile_bind$socialprofiles?: string | null;
  objectid_solutioncomponentattributeconfiguration_bind$solutioncomponentattributeconfigurations?: string | null;
  objectid_solutioncomponentbatchconfiguration_bind$solutioncomponentbatchconfigurations?: string | null;
  objectid_solutioncomponentconfiguration_bind$solutioncomponentconfigurations?: string | null;
  objectid_solutioncomponentrelationshipconfiguration_bind$solutioncomponentrelationshipconfigurations?: string | null;
  objectid_stagesolutionupload_bind$stagesolutionuploads?: string | null;
  objectid_systemuser_bind$systemusers?: string | null;
  objectid_systemuserauthorizationchangetracker_bind$systemuserauthorizationchangetrackers?: string | null;
  objectid_task_bind$tasks?: string | null;
  objectid_team_bind$teams?: string | null;
  objectid_teammobileofflineprofilemembership_bind$teammobileofflineprofilememberships?: string | null;
  objectid_territory_bind$territories?: string | null;
  objectid_usermobileofflineprofilemembership_bind$usermobileofflineprofilememberships?: string | null;
  objectid_virtualentitymetadata_bind$virtualentitymetadatas?: string | null;
  objectid_workflowbinary_bind$workflowbinaries?: string | null;
  principalid_systemuser_bind$systemusers?: string | null;
  principalid_team_bind$teams?: string | null;
}
interface PrincipalObjectAttributeAccess_Update extends PrincipalObjectAttributeAccess {
}
interface PrincipalObjectAttributeAccess_Select {
  attributeid: WebAttribute<PrincipalObjectAttributeAccess_Select, { attributeid: string | null }, {  }>;
  objectid_guid: WebAttribute<PrincipalObjectAttributeAccess_Select, { objectid_guid: string | null }, { objectid_formatted?: string }>;
  organizationid_guid: WebAttribute<PrincipalObjectAttributeAccess_Select, { organizationid_guid: string | null }, { organizationid_formatted?: string }>;
  principalid_guid: WebAttribute<PrincipalObjectAttributeAccess_Select, { principalid_guid: string | null }, { principalid_formatted?: string }>;
  principalobjectattributeaccessid: WebAttribute<PrincipalObjectAttributeAccess_Select, { principalobjectattributeaccessid: string | null }, {  }>;
  readaccess: WebAttribute<PrincipalObjectAttributeAccess_Select, { readaccess: boolean | null }, {  }>;
  updateaccess: WebAttribute<PrincipalObjectAttributeAccess_Select, { updateaccess: boolean | null }, {  }>;
  versionnumber: WebAttribute<PrincipalObjectAttributeAccess_Select, { versionnumber: number | null }, {  }>;
}
interface PrincipalObjectAttributeAccess_Filter {
  attributeid: XQW.Guid;
  objectid_guid: XQW.Guid;
  organizationid_guid: XQW.Guid;
  principalid_guid: XQW.Guid;
  principalobjectattributeaccessid: XQW.Guid;
  readaccess: boolean;
  updateaccess: boolean;
  versionnumber: number;
}
interface PrincipalObjectAttributeAccess_Expand {
  channelaccessprofile_principalobjectattributeaccess: WebExpand<PrincipalObjectAttributeAccess_Expand, ChannelAccessProfile_Select, ChannelAccessProfile_Filter, { channelaccessprofile_principalobjectattributeaccess: ChannelAccessProfile_Result }>;
  objectid_account: WebExpand<PrincipalObjectAttributeAccess_Expand, Account_Select, Account_Filter, { objectid_account: Account_Result }>;
  objectid_activityfileattachment: WebExpand<PrincipalObjectAttributeAccess_Expand, activityfileattachment_Select, activityfileattachment_Filter, { objectid_activityfileattachment: activityfileattachment_Result }>;
  objectid_appaction: WebExpand<PrincipalObjectAttributeAccess_Expand, appaction_Select, appaction_Filter, { objectid_appaction: appaction_Result }>;
  objectid_appelement: WebExpand<PrincipalObjectAttributeAccess_Expand, AppElement_Select, AppElement_Filter, { objectid_appelement: AppElement_Result }>;
  objectid_applicationuser: WebExpand<PrincipalObjectAttributeAccess_Expand, ApplicationUser_Select, ApplicationUser_Filter, { objectid_applicationuser: ApplicationUser_Result }>;
  objectid_appmodulecomponentedge: WebExpand<PrincipalObjectAttributeAccess_Expand, AppModuleComponentEdge_Select, AppModuleComponentEdge_Filter, { objectid_appmodulecomponentedge: AppModuleComponentEdge_Result }>;
  objectid_appmodulecomponentnode: WebExpand<PrincipalObjectAttributeAccess_Expand, AppModuleComponentNode_Select, AppModuleComponentNode_Filter, { objectid_appmodulecomponentnode: AppModuleComponentNode_Result }>;
  objectid_appointment: WebExpand<PrincipalObjectAttributeAccess_Expand, Appointment_Select, Appointment_Filter, { objectid_appointment: Appointment_Result }>;
  objectid_appsetting: WebExpand<PrincipalObjectAttributeAccess_Expand, AppSetting_Select, AppSetting_Filter, { objectid_appsetting: AppSetting_Result }>;
  objectid_appusersetting: WebExpand<PrincipalObjectAttributeAccess_Expand, AppUserSetting_Select, AppUserSetting_Filter, { objectid_appusersetting: AppUserSetting_Result }>;
  objectid_attributeimageconfig: WebExpand<PrincipalObjectAttributeAccess_Expand, AttributeImageConfig_Select, AttributeImageConfig_Filter, { objectid_attributeimageconfig: AttributeImageConfig_Result }>;
  objectid_bot: WebExpand<PrincipalObjectAttributeAccess_Expand, bot_Select, bot_Filter, { objectid_bot: bot_Result }>;
  objectid_botcomponent: WebExpand<PrincipalObjectAttributeAccess_Expand, botcomponent_Select, botcomponent_Filter, { objectid_botcomponent: botcomponent_Result }>;
  objectid_businessunit: WebExpand<PrincipalObjectAttributeAccess_Expand, BusinessUnit_Select, BusinessUnit_Filter, { objectid_businessunit: BusinessUnit_Result }>;
  objectid_canvasappextendedmetadata: WebExpand<PrincipalObjectAttributeAccess_Expand, CanvasAppExtendedMetadata_Select, CanvasAppExtendedMetadata_Filter, { objectid_canvasappextendedmetadata: CanvasAppExtendedMetadata_Result }>;
  objectid_cascadegrantrevokeaccessrecordstracker: WebExpand<PrincipalObjectAttributeAccess_Expand, cascadegrantrevokeaccessrecordstracker_Select, cascadegrantrevokeaccessrecordstracker_Filter, { objectid_cascadegrantrevokeaccessrecordstracker: cascadegrantrevokeaccessrecordstracker_Result }>;
  objectid_cascadegrantrevokeaccessversiontracker: WebExpand<PrincipalObjectAttributeAccess_Expand, cascadegrantrevokeaccessversiontracker_Select, cascadegrantrevokeaccessversiontracker_Filter, { objectid_cascadegrantrevokeaccessversiontracker: cascadegrantrevokeaccessversiontracker_Result }>;
  objectid_catalog: WebExpand<PrincipalObjectAttributeAccess_Expand, Catalog_Select, Catalog_Filter, { objectid_catalog: Catalog_Result }>;
  objectid_catalogassignment: WebExpand<PrincipalObjectAttributeAccess_Expand, CatalogAssignment_Select, CatalogAssignment_Filter, { objectid_catalogassignment: CatalogAssignment_Result }>;
  objectid_connection: WebExpand<PrincipalObjectAttributeAccess_Expand, Connection_Select, Connection_Filter, { objectid_connection: Connection_Result }>;
  objectid_connectionreference: WebExpand<PrincipalObjectAttributeAccess_Expand, connectionreference_Select, connectionreference_Filter, { objectid_connectionreference: connectionreference_Result }>;
  objectid_connector: WebExpand<PrincipalObjectAttributeAccess_Expand, connector_Select, connector_Filter, { objectid_connector: connector_Result }>;
  objectid_contact: WebExpand<PrincipalObjectAttributeAccess_Expand, Contact_Select, Contact_Filter, { objectid_contact: Contact_Result }>;
  objectid_conversationtranscript: WebExpand<PrincipalObjectAttributeAccess_Expand, conversationtranscript_Select, conversationtranscript_Filter, { objectid_conversationtranscript: conversationtranscript_Result }>;
  objectid_customapi: WebExpand<PrincipalObjectAttributeAccess_Expand, CustomAPI_Select, CustomAPI_Filter, { objectid_customapi: CustomAPI_Result }>;
  objectid_customapirequestparameter: WebExpand<PrincipalObjectAttributeAccess_Expand, CustomAPIRequestParameter_Select, CustomAPIRequestParameter_Filter, { objectid_customapirequestparameter: CustomAPIRequestParameter_Result }>;
  objectid_customapiresponseproperty: WebExpand<PrincipalObjectAttributeAccess_Expand, CustomAPIResponseProperty_Select, CustomAPIResponseProperty_Filter, { objectid_customapiresponseproperty: CustomAPIResponseProperty_Result }>;
  objectid_customeraddress: WebExpand<PrincipalObjectAttributeAccess_Expand, CustomerAddress_Select, CustomerAddress_Filter, { objectid_customeraddress: CustomerAddress_Result }>;
  objectid_datalakefolder: WebExpand<PrincipalObjectAttributeAccess_Expand, datalakefolder_Select, datalakefolder_Filter, { objectid_datalakefolder: datalakefolder_Result }>;
  objectid_datalakefolderpermission: WebExpand<PrincipalObjectAttributeAccess_Expand, datalakefolderpermission_Select, datalakefolderpermission_Filter, { objectid_datalakefolderpermission: datalakefolderpermission_Result }>;
  objectid_datalakeworkspace: WebExpand<PrincipalObjectAttributeAccess_Expand, datalakeworkspace_Select, datalakeworkspace_Filter, { objectid_datalakeworkspace: datalakeworkspace_Result }>;
  objectid_datalakeworkspacepermission: WebExpand<PrincipalObjectAttributeAccess_Expand, datalakeworkspacepermission_Select, datalakeworkspacepermission_Filter, { objectid_datalakeworkspacepermission: datalakeworkspacepermission_Result }>;
  objectid_email: WebExpand<PrincipalObjectAttributeAccess_Expand, Email_Select, Email_Filter, { objectid_email: Email_Result }>;
  objectid_entityanalyticsconfig: WebExpand<PrincipalObjectAttributeAccess_Expand, EntityAnalyticsConfig_Select, EntityAnalyticsConfig_Filter, { objectid_entityanalyticsconfig: EntityAnalyticsConfig_Result }>;
  objectid_entityimageconfig: WebExpand<PrincipalObjectAttributeAccess_Expand, EntityImageConfig_Select, EntityImageConfig_Filter, { objectid_entityimageconfig: EntityImageConfig_Result }>;
  objectid_entityindex: WebExpand<PrincipalObjectAttributeAccess_Expand, EntityIndex_Select, EntityIndex_Filter, { objectid_entityindex: EntityIndex_Result }>;
  objectid_environmentvariabledefinition: WebExpand<PrincipalObjectAttributeAccess_Expand, EnvironmentVariableDefinition_Select, EnvironmentVariableDefinition_Filter, { objectid_environmentvariabledefinition: EnvironmentVariableDefinition_Result }>;
  objectid_environmentvariablevalue: WebExpand<PrincipalObjectAttributeAccess_Expand, EnvironmentVariableValue_Select, EnvironmentVariableValue_Filter, { objectid_environmentvariablevalue: EnvironmentVariableValue_Result }>;
  objectid_exportsolutionupload: WebExpand<PrincipalObjectAttributeAccess_Expand, ExportSolutionUpload_Select, ExportSolutionUpload_Filter, { objectid_exportsolutionupload: ExportSolutionUpload_Result }>;
  objectid_fax: WebExpand<PrincipalObjectAttributeAccess_Expand, Fax_Select, Fax_Filter, { objectid_fax: Fax_Result }>;
  objectid_featurecontrolsetting: WebExpand<PrincipalObjectAttributeAccess_Expand, featurecontrolsetting_Select, featurecontrolsetting_Filter, { objectid_featurecontrolsetting: featurecontrolsetting_Result }>;
  objectid_feedback: WebExpand<PrincipalObjectAttributeAccess_Expand, Feedback_Select, Feedback_Filter, { objectid_feedback: Feedback_Result }>;
  objectid_flowmachine: WebExpand<PrincipalObjectAttributeAccess_Expand, flowmachine_Select, flowmachine_Filter, { objectid_flowmachine: flowmachine_Result }>;
  objectid_flowmachinegroup: WebExpand<PrincipalObjectAttributeAccess_Expand, flowmachinegroup_Select, flowmachinegroup_Filter, { objectid_flowmachinegroup: flowmachinegroup_Result }>;
  objectid_flowsession: WebExpand<PrincipalObjectAttributeAccess_Expand, flowsession_Select, flowsession_Filter, { objectid_flowsession: flowsession_Result }>;
  objectid_goal: WebExpand<PrincipalObjectAttributeAccess_Expand, Goal_Select, Goal_Filter, { objectid_goal: Goal_Result }>;
  objectid_holidaywrapper: WebExpand<PrincipalObjectAttributeAccess_Expand, holidaywrapper_Select, holidaywrapper_Filter, { objectid_holidaywrapper: holidaywrapper_Result }>;
  objectid_indexattributes: WebExpand<PrincipalObjectAttributeAccess_Expand, IndexAttributes_Select, IndexAttributes_Filter, { objectid_indexattributes: IndexAttributes_Result }>;
  objectid_internalcatalogassignment: WebExpand<PrincipalObjectAttributeAccess_Expand, InternalCatalogAssignment_Select, InternalCatalogAssignment_Filter, { objectid_internalcatalogassignment: InternalCatalogAssignment_Result }>;
  objectid_kbarticle: WebExpand<PrincipalObjectAttributeAccess_Expand, KbArticle_Select, KbArticle_Filter, { objectid_kbarticle: KbArticle_Result }>;
  objectid_keyvaultreference: WebExpand<PrincipalObjectAttributeAccess_Expand, KeyVaultReference_Select, KeyVaultReference_Filter, { objectid_keyvaultreference: KeyVaultReference_Result }>;
  objectid_knowledgearticle: WebExpand<PrincipalObjectAttributeAccess_Expand, KnowledgeArticle_Select, KnowledgeArticle_Filter, { objectid_knowledgearticle: KnowledgeArticle_Result }>;
  objectid_knowledgearticleviews: WebExpand<PrincipalObjectAttributeAccess_Expand, KnowledgeArticleViews_Select, KnowledgeArticleViews_Filter, { objectid_knowledgearticleviews: KnowledgeArticleViews_Result }>;
  objectid_knowledgebaserecord: WebExpand<PrincipalObjectAttributeAccess_Expand, KnowledgeBaseRecord_Select, KnowledgeBaseRecord_Filter, { objectid_knowledgebaserecord: KnowledgeBaseRecord_Result }>;
  objectid_letter: WebExpand<PrincipalObjectAttributeAccess_Expand, Letter_Select, Letter_Filter, { objectid_letter: Letter_Result }>;
  objectid_mailmergetemplate: WebExpand<PrincipalObjectAttributeAccess_Expand, MailMergeTemplate_Select, MailMergeTemplate_Filter, { objectid_mailmergetemplate: MailMergeTemplate_Result }>;
  objectid_managedidentity: WebExpand<PrincipalObjectAttributeAccess_Expand, ManagedIdentity_Select, ManagedIdentity_Filter, { objectid_managedidentity: ManagedIdentity_Result }>;
  objectid_mbs_pluginprofile: WebExpand<PrincipalObjectAttributeAccess_Expand, mbs_pluginprofile_Select, mbs_pluginprofile_Filter, { objectid_mbs_pluginprofile: mbs_pluginprofile_Result }>;
  objectid_msdyn_aibdataset: WebExpand<PrincipalObjectAttributeAccess_Expand, msdyn_AIBDataset_Select, msdyn_AIBDataset_Filter, { objectid_msdyn_aibdataset: msdyn_AIBDataset_Result }>;
  objectid_msdyn_aibdatasetfile: WebExpand<PrincipalObjectAttributeAccess_Expand, msdyn_AIBDatasetFile_Select, msdyn_AIBDatasetFile_Filter, { objectid_msdyn_aibdatasetfile: msdyn_AIBDatasetFile_Result }>;
  objectid_msdyn_aibdatasetrecord: WebExpand<PrincipalObjectAttributeAccess_Expand, msdyn_AIBDatasetRecord_Select, msdyn_AIBDatasetRecord_Filter, { objectid_msdyn_aibdatasetrecord: msdyn_AIBDatasetRecord_Result }>;
  objectid_msdyn_aibdatasetscontainer: WebExpand<PrincipalObjectAttributeAccess_Expand, msdyn_AIBDatasetsContainer_Select, msdyn_AIBDatasetsContainer_Filter, { objectid_msdyn_aibdatasetscontainer: msdyn_AIBDatasetsContainer_Result }>;
  objectid_msdyn_aibfile: WebExpand<PrincipalObjectAttributeAccess_Expand, msdyn_AIBFile_Select, msdyn_AIBFile_Filter, { objectid_msdyn_aibfile: msdyn_AIBFile_Result }>;
  objectid_msdyn_aibfileattacheddata: WebExpand<PrincipalObjectAttributeAccess_Expand, msdyn_AIBFileAttachedData_Select, msdyn_AIBFileAttachedData_Filter, { objectid_msdyn_aibfileattacheddata: msdyn_AIBFileAttachedData_Result }>;
  objectid_msdyn_aiconfiguration: WebExpand<PrincipalObjectAttributeAccess_Expand, msdyn_AIConfiguration_Select, msdyn_AIConfiguration_Filter, { objectid_msdyn_aiconfiguration: msdyn_AIConfiguration_Result }>;
  objectid_msdyn_aifptrainingdocument: WebExpand<PrincipalObjectAttributeAccess_Expand, msdyn_AIFpTrainingDocument_Select, msdyn_AIFpTrainingDocument_Filter, { objectid_msdyn_aifptrainingdocument: msdyn_AIFpTrainingDocument_Result }>;
  objectid_msdyn_aimodel: WebExpand<PrincipalObjectAttributeAccess_Expand, msdyn_AIModel_Select, msdyn_AIModel_Filter, { objectid_msdyn_aimodel: msdyn_AIModel_Result }>;
  objectid_msdyn_aiodimage: WebExpand<PrincipalObjectAttributeAccess_Expand, msdyn_AIOdImage_Select, msdyn_AIOdImage_Filter, { objectid_msdyn_aiodimage: msdyn_AIOdImage_Result }>;
  objectid_msdyn_aiodlabel: WebExpand<PrincipalObjectAttributeAccess_Expand, msdyn_AIOdLabel_Select, msdyn_AIOdLabel_Filter, { objectid_msdyn_aiodlabel: msdyn_AIOdLabel_Result }>;
  objectid_msdyn_aiodtrainingboundingbox: WebExpand<PrincipalObjectAttributeAccess_Expand, msdyn_AIOdTrainingBoundingBox_Select, msdyn_AIOdTrainingBoundingBox_Filter, { objectid_msdyn_aiodtrainingboundingbox: msdyn_AIOdTrainingBoundingBox_Result }>;
  objectid_msdyn_aiodtrainingimage: WebExpand<PrincipalObjectAttributeAccess_Expand, msdyn_AIOdTrainingImage_Select, msdyn_AIOdTrainingImage_Filter, { objectid_msdyn_aiodtrainingimage: msdyn_AIOdTrainingImage_Result }>;
  objectid_msdyn_aitemplate: WebExpand<PrincipalObjectAttributeAccess_Expand, msdyn_AITemplate_Select, msdyn_AITemplate_Filter, { objectid_msdyn_aitemplate: msdyn_AITemplate_Result }>;
  objectid_msdyn_analysiscomponent: WebExpand<PrincipalObjectAttributeAccess_Expand, msdyn_analysiscomponent_Select, msdyn_analysiscomponent_Filter, { objectid_msdyn_analysiscomponent: msdyn_analysiscomponent_Result }>;
  objectid_msdyn_analysisjob: WebExpand<PrincipalObjectAttributeAccess_Expand, msdyn_analysisjob_Select, msdyn_analysisjob_Filter, { objectid_msdyn_analysisjob: msdyn_analysisjob_Result }>;
  objectid_msdyn_analysisresult: WebExpand<PrincipalObjectAttributeAccess_Expand, msdyn_analysisresult_Select, msdyn_analysisresult_Filter, { objectid_msdyn_analysisresult: msdyn_analysisresult_Result }>;
  objectid_msdyn_analysisresultdetail: WebExpand<PrincipalObjectAttributeAccess_Expand, msdyn_analysisresultdetail_Select, msdyn_analysisresultdetail_Filter, { objectid_msdyn_analysisresultdetail: msdyn_analysisresultdetail_Result }>;
  objectid_msdyn_dataflow: WebExpand<PrincipalObjectAttributeAccess_Expand, msdyn_dataflow_Select, msdyn_dataflow_Filter, { objectid_msdyn_dataflow: msdyn_dataflow_Result }>;
  objectid_msdyn_federatedarticle: WebExpand<PrincipalObjectAttributeAccess_Expand, msdyn_federatedarticle_Select, msdyn_federatedarticle_Filter, { objectid_msdyn_federatedarticle: msdyn_federatedarticle_Result }>;
  objectid_msdyn_federatedarticleincident: WebExpand<PrincipalObjectAttributeAccess_Expand, msdyn_federatedarticleincident_Select, msdyn_federatedarticleincident_Filter, { objectid_msdyn_federatedarticleincident: msdyn_federatedarticleincident_Result }>;
  objectid_msdyn_helppage: WebExpand<PrincipalObjectAttributeAccess_Expand, msdyn_helppage_Select, msdyn_helppage_Filter, { objectid_msdyn_helppage: msdyn_helppage_Result }>;
  objectid_msdyn_kalanguagesetting: WebExpand<PrincipalObjectAttributeAccess_Expand, msdyn_kalanguagesetting_Select, msdyn_kalanguagesetting_Filter, { objectid_msdyn_kalanguagesetting: msdyn_kalanguagesetting_Result }>;
  objectid_msdyn_kmfederatedsearchconfig: WebExpand<PrincipalObjectAttributeAccess_Expand, msdyn_kmfederatedsearchconfig_Select, msdyn_kmfederatedsearchconfig_Filter, { objectid_msdyn_kmfederatedsearchconfig: msdyn_kmfederatedsearchconfig_Result }>;
  objectid_msdyn_kmpersonalizationsetting: WebExpand<PrincipalObjectAttributeAccess_Expand, msdyn_kmpersonalizationsetting_Select, msdyn_kmpersonalizationsetting_Filter, { objectid_msdyn_kmpersonalizationsetting: msdyn_kmpersonalizationsetting_Result }>;
  objectid_msdyn_knowledgearticleimage: WebExpand<PrincipalObjectAttributeAccess_Expand, msdyn_knowledgearticleimage_Select, msdyn_knowledgearticleimage_Filter, { objectid_msdyn_knowledgearticleimage: msdyn_knowledgearticleimage_Result }>;
  objectid_msdyn_knowledgearticletemplate: WebExpand<PrincipalObjectAttributeAccess_Expand, msdyn_knowledgearticletemplate_Select, msdyn_knowledgearticletemplate_Filter, { objectid_msdyn_knowledgearticletemplate: msdyn_knowledgearticletemplate_Result }>;
  objectid_msdyn_knowledgeinteractioninsight: WebExpand<PrincipalObjectAttributeAccess_Expand, msdyn_knowledgeinteractioninsight_Select, msdyn_knowledgeinteractioninsight_Filter, { objectid_msdyn_knowledgeinteractioninsight: msdyn_knowledgeinteractioninsight_Result }>;
  objectid_msdyn_knowledgepersonalfilter: WebExpand<PrincipalObjectAttributeAccess_Expand, msdyn_knowledgepersonalfilter_Select, msdyn_knowledgepersonalfilter_Filter, { objectid_msdyn_knowledgepersonalfilter: msdyn_knowledgepersonalfilter_Result }>;
  objectid_msdyn_knowledgesearchfilter: WebExpand<PrincipalObjectAttributeAccess_Expand, msdyn_knowledgesearchfilter_Select, msdyn_knowledgesearchfilter_Filter, { objectid_msdyn_knowledgesearchfilter: msdyn_knowledgesearchfilter_Result }>;
  objectid_msdyn_knowledgesearchinsight: WebExpand<PrincipalObjectAttributeAccess_Expand, msdyn_knowledgesearchinsight_Select, msdyn_knowledgesearchinsight_Filter, { objectid_msdyn_knowledgesearchinsight: msdyn_knowledgesearchinsight_Result }>;
  objectid_msdyn_pminferredtask: WebExpand<PrincipalObjectAttributeAccess_Expand, msdyn_pminferredtask_Select, msdyn_pminferredtask_Filter, { objectid_msdyn_pminferredtask: msdyn_pminferredtask_Result }>;
  objectid_msdyn_pmrecording: WebExpand<PrincipalObjectAttributeAccess_Expand, msdyn_pmrecording_Select, msdyn_pmrecording_Filter, { objectid_msdyn_pmrecording: msdyn_pmrecording_Result }>;
  objectid_msdyn_richtextfile: WebExpand<PrincipalObjectAttributeAccess_Expand, msdyn_richtextfile_Select, msdyn_richtextfile_Filter, { objectid_msdyn_richtextfile: msdyn_richtextfile_Result }>;
  objectid_msdyn_serviceconfiguration: WebExpand<PrincipalObjectAttributeAccess_Expand, msdyn_serviceconfiguration_Select, msdyn_serviceconfiguration_Filter, { objectid_msdyn_serviceconfiguration: msdyn_serviceconfiguration_Result }>;
  objectid_msdyn_slakpi: WebExpand<PrincipalObjectAttributeAccess_Expand, msdyn_slakpi_Select, msdyn_slakpi_Filter, { objectid_msdyn_slakpi: msdyn_slakpi_Result }>;
  objectid_msdyn_solutionhealthrule: WebExpand<PrincipalObjectAttributeAccess_Expand, msdyn_solutionhealthrule_Select, msdyn_solutionhealthrule_Filter, { objectid_msdyn_solutionhealthrule: msdyn_solutionhealthrule_Result }>;
  objectid_msdyn_solutionhealthruleargument: WebExpand<PrincipalObjectAttributeAccess_Expand, msdyn_solutionhealthruleargument_Select, msdyn_solutionhealthruleargument_Filter, { objectid_msdyn_solutionhealthruleargument: msdyn_solutionhealthruleargument_Result }>;
  objectid_msdyn_solutionhealthruleset: WebExpand<PrincipalObjectAttributeAccess_Expand, msdyn_solutionhealthruleset_Select, msdyn_solutionhealthruleset_Filter, { objectid_msdyn_solutionhealthruleset: msdyn_solutionhealthruleset_Result }>;
  objectid_msdyn_tour: WebExpand<PrincipalObjectAttributeAccess_Expand, msdyn_tour_Select, msdyn_tour_Filter, { objectid_msdyn_tour: msdyn_tour_Result }>;
  objectid_msdynce_botcontent: WebExpand<PrincipalObjectAttributeAccess_Expand, msdynce_botcontent_Select, msdynce_botcontent_Filter, { objectid_msdynce_botcontent: msdynce_botcontent_Result }>;
  objectid_organizationdatasyncsubscription: WebExpand<PrincipalObjectAttributeAccess_Expand, organizationdatasyncsubscription_Select, organizationdatasyncsubscription_Filter, { objectid_organizationdatasyncsubscription: organizationdatasyncsubscription_Result }>;
  objectid_organizationdatasyncsubscriptionentity: WebExpand<PrincipalObjectAttributeAccess_Expand, organizationdatasyncsubscriptionentity_Select, organizationdatasyncsubscriptionentity_Filter, { objectid_organizationdatasyncsubscriptionentity: organizationdatasyncsubscriptionentity_Result }>;
  objectid_organizationsetting: WebExpand<PrincipalObjectAttributeAccess_Expand, OrganizationSetting_Select, OrganizationSetting_Filter, { objectid_organizationsetting: OrganizationSetting_Result }>;
  objectid_package: WebExpand<PrincipalObjectAttributeAccess_Expand, package_Select, package_Filter, { objectid_package: package_Result }>;
  objectid_pc_bankaccount: WebExpand<PrincipalObjectAttributeAccess_Expand, pc_BankAccount_Select, pc_BankAccount_Filter, { objectid_pc_bankaccount: pc_BankAccount_Result }>;
  objectid_pc_participation: WebExpand<PrincipalObjectAttributeAccess_Expand, pc_Participation_Select, pc_Participation_Filter, { objectid_pc_participation: pc_Participation_Result }>;
  objectid_pc_participationfeeexemption: WebExpand<PrincipalObjectAttributeAccess_Expand, pc_ParticipationFeeExemption_Select, pc_ParticipationFeeExemption_Filter, { objectid_pc_participationfeeexemption: pc_ParticipationFeeExemption_Result }>;
  objectid_pc_payment: WebExpand<PrincipalObjectAttributeAccess_Expand, pc_Payment_Select, pc_Payment_Filter, { objectid_pc_payment: pc_Payment_Result }>;
  objectid_pc_scheduledjob: WebExpand<PrincipalObjectAttributeAccess_Expand, pc_ScheduledJob_Select, pc_ScheduledJob_Filter, { objectid_pc_scheduledjob: pc_ScheduledJob_Result }>;
  objectid_pc_settings: WebExpand<PrincipalObjectAttributeAccess_Expand, pc_Settings_Select, pc_Settings_Filter, { objectid_pc_settings: pc_Settings_Result }>;
  objectid_pc_transaction: WebExpand<PrincipalObjectAttributeAccess_Expand, pc_Transaction_Select, pc_Transaction_Filter, { objectid_pc_transaction: pc_Transaction_Result }>;
  objectid_pdfsetting: WebExpand<PrincipalObjectAttributeAccess_Expand, PDFSetting_Select, PDFSetting_Filter, { objectid_pdfsetting: PDFSetting_Result }>;
  objectid_phonecall: WebExpand<PrincipalObjectAttributeAccess_Expand, PhoneCall_Select, PhoneCall_Filter, { objectid_phonecall: PhoneCall_Result }>;
  objectid_pluginpackage: WebExpand<PrincipalObjectAttributeAccess_Expand, pluginpackage_Select, pluginpackage_Filter, { objectid_pluginpackage: pluginpackage_Result }>;
  objectid_position: WebExpand<PrincipalObjectAttributeAccess_Expand, Position_Select, Position_Filter, { objectid_position: Position_Result }>;
  objectid_processstageparameter: WebExpand<PrincipalObjectAttributeAccess_Expand, processstageparameter_Select, processstageparameter_Filter, { objectid_processstageparameter: processstageparameter_Result }>;
  objectid_provisionlanguageforuser: WebExpand<PrincipalObjectAttributeAccess_Expand, ProvisionLanguageForUser_Select, ProvisionLanguageForUser_Filter, { objectid_provisionlanguageforuser: ProvisionLanguageForUser_Result }>;
  objectid_queue: WebExpand<PrincipalObjectAttributeAccess_Expand, Queue_Select, Queue_Filter, { objectid_queue: Queue_Result }>;
  objectid_queueitem: WebExpand<PrincipalObjectAttributeAccess_Expand, QueueItem_Select, QueueItem_Filter, { objectid_queueitem: QueueItem_Result }>;
  objectid_recurringappointmentmaster: WebExpand<PrincipalObjectAttributeAccess_Expand, RecurringAppointmentMaster_Select, RecurringAppointmentMaster_Filter, { objectid_recurringappointmentmaster: RecurringAppointmentMaster_Result }>;
  objectid_relationshipattribute: WebExpand<PrincipalObjectAttributeAccess_Expand, RelationshipAttribute_Select, RelationshipAttribute_Filter, { objectid_relationshipattribute: RelationshipAttribute_Result }>;
  objectid_reportcategory: WebExpand<PrincipalObjectAttributeAccess_Expand, ReportCategory_Select, ReportCategory_Filter, { objectid_reportcategory: ReportCategory_Result }>;
  objectid_revokeinheritedaccessrecordstracker: WebExpand<PrincipalObjectAttributeAccess_Expand, revokeinheritedaccessrecordstracker_Select, revokeinheritedaccessrecordstracker_Filter, { objectid_revokeinheritedaccessrecordstracker: revokeinheritedaccessrecordstracker_Result }>;
  objectid_serviceplan: WebExpand<PrincipalObjectAttributeAccess_Expand, ServicePlan_Select, ServicePlan_Filter, { objectid_serviceplan: ServicePlan_Result }>;
  objectid_serviceplanmapping: WebExpand<PrincipalObjectAttributeAccess_Expand, ServicePlanMapping_Select, ServicePlanMapping_Filter, { objectid_serviceplanmapping: ServicePlanMapping_Result }>;
  objectid_settingdefinition: WebExpand<PrincipalObjectAttributeAccess_Expand, SettingDefinition_Select, SettingDefinition_Filter, { objectid_settingdefinition: SettingDefinition_Result }>;
  objectid_sharepointdocumentlocation: WebExpand<PrincipalObjectAttributeAccess_Expand, SharePointDocumentLocation_Select, SharePointDocumentLocation_Filter, { objectid_sharepointdocumentlocation: SharePointDocumentLocation_Result }>;
  objectid_sharepointsite: WebExpand<PrincipalObjectAttributeAccess_Expand, SharePointSite_Select, SharePointSite_Filter, { objectid_sharepointsite: SharePointSite_Result }>;
  objectid_socialactivity: WebExpand<PrincipalObjectAttributeAccess_Expand, SocialActivity_Select, SocialActivity_Filter, { objectid_socialactivity: SocialActivity_Result }>;
  objectid_socialprofile: WebExpand<PrincipalObjectAttributeAccess_Expand, SocialProfile_Select, SocialProfile_Filter, { objectid_socialprofile: SocialProfile_Result }>;
  objectid_solutioncomponentattributeconfiguration: WebExpand<PrincipalObjectAttributeAccess_Expand, solutioncomponentattributeconfiguration_Select, solutioncomponentattributeconfiguration_Filter, { objectid_solutioncomponentattributeconfiguration: solutioncomponentattributeconfiguration_Result }>;
  objectid_solutioncomponentbatchconfiguration: WebExpand<PrincipalObjectAttributeAccess_Expand, solutioncomponentbatchconfiguration_Select, solutioncomponentbatchconfiguration_Filter, { objectid_solutioncomponentbatchconfiguration: solutioncomponentbatchconfiguration_Result }>;
  objectid_solutioncomponentconfiguration: WebExpand<PrincipalObjectAttributeAccess_Expand, solutioncomponentconfiguration_Select, solutioncomponentconfiguration_Filter, { objectid_solutioncomponentconfiguration: solutioncomponentconfiguration_Result }>;
  objectid_solutioncomponentrelationshipconfiguration: WebExpand<PrincipalObjectAttributeAccess_Expand, solutioncomponentrelationshipconfiguration_Select, solutioncomponentrelationshipconfiguration_Filter, { objectid_solutioncomponentrelationshipconfiguration: solutioncomponentrelationshipconfiguration_Result }>;
  objectid_stagesolutionupload: WebExpand<PrincipalObjectAttributeAccess_Expand, StageSolutionUpload_Select, StageSolutionUpload_Filter, { objectid_stagesolutionupload: StageSolutionUpload_Result }>;
  objectid_systemuser: WebExpand<PrincipalObjectAttributeAccess_Expand, SystemUser_Select, SystemUser_Filter, { objectid_systemuser: SystemUser_Result }>;
  objectid_systemuserauthorizationchangetracker: WebExpand<PrincipalObjectAttributeAccess_Expand, SystemUserAuthorizationChangeTracker_Select, SystemUserAuthorizationChangeTracker_Filter, { objectid_systemuserauthorizationchangetracker: SystemUserAuthorizationChangeTracker_Result }>;
  objectid_task: WebExpand<PrincipalObjectAttributeAccess_Expand, Task_Select, Task_Filter, { objectid_task: Task_Result }>;
  objectid_team: WebExpand<PrincipalObjectAttributeAccess_Expand, Team_Select, Team_Filter, { objectid_team: Team_Result }>;
  objectid_teammobileofflineprofilemembership: WebExpand<PrincipalObjectAttributeAccess_Expand, teammobileofflineprofilemembership_Select, teammobileofflineprofilemembership_Filter, { objectid_teammobileofflineprofilemembership: teammobileofflineprofilemembership_Result }>;
  objectid_territory: WebExpand<PrincipalObjectAttributeAccess_Expand, Territory_Select, Territory_Filter, { objectid_territory: Territory_Result }>;
  objectid_usermobileofflineprofilemembership: WebExpand<PrincipalObjectAttributeAccess_Expand, usermobileofflineprofilemembership_Select, usermobileofflineprofilemembership_Filter, { objectid_usermobileofflineprofilemembership: usermobileofflineprofilemembership_Result }>;
  objectid_virtualentitymetadata: WebExpand<PrincipalObjectAttributeAccess_Expand, VirtualEntityMetadata_Select, VirtualEntityMetadata_Filter, { objectid_virtualentitymetadata: VirtualEntityMetadata_Result }>;
  objectid_workflowbinary: WebExpand<PrincipalObjectAttributeAccess_Expand, workflowbinary_Select, workflowbinary_Filter, { objectid_workflowbinary: workflowbinary_Result }>;
  organizationid: WebExpand<PrincipalObjectAttributeAccess_Expand, Organization_Select, Organization_Filter, { organizationid: Organization_Result }>;
  principalid_systemuser: WebExpand<PrincipalObjectAttributeAccess_Expand, SystemUser_Select, SystemUser_Filter, { principalid_systemuser: SystemUser_Result }>;
  principalid_team: WebExpand<PrincipalObjectAttributeAccess_Expand, Team_Select, Team_Filter, { principalid_team: Team_Result }>;
  userentityinstancedata_principalobjectattributeaccess: WebExpand<PrincipalObjectAttributeAccess_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { userentityinstancedata_principalobjectattributeaccess: UserEntityInstanceData_Result[] }>;
}
interface PrincipalObjectAttributeAccess_FormattedResult {
  objectid_formatted?: string;
  organizationid_formatted?: string;
  principalid_formatted?: string;
}
interface PrincipalObjectAttributeAccess_Result extends PrincipalObjectAttributeAccess_Base, PrincipalObjectAttributeAccess_Relationships {
  "@odata.etag": string;
  objectid_guid: string | null;
  organizationid_guid: string | null;
  principalid_guid: string | null;
}
interface PrincipalObjectAttributeAccess_RelatedOne {
  channelaccessprofile_principalobjectattributeaccess: WebMappingRetrieve<ChannelAccessProfile_Select,ChannelAccessProfile_Expand,ChannelAccessProfile_Filter,ChannelAccessProfile_Fixed,ChannelAccessProfile_Result,ChannelAccessProfile_FormattedResult>;
  objectid_account: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  objectid_activityfileattachment: WebMappingRetrieve<activityfileattachment_Select,activityfileattachment_Expand,activityfileattachment_Filter,activityfileattachment_Fixed,activityfileattachment_Result,activityfileattachment_FormattedResult>;
  objectid_appaction: WebMappingRetrieve<appaction_Select,appaction_Expand,appaction_Filter,appaction_Fixed,appaction_Result,appaction_FormattedResult>;
  objectid_appelement: WebMappingRetrieve<AppElement_Select,AppElement_Expand,AppElement_Filter,AppElement_Fixed,AppElement_Result,AppElement_FormattedResult>;
  objectid_applicationuser: WebMappingRetrieve<ApplicationUser_Select,ApplicationUser_Expand,ApplicationUser_Filter,ApplicationUser_Fixed,ApplicationUser_Result,ApplicationUser_FormattedResult>;
  objectid_appmodulecomponentedge: WebMappingRetrieve<AppModuleComponentEdge_Select,AppModuleComponentEdge_Expand,AppModuleComponentEdge_Filter,AppModuleComponentEdge_Fixed,AppModuleComponentEdge_Result,AppModuleComponentEdge_FormattedResult>;
  objectid_appmodulecomponentnode: WebMappingRetrieve<AppModuleComponentNode_Select,AppModuleComponentNode_Expand,AppModuleComponentNode_Filter,AppModuleComponentNode_Fixed,AppModuleComponentNode_Result,AppModuleComponentNode_FormattedResult>;
  objectid_appointment: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
  objectid_appsetting: WebMappingRetrieve<AppSetting_Select,AppSetting_Expand,AppSetting_Filter,AppSetting_Fixed,AppSetting_Result,AppSetting_FormattedResult>;
  objectid_appusersetting: WebMappingRetrieve<AppUserSetting_Select,AppUserSetting_Expand,AppUserSetting_Filter,AppUserSetting_Fixed,AppUserSetting_Result,AppUserSetting_FormattedResult>;
  objectid_attributeimageconfig: WebMappingRetrieve<AttributeImageConfig_Select,AttributeImageConfig_Expand,AttributeImageConfig_Filter,AttributeImageConfig_Fixed,AttributeImageConfig_Result,AttributeImageConfig_FormattedResult>;
  objectid_bot: WebMappingRetrieve<bot_Select,bot_Expand,bot_Filter,bot_Fixed,bot_Result,bot_FormattedResult>;
  objectid_botcomponent: WebMappingRetrieve<botcomponent_Select,botcomponent_Expand,botcomponent_Filter,botcomponent_Fixed,botcomponent_Result,botcomponent_FormattedResult>;
  objectid_businessunit: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  objectid_canvasappextendedmetadata: WebMappingRetrieve<CanvasAppExtendedMetadata_Select,CanvasAppExtendedMetadata_Expand,CanvasAppExtendedMetadata_Filter,CanvasAppExtendedMetadata_Fixed,CanvasAppExtendedMetadata_Result,CanvasAppExtendedMetadata_FormattedResult>;
  objectid_cascadegrantrevokeaccessrecordstracker: WebMappingRetrieve<cascadegrantrevokeaccessrecordstracker_Select,cascadegrantrevokeaccessrecordstracker_Expand,cascadegrantrevokeaccessrecordstracker_Filter,cascadegrantrevokeaccessrecordstracker_Fixed,cascadegrantrevokeaccessrecordstracker_Result,cascadegrantrevokeaccessrecordstracker_FormattedResult>;
  objectid_cascadegrantrevokeaccessversiontracker: WebMappingRetrieve<cascadegrantrevokeaccessversiontracker_Select,cascadegrantrevokeaccessversiontracker_Expand,cascadegrantrevokeaccessversiontracker_Filter,cascadegrantrevokeaccessversiontracker_Fixed,cascadegrantrevokeaccessversiontracker_Result,cascadegrantrevokeaccessversiontracker_FormattedResult>;
  objectid_catalog: WebMappingRetrieve<Catalog_Select,Catalog_Expand,Catalog_Filter,Catalog_Fixed,Catalog_Result,Catalog_FormattedResult>;
  objectid_catalogassignment: WebMappingRetrieve<CatalogAssignment_Select,CatalogAssignment_Expand,CatalogAssignment_Filter,CatalogAssignment_Fixed,CatalogAssignment_Result,CatalogAssignment_FormattedResult>;
  objectid_connection: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  objectid_connectionreference: WebMappingRetrieve<connectionreference_Select,connectionreference_Expand,connectionreference_Filter,connectionreference_Fixed,connectionreference_Result,connectionreference_FormattedResult>;
  objectid_connector: WebMappingRetrieve<connector_Select,connector_Expand,connector_Filter,connector_Fixed,connector_Result,connector_FormattedResult>;
  objectid_contact: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  objectid_conversationtranscript: WebMappingRetrieve<conversationtranscript_Select,conversationtranscript_Expand,conversationtranscript_Filter,conversationtranscript_Fixed,conversationtranscript_Result,conversationtranscript_FormattedResult>;
  objectid_customapi: WebMappingRetrieve<CustomAPI_Select,CustomAPI_Expand,CustomAPI_Filter,CustomAPI_Fixed,CustomAPI_Result,CustomAPI_FormattedResult>;
  objectid_customapirequestparameter: WebMappingRetrieve<CustomAPIRequestParameter_Select,CustomAPIRequestParameter_Expand,CustomAPIRequestParameter_Filter,CustomAPIRequestParameter_Fixed,CustomAPIRequestParameter_Result,CustomAPIRequestParameter_FormattedResult>;
  objectid_customapiresponseproperty: WebMappingRetrieve<CustomAPIResponseProperty_Select,CustomAPIResponseProperty_Expand,CustomAPIResponseProperty_Filter,CustomAPIResponseProperty_Fixed,CustomAPIResponseProperty_Result,CustomAPIResponseProperty_FormattedResult>;
  objectid_customeraddress: WebMappingRetrieve<CustomerAddress_Select,CustomerAddress_Expand,CustomerAddress_Filter,CustomerAddress_Fixed,CustomerAddress_Result,CustomerAddress_FormattedResult>;
  objectid_datalakefolder: WebMappingRetrieve<datalakefolder_Select,datalakefolder_Expand,datalakefolder_Filter,datalakefolder_Fixed,datalakefolder_Result,datalakefolder_FormattedResult>;
  objectid_datalakefolderpermission: WebMappingRetrieve<datalakefolderpermission_Select,datalakefolderpermission_Expand,datalakefolderpermission_Filter,datalakefolderpermission_Fixed,datalakefolderpermission_Result,datalakefolderpermission_FormattedResult>;
  objectid_datalakeworkspace: WebMappingRetrieve<datalakeworkspace_Select,datalakeworkspace_Expand,datalakeworkspace_Filter,datalakeworkspace_Fixed,datalakeworkspace_Result,datalakeworkspace_FormattedResult>;
  objectid_datalakeworkspacepermission: WebMappingRetrieve<datalakeworkspacepermission_Select,datalakeworkspacepermission_Expand,datalakeworkspacepermission_Filter,datalakeworkspacepermission_Fixed,datalakeworkspacepermission_Result,datalakeworkspacepermission_FormattedResult>;
  objectid_email: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  objectid_entityanalyticsconfig: WebMappingRetrieve<EntityAnalyticsConfig_Select,EntityAnalyticsConfig_Expand,EntityAnalyticsConfig_Filter,EntityAnalyticsConfig_Fixed,EntityAnalyticsConfig_Result,EntityAnalyticsConfig_FormattedResult>;
  objectid_entityimageconfig: WebMappingRetrieve<EntityImageConfig_Select,EntityImageConfig_Expand,EntityImageConfig_Filter,EntityImageConfig_Fixed,EntityImageConfig_Result,EntityImageConfig_FormattedResult>;
  objectid_entityindex: WebMappingRetrieve<EntityIndex_Select,EntityIndex_Expand,EntityIndex_Filter,EntityIndex_Fixed,EntityIndex_Result,EntityIndex_FormattedResult>;
  objectid_environmentvariabledefinition: WebMappingRetrieve<EnvironmentVariableDefinition_Select,EnvironmentVariableDefinition_Expand,EnvironmentVariableDefinition_Filter,EnvironmentVariableDefinition_Fixed,EnvironmentVariableDefinition_Result,EnvironmentVariableDefinition_FormattedResult>;
  objectid_environmentvariablevalue: WebMappingRetrieve<EnvironmentVariableValue_Select,EnvironmentVariableValue_Expand,EnvironmentVariableValue_Filter,EnvironmentVariableValue_Fixed,EnvironmentVariableValue_Result,EnvironmentVariableValue_FormattedResult>;
  objectid_exportsolutionupload: WebMappingRetrieve<ExportSolutionUpload_Select,ExportSolutionUpload_Expand,ExportSolutionUpload_Filter,ExportSolutionUpload_Fixed,ExportSolutionUpload_Result,ExportSolutionUpload_FormattedResult>;
  objectid_fax: WebMappingRetrieve<Fax_Select,Fax_Expand,Fax_Filter,Fax_Fixed,Fax_Result,Fax_FormattedResult>;
  objectid_featurecontrolsetting: WebMappingRetrieve<featurecontrolsetting_Select,featurecontrolsetting_Expand,featurecontrolsetting_Filter,featurecontrolsetting_Fixed,featurecontrolsetting_Result,featurecontrolsetting_FormattedResult>;
  objectid_feedback: WebMappingRetrieve<Feedback_Select,Feedback_Expand,Feedback_Filter,Feedback_Fixed,Feedback_Result,Feedback_FormattedResult>;
  objectid_flowmachine: WebMappingRetrieve<flowmachine_Select,flowmachine_Expand,flowmachine_Filter,flowmachine_Fixed,flowmachine_Result,flowmachine_FormattedResult>;
  objectid_flowmachinegroup: WebMappingRetrieve<flowmachinegroup_Select,flowmachinegroup_Expand,flowmachinegroup_Filter,flowmachinegroup_Fixed,flowmachinegroup_Result,flowmachinegroup_FormattedResult>;
  objectid_flowsession: WebMappingRetrieve<flowsession_Select,flowsession_Expand,flowsession_Filter,flowsession_Fixed,flowsession_Result,flowsession_FormattedResult>;
  objectid_goal: WebMappingRetrieve<Goal_Select,Goal_Expand,Goal_Filter,Goal_Fixed,Goal_Result,Goal_FormattedResult>;
  objectid_holidaywrapper: WebMappingRetrieve<holidaywrapper_Select,holidaywrapper_Expand,holidaywrapper_Filter,holidaywrapper_Fixed,holidaywrapper_Result,holidaywrapper_FormattedResult>;
  objectid_indexattributes: WebMappingRetrieve<IndexAttributes_Select,IndexAttributes_Expand,IndexAttributes_Filter,IndexAttributes_Fixed,IndexAttributes_Result,IndexAttributes_FormattedResult>;
  objectid_internalcatalogassignment: WebMappingRetrieve<InternalCatalogAssignment_Select,InternalCatalogAssignment_Expand,InternalCatalogAssignment_Filter,InternalCatalogAssignment_Fixed,InternalCatalogAssignment_Result,InternalCatalogAssignment_FormattedResult>;
  objectid_kbarticle: WebMappingRetrieve<KbArticle_Select,KbArticle_Expand,KbArticle_Filter,KbArticle_Fixed,KbArticle_Result,KbArticle_FormattedResult>;
  objectid_keyvaultreference: WebMappingRetrieve<KeyVaultReference_Select,KeyVaultReference_Expand,KeyVaultReference_Filter,KeyVaultReference_Fixed,KeyVaultReference_Result,KeyVaultReference_FormattedResult>;
  objectid_knowledgearticle: WebMappingRetrieve<KnowledgeArticle_Select,KnowledgeArticle_Expand,KnowledgeArticle_Filter,KnowledgeArticle_Fixed,KnowledgeArticle_Result,KnowledgeArticle_FormattedResult>;
  objectid_knowledgearticleviews: WebMappingRetrieve<KnowledgeArticleViews_Select,KnowledgeArticleViews_Expand,KnowledgeArticleViews_Filter,KnowledgeArticleViews_Fixed,KnowledgeArticleViews_Result,KnowledgeArticleViews_FormattedResult>;
  objectid_knowledgebaserecord: WebMappingRetrieve<KnowledgeBaseRecord_Select,KnowledgeBaseRecord_Expand,KnowledgeBaseRecord_Filter,KnowledgeBaseRecord_Fixed,KnowledgeBaseRecord_Result,KnowledgeBaseRecord_FormattedResult>;
  objectid_letter: WebMappingRetrieve<Letter_Select,Letter_Expand,Letter_Filter,Letter_Fixed,Letter_Result,Letter_FormattedResult>;
  objectid_mailmergetemplate: WebMappingRetrieve<MailMergeTemplate_Select,MailMergeTemplate_Expand,MailMergeTemplate_Filter,MailMergeTemplate_Fixed,MailMergeTemplate_Result,MailMergeTemplate_FormattedResult>;
  objectid_managedidentity: WebMappingRetrieve<ManagedIdentity_Select,ManagedIdentity_Expand,ManagedIdentity_Filter,ManagedIdentity_Fixed,ManagedIdentity_Result,ManagedIdentity_FormattedResult>;
  objectid_mbs_pluginprofile: WebMappingRetrieve<mbs_pluginprofile_Select,mbs_pluginprofile_Expand,mbs_pluginprofile_Filter,mbs_pluginprofile_Fixed,mbs_pluginprofile_Result,mbs_pluginprofile_FormattedResult>;
  objectid_msdyn_aibdataset: WebMappingRetrieve<msdyn_AIBDataset_Select,msdyn_AIBDataset_Expand,msdyn_AIBDataset_Filter,msdyn_AIBDataset_Fixed,msdyn_AIBDataset_Result,msdyn_AIBDataset_FormattedResult>;
  objectid_msdyn_aibdatasetfile: WebMappingRetrieve<msdyn_AIBDatasetFile_Select,msdyn_AIBDatasetFile_Expand,msdyn_AIBDatasetFile_Filter,msdyn_AIBDatasetFile_Fixed,msdyn_AIBDatasetFile_Result,msdyn_AIBDatasetFile_FormattedResult>;
  objectid_msdyn_aibdatasetrecord: WebMappingRetrieve<msdyn_AIBDatasetRecord_Select,msdyn_AIBDatasetRecord_Expand,msdyn_AIBDatasetRecord_Filter,msdyn_AIBDatasetRecord_Fixed,msdyn_AIBDatasetRecord_Result,msdyn_AIBDatasetRecord_FormattedResult>;
  objectid_msdyn_aibdatasetscontainer: WebMappingRetrieve<msdyn_AIBDatasetsContainer_Select,msdyn_AIBDatasetsContainer_Expand,msdyn_AIBDatasetsContainer_Filter,msdyn_AIBDatasetsContainer_Fixed,msdyn_AIBDatasetsContainer_Result,msdyn_AIBDatasetsContainer_FormattedResult>;
  objectid_msdyn_aibfile: WebMappingRetrieve<msdyn_AIBFile_Select,msdyn_AIBFile_Expand,msdyn_AIBFile_Filter,msdyn_AIBFile_Fixed,msdyn_AIBFile_Result,msdyn_AIBFile_FormattedResult>;
  objectid_msdyn_aibfileattacheddata: WebMappingRetrieve<msdyn_AIBFileAttachedData_Select,msdyn_AIBFileAttachedData_Expand,msdyn_AIBFileAttachedData_Filter,msdyn_AIBFileAttachedData_Fixed,msdyn_AIBFileAttachedData_Result,msdyn_AIBFileAttachedData_FormattedResult>;
  objectid_msdyn_aiconfiguration: WebMappingRetrieve<msdyn_AIConfiguration_Select,msdyn_AIConfiguration_Expand,msdyn_AIConfiguration_Filter,msdyn_AIConfiguration_Fixed,msdyn_AIConfiguration_Result,msdyn_AIConfiguration_FormattedResult>;
  objectid_msdyn_aifptrainingdocument: WebMappingRetrieve<msdyn_AIFpTrainingDocument_Select,msdyn_AIFpTrainingDocument_Expand,msdyn_AIFpTrainingDocument_Filter,msdyn_AIFpTrainingDocument_Fixed,msdyn_AIFpTrainingDocument_Result,msdyn_AIFpTrainingDocument_FormattedResult>;
  objectid_msdyn_aimodel: WebMappingRetrieve<msdyn_AIModel_Select,msdyn_AIModel_Expand,msdyn_AIModel_Filter,msdyn_AIModel_Fixed,msdyn_AIModel_Result,msdyn_AIModel_FormattedResult>;
  objectid_msdyn_aiodimage: WebMappingRetrieve<msdyn_AIOdImage_Select,msdyn_AIOdImage_Expand,msdyn_AIOdImage_Filter,msdyn_AIOdImage_Fixed,msdyn_AIOdImage_Result,msdyn_AIOdImage_FormattedResult>;
  objectid_msdyn_aiodlabel: WebMappingRetrieve<msdyn_AIOdLabel_Select,msdyn_AIOdLabel_Expand,msdyn_AIOdLabel_Filter,msdyn_AIOdLabel_Fixed,msdyn_AIOdLabel_Result,msdyn_AIOdLabel_FormattedResult>;
  objectid_msdyn_aiodtrainingboundingbox: WebMappingRetrieve<msdyn_AIOdTrainingBoundingBox_Select,msdyn_AIOdTrainingBoundingBox_Expand,msdyn_AIOdTrainingBoundingBox_Filter,msdyn_AIOdTrainingBoundingBox_Fixed,msdyn_AIOdTrainingBoundingBox_Result,msdyn_AIOdTrainingBoundingBox_FormattedResult>;
  objectid_msdyn_aiodtrainingimage: WebMappingRetrieve<msdyn_AIOdTrainingImage_Select,msdyn_AIOdTrainingImage_Expand,msdyn_AIOdTrainingImage_Filter,msdyn_AIOdTrainingImage_Fixed,msdyn_AIOdTrainingImage_Result,msdyn_AIOdTrainingImage_FormattedResult>;
  objectid_msdyn_aitemplate: WebMappingRetrieve<msdyn_AITemplate_Select,msdyn_AITemplate_Expand,msdyn_AITemplate_Filter,msdyn_AITemplate_Fixed,msdyn_AITemplate_Result,msdyn_AITemplate_FormattedResult>;
  objectid_msdyn_analysiscomponent: WebMappingRetrieve<msdyn_analysiscomponent_Select,msdyn_analysiscomponent_Expand,msdyn_analysiscomponent_Filter,msdyn_analysiscomponent_Fixed,msdyn_analysiscomponent_Result,msdyn_analysiscomponent_FormattedResult>;
  objectid_msdyn_analysisjob: WebMappingRetrieve<msdyn_analysisjob_Select,msdyn_analysisjob_Expand,msdyn_analysisjob_Filter,msdyn_analysisjob_Fixed,msdyn_analysisjob_Result,msdyn_analysisjob_FormattedResult>;
  objectid_msdyn_analysisresult: WebMappingRetrieve<msdyn_analysisresult_Select,msdyn_analysisresult_Expand,msdyn_analysisresult_Filter,msdyn_analysisresult_Fixed,msdyn_analysisresult_Result,msdyn_analysisresult_FormattedResult>;
  objectid_msdyn_analysisresultdetail: WebMappingRetrieve<msdyn_analysisresultdetail_Select,msdyn_analysisresultdetail_Expand,msdyn_analysisresultdetail_Filter,msdyn_analysisresultdetail_Fixed,msdyn_analysisresultdetail_Result,msdyn_analysisresultdetail_FormattedResult>;
  objectid_msdyn_dataflow: WebMappingRetrieve<msdyn_dataflow_Select,msdyn_dataflow_Expand,msdyn_dataflow_Filter,msdyn_dataflow_Fixed,msdyn_dataflow_Result,msdyn_dataflow_FormattedResult>;
  objectid_msdyn_federatedarticle: WebMappingRetrieve<msdyn_federatedarticle_Select,msdyn_federatedarticle_Expand,msdyn_federatedarticle_Filter,msdyn_federatedarticle_Fixed,msdyn_federatedarticle_Result,msdyn_federatedarticle_FormattedResult>;
  objectid_msdyn_federatedarticleincident: WebMappingRetrieve<msdyn_federatedarticleincident_Select,msdyn_federatedarticleincident_Expand,msdyn_federatedarticleincident_Filter,msdyn_federatedarticleincident_Fixed,msdyn_federatedarticleincident_Result,msdyn_federatedarticleincident_FormattedResult>;
  objectid_msdyn_helppage: WebMappingRetrieve<msdyn_helppage_Select,msdyn_helppage_Expand,msdyn_helppage_Filter,msdyn_helppage_Fixed,msdyn_helppage_Result,msdyn_helppage_FormattedResult>;
  objectid_msdyn_kalanguagesetting: WebMappingRetrieve<msdyn_kalanguagesetting_Select,msdyn_kalanguagesetting_Expand,msdyn_kalanguagesetting_Filter,msdyn_kalanguagesetting_Fixed,msdyn_kalanguagesetting_Result,msdyn_kalanguagesetting_FormattedResult>;
  objectid_msdyn_kmfederatedsearchconfig: WebMappingRetrieve<msdyn_kmfederatedsearchconfig_Select,msdyn_kmfederatedsearchconfig_Expand,msdyn_kmfederatedsearchconfig_Filter,msdyn_kmfederatedsearchconfig_Fixed,msdyn_kmfederatedsearchconfig_Result,msdyn_kmfederatedsearchconfig_FormattedResult>;
  objectid_msdyn_kmpersonalizationsetting: WebMappingRetrieve<msdyn_kmpersonalizationsetting_Select,msdyn_kmpersonalizationsetting_Expand,msdyn_kmpersonalizationsetting_Filter,msdyn_kmpersonalizationsetting_Fixed,msdyn_kmpersonalizationsetting_Result,msdyn_kmpersonalizationsetting_FormattedResult>;
  objectid_msdyn_knowledgearticleimage: WebMappingRetrieve<msdyn_knowledgearticleimage_Select,msdyn_knowledgearticleimage_Expand,msdyn_knowledgearticleimage_Filter,msdyn_knowledgearticleimage_Fixed,msdyn_knowledgearticleimage_Result,msdyn_knowledgearticleimage_FormattedResult>;
  objectid_msdyn_knowledgearticletemplate: WebMappingRetrieve<msdyn_knowledgearticletemplate_Select,msdyn_knowledgearticletemplate_Expand,msdyn_knowledgearticletemplate_Filter,msdyn_knowledgearticletemplate_Fixed,msdyn_knowledgearticletemplate_Result,msdyn_knowledgearticletemplate_FormattedResult>;
  objectid_msdyn_knowledgeinteractioninsight: WebMappingRetrieve<msdyn_knowledgeinteractioninsight_Select,msdyn_knowledgeinteractioninsight_Expand,msdyn_knowledgeinteractioninsight_Filter,msdyn_knowledgeinteractioninsight_Fixed,msdyn_knowledgeinteractioninsight_Result,msdyn_knowledgeinteractioninsight_FormattedResult>;
  objectid_msdyn_knowledgepersonalfilter: WebMappingRetrieve<msdyn_knowledgepersonalfilter_Select,msdyn_knowledgepersonalfilter_Expand,msdyn_knowledgepersonalfilter_Filter,msdyn_knowledgepersonalfilter_Fixed,msdyn_knowledgepersonalfilter_Result,msdyn_knowledgepersonalfilter_FormattedResult>;
  objectid_msdyn_knowledgesearchfilter: WebMappingRetrieve<msdyn_knowledgesearchfilter_Select,msdyn_knowledgesearchfilter_Expand,msdyn_knowledgesearchfilter_Filter,msdyn_knowledgesearchfilter_Fixed,msdyn_knowledgesearchfilter_Result,msdyn_knowledgesearchfilter_FormattedResult>;
  objectid_msdyn_knowledgesearchinsight: WebMappingRetrieve<msdyn_knowledgesearchinsight_Select,msdyn_knowledgesearchinsight_Expand,msdyn_knowledgesearchinsight_Filter,msdyn_knowledgesearchinsight_Fixed,msdyn_knowledgesearchinsight_Result,msdyn_knowledgesearchinsight_FormattedResult>;
  objectid_msdyn_pminferredtask: WebMappingRetrieve<msdyn_pminferredtask_Select,msdyn_pminferredtask_Expand,msdyn_pminferredtask_Filter,msdyn_pminferredtask_Fixed,msdyn_pminferredtask_Result,msdyn_pminferredtask_FormattedResult>;
  objectid_msdyn_pmrecording: WebMappingRetrieve<msdyn_pmrecording_Select,msdyn_pmrecording_Expand,msdyn_pmrecording_Filter,msdyn_pmrecording_Fixed,msdyn_pmrecording_Result,msdyn_pmrecording_FormattedResult>;
  objectid_msdyn_richtextfile: WebMappingRetrieve<msdyn_richtextfile_Select,msdyn_richtextfile_Expand,msdyn_richtextfile_Filter,msdyn_richtextfile_Fixed,msdyn_richtextfile_Result,msdyn_richtextfile_FormattedResult>;
  objectid_msdyn_serviceconfiguration: WebMappingRetrieve<msdyn_serviceconfiguration_Select,msdyn_serviceconfiguration_Expand,msdyn_serviceconfiguration_Filter,msdyn_serviceconfiguration_Fixed,msdyn_serviceconfiguration_Result,msdyn_serviceconfiguration_FormattedResult>;
  objectid_msdyn_slakpi: WebMappingRetrieve<msdyn_slakpi_Select,msdyn_slakpi_Expand,msdyn_slakpi_Filter,msdyn_slakpi_Fixed,msdyn_slakpi_Result,msdyn_slakpi_FormattedResult>;
  objectid_msdyn_solutionhealthrule: WebMappingRetrieve<msdyn_solutionhealthrule_Select,msdyn_solutionhealthrule_Expand,msdyn_solutionhealthrule_Filter,msdyn_solutionhealthrule_Fixed,msdyn_solutionhealthrule_Result,msdyn_solutionhealthrule_FormattedResult>;
  objectid_msdyn_solutionhealthruleargument: WebMappingRetrieve<msdyn_solutionhealthruleargument_Select,msdyn_solutionhealthruleargument_Expand,msdyn_solutionhealthruleargument_Filter,msdyn_solutionhealthruleargument_Fixed,msdyn_solutionhealthruleargument_Result,msdyn_solutionhealthruleargument_FormattedResult>;
  objectid_msdyn_solutionhealthruleset: WebMappingRetrieve<msdyn_solutionhealthruleset_Select,msdyn_solutionhealthruleset_Expand,msdyn_solutionhealthruleset_Filter,msdyn_solutionhealthruleset_Fixed,msdyn_solutionhealthruleset_Result,msdyn_solutionhealthruleset_FormattedResult>;
  objectid_msdyn_tour: WebMappingRetrieve<msdyn_tour_Select,msdyn_tour_Expand,msdyn_tour_Filter,msdyn_tour_Fixed,msdyn_tour_Result,msdyn_tour_FormattedResult>;
  objectid_msdynce_botcontent: WebMappingRetrieve<msdynce_botcontent_Select,msdynce_botcontent_Expand,msdynce_botcontent_Filter,msdynce_botcontent_Fixed,msdynce_botcontent_Result,msdynce_botcontent_FormattedResult>;
  objectid_organizationdatasyncsubscription: WebMappingRetrieve<organizationdatasyncsubscription_Select,organizationdatasyncsubscription_Expand,organizationdatasyncsubscription_Filter,organizationdatasyncsubscription_Fixed,organizationdatasyncsubscription_Result,organizationdatasyncsubscription_FormattedResult>;
  objectid_organizationdatasyncsubscriptionentity: WebMappingRetrieve<organizationdatasyncsubscriptionentity_Select,organizationdatasyncsubscriptionentity_Expand,organizationdatasyncsubscriptionentity_Filter,organizationdatasyncsubscriptionentity_Fixed,organizationdatasyncsubscriptionentity_Result,organizationdatasyncsubscriptionentity_FormattedResult>;
  objectid_organizationsetting: WebMappingRetrieve<OrganizationSetting_Select,OrganizationSetting_Expand,OrganizationSetting_Filter,OrganizationSetting_Fixed,OrganizationSetting_Result,OrganizationSetting_FormattedResult>;
  objectid_package: WebMappingRetrieve<package_Select,package_Expand,package_Filter,package_Fixed,package_Result,package_FormattedResult>;
  objectid_pc_bankaccount: WebMappingRetrieve<pc_BankAccount_Select,pc_BankAccount_Expand,pc_BankAccount_Filter,pc_BankAccount_Fixed,pc_BankAccount_Result,pc_BankAccount_FormattedResult>;
  objectid_pc_participation: WebMappingRetrieve<pc_Participation_Select,pc_Participation_Expand,pc_Participation_Filter,pc_Participation_Fixed,pc_Participation_Result,pc_Participation_FormattedResult>;
  objectid_pc_participationfeeexemption: WebMappingRetrieve<pc_ParticipationFeeExemption_Select,pc_ParticipationFeeExemption_Expand,pc_ParticipationFeeExemption_Filter,pc_ParticipationFeeExemption_Fixed,pc_ParticipationFeeExemption_Result,pc_ParticipationFeeExemption_FormattedResult>;
  objectid_pc_payment: WebMappingRetrieve<pc_Payment_Select,pc_Payment_Expand,pc_Payment_Filter,pc_Payment_Fixed,pc_Payment_Result,pc_Payment_FormattedResult>;
  objectid_pc_scheduledjob: WebMappingRetrieve<pc_ScheduledJob_Select,pc_ScheduledJob_Expand,pc_ScheduledJob_Filter,pc_ScheduledJob_Fixed,pc_ScheduledJob_Result,pc_ScheduledJob_FormattedResult>;
  objectid_pc_settings: WebMappingRetrieve<pc_Settings_Select,pc_Settings_Expand,pc_Settings_Filter,pc_Settings_Fixed,pc_Settings_Result,pc_Settings_FormattedResult>;
  objectid_pc_transaction: WebMappingRetrieve<pc_Transaction_Select,pc_Transaction_Expand,pc_Transaction_Filter,pc_Transaction_Fixed,pc_Transaction_Result,pc_Transaction_FormattedResult>;
  objectid_pdfsetting: WebMappingRetrieve<PDFSetting_Select,PDFSetting_Expand,PDFSetting_Filter,PDFSetting_Fixed,PDFSetting_Result,PDFSetting_FormattedResult>;
  objectid_phonecall: WebMappingRetrieve<PhoneCall_Select,PhoneCall_Expand,PhoneCall_Filter,PhoneCall_Fixed,PhoneCall_Result,PhoneCall_FormattedResult>;
  objectid_pluginpackage: WebMappingRetrieve<pluginpackage_Select,pluginpackage_Expand,pluginpackage_Filter,pluginpackage_Fixed,pluginpackage_Result,pluginpackage_FormattedResult>;
  objectid_position: WebMappingRetrieve<Position_Select,Position_Expand,Position_Filter,Position_Fixed,Position_Result,Position_FormattedResult>;
  objectid_processstageparameter: WebMappingRetrieve<processstageparameter_Select,processstageparameter_Expand,processstageparameter_Filter,processstageparameter_Fixed,processstageparameter_Result,processstageparameter_FormattedResult>;
  objectid_provisionlanguageforuser: WebMappingRetrieve<ProvisionLanguageForUser_Select,ProvisionLanguageForUser_Expand,ProvisionLanguageForUser_Filter,ProvisionLanguageForUser_Fixed,ProvisionLanguageForUser_Result,ProvisionLanguageForUser_FormattedResult>;
  objectid_queue: WebMappingRetrieve<Queue_Select,Queue_Expand,Queue_Filter,Queue_Fixed,Queue_Result,Queue_FormattedResult>;
  objectid_queueitem: WebMappingRetrieve<QueueItem_Select,QueueItem_Expand,QueueItem_Filter,QueueItem_Fixed,QueueItem_Result,QueueItem_FormattedResult>;
  objectid_recurringappointmentmaster: WebMappingRetrieve<RecurringAppointmentMaster_Select,RecurringAppointmentMaster_Expand,RecurringAppointmentMaster_Filter,RecurringAppointmentMaster_Fixed,RecurringAppointmentMaster_Result,RecurringAppointmentMaster_FormattedResult>;
  objectid_relationshipattribute: WebMappingRetrieve<RelationshipAttribute_Select,RelationshipAttribute_Expand,RelationshipAttribute_Filter,RelationshipAttribute_Fixed,RelationshipAttribute_Result,RelationshipAttribute_FormattedResult>;
  objectid_reportcategory: WebMappingRetrieve<ReportCategory_Select,ReportCategory_Expand,ReportCategory_Filter,ReportCategory_Fixed,ReportCategory_Result,ReportCategory_FormattedResult>;
  objectid_revokeinheritedaccessrecordstracker: WebMappingRetrieve<revokeinheritedaccessrecordstracker_Select,revokeinheritedaccessrecordstracker_Expand,revokeinheritedaccessrecordstracker_Filter,revokeinheritedaccessrecordstracker_Fixed,revokeinheritedaccessrecordstracker_Result,revokeinheritedaccessrecordstracker_FormattedResult>;
  objectid_serviceplan: WebMappingRetrieve<ServicePlan_Select,ServicePlan_Expand,ServicePlan_Filter,ServicePlan_Fixed,ServicePlan_Result,ServicePlan_FormattedResult>;
  objectid_serviceplanmapping: WebMappingRetrieve<ServicePlanMapping_Select,ServicePlanMapping_Expand,ServicePlanMapping_Filter,ServicePlanMapping_Fixed,ServicePlanMapping_Result,ServicePlanMapping_FormattedResult>;
  objectid_settingdefinition: WebMappingRetrieve<SettingDefinition_Select,SettingDefinition_Expand,SettingDefinition_Filter,SettingDefinition_Fixed,SettingDefinition_Result,SettingDefinition_FormattedResult>;
  objectid_sharepointdocumentlocation: WebMappingRetrieve<SharePointDocumentLocation_Select,SharePointDocumentLocation_Expand,SharePointDocumentLocation_Filter,SharePointDocumentLocation_Fixed,SharePointDocumentLocation_Result,SharePointDocumentLocation_FormattedResult>;
  objectid_sharepointsite: WebMappingRetrieve<SharePointSite_Select,SharePointSite_Expand,SharePointSite_Filter,SharePointSite_Fixed,SharePointSite_Result,SharePointSite_FormattedResult>;
  objectid_socialactivity: WebMappingRetrieve<SocialActivity_Select,SocialActivity_Expand,SocialActivity_Filter,SocialActivity_Fixed,SocialActivity_Result,SocialActivity_FormattedResult>;
  objectid_socialprofile: WebMappingRetrieve<SocialProfile_Select,SocialProfile_Expand,SocialProfile_Filter,SocialProfile_Fixed,SocialProfile_Result,SocialProfile_FormattedResult>;
  objectid_solutioncomponentattributeconfiguration: WebMappingRetrieve<solutioncomponentattributeconfiguration_Select,solutioncomponentattributeconfiguration_Expand,solutioncomponentattributeconfiguration_Filter,solutioncomponentattributeconfiguration_Fixed,solutioncomponentattributeconfiguration_Result,solutioncomponentattributeconfiguration_FormattedResult>;
  objectid_solutioncomponentbatchconfiguration: WebMappingRetrieve<solutioncomponentbatchconfiguration_Select,solutioncomponentbatchconfiguration_Expand,solutioncomponentbatchconfiguration_Filter,solutioncomponentbatchconfiguration_Fixed,solutioncomponentbatchconfiguration_Result,solutioncomponentbatchconfiguration_FormattedResult>;
  objectid_solutioncomponentconfiguration: WebMappingRetrieve<solutioncomponentconfiguration_Select,solutioncomponentconfiguration_Expand,solutioncomponentconfiguration_Filter,solutioncomponentconfiguration_Fixed,solutioncomponentconfiguration_Result,solutioncomponentconfiguration_FormattedResult>;
  objectid_solutioncomponentrelationshipconfiguration: WebMappingRetrieve<solutioncomponentrelationshipconfiguration_Select,solutioncomponentrelationshipconfiguration_Expand,solutioncomponentrelationshipconfiguration_Filter,solutioncomponentrelationshipconfiguration_Fixed,solutioncomponentrelationshipconfiguration_Result,solutioncomponentrelationshipconfiguration_FormattedResult>;
  objectid_stagesolutionupload: WebMappingRetrieve<StageSolutionUpload_Select,StageSolutionUpload_Expand,StageSolutionUpload_Filter,StageSolutionUpload_Fixed,StageSolutionUpload_Result,StageSolutionUpload_FormattedResult>;
  objectid_systemuser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  objectid_systemuserauthorizationchangetracker: WebMappingRetrieve<SystemUserAuthorizationChangeTracker_Select,SystemUserAuthorizationChangeTracker_Expand,SystemUserAuthorizationChangeTracker_Filter,SystemUserAuthorizationChangeTracker_Fixed,SystemUserAuthorizationChangeTracker_Result,SystemUserAuthorizationChangeTracker_FormattedResult>;
  objectid_task: WebMappingRetrieve<Task_Select,Task_Expand,Task_Filter,Task_Fixed,Task_Result,Task_FormattedResult>;
  objectid_team: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  objectid_teammobileofflineprofilemembership: WebMappingRetrieve<teammobileofflineprofilemembership_Select,teammobileofflineprofilemembership_Expand,teammobileofflineprofilemembership_Filter,teammobileofflineprofilemembership_Fixed,teammobileofflineprofilemembership_Result,teammobileofflineprofilemembership_FormattedResult>;
  objectid_territory: WebMappingRetrieve<Territory_Select,Territory_Expand,Territory_Filter,Territory_Fixed,Territory_Result,Territory_FormattedResult>;
  objectid_usermobileofflineprofilemembership: WebMappingRetrieve<usermobileofflineprofilemembership_Select,usermobileofflineprofilemembership_Expand,usermobileofflineprofilemembership_Filter,usermobileofflineprofilemembership_Fixed,usermobileofflineprofilemembership_Result,usermobileofflineprofilemembership_FormattedResult>;
  objectid_virtualentitymetadata: WebMappingRetrieve<VirtualEntityMetadata_Select,VirtualEntityMetadata_Expand,VirtualEntityMetadata_Filter,VirtualEntityMetadata_Fixed,VirtualEntityMetadata_Result,VirtualEntityMetadata_FormattedResult>;
  objectid_workflowbinary: WebMappingRetrieve<workflowbinary_Select,workflowbinary_Expand,workflowbinary_Filter,workflowbinary_Fixed,workflowbinary_Result,workflowbinary_FormattedResult>;
  organizationid: WebMappingRetrieve<Organization_Select,Organization_Expand,Organization_Filter,Organization_Fixed,Organization_Result,Organization_FormattedResult>;
  principalid_systemuser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  principalid_team: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
}
interface PrincipalObjectAttributeAccess_RelatedMany {
  userentityinstancedata_principalobjectattributeaccess: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
}
interface WebEntitiesRetrieve {
  principalobjectattributeaccessset: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
}
interface WebEntitiesRelated {
  principalobjectattributeaccessset: WebMappingRelated<PrincipalObjectAttributeAccess_RelatedOne,PrincipalObjectAttributeAccess_RelatedMany>;
}
interface WebEntitiesCUDA {
  principalobjectattributeaccessset: WebMappingCUDA<PrincipalObjectAttributeAccess_Create,PrincipalObjectAttributeAccess_Update,PrincipalObjectAttributeAccess_Select>;
}
