interface Team_Base extends WebEntity {
  azureactivedirectoryobjectid?: string | null;
  createdon?: Date | null;
  description?: string | null;
  emailaddress?: string | null;
  exchangerate?: number | null;
  importsequencenumber?: number | null;
  isdefault?: boolean | null;
  membershiptype?: team_membershiptype | null;
  modifiedon?: Date | null;
  name?: string | null;
  organizationid?: string | null;
  overriddencreatedon?: Date | null;
  processid?: string | null;
  stageid?: string | null;
  systemmanaged?: boolean | null;
  teamid?: string | null;
  teamtype?: team_type | null;
  traversedpath?: string | null;
  versionnumber?: number | null;
}
interface Team_Relationships {
  ImportFile_Team?: ImportFile_Result[] | null;
  OwningTeam_postfollows?: PostFollow_Result[] | null;
  Team_AsyncOperations?: AsyncOperation_Result[] | null;
  Team_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  Team_DuplicateBaseRecord?: DuplicateRecord_Result[] | null;
  Team_DuplicateMatchingRecord?: DuplicateRecord_Result[] | null;
  Team_ProcessSessions?: ProcessSession_Result[] | null;
  Team_SyncErrors?: SyncError_Result[] | null;
  associatedteamtemplateid?: TeamTemplate_Result | null;
  organizationid_organization?: Organization_Result | null;
  regardingobjectid_knowledgearticle?: KnowledgeArticle_Result | null;
  stageid_processstage?: ProcessStage_Result | null;
  team_DuplicateRules?: DuplicateRule_Result[] | null;
  team_ImportData?: ImportData_Result[] | null;
  team_ImportFiles?: ImportFile_Result[] | null;
  team_ImportLogs?: ImportLog_Result[] | null;
  team_ImportMaps?: ImportMap_Result[] | null;
  team_Imports?: Import_Result[] | null;
  team_PostRegardings?: PostRegarding_Result[] | null;
  team_PostRoles?: PostRole_Result[] | null;
  team_SyncError?: SyncError_Result[] | null;
  team_accounts?: Account_Result[] | null;
  team_actioncardusersettings?: ActionCardUserSettings_Result[] | null;
  team_activity?: ActivityPointer_Result[] | null;
  team_activityfileattachment?: activityfileattachment_Result[] | null;
  team_annotations?: Annotation_Result[] | null;
  team_appnotification?: appnotification_Result[] | null;
  team_appointment?: Appointment_Result[] | null;
  team_asyncoperation?: AsyncOperation_Result[] | null;
  team_bot?: bot_Result[] | null;
  team_botcomponent?: botcomponent_Result[] | null;
  team_canvasappextendedmetadata?: CanvasAppExtendedMetadata_Result[] | null;
  team_channelaccessprofile?: ChannelAccessProfile_Result[] | null;
  team_connectionreference?: connectionreference_Result[] | null;
  team_connections1?: Connection_Result[] | null;
  team_connections2?: Connection_Result[] | null;
  team_connector?: connector_Result[] | null;
  team_contacts?: Contact_Result[] | null;
  team_conversationtranscript?: conversationtranscript_Result[] | null;
  team_convertrule?: ConvertRule_Result[] | null;
  team_customapi?: CustomAPI_Result[] | null;
  team_customapirequestparameter?: CustomAPIRequestParameter_Result[] | null;
  team_customapiresponseproperty?: CustomAPIResponseProperty_Result[] | null;
  team_customer_relationship?: CustomerRelationship_Result[] | null;
  team_datalakefolder?: datalakefolder_Result[] | null;
  team_datalakefolderpermission?: datalakefolderpermission_Result[] | null;
  team_email?: Email_Result[] | null;
  team_email_templates?: Template_Result[] | null;
  team_emailserverprofile?: EmailServerProfile_Result[] | null;
  team_environmentvariabledefinition?: EnvironmentVariableDefinition_Result[] | null;
  team_environmentvariablevalue?: EnvironmentVariableValue_Result[] | null;
  team_exchangesyncidmapping?: ExchangeSyncIdMapping_Result[] | null;
  team_exportsolutionupload?: ExportSolutionUpload_Result[] | null;
  team_externalparty?: ExternalParty_Result[] | null;
  team_fax?: Fax_Result[] | null;
  team_featurecontrolsetting?: featurecontrolsetting_Result[] | null;
  team_flowmachine?: flowmachine_Result[] | null;
  team_flowmachinegroup?: flowmachinegroup_Result[] | null;
  team_flowsession?: flowsession_Result[] | null;
  team_goal?: Goal_Result[] | null;
  team_goal_goalowner?: Goal_Result[] | null;
  team_goalrollupquery?: GoalRollupQuery_Result[] | null;
  team_keyvaultreference?: KeyVaultReference_Result[] | null;
  team_knowledgearticle?: KnowledgeArticle_Result[] | null;
  team_letter?: Letter_Result[] | null;
  team_mailbox?: Mailbox_Result[] | null;
  team_mailboxtrackingcategory?: MailboxTrackingCategory_Result[] | null;
  team_mailboxtrackingfolder?: MailboxTrackingFolder_Result[] | null;
  team_managedidentity?: ManagedIdentity_Result[] | null;
  team_msdyn_aibdataset?: msdyn_AIBDataset_Result[] | null;
  team_msdyn_aibdatasetfile?: msdyn_AIBDatasetFile_Result[] | null;
  team_msdyn_aibdatasetrecord?: msdyn_AIBDatasetRecord_Result[] | null;
  team_msdyn_aibdatasetscontainer?: msdyn_AIBDatasetsContainer_Result[] | null;
  team_msdyn_aibfile?: msdyn_AIBFile_Result[] | null;
  team_msdyn_aibfileattacheddata?: msdyn_AIBFileAttachedData_Result[] | null;
  team_msdyn_aiconfiguration?: msdyn_AIConfiguration_Result[] | null;
  team_msdyn_aifptrainingdocument?: msdyn_AIFpTrainingDocument_Result[] | null;
  team_msdyn_aimodel?: msdyn_AIModel_Result[] | null;
  team_msdyn_aiodimage?: msdyn_AIOdImage_Result[] | null;
  team_msdyn_aiodlabel?: msdyn_AIOdLabel_Result[] | null;
  team_msdyn_aiodtrainingboundingbox?: msdyn_AIOdTrainingBoundingBox_Result[] | null;
  team_msdyn_aiodtrainingimage?: msdyn_AIOdTrainingImage_Result[] | null;
  team_msdyn_aitemplate?: msdyn_AITemplate_Result[] | null;
  team_msdyn_analysiscomponent?: msdyn_analysiscomponent_Result[] | null;
  team_msdyn_analysisjob?: msdyn_analysisjob_Result[] | null;
  team_msdyn_analysisresult?: msdyn_analysisresult_Result[] | null;
  team_msdyn_analysisresultdetail?: msdyn_analysisresultdetail_Result[] | null;
  team_msdyn_dataflow?: msdyn_dataflow_Result[] | null;
  team_msdyn_federatedarticle?: msdyn_federatedarticle_Result[] | null;
  team_msdyn_kalanguagesetting?: msdyn_kalanguagesetting_Result[] | null;
  team_msdyn_kmfederatedsearchconfig?: msdyn_kmfederatedsearchconfig_Result[] | null;
  team_msdyn_knowledgearticleimage?: msdyn_knowledgearticleimage_Result[] | null;
  team_msdyn_knowledgearticletemplate?: msdyn_knowledgearticletemplate_Result[] | null;
  team_msdyn_knowledgeinteractioninsight?: msdyn_knowledgeinteractioninsight_Result[] | null;
  team_msdyn_knowledgepersonalfilter?: msdyn_knowledgepersonalfilter_Result[] | null;
  team_msdyn_knowledgesearchfilter?: msdyn_knowledgesearchfilter_Result[] | null;
  team_msdyn_knowledgesearchinsight?: msdyn_knowledgesearchinsight_Result[] | null;
  team_msdyn_pminferredtask?: msdyn_pminferredtask_Result[] | null;
  team_msdyn_pmrecording?: msdyn_pmrecording_Result[] | null;
  team_msdyn_richtextfile?: msdyn_richtextfile_Result[] | null;
  team_msdyn_serviceconfiguration?: msdyn_serviceconfiguration_Result[] | null;
  team_msdyn_slakpi?: msdyn_slakpi_Result[] | null;
  team_msdyn_solutionhealthrule?: msdyn_solutionhealthrule_Result[] | null;
  team_msdyn_solutionhealthruleargument?: msdyn_solutionhealthruleargument_Result[] | null;
  team_msdynce_botcontent?: msdynce_botcontent_Result[] | null;
  team_new_interactionforemail?: InteractionForEmail_Result[] | null;
  team_pdfsetting?: PDFSetting_Result[] | null;
  team_phonecall?: PhoneCall_Result[] | null;
  team_principalobjectattributeaccess?: PrincipalObjectAttributeAccess_Result[] | null;
  team_principalobjectattributeaccess_principalid?: PrincipalObjectAttributeAccess_Result[] | null;
  team_processsession?: ProcessSession_Result[] | null;
  team_processstageparameter?: processstageparameter_Result[] | null;
  team_profilerule?: ChannelAccessProfileRule_Result[] | null;
  team_queueitembase_workerid?: QueueItem_Result[] | null;
  team_recurringappointmentmaster?: RecurringAppointmentMaster_Result[] | null;
  team_revokeinheritedaccessrecordstracker?: revokeinheritedaccessrecordstracker_Result[] | null;
  team_routingrule?: RoutingRule_Result[] | null;
  team_routingruleitem?: RoutingRuleItem_Result[] | null;
  team_sharepointdocumentlocation?: SharePointDocumentLocation_Result[] | null;
  team_sharepointsite?: SharePointSite_Result[] | null;
  team_slaBase?: SLA_Result[] | null;
  team_socialactivity?: SocialActivity_Result[] | null;
  team_solutioncomponentbatchconfiguration?: solutioncomponentbatchconfiguration_Result[] | null;
  team_stagesolutionupload?: StageSolutionUpload_Result[] | null;
  team_task?: Task_Result[] | null;
  team_teammobileofflineprofilemembership_TeamId?: teammobileofflineprofilemembership_Result[] | null;
  team_userentityinstancedata?: UserEntityInstanceData_Result[] | null;
  team_userentityuisettings?: UserEntityUISettings_Result[] | null;
  team_userform?: UserForm_Result[] | null;
  team_userquery?: UserQuery_Result[] | null;
  team_userqueryvisualizations?: UserQueryVisualization_Result[] | null;
  team_workflow?: Workflow_Result[] | null;
  team_workflowbinary?: workflowbinary_Result[] | null;
  team_workflowlog?: WorkflowLog_Result[] | null;
  teammembership_association?: SystemUser_Result[] | null;
  teamprofiles_association?: FieldSecurityProfile_Result[] | null;
  teamroles_association?: Role_Result[] | null;
  teamsyncattributemappingprofiles_association?: SyncAttributeMappingProfile_Result[] | null;
  userentityinstancedata_team?: UserEntityInstanceData_Result[] | null;
}
interface Team extends Team_Base, Team_Relationships {
  administratorid_bind$systemusers?: string | null;
  businessunitid_bind$businessunits?: string | null;
  queueid_bind$queues?: string | null;
  stageid_processstage_bind$processstages?: string | null;
  transactioncurrencyid_bind$transactioncurrencies?: string | null;
}
interface Team_Create extends Team {
  associatedteamtemplateid_bind$teamtemplates?: string | null;
  regardingobjectid_knowledgearticle_bind$knowledgearticles?: string | null;
}
interface Team_Update extends Team {
}
interface Team_Select {
  administratorid_guid: WebAttribute<Team_Select, { administratorid_guid: string | null }, { administratorid_formatted?: string }>;
  azureactivedirectoryobjectid: WebAttribute<Team_Select, { azureactivedirectoryobjectid: string | null }, {  }>;
  businessunitid_guid: WebAttribute<Team_Select, { businessunitid_guid: string | null }, { businessunitid_formatted?: string }>;
  createdby_guid: WebAttribute<Team_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<Team_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<Team_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  description: WebAttribute<Team_Select, { description: string | null }, {  }>;
  emailaddress: WebAttribute<Team_Select, { emailaddress: string | null }, {  }>;
  exchangerate: WebAttribute<Team_Select, { exchangerate: number | null }, {  }>;
  importsequencenumber: WebAttribute<Team_Select, { importsequencenumber: number | null }, {  }>;
  isdefault: WebAttribute<Team_Select, { isdefault: boolean | null }, {  }>;
  membershiptype: WebAttribute<Team_Select, { membershiptype: team_membershiptype | null }, { membershiptype_formatted?: string }>;
  modifiedby_guid: WebAttribute<Team_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<Team_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<Team_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  name: WebAttribute<Team_Select, { name: string | null }, {  }>;
  organizationid: WebAttribute<Team_Select, { organizationid: string | null }, {  }>;
  overriddencreatedon: WebAttribute<Team_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  processid: WebAttribute<Team_Select, { processid: string | null }, {  }>;
  queueid_guid: WebAttribute<Team_Select, { queueid_guid: string | null }, { queueid_formatted?: string }>;
  regardingobjectid_guid: WebAttribute<Team_Select, { regardingobjectid_guid: string | null }, { regardingobjectid_formatted?: string }>;
  stageid: WebAttribute<Team_Select, { stageid: string | null }, {  }>;
  systemmanaged: WebAttribute<Team_Select, { systemmanaged: boolean | null }, {  }>;
  teamid: WebAttribute<Team_Select, { teamid: string | null }, {  }>;
  teamtemplateid_guid: WebAttribute<Team_Select, { teamtemplateid_guid: string | null }, { teamtemplateid_formatted?: string }>;
  teamtype: WebAttribute<Team_Select, { teamtype: team_type | null }, { teamtype_formatted?: string }>;
  transactioncurrencyid_guid: WebAttribute<Team_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  traversedpath: WebAttribute<Team_Select, { traversedpath: string | null }, {  }>;
  versionnumber: WebAttribute<Team_Select, { versionnumber: number | null }, {  }>;
}
interface Team_Filter {
  administratorid_guid: XQW.Guid;
  azureactivedirectoryobjectid: XQW.Guid;
  businessunitid_guid: XQW.Guid;
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  description: string;
  emailaddress: string;
  exchangerate: any;
  importsequencenumber: number;
  isdefault: boolean;
  membershiptype: team_membershiptype;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  name: string;
  organizationid: XQW.Guid;
  overriddencreatedon: Date;
  processid: XQW.Guid;
  queueid_guid: XQW.Guid;
  regardingobjectid_guid: XQW.Guid;
  stageid: XQW.Guid;
  systemmanaged: boolean;
  teamid: XQW.Guid;
  teamtemplateid_guid: XQW.Guid;
  teamtype: team_type;
  transactioncurrencyid_guid: XQW.Guid;
  traversedpath: string;
  versionnumber: number;
}
interface Team_Expand {
  ImportFile_Team: WebExpand<Team_Expand, ImportFile_Select, ImportFile_Filter, { ImportFile_Team: ImportFile_Result[] }>;
  OwningTeam_postfollows: WebExpand<Team_Expand, PostFollow_Select, PostFollow_Filter, { OwningTeam_postfollows: PostFollow_Result[] }>;
  Team_AsyncOperations: WebExpand<Team_Expand, AsyncOperation_Select, AsyncOperation_Filter, { Team_AsyncOperations: AsyncOperation_Result[] }>;
  Team_BulkDeleteFailures: WebExpand<Team_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { Team_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  Team_DuplicateBaseRecord: WebExpand<Team_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { Team_DuplicateBaseRecord: DuplicateRecord_Result[] }>;
  Team_DuplicateMatchingRecord: WebExpand<Team_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { Team_DuplicateMatchingRecord: DuplicateRecord_Result[] }>;
  Team_ProcessSessions: WebExpand<Team_Expand, ProcessSession_Select, ProcessSession_Filter, { Team_ProcessSessions: ProcessSession_Result[] }>;
  Team_SyncErrors: WebExpand<Team_Expand, SyncError_Select, SyncError_Filter, { Team_SyncErrors: SyncError_Result[] }>;
  administratorid: WebExpand<Team_Expand, SystemUser_Select, SystemUser_Filter, { administratorid: SystemUser_Result }>;
  associatedteamtemplateid: WebExpand<Team_Expand, TeamTemplate_Select, TeamTemplate_Filter, { associatedteamtemplateid: TeamTemplate_Result }>;
  businessunitid: WebExpand<Team_Expand, BusinessUnit_Select, BusinessUnit_Filter, { businessunitid: BusinessUnit_Result }>;
  createdby: WebExpand<Team_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<Team_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  modifiedby: WebExpand<Team_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<Team_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  organizationid_organization: WebExpand<Team_Expand, Organization_Select, Organization_Filter, { organizationid_organization: Organization_Result }>;
  queueid: WebExpand<Team_Expand, Queue_Select, Queue_Filter, { queueid: Queue_Result }>;
  regardingobjectid_knowledgearticle: WebExpand<Team_Expand, KnowledgeArticle_Select, KnowledgeArticle_Filter, { regardingobjectid_knowledgearticle: KnowledgeArticle_Result }>;
  stageid_processstage: WebExpand<Team_Expand, ProcessStage_Select, ProcessStage_Filter, { stageid_processstage: ProcessStage_Result }>;
  team_DuplicateRules: WebExpand<Team_Expand, DuplicateRule_Select, DuplicateRule_Filter, { team_DuplicateRules: DuplicateRule_Result[] }>;
  team_ImportData: WebExpand<Team_Expand, ImportData_Select, ImportData_Filter, { team_ImportData: ImportData_Result[] }>;
  team_ImportFiles: WebExpand<Team_Expand, ImportFile_Select, ImportFile_Filter, { team_ImportFiles: ImportFile_Result[] }>;
  team_ImportLogs: WebExpand<Team_Expand, ImportLog_Select, ImportLog_Filter, { team_ImportLogs: ImportLog_Result[] }>;
  team_ImportMaps: WebExpand<Team_Expand, ImportMap_Select, ImportMap_Filter, { team_ImportMaps: ImportMap_Result[] }>;
  team_Imports: WebExpand<Team_Expand, Import_Select, Import_Filter, { team_Imports: Import_Result[] }>;
  team_PostRegardings: WebExpand<Team_Expand, PostRegarding_Select, PostRegarding_Filter, { team_PostRegardings: PostRegarding_Result[] }>;
  team_PostRoles: WebExpand<Team_Expand, PostRole_Select, PostRole_Filter, { team_PostRoles: PostRole_Result[] }>;
  team_SyncError: WebExpand<Team_Expand, SyncError_Select, SyncError_Filter, { team_SyncError: SyncError_Result[] }>;
  team_accounts: WebExpand<Team_Expand, Account_Select, Account_Filter, { team_accounts: Account_Result[] }>;
  team_actioncardusersettings: WebExpand<Team_Expand, ActionCardUserSettings_Select, ActionCardUserSettings_Filter, { team_actioncardusersettings: ActionCardUserSettings_Result[] }>;
  team_activity: WebExpand<Team_Expand, ActivityPointer_Select, ActivityPointer_Filter, { team_activity: ActivityPointer_Result[] }>;
  team_activityfileattachment: WebExpand<Team_Expand, activityfileattachment_Select, activityfileattachment_Filter, { team_activityfileattachment: activityfileattachment_Result[] }>;
  team_annotations: WebExpand<Team_Expand, Annotation_Select, Annotation_Filter, { team_annotations: Annotation_Result[] }>;
  team_appnotification: WebExpand<Team_Expand, appnotification_Select, appnotification_Filter, { team_appnotification: appnotification_Result[] }>;
  team_appointment: WebExpand<Team_Expand, Appointment_Select, Appointment_Filter, { team_appointment: Appointment_Result[] }>;
  team_asyncoperation: WebExpand<Team_Expand, AsyncOperation_Select, AsyncOperation_Filter, { team_asyncoperation: AsyncOperation_Result[] }>;
  team_bot: WebExpand<Team_Expand, bot_Select, bot_Filter, { team_bot: bot_Result[] }>;
  team_botcomponent: WebExpand<Team_Expand, botcomponent_Select, botcomponent_Filter, { team_botcomponent: botcomponent_Result[] }>;
  team_canvasappextendedmetadata: WebExpand<Team_Expand, CanvasAppExtendedMetadata_Select, CanvasAppExtendedMetadata_Filter, { team_canvasappextendedmetadata: CanvasAppExtendedMetadata_Result[] }>;
  team_channelaccessprofile: WebExpand<Team_Expand, ChannelAccessProfile_Select, ChannelAccessProfile_Filter, { team_channelaccessprofile: ChannelAccessProfile_Result[] }>;
  team_connectionreference: WebExpand<Team_Expand, connectionreference_Select, connectionreference_Filter, { team_connectionreference: connectionreference_Result[] }>;
  team_connections1: WebExpand<Team_Expand, Connection_Select, Connection_Filter, { team_connections1: Connection_Result[] }>;
  team_connections2: WebExpand<Team_Expand, Connection_Select, Connection_Filter, { team_connections2: Connection_Result[] }>;
  team_connector: WebExpand<Team_Expand, connector_Select, connector_Filter, { team_connector: connector_Result[] }>;
  team_contacts: WebExpand<Team_Expand, Contact_Select, Contact_Filter, { team_contacts: Contact_Result[] }>;
  team_conversationtranscript: WebExpand<Team_Expand, conversationtranscript_Select, conversationtranscript_Filter, { team_conversationtranscript: conversationtranscript_Result[] }>;
  team_convertrule: WebExpand<Team_Expand, ConvertRule_Select, ConvertRule_Filter, { team_convertrule: ConvertRule_Result[] }>;
  team_customapi: WebExpand<Team_Expand, CustomAPI_Select, CustomAPI_Filter, { team_customapi: CustomAPI_Result[] }>;
  team_customapirequestparameter: WebExpand<Team_Expand, CustomAPIRequestParameter_Select, CustomAPIRequestParameter_Filter, { team_customapirequestparameter: CustomAPIRequestParameter_Result[] }>;
  team_customapiresponseproperty: WebExpand<Team_Expand, CustomAPIResponseProperty_Select, CustomAPIResponseProperty_Filter, { team_customapiresponseproperty: CustomAPIResponseProperty_Result[] }>;
  team_customer_relationship: WebExpand<Team_Expand, CustomerRelationship_Select, CustomerRelationship_Filter, { team_customer_relationship: CustomerRelationship_Result[] }>;
  team_datalakefolder: WebExpand<Team_Expand, datalakefolder_Select, datalakefolder_Filter, { team_datalakefolder: datalakefolder_Result[] }>;
  team_datalakefolderpermission: WebExpand<Team_Expand, datalakefolderpermission_Select, datalakefolderpermission_Filter, { team_datalakefolderpermission: datalakefolderpermission_Result[] }>;
  team_email: WebExpand<Team_Expand, Email_Select, Email_Filter, { team_email: Email_Result[] }>;
  team_email_templates: WebExpand<Team_Expand, Template_Select, Template_Filter, { team_email_templates: Template_Result[] }>;
  team_emailserverprofile: WebExpand<Team_Expand, EmailServerProfile_Select, EmailServerProfile_Filter, { team_emailserverprofile: EmailServerProfile_Result[] }>;
  team_environmentvariabledefinition: WebExpand<Team_Expand, EnvironmentVariableDefinition_Select, EnvironmentVariableDefinition_Filter, { team_environmentvariabledefinition: EnvironmentVariableDefinition_Result[] }>;
  team_environmentvariablevalue: WebExpand<Team_Expand, EnvironmentVariableValue_Select, EnvironmentVariableValue_Filter, { team_environmentvariablevalue: EnvironmentVariableValue_Result[] }>;
  team_exchangesyncidmapping: WebExpand<Team_Expand, ExchangeSyncIdMapping_Select, ExchangeSyncIdMapping_Filter, { team_exchangesyncidmapping: ExchangeSyncIdMapping_Result[] }>;
  team_exportsolutionupload: WebExpand<Team_Expand, ExportSolutionUpload_Select, ExportSolutionUpload_Filter, { team_exportsolutionupload: ExportSolutionUpload_Result[] }>;
  team_externalparty: WebExpand<Team_Expand, ExternalParty_Select, ExternalParty_Filter, { team_externalparty: ExternalParty_Result[] }>;
  team_fax: WebExpand<Team_Expand, Fax_Select, Fax_Filter, { team_fax: Fax_Result[] }>;
  team_featurecontrolsetting: WebExpand<Team_Expand, featurecontrolsetting_Select, featurecontrolsetting_Filter, { team_featurecontrolsetting: featurecontrolsetting_Result[] }>;
  team_flowmachine: WebExpand<Team_Expand, flowmachine_Select, flowmachine_Filter, { team_flowmachine: flowmachine_Result[] }>;
  team_flowmachinegroup: WebExpand<Team_Expand, flowmachinegroup_Select, flowmachinegroup_Filter, { team_flowmachinegroup: flowmachinegroup_Result[] }>;
  team_flowsession: WebExpand<Team_Expand, flowsession_Select, flowsession_Filter, { team_flowsession: flowsession_Result[] }>;
  team_goal: WebExpand<Team_Expand, Goal_Select, Goal_Filter, { team_goal: Goal_Result[] }>;
  team_goal_goalowner: WebExpand<Team_Expand, Goal_Select, Goal_Filter, { team_goal_goalowner: Goal_Result[] }>;
  team_goalrollupquery: WebExpand<Team_Expand, GoalRollupQuery_Select, GoalRollupQuery_Filter, { team_goalrollupquery: GoalRollupQuery_Result[] }>;
  team_keyvaultreference: WebExpand<Team_Expand, KeyVaultReference_Select, KeyVaultReference_Filter, { team_keyvaultreference: KeyVaultReference_Result[] }>;
  team_knowledgearticle: WebExpand<Team_Expand, KnowledgeArticle_Select, KnowledgeArticle_Filter, { team_knowledgearticle: KnowledgeArticle_Result[] }>;
  team_letter: WebExpand<Team_Expand, Letter_Select, Letter_Filter, { team_letter: Letter_Result[] }>;
  team_mailbox: WebExpand<Team_Expand, Mailbox_Select, Mailbox_Filter, { team_mailbox: Mailbox_Result[] }>;
  team_mailboxtrackingcategory: WebExpand<Team_Expand, MailboxTrackingCategory_Select, MailboxTrackingCategory_Filter, { team_mailboxtrackingcategory: MailboxTrackingCategory_Result[] }>;
  team_mailboxtrackingfolder: WebExpand<Team_Expand, MailboxTrackingFolder_Select, MailboxTrackingFolder_Filter, { team_mailboxtrackingfolder: MailboxTrackingFolder_Result[] }>;
  team_managedidentity: WebExpand<Team_Expand, ManagedIdentity_Select, ManagedIdentity_Filter, { team_managedidentity: ManagedIdentity_Result[] }>;
  team_msdyn_aibdataset: WebExpand<Team_Expand, msdyn_AIBDataset_Select, msdyn_AIBDataset_Filter, { team_msdyn_aibdataset: msdyn_AIBDataset_Result[] }>;
  team_msdyn_aibdatasetfile: WebExpand<Team_Expand, msdyn_AIBDatasetFile_Select, msdyn_AIBDatasetFile_Filter, { team_msdyn_aibdatasetfile: msdyn_AIBDatasetFile_Result[] }>;
  team_msdyn_aibdatasetrecord: WebExpand<Team_Expand, msdyn_AIBDatasetRecord_Select, msdyn_AIBDatasetRecord_Filter, { team_msdyn_aibdatasetrecord: msdyn_AIBDatasetRecord_Result[] }>;
  team_msdyn_aibdatasetscontainer: WebExpand<Team_Expand, msdyn_AIBDatasetsContainer_Select, msdyn_AIBDatasetsContainer_Filter, { team_msdyn_aibdatasetscontainer: msdyn_AIBDatasetsContainer_Result[] }>;
  team_msdyn_aibfile: WebExpand<Team_Expand, msdyn_AIBFile_Select, msdyn_AIBFile_Filter, { team_msdyn_aibfile: msdyn_AIBFile_Result[] }>;
  team_msdyn_aibfileattacheddata: WebExpand<Team_Expand, msdyn_AIBFileAttachedData_Select, msdyn_AIBFileAttachedData_Filter, { team_msdyn_aibfileattacheddata: msdyn_AIBFileAttachedData_Result[] }>;
  team_msdyn_aiconfiguration: WebExpand<Team_Expand, msdyn_AIConfiguration_Select, msdyn_AIConfiguration_Filter, { team_msdyn_aiconfiguration: msdyn_AIConfiguration_Result[] }>;
  team_msdyn_aifptrainingdocument: WebExpand<Team_Expand, msdyn_AIFpTrainingDocument_Select, msdyn_AIFpTrainingDocument_Filter, { team_msdyn_aifptrainingdocument: msdyn_AIFpTrainingDocument_Result[] }>;
  team_msdyn_aimodel: WebExpand<Team_Expand, msdyn_AIModel_Select, msdyn_AIModel_Filter, { team_msdyn_aimodel: msdyn_AIModel_Result[] }>;
  team_msdyn_aiodimage: WebExpand<Team_Expand, msdyn_AIOdImage_Select, msdyn_AIOdImage_Filter, { team_msdyn_aiodimage: msdyn_AIOdImage_Result[] }>;
  team_msdyn_aiodlabel: WebExpand<Team_Expand, msdyn_AIOdLabel_Select, msdyn_AIOdLabel_Filter, { team_msdyn_aiodlabel: msdyn_AIOdLabel_Result[] }>;
  team_msdyn_aiodtrainingboundingbox: WebExpand<Team_Expand, msdyn_AIOdTrainingBoundingBox_Select, msdyn_AIOdTrainingBoundingBox_Filter, { team_msdyn_aiodtrainingboundingbox: msdyn_AIOdTrainingBoundingBox_Result[] }>;
  team_msdyn_aiodtrainingimage: WebExpand<Team_Expand, msdyn_AIOdTrainingImage_Select, msdyn_AIOdTrainingImage_Filter, { team_msdyn_aiodtrainingimage: msdyn_AIOdTrainingImage_Result[] }>;
  team_msdyn_aitemplate: WebExpand<Team_Expand, msdyn_AITemplate_Select, msdyn_AITemplate_Filter, { team_msdyn_aitemplate: msdyn_AITemplate_Result[] }>;
  team_msdyn_analysiscomponent: WebExpand<Team_Expand, msdyn_analysiscomponent_Select, msdyn_analysiscomponent_Filter, { team_msdyn_analysiscomponent: msdyn_analysiscomponent_Result[] }>;
  team_msdyn_analysisjob: WebExpand<Team_Expand, msdyn_analysisjob_Select, msdyn_analysisjob_Filter, { team_msdyn_analysisjob: msdyn_analysisjob_Result[] }>;
  team_msdyn_analysisresult: WebExpand<Team_Expand, msdyn_analysisresult_Select, msdyn_analysisresult_Filter, { team_msdyn_analysisresult: msdyn_analysisresult_Result[] }>;
  team_msdyn_analysisresultdetail: WebExpand<Team_Expand, msdyn_analysisresultdetail_Select, msdyn_analysisresultdetail_Filter, { team_msdyn_analysisresultdetail: msdyn_analysisresultdetail_Result[] }>;
  team_msdyn_dataflow: WebExpand<Team_Expand, msdyn_dataflow_Select, msdyn_dataflow_Filter, { team_msdyn_dataflow: msdyn_dataflow_Result[] }>;
  team_msdyn_federatedarticle: WebExpand<Team_Expand, msdyn_federatedarticle_Select, msdyn_federatedarticle_Filter, { team_msdyn_federatedarticle: msdyn_federatedarticle_Result[] }>;
  team_msdyn_kalanguagesetting: WebExpand<Team_Expand, msdyn_kalanguagesetting_Select, msdyn_kalanguagesetting_Filter, { team_msdyn_kalanguagesetting: msdyn_kalanguagesetting_Result[] }>;
  team_msdyn_kmfederatedsearchconfig: WebExpand<Team_Expand, msdyn_kmfederatedsearchconfig_Select, msdyn_kmfederatedsearchconfig_Filter, { team_msdyn_kmfederatedsearchconfig: msdyn_kmfederatedsearchconfig_Result[] }>;
  team_msdyn_knowledgearticleimage: WebExpand<Team_Expand, msdyn_knowledgearticleimage_Select, msdyn_knowledgearticleimage_Filter, { team_msdyn_knowledgearticleimage: msdyn_knowledgearticleimage_Result[] }>;
  team_msdyn_knowledgearticletemplate: WebExpand<Team_Expand, msdyn_knowledgearticletemplate_Select, msdyn_knowledgearticletemplate_Filter, { team_msdyn_knowledgearticletemplate: msdyn_knowledgearticletemplate_Result[] }>;
  team_msdyn_knowledgeinteractioninsight: WebExpand<Team_Expand, msdyn_knowledgeinteractioninsight_Select, msdyn_knowledgeinteractioninsight_Filter, { team_msdyn_knowledgeinteractioninsight: msdyn_knowledgeinteractioninsight_Result[] }>;
  team_msdyn_knowledgepersonalfilter: WebExpand<Team_Expand, msdyn_knowledgepersonalfilter_Select, msdyn_knowledgepersonalfilter_Filter, { team_msdyn_knowledgepersonalfilter: msdyn_knowledgepersonalfilter_Result[] }>;
  team_msdyn_knowledgesearchfilter: WebExpand<Team_Expand, msdyn_knowledgesearchfilter_Select, msdyn_knowledgesearchfilter_Filter, { team_msdyn_knowledgesearchfilter: msdyn_knowledgesearchfilter_Result[] }>;
  team_msdyn_knowledgesearchinsight: WebExpand<Team_Expand, msdyn_knowledgesearchinsight_Select, msdyn_knowledgesearchinsight_Filter, { team_msdyn_knowledgesearchinsight: msdyn_knowledgesearchinsight_Result[] }>;
  team_msdyn_pminferredtask: WebExpand<Team_Expand, msdyn_pminferredtask_Select, msdyn_pminferredtask_Filter, { team_msdyn_pminferredtask: msdyn_pminferredtask_Result[] }>;
  team_msdyn_pmrecording: WebExpand<Team_Expand, msdyn_pmrecording_Select, msdyn_pmrecording_Filter, { team_msdyn_pmrecording: msdyn_pmrecording_Result[] }>;
  team_msdyn_richtextfile: WebExpand<Team_Expand, msdyn_richtextfile_Select, msdyn_richtextfile_Filter, { team_msdyn_richtextfile: msdyn_richtextfile_Result[] }>;
  team_msdyn_serviceconfiguration: WebExpand<Team_Expand, msdyn_serviceconfiguration_Select, msdyn_serviceconfiguration_Filter, { team_msdyn_serviceconfiguration: msdyn_serviceconfiguration_Result[] }>;
  team_msdyn_slakpi: WebExpand<Team_Expand, msdyn_slakpi_Select, msdyn_slakpi_Filter, { team_msdyn_slakpi: msdyn_slakpi_Result[] }>;
  team_msdyn_solutionhealthrule: WebExpand<Team_Expand, msdyn_solutionhealthrule_Select, msdyn_solutionhealthrule_Filter, { team_msdyn_solutionhealthrule: msdyn_solutionhealthrule_Result[] }>;
  team_msdyn_solutionhealthruleargument: WebExpand<Team_Expand, msdyn_solutionhealthruleargument_Select, msdyn_solutionhealthruleargument_Filter, { team_msdyn_solutionhealthruleargument: msdyn_solutionhealthruleargument_Result[] }>;
  team_msdynce_botcontent: WebExpand<Team_Expand, msdynce_botcontent_Select, msdynce_botcontent_Filter, { team_msdynce_botcontent: msdynce_botcontent_Result[] }>;
  team_new_interactionforemail: WebExpand<Team_Expand, InteractionForEmail_Select, InteractionForEmail_Filter, { team_new_interactionforemail: InteractionForEmail_Result[] }>;
  team_pdfsetting: WebExpand<Team_Expand, PDFSetting_Select, PDFSetting_Filter, { team_pdfsetting: PDFSetting_Result[] }>;
  team_phonecall: WebExpand<Team_Expand, PhoneCall_Select, PhoneCall_Filter, { team_phonecall: PhoneCall_Result[] }>;
  team_principalobjectattributeaccess: WebExpand<Team_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { team_principalobjectattributeaccess: PrincipalObjectAttributeAccess_Result[] }>;
  team_principalobjectattributeaccess_principalid: WebExpand<Team_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { team_principalobjectattributeaccess_principalid: PrincipalObjectAttributeAccess_Result[] }>;
  team_processsession: WebExpand<Team_Expand, ProcessSession_Select, ProcessSession_Filter, { team_processsession: ProcessSession_Result[] }>;
  team_processstageparameter: WebExpand<Team_Expand, processstageparameter_Select, processstageparameter_Filter, { team_processstageparameter: processstageparameter_Result[] }>;
  team_profilerule: WebExpand<Team_Expand, ChannelAccessProfileRule_Select, ChannelAccessProfileRule_Filter, { team_profilerule: ChannelAccessProfileRule_Result[] }>;
  team_queueitembase_workerid: WebExpand<Team_Expand, QueueItem_Select, QueueItem_Filter, { team_queueitembase_workerid: QueueItem_Result[] }>;
  team_recurringappointmentmaster: WebExpand<Team_Expand, RecurringAppointmentMaster_Select, RecurringAppointmentMaster_Filter, { team_recurringappointmentmaster: RecurringAppointmentMaster_Result[] }>;
  team_revokeinheritedaccessrecordstracker: WebExpand<Team_Expand, revokeinheritedaccessrecordstracker_Select, revokeinheritedaccessrecordstracker_Filter, { team_revokeinheritedaccessrecordstracker: revokeinheritedaccessrecordstracker_Result[] }>;
  team_routingrule: WebExpand<Team_Expand, RoutingRule_Select, RoutingRule_Filter, { team_routingrule: RoutingRule_Result[] }>;
  team_routingruleitem: WebExpand<Team_Expand, RoutingRuleItem_Select, RoutingRuleItem_Filter, { team_routingruleitem: RoutingRuleItem_Result[] }>;
  team_sharepointdocumentlocation: WebExpand<Team_Expand, SharePointDocumentLocation_Select, SharePointDocumentLocation_Filter, { team_sharepointdocumentlocation: SharePointDocumentLocation_Result[] }>;
  team_sharepointsite: WebExpand<Team_Expand, SharePointSite_Select, SharePointSite_Filter, { team_sharepointsite: SharePointSite_Result[] }>;
  team_slaBase: WebExpand<Team_Expand, SLA_Select, SLA_Filter, { team_slaBase: SLA_Result[] }>;
  team_socialactivity: WebExpand<Team_Expand, SocialActivity_Select, SocialActivity_Filter, { team_socialactivity: SocialActivity_Result[] }>;
  team_solutioncomponentbatchconfiguration: WebExpand<Team_Expand, solutioncomponentbatchconfiguration_Select, solutioncomponentbatchconfiguration_Filter, { team_solutioncomponentbatchconfiguration: solutioncomponentbatchconfiguration_Result[] }>;
  team_stagesolutionupload: WebExpand<Team_Expand, StageSolutionUpload_Select, StageSolutionUpload_Filter, { team_stagesolutionupload: StageSolutionUpload_Result[] }>;
  team_task: WebExpand<Team_Expand, Task_Select, Task_Filter, { team_task: Task_Result[] }>;
  team_teammobileofflineprofilemembership_TeamId: WebExpand<Team_Expand, teammobileofflineprofilemembership_Select, teammobileofflineprofilemembership_Filter, { team_teammobileofflineprofilemembership_TeamId: teammobileofflineprofilemembership_Result[] }>;
  team_userentityinstancedata: WebExpand<Team_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { team_userentityinstancedata: UserEntityInstanceData_Result[] }>;
  team_userentityuisettings: WebExpand<Team_Expand, UserEntityUISettings_Select, UserEntityUISettings_Filter, { team_userentityuisettings: UserEntityUISettings_Result[] }>;
  team_userform: WebExpand<Team_Expand, UserForm_Select, UserForm_Filter, { team_userform: UserForm_Result[] }>;
  team_userquery: WebExpand<Team_Expand, UserQuery_Select, UserQuery_Filter, { team_userquery: UserQuery_Result[] }>;
  team_userqueryvisualizations: WebExpand<Team_Expand, UserQueryVisualization_Select, UserQueryVisualization_Filter, { team_userqueryvisualizations: UserQueryVisualization_Result[] }>;
  team_workflow: WebExpand<Team_Expand, Workflow_Select, Workflow_Filter, { team_workflow: Workflow_Result[] }>;
  team_workflowbinary: WebExpand<Team_Expand, workflowbinary_Select, workflowbinary_Filter, { team_workflowbinary: workflowbinary_Result[] }>;
  team_workflowlog: WebExpand<Team_Expand, WorkflowLog_Select, WorkflowLog_Filter, { team_workflowlog: WorkflowLog_Result[] }>;
  teammembership_association: WebExpand<Team_Expand, SystemUser_Select, SystemUser_Filter, { teammembership_association: SystemUser_Result[] }>;
  teamprofiles_association: WebExpand<Team_Expand, FieldSecurityProfile_Select, FieldSecurityProfile_Filter, { teamprofiles_association: FieldSecurityProfile_Result[] }>;
  teamroles_association: WebExpand<Team_Expand, Role_Select, Role_Filter, { teamroles_association: Role_Result[] }>;
  teamsyncattributemappingprofiles_association: WebExpand<Team_Expand, SyncAttributeMappingProfile_Select, SyncAttributeMappingProfile_Filter, { teamsyncattributemappingprofiles_association: SyncAttributeMappingProfile_Result[] }>;
  transactioncurrencyid: WebExpand<Team_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid: TransactionCurrency_Result }>;
  userentityinstancedata_team: WebExpand<Team_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { userentityinstancedata_team: UserEntityInstanceData_Result[] }>;
}
interface Team_FormattedResult {
  administratorid_formatted?: string;
  businessunitid_formatted?: string;
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  membershiptype_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  overriddencreatedon_formatted?: string;
  queueid_formatted?: string;
  regardingobjectid_formatted?: string;
  teamtemplateid_formatted?: string;
  teamtype_formatted?: string;
  transactioncurrencyid_formatted?: string;
}
interface Team_Result extends Team_Base, Team_Relationships {
  "@odata.etag": string;
  administratorid_guid: string | null;
  businessunitid_guid: string | null;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  queueid_guid: string | null;
  regardingobjectid_guid: string | null;
  teamtemplateid_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface Team_RelatedOne {
  administratorid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  associatedteamtemplateid: WebMappingRetrieve<TeamTemplate_Select,TeamTemplate_Expand,TeamTemplate_Filter,TeamTemplate_Fixed,TeamTemplate_Result,TeamTemplate_FormattedResult>;
  businessunitid: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  organizationid_organization: WebMappingRetrieve<Organization_Select,Organization_Expand,Organization_Filter,Organization_Fixed,Organization_Result,Organization_FormattedResult>;
  queueid: WebMappingRetrieve<Queue_Select,Queue_Expand,Queue_Filter,Queue_Fixed,Queue_Result,Queue_FormattedResult>;
  regardingobjectid_knowledgearticle: WebMappingRetrieve<KnowledgeArticle_Select,KnowledgeArticle_Expand,KnowledgeArticle_Filter,KnowledgeArticle_Fixed,KnowledgeArticle_Result,KnowledgeArticle_FormattedResult>;
  stageid_processstage: WebMappingRetrieve<ProcessStage_Select,ProcessStage_Expand,ProcessStage_Filter,ProcessStage_Fixed,ProcessStage_Result,ProcessStage_FormattedResult>;
  transactioncurrencyid: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface Team_RelatedMany {
  ImportFile_Team: WebMappingRetrieve<ImportFile_Select,ImportFile_Expand,ImportFile_Filter,ImportFile_Fixed,ImportFile_Result,ImportFile_FormattedResult>;
  OwningTeam_postfollows: WebMappingRetrieve<PostFollow_Select,PostFollow_Expand,PostFollow_Filter,PostFollow_Fixed,PostFollow_Result,PostFollow_FormattedResult>;
  Team_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  Team_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  Team_DuplicateBaseRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  Team_DuplicateMatchingRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  Team_ProcessSessions: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  Team_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  team_DuplicateRules: WebMappingRetrieve<DuplicateRule_Select,DuplicateRule_Expand,DuplicateRule_Filter,DuplicateRule_Fixed,DuplicateRule_Result,DuplicateRule_FormattedResult>;
  team_ImportData: WebMappingRetrieve<ImportData_Select,ImportData_Expand,ImportData_Filter,ImportData_Fixed,ImportData_Result,ImportData_FormattedResult>;
  team_ImportFiles: WebMappingRetrieve<ImportFile_Select,ImportFile_Expand,ImportFile_Filter,ImportFile_Fixed,ImportFile_Result,ImportFile_FormattedResult>;
  team_ImportLogs: WebMappingRetrieve<ImportLog_Select,ImportLog_Expand,ImportLog_Filter,ImportLog_Fixed,ImportLog_Result,ImportLog_FormattedResult>;
  team_ImportMaps: WebMappingRetrieve<ImportMap_Select,ImportMap_Expand,ImportMap_Filter,ImportMap_Fixed,ImportMap_Result,ImportMap_FormattedResult>;
  team_Imports: WebMappingRetrieve<Import_Select,Import_Expand,Import_Filter,Import_Fixed,Import_Result,Import_FormattedResult>;
  team_PostRegardings: WebMappingRetrieve<PostRegarding_Select,PostRegarding_Expand,PostRegarding_Filter,PostRegarding_Fixed,PostRegarding_Result,PostRegarding_FormattedResult>;
  team_PostRoles: WebMappingRetrieve<PostRole_Select,PostRole_Expand,PostRole_Filter,PostRole_Fixed,PostRole_Result,PostRole_FormattedResult>;
  team_SyncError: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  team_accounts: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  team_actioncardusersettings: WebMappingRetrieve<ActionCardUserSettings_Select,ActionCardUserSettings_Expand,ActionCardUserSettings_Filter,ActionCardUserSettings_Fixed,ActionCardUserSettings_Result,ActionCardUserSettings_FormattedResult>;
  team_activity: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  team_activityfileattachment: WebMappingRetrieve<activityfileattachment_Select,activityfileattachment_Expand,activityfileattachment_Filter,activityfileattachment_Fixed,activityfileattachment_Result,activityfileattachment_FormattedResult>;
  team_annotations: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  team_appnotification: WebMappingRetrieve<appnotification_Select,appnotification_Expand,appnotification_Filter,appnotification_Fixed,appnotification_Result,appnotification_FormattedResult>;
  team_appointment: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
  team_asyncoperation: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  team_bot: WebMappingRetrieve<bot_Select,bot_Expand,bot_Filter,bot_Fixed,bot_Result,bot_FormattedResult>;
  team_botcomponent: WebMappingRetrieve<botcomponent_Select,botcomponent_Expand,botcomponent_Filter,botcomponent_Fixed,botcomponent_Result,botcomponent_FormattedResult>;
  team_canvasappextendedmetadata: WebMappingRetrieve<CanvasAppExtendedMetadata_Select,CanvasAppExtendedMetadata_Expand,CanvasAppExtendedMetadata_Filter,CanvasAppExtendedMetadata_Fixed,CanvasAppExtendedMetadata_Result,CanvasAppExtendedMetadata_FormattedResult>;
  team_channelaccessprofile: WebMappingRetrieve<ChannelAccessProfile_Select,ChannelAccessProfile_Expand,ChannelAccessProfile_Filter,ChannelAccessProfile_Fixed,ChannelAccessProfile_Result,ChannelAccessProfile_FormattedResult>;
  team_connectionreference: WebMappingRetrieve<connectionreference_Select,connectionreference_Expand,connectionreference_Filter,connectionreference_Fixed,connectionreference_Result,connectionreference_FormattedResult>;
  team_connections1: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  team_connections2: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  team_connector: WebMappingRetrieve<connector_Select,connector_Expand,connector_Filter,connector_Fixed,connector_Result,connector_FormattedResult>;
  team_contacts: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  team_conversationtranscript: WebMappingRetrieve<conversationtranscript_Select,conversationtranscript_Expand,conversationtranscript_Filter,conversationtranscript_Fixed,conversationtranscript_Result,conversationtranscript_FormattedResult>;
  team_convertrule: WebMappingRetrieve<ConvertRule_Select,ConvertRule_Expand,ConvertRule_Filter,ConvertRule_Fixed,ConvertRule_Result,ConvertRule_FormattedResult>;
  team_customapi: WebMappingRetrieve<CustomAPI_Select,CustomAPI_Expand,CustomAPI_Filter,CustomAPI_Fixed,CustomAPI_Result,CustomAPI_FormattedResult>;
  team_customapirequestparameter: WebMappingRetrieve<CustomAPIRequestParameter_Select,CustomAPIRequestParameter_Expand,CustomAPIRequestParameter_Filter,CustomAPIRequestParameter_Fixed,CustomAPIRequestParameter_Result,CustomAPIRequestParameter_FormattedResult>;
  team_customapiresponseproperty: WebMappingRetrieve<CustomAPIResponseProperty_Select,CustomAPIResponseProperty_Expand,CustomAPIResponseProperty_Filter,CustomAPIResponseProperty_Fixed,CustomAPIResponseProperty_Result,CustomAPIResponseProperty_FormattedResult>;
  team_customer_relationship: WebMappingRetrieve<CustomerRelationship_Select,CustomerRelationship_Expand,CustomerRelationship_Filter,CustomerRelationship_Fixed,CustomerRelationship_Result,CustomerRelationship_FormattedResult>;
  team_datalakefolder: WebMappingRetrieve<datalakefolder_Select,datalakefolder_Expand,datalakefolder_Filter,datalakefolder_Fixed,datalakefolder_Result,datalakefolder_FormattedResult>;
  team_datalakefolderpermission: WebMappingRetrieve<datalakefolderpermission_Select,datalakefolderpermission_Expand,datalakefolderpermission_Filter,datalakefolderpermission_Fixed,datalakefolderpermission_Result,datalakefolderpermission_FormattedResult>;
  team_email: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  team_email_templates: WebMappingRetrieve<Template_Select,Template_Expand,Template_Filter,Template_Fixed,Template_Result,Template_FormattedResult>;
  team_emailserverprofile: WebMappingRetrieve<EmailServerProfile_Select,EmailServerProfile_Expand,EmailServerProfile_Filter,EmailServerProfile_Fixed,EmailServerProfile_Result,EmailServerProfile_FormattedResult>;
  team_environmentvariabledefinition: WebMappingRetrieve<EnvironmentVariableDefinition_Select,EnvironmentVariableDefinition_Expand,EnvironmentVariableDefinition_Filter,EnvironmentVariableDefinition_Fixed,EnvironmentVariableDefinition_Result,EnvironmentVariableDefinition_FormattedResult>;
  team_environmentvariablevalue: WebMappingRetrieve<EnvironmentVariableValue_Select,EnvironmentVariableValue_Expand,EnvironmentVariableValue_Filter,EnvironmentVariableValue_Fixed,EnvironmentVariableValue_Result,EnvironmentVariableValue_FormattedResult>;
  team_exchangesyncidmapping: WebMappingRetrieve<ExchangeSyncIdMapping_Select,ExchangeSyncIdMapping_Expand,ExchangeSyncIdMapping_Filter,ExchangeSyncIdMapping_Fixed,ExchangeSyncIdMapping_Result,ExchangeSyncIdMapping_FormattedResult>;
  team_exportsolutionupload: WebMappingRetrieve<ExportSolutionUpload_Select,ExportSolutionUpload_Expand,ExportSolutionUpload_Filter,ExportSolutionUpload_Fixed,ExportSolutionUpload_Result,ExportSolutionUpload_FormattedResult>;
  team_externalparty: WebMappingRetrieve<ExternalParty_Select,ExternalParty_Expand,ExternalParty_Filter,ExternalParty_Fixed,ExternalParty_Result,ExternalParty_FormattedResult>;
  team_fax: WebMappingRetrieve<Fax_Select,Fax_Expand,Fax_Filter,Fax_Fixed,Fax_Result,Fax_FormattedResult>;
  team_featurecontrolsetting: WebMappingRetrieve<featurecontrolsetting_Select,featurecontrolsetting_Expand,featurecontrolsetting_Filter,featurecontrolsetting_Fixed,featurecontrolsetting_Result,featurecontrolsetting_FormattedResult>;
  team_flowmachine: WebMappingRetrieve<flowmachine_Select,flowmachine_Expand,flowmachine_Filter,flowmachine_Fixed,flowmachine_Result,flowmachine_FormattedResult>;
  team_flowmachinegroup: WebMappingRetrieve<flowmachinegroup_Select,flowmachinegroup_Expand,flowmachinegroup_Filter,flowmachinegroup_Fixed,flowmachinegroup_Result,flowmachinegroup_FormattedResult>;
  team_flowsession: WebMappingRetrieve<flowsession_Select,flowsession_Expand,flowsession_Filter,flowsession_Fixed,flowsession_Result,flowsession_FormattedResult>;
  team_goal: WebMappingRetrieve<Goal_Select,Goal_Expand,Goal_Filter,Goal_Fixed,Goal_Result,Goal_FormattedResult>;
  team_goal_goalowner: WebMappingRetrieve<Goal_Select,Goal_Expand,Goal_Filter,Goal_Fixed,Goal_Result,Goal_FormattedResult>;
  team_goalrollupquery: WebMappingRetrieve<GoalRollupQuery_Select,GoalRollupQuery_Expand,GoalRollupQuery_Filter,GoalRollupQuery_Fixed,GoalRollupQuery_Result,GoalRollupQuery_FormattedResult>;
  team_keyvaultreference: WebMappingRetrieve<KeyVaultReference_Select,KeyVaultReference_Expand,KeyVaultReference_Filter,KeyVaultReference_Fixed,KeyVaultReference_Result,KeyVaultReference_FormattedResult>;
  team_knowledgearticle: WebMappingRetrieve<KnowledgeArticle_Select,KnowledgeArticle_Expand,KnowledgeArticle_Filter,KnowledgeArticle_Fixed,KnowledgeArticle_Result,KnowledgeArticle_FormattedResult>;
  team_letter: WebMappingRetrieve<Letter_Select,Letter_Expand,Letter_Filter,Letter_Fixed,Letter_Result,Letter_FormattedResult>;
  team_mailbox: WebMappingRetrieve<Mailbox_Select,Mailbox_Expand,Mailbox_Filter,Mailbox_Fixed,Mailbox_Result,Mailbox_FormattedResult>;
  team_mailboxtrackingcategory: WebMappingRetrieve<MailboxTrackingCategory_Select,MailboxTrackingCategory_Expand,MailboxTrackingCategory_Filter,MailboxTrackingCategory_Fixed,MailboxTrackingCategory_Result,MailboxTrackingCategory_FormattedResult>;
  team_mailboxtrackingfolder: WebMappingRetrieve<MailboxTrackingFolder_Select,MailboxTrackingFolder_Expand,MailboxTrackingFolder_Filter,MailboxTrackingFolder_Fixed,MailboxTrackingFolder_Result,MailboxTrackingFolder_FormattedResult>;
  team_managedidentity: WebMappingRetrieve<ManagedIdentity_Select,ManagedIdentity_Expand,ManagedIdentity_Filter,ManagedIdentity_Fixed,ManagedIdentity_Result,ManagedIdentity_FormattedResult>;
  team_msdyn_aibdataset: WebMappingRetrieve<msdyn_AIBDataset_Select,msdyn_AIBDataset_Expand,msdyn_AIBDataset_Filter,msdyn_AIBDataset_Fixed,msdyn_AIBDataset_Result,msdyn_AIBDataset_FormattedResult>;
  team_msdyn_aibdatasetfile: WebMappingRetrieve<msdyn_AIBDatasetFile_Select,msdyn_AIBDatasetFile_Expand,msdyn_AIBDatasetFile_Filter,msdyn_AIBDatasetFile_Fixed,msdyn_AIBDatasetFile_Result,msdyn_AIBDatasetFile_FormattedResult>;
  team_msdyn_aibdatasetrecord: WebMappingRetrieve<msdyn_AIBDatasetRecord_Select,msdyn_AIBDatasetRecord_Expand,msdyn_AIBDatasetRecord_Filter,msdyn_AIBDatasetRecord_Fixed,msdyn_AIBDatasetRecord_Result,msdyn_AIBDatasetRecord_FormattedResult>;
  team_msdyn_aibdatasetscontainer: WebMappingRetrieve<msdyn_AIBDatasetsContainer_Select,msdyn_AIBDatasetsContainer_Expand,msdyn_AIBDatasetsContainer_Filter,msdyn_AIBDatasetsContainer_Fixed,msdyn_AIBDatasetsContainer_Result,msdyn_AIBDatasetsContainer_FormattedResult>;
  team_msdyn_aibfile: WebMappingRetrieve<msdyn_AIBFile_Select,msdyn_AIBFile_Expand,msdyn_AIBFile_Filter,msdyn_AIBFile_Fixed,msdyn_AIBFile_Result,msdyn_AIBFile_FormattedResult>;
  team_msdyn_aibfileattacheddata: WebMappingRetrieve<msdyn_AIBFileAttachedData_Select,msdyn_AIBFileAttachedData_Expand,msdyn_AIBFileAttachedData_Filter,msdyn_AIBFileAttachedData_Fixed,msdyn_AIBFileAttachedData_Result,msdyn_AIBFileAttachedData_FormattedResult>;
  team_msdyn_aiconfiguration: WebMappingRetrieve<msdyn_AIConfiguration_Select,msdyn_AIConfiguration_Expand,msdyn_AIConfiguration_Filter,msdyn_AIConfiguration_Fixed,msdyn_AIConfiguration_Result,msdyn_AIConfiguration_FormattedResult>;
  team_msdyn_aifptrainingdocument: WebMappingRetrieve<msdyn_AIFpTrainingDocument_Select,msdyn_AIFpTrainingDocument_Expand,msdyn_AIFpTrainingDocument_Filter,msdyn_AIFpTrainingDocument_Fixed,msdyn_AIFpTrainingDocument_Result,msdyn_AIFpTrainingDocument_FormattedResult>;
  team_msdyn_aimodel: WebMappingRetrieve<msdyn_AIModel_Select,msdyn_AIModel_Expand,msdyn_AIModel_Filter,msdyn_AIModel_Fixed,msdyn_AIModel_Result,msdyn_AIModel_FormattedResult>;
  team_msdyn_aiodimage: WebMappingRetrieve<msdyn_AIOdImage_Select,msdyn_AIOdImage_Expand,msdyn_AIOdImage_Filter,msdyn_AIOdImage_Fixed,msdyn_AIOdImage_Result,msdyn_AIOdImage_FormattedResult>;
  team_msdyn_aiodlabel: WebMappingRetrieve<msdyn_AIOdLabel_Select,msdyn_AIOdLabel_Expand,msdyn_AIOdLabel_Filter,msdyn_AIOdLabel_Fixed,msdyn_AIOdLabel_Result,msdyn_AIOdLabel_FormattedResult>;
  team_msdyn_aiodtrainingboundingbox: WebMappingRetrieve<msdyn_AIOdTrainingBoundingBox_Select,msdyn_AIOdTrainingBoundingBox_Expand,msdyn_AIOdTrainingBoundingBox_Filter,msdyn_AIOdTrainingBoundingBox_Fixed,msdyn_AIOdTrainingBoundingBox_Result,msdyn_AIOdTrainingBoundingBox_FormattedResult>;
  team_msdyn_aiodtrainingimage: WebMappingRetrieve<msdyn_AIOdTrainingImage_Select,msdyn_AIOdTrainingImage_Expand,msdyn_AIOdTrainingImage_Filter,msdyn_AIOdTrainingImage_Fixed,msdyn_AIOdTrainingImage_Result,msdyn_AIOdTrainingImage_FormattedResult>;
  team_msdyn_aitemplate: WebMappingRetrieve<msdyn_AITemplate_Select,msdyn_AITemplate_Expand,msdyn_AITemplate_Filter,msdyn_AITemplate_Fixed,msdyn_AITemplate_Result,msdyn_AITemplate_FormattedResult>;
  team_msdyn_analysiscomponent: WebMappingRetrieve<msdyn_analysiscomponent_Select,msdyn_analysiscomponent_Expand,msdyn_analysiscomponent_Filter,msdyn_analysiscomponent_Fixed,msdyn_analysiscomponent_Result,msdyn_analysiscomponent_FormattedResult>;
  team_msdyn_analysisjob: WebMappingRetrieve<msdyn_analysisjob_Select,msdyn_analysisjob_Expand,msdyn_analysisjob_Filter,msdyn_analysisjob_Fixed,msdyn_analysisjob_Result,msdyn_analysisjob_FormattedResult>;
  team_msdyn_analysisresult: WebMappingRetrieve<msdyn_analysisresult_Select,msdyn_analysisresult_Expand,msdyn_analysisresult_Filter,msdyn_analysisresult_Fixed,msdyn_analysisresult_Result,msdyn_analysisresult_FormattedResult>;
  team_msdyn_analysisresultdetail: WebMappingRetrieve<msdyn_analysisresultdetail_Select,msdyn_analysisresultdetail_Expand,msdyn_analysisresultdetail_Filter,msdyn_analysisresultdetail_Fixed,msdyn_analysisresultdetail_Result,msdyn_analysisresultdetail_FormattedResult>;
  team_msdyn_dataflow: WebMappingRetrieve<msdyn_dataflow_Select,msdyn_dataflow_Expand,msdyn_dataflow_Filter,msdyn_dataflow_Fixed,msdyn_dataflow_Result,msdyn_dataflow_FormattedResult>;
  team_msdyn_federatedarticle: WebMappingRetrieve<msdyn_federatedarticle_Select,msdyn_federatedarticle_Expand,msdyn_federatedarticle_Filter,msdyn_federatedarticle_Fixed,msdyn_federatedarticle_Result,msdyn_federatedarticle_FormattedResult>;
  team_msdyn_kalanguagesetting: WebMappingRetrieve<msdyn_kalanguagesetting_Select,msdyn_kalanguagesetting_Expand,msdyn_kalanguagesetting_Filter,msdyn_kalanguagesetting_Fixed,msdyn_kalanguagesetting_Result,msdyn_kalanguagesetting_FormattedResult>;
  team_msdyn_kmfederatedsearchconfig: WebMappingRetrieve<msdyn_kmfederatedsearchconfig_Select,msdyn_kmfederatedsearchconfig_Expand,msdyn_kmfederatedsearchconfig_Filter,msdyn_kmfederatedsearchconfig_Fixed,msdyn_kmfederatedsearchconfig_Result,msdyn_kmfederatedsearchconfig_FormattedResult>;
  team_msdyn_knowledgearticleimage: WebMappingRetrieve<msdyn_knowledgearticleimage_Select,msdyn_knowledgearticleimage_Expand,msdyn_knowledgearticleimage_Filter,msdyn_knowledgearticleimage_Fixed,msdyn_knowledgearticleimage_Result,msdyn_knowledgearticleimage_FormattedResult>;
  team_msdyn_knowledgearticletemplate: WebMappingRetrieve<msdyn_knowledgearticletemplate_Select,msdyn_knowledgearticletemplate_Expand,msdyn_knowledgearticletemplate_Filter,msdyn_knowledgearticletemplate_Fixed,msdyn_knowledgearticletemplate_Result,msdyn_knowledgearticletemplate_FormattedResult>;
  team_msdyn_knowledgeinteractioninsight: WebMappingRetrieve<msdyn_knowledgeinteractioninsight_Select,msdyn_knowledgeinteractioninsight_Expand,msdyn_knowledgeinteractioninsight_Filter,msdyn_knowledgeinteractioninsight_Fixed,msdyn_knowledgeinteractioninsight_Result,msdyn_knowledgeinteractioninsight_FormattedResult>;
  team_msdyn_knowledgepersonalfilter: WebMappingRetrieve<msdyn_knowledgepersonalfilter_Select,msdyn_knowledgepersonalfilter_Expand,msdyn_knowledgepersonalfilter_Filter,msdyn_knowledgepersonalfilter_Fixed,msdyn_knowledgepersonalfilter_Result,msdyn_knowledgepersonalfilter_FormattedResult>;
  team_msdyn_knowledgesearchfilter: WebMappingRetrieve<msdyn_knowledgesearchfilter_Select,msdyn_knowledgesearchfilter_Expand,msdyn_knowledgesearchfilter_Filter,msdyn_knowledgesearchfilter_Fixed,msdyn_knowledgesearchfilter_Result,msdyn_knowledgesearchfilter_FormattedResult>;
  team_msdyn_knowledgesearchinsight: WebMappingRetrieve<msdyn_knowledgesearchinsight_Select,msdyn_knowledgesearchinsight_Expand,msdyn_knowledgesearchinsight_Filter,msdyn_knowledgesearchinsight_Fixed,msdyn_knowledgesearchinsight_Result,msdyn_knowledgesearchinsight_FormattedResult>;
  team_msdyn_pminferredtask: WebMappingRetrieve<msdyn_pminferredtask_Select,msdyn_pminferredtask_Expand,msdyn_pminferredtask_Filter,msdyn_pminferredtask_Fixed,msdyn_pminferredtask_Result,msdyn_pminferredtask_FormattedResult>;
  team_msdyn_pmrecording: WebMappingRetrieve<msdyn_pmrecording_Select,msdyn_pmrecording_Expand,msdyn_pmrecording_Filter,msdyn_pmrecording_Fixed,msdyn_pmrecording_Result,msdyn_pmrecording_FormattedResult>;
  team_msdyn_richtextfile: WebMappingRetrieve<msdyn_richtextfile_Select,msdyn_richtextfile_Expand,msdyn_richtextfile_Filter,msdyn_richtextfile_Fixed,msdyn_richtextfile_Result,msdyn_richtextfile_FormattedResult>;
  team_msdyn_serviceconfiguration: WebMappingRetrieve<msdyn_serviceconfiguration_Select,msdyn_serviceconfiguration_Expand,msdyn_serviceconfiguration_Filter,msdyn_serviceconfiguration_Fixed,msdyn_serviceconfiguration_Result,msdyn_serviceconfiguration_FormattedResult>;
  team_msdyn_slakpi: WebMappingRetrieve<msdyn_slakpi_Select,msdyn_slakpi_Expand,msdyn_slakpi_Filter,msdyn_slakpi_Fixed,msdyn_slakpi_Result,msdyn_slakpi_FormattedResult>;
  team_msdyn_solutionhealthrule: WebMappingRetrieve<msdyn_solutionhealthrule_Select,msdyn_solutionhealthrule_Expand,msdyn_solutionhealthrule_Filter,msdyn_solutionhealthrule_Fixed,msdyn_solutionhealthrule_Result,msdyn_solutionhealthrule_FormattedResult>;
  team_msdyn_solutionhealthruleargument: WebMappingRetrieve<msdyn_solutionhealthruleargument_Select,msdyn_solutionhealthruleargument_Expand,msdyn_solutionhealthruleargument_Filter,msdyn_solutionhealthruleargument_Fixed,msdyn_solutionhealthruleargument_Result,msdyn_solutionhealthruleargument_FormattedResult>;
  team_msdynce_botcontent: WebMappingRetrieve<msdynce_botcontent_Select,msdynce_botcontent_Expand,msdynce_botcontent_Filter,msdynce_botcontent_Fixed,msdynce_botcontent_Result,msdynce_botcontent_FormattedResult>;
  team_new_interactionforemail: WebMappingRetrieve<InteractionForEmail_Select,InteractionForEmail_Expand,InteractionForEmail_Filter,InteractionForEmail_Fixed,InteractionForEmail_Result,InteractionForEmail_FormattedResult>;
  team_pdfsetting: WebMappingRetrieve<PDFSetting_Select,PDFSetting_Expand,PDFSetting_Filter,PDFSetting_Fixed,PDFSetting_Result,PDFSetting_FormattedResult>;
  team_phonecall: WebMappingRetrieve<PhoneCall_Select,PhoneCall_Expand,PhoneCall_Filter,PhoneCall_Fixed,PhoneCall_Result,PhoneCall_FormattedResult>;
  team_principalobjectattributeaccess: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  team_principalobjectattributeaccess_principalid: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  team_processsession: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  team_processstageparameter: WebMappingRetrieve<processstageparameter_Select,processstageparameter_Expand,processstageparameter_Filter,processstageparameter_Fixed,processstageparameter_Result,processstageparameter_FormattedResult>;
  team_profilerule: WebMappingRetrieve<ChannelAccessProfileRule_Select,ChannelAccessProfileRule_Expand,ChannelAccessProfileRule_Filter,ChannelAccessProfileRule_Fixed,ChannelAccessProfileRule_Result,ChannelAccessProfileRule_FormattedResult>;
  team_queueitembase_workerid: WebMappingRetrieve<QueueItem_Select,QueueItem_Expand,QueueItem_Filter,QueueItem_Fixed,QueueItem_Result,QueueItem_FormattedResult>;
  team_recurringappointmentmaster: WebMappingRetrieve<RecurringAppointmentMaster_Select,RecurringAppointmentMaster_Expand,RecurringAppointmentMaster_Filter,RecurringAppointmentMaster_Fixed,RecurringAppointmentMaster_Result,RecurringAppointmentMaster_FormattedResult>;
  team_revokeinheritedaccessrecordstracker: WebMappingRetrieve<revokeinheritedaccessrecordstracker_Select,revokeinheritedaccessrecordstracker_Expand,revokeinheritedaccessrecordstracker_Filter,revokeinheritedaccessrecordstracker_Fixed,revokeinheritedaccessrecordstracker_Result,revokeinheritedaccessrecordstracker_FormattedResult>;
  team_routingrule: WebMappingRetrieve<RoutingRule_Select,RoutingRule_Expand,RoutingRule_Filter,RoutingRule_Fixed,RoutingRule_Result,RoutingRule_FormattedResult>;
  team_routingruleitem: WebMappingRetrieve<RoutingRuleItem_Select,RoutingRuleItem_Expand,RoutingRuleItem_Filter,RoutingRuleItem_Fixed,RoutingRuleItem_Result,RoutingRuleItem_FormattedResult>;
  team_sharepointdocumentlocation: WebMappingRetrieve<SharePointDocumentLocation_Select,SharePointDocumentLocation_Expand,SharePointDocumentLocation_Filter,SharePointDocumentLocation_Fixed,SharePointDocumentLocation_Result,SharePointDocumentLocation_FormattedResult>;
  team_sharepointsite: WebMappingRetrieve<SharePointSite_Select,SharePointSite_Expand,SharePointSite_Filter,SharePointSite_Fixed,SharePointSite_Result,SharePointSite_FormattedResult>;
  team_slaBase: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  team_socialactivity: WebMappingRetrieve<SocialActivity_Select,SocialActivity_Expand,SocialActivity_Filter,SocialActivity_Fixed,SocialActivity_Result,SocialActivity_FormattedResult>;
  team_solutioncomponentbatchconfiguration: WebMappingRetrieve<solutioncomponentbatchconfiguration_Select,solutioncomponentbatchconfiguration_Expand,solutioncomponentbatchconfiguration_Filter,solutioncomponentbatchconfiguration_Fixed,solutioncomponentbatchconfiguration_Result,solutioncomponentbatchconfiguration_FormattedResult>;
  team_stagesolutionupload: WebMappingRetrieve<StageSolutionUpload_Select,StageSolutionUpload_Expand,StageSolutionUpload_Filter,StageSolutionUpload_Fixed,StageSolutionUpload_Result,StageSolutionUpload_FormattedResult>;
  team_task: WebMappingRetrieve<Task_Select,Task_Expand,Task_Filter,Task_Fixed,Task_Result,Task_FormattedResult>;
  team_teammobileofflineprofilemembership_TeamId: WebMappingRetrieve<teammobileofflineprofilemembership_Select,teammobileofflineprofilemembership_Expand,teammobileofflineprofilemembership_Filter,teammobileofflineprofilemembership_Fixed,teammobileofflineprofilemembership_Result,teammobileofflineprofilemembership_FormattedResult>;
  team_userentityinstancedata: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
  team_userentityuisettings: WebMappingRetrieve<UserEntityUISettings_Select,UserEntityUISettings_Expand,UserEntityUISettings_Filter,UserEntityUISettings_Fixed,UserEntityUISettings_Result,UserEntityUISettings_FormattedResult>;
  team_userform: WebMappingRetrieve<UserForm_Select,UserForm_Expand,UserForm_Filter,UserForm_Fixed,UserForm_Result,UserForm_FormattedResult>;
  team_userquery: WebMappingRetrieve<UserQuery_Select,UserQuery_Expand,UserQuery_Filter,UserQuery_Fixed,UserQuery_Result,UserQuery_FormattedResult>;
  team_userqueryvisualizations: WebMappingRetrieve<UserQueryVisualization_Select,UserQueryVisualization_Expand,UserQueryVisualization_Filter,UserQueryVisualization_Fixed,UserQueryVisualization_Result,UserQueryVisualization_FormattedResult>;
  team_workflow: WebMappingRetrieve<Workflow_Select,Workflow_Expand,Workflow_Filter,Workflow_Fixed,Workflow_Result,Workflow_FormattedResult>;
  team_workflowbinary: WebMappingRetrieve<workflowbinary_Select,workflowbinary_Expand,workflowbinary_Filter,workflowbinary_Fixed,workflowbinary_Result,workflowbinary_FormattedResult>;
  team_workflowlog: WebMappingRetrieve<WorkflowLog_Select,WorkflowLog_Expand,WorkflowLog_Filter,WorkflowLog_Fixed,WorkflowLog_Result,WorkflowLog_FormattedResult>;
  teammembership_association: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  teamprofiles_association: WebMappingRetrieve<FieldSecurityProfile_Select,FieldSecurityProfile_Expand,FieldSecurityProfile_Filter,FieldSecurityProfile_Fixed,FieldSecurityProfile_Result,FieldSecurityProfile_FormattedResult>;
  teamroles_association: WebMappingRetrieve<Role_Select,Role_Expand,Role_Filter,Role_Fixed,Role_Result,Role_FormattedResult>;
  teamsyncattributemappingprofiles_association: WebMappingRetrieve<SyncAttributeMappingProfile_Select,SyncAttributeMappingProfile_Expand,SyncAttributeMappingProfile_Filter,SyncAttributeMappingProfile_Fixed,SyncAttributeMappingProfile_Result,SyncAttributeMappingProfile_FormattedResult>;
  userentityinstancedata_team: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
}
interface WebEntitiesRetrieve {
  teams: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
}
interface WebEntitiesRelated {
  teams: WebMappingRelated<Team_RelatedOne,Team_RelatedMany>;
}
interface WebEntitiesCUDA {
  teams: WebMappingCUDA<Team_Create,Team_Update,Team_Select>;
}
