interface TransactionCurrency_Base extends WebEntity {
  createdon?: Date | null;
  currencyname?: string | null;
  currencyprecision?: number | null;
  currencysymbol?: string | null;
  entityimageid?: string | null;
  exchangerate?: number | null;
  importsequencenumber?: number | null;
  isocurrencycode?: string | null;
  modifiedon?: Date | null;
  overriddencreatedon?: Date | null;
  statecode?: transactioncurrency_statecode | null;
  statuscode?: transactioncurrency_statuscode | null;
  transactioncurrencyid?: string | null;
  uniquedscid?: string | null;
  versionnumber?: number | null;
}
interface TransactionCurrency_Relationships {
  TransactionCurrency_ActionCardUserState?: ActionCardUserState_Result[] | null;
  TransactionCurrency_ActivityPointer?: ActivityPointer_Result[] | null;
  TransactionCurrency_Appointment?: Appointment_Result[] | null;
  TransactionCurrency_AsyncOperations?: AsyncOperation_Result[] | null;
  TransactionCurrency_BusinessUnit?: BusinessUnit_Result[] | null;
  TransactionCurrency_Connection?: Connection_Result[] | null;
  TransactionCurrency_ConvertRule?: ConvertRule_Result[] | null;
  TransactionCurrency_CustomerAddress?: CustomerAddress_Result[] | null;
  TransactionCurrency_DuplicateBaseRecord?: DuplicateRecord_Result[] | null;
  TransactionCurrency_DuplicateMatchingRecord?: DuplicateRecord_Result[] | null;
  TransactionCurrency_Email?: Email_Result[] | null;
  TransactionCurrency_Fax?: Fax_Result[] | null;
  TransactionCurrency_Goal?: Goal_Result[] | null;
  TransactionCurrency_InteractionForEmail?: InteractionForEmail_Result[] | null;
  TransactionCurrency_KbArticle?: KbArticle_Result[] | null;
  TransactionCurrency_KnowledgeBaseRecord?: KnowledgeBaseRecord_Result[] | null;
  TransactionCurrency_Letter?: Letter_Result[] | null;
  TransactionCurrency_MailMergeTemplate?: MailMergeTemplate_Result[] | null;
  TransactionCurrency_PhoneCall?: PhoneCall_Result[] | null;
  TransactionCurrency_ProcessSessions?: ProcessSession_Result[] | null;
  TransactionCurrency_Queue?: Queue_Result[] | null;
  TransactionCurrency_QueueItem?: QueueItem_Result[] | null;
  TransactionCurrency_RecurringAppointmentMaster?: RecurringAppointmentMaster_Result[] | null;
  TransactionCurrency_ReportCategory?: ReportCategory_Result[] | null;
  TransactionCurrency_Routingrule?: RoutingRule_Result[] | null;
  TransactionCurrency_SLA?: SLA_Result[] | null;
  TransactionCurrency_SLAItem?: SLAItem_Result[] | null;
  TransactionCurrency_SharePointDocument?: SharePointDocument_Result[] | null;
  TransactionCurrency_SharePointDocumentLocation?: SharePointDocumentLocation_Result[] | null;
  TransactionCurrency_SharePointSite?: SharePointSite_Result[] | null;
  TransactionCurrency_SimilarityRule?: SimilarityRule_Result[] | null;
  TransactionCurrency_SyncErrors?: SyncError_Result[] | null;
  TransactionCurrency_SystemUser?: SystemUser_Result[] | null;
  TransactionCurrency_Task?: Task_Result[] | null;
  TransactionCurrency_Team?: Team_Result[] | null;
  TransactionCurrency_Territory?: Territory_Result[] | null;
  TransactionCurrency_Theme?: Theme_Result[] | null;
  TransactionCurrency_UntrackedEmail?: UntrackedEmail_Result[] | null;
  TransactionCurrency_UserMapping?: UserMapping_Result[] | null;
  TransactionCurrency_delveactionhub?: DelveActionHub_Result[] | null;
  TransactionCurrency_externalpartyitem?: ExternalPartyItem_Result[] | null;
  TransactionCurrency_officegraphdocument?: OfficeGraphDocument_Result[] | null;
  TransactionCurrency_pc_Payment?: pc_Payment_Result[] | null;
  TransactionCurrency_pc_Transaction?: pc_Transaction_Result[] | null;
  TransactionCurrency_profilerule?: ChannelAccessProfileRule_Result[] | null;
  TransactionCurrency_profileruleitem?: ChannelAccessProfileRuleItem_Result[] | null;
  TransactionCurrency_recommendeddocument?: RecommendedDocument_Result[] | null;
  TransactionCurrency_routingruleitem?: RoutingRuleItem_Result[] | null;
  TransactionCurrency_slakpiinstance?: SLAKPIInstance_Result[] | null;
  basecurrency_organization?: Organization_Result[] | null;
  entityimageid_imagedescriptor?: ImageDescriptor_Result | null;
  transactioncurrency_SocialProfile?: SocialProfile_Result[] | null;
  transactioncurrency_account?: Account_Result[] | null;
  transactioncurrency_actioncard?: ActionCard_Result[] | null;
  transactioncurrency_annualfiscalcalendar?: AnnualFiscalCalendar_Result[] | null;
  transactioncurrency_cardtype?: CardType_Result[] | null;
  transactioncurrency_category?: Category_Result[] | null;
  transactioncurrency_channelaccessprofile?: ChannelAccessProfile_Result[] | null;
  transactioncurrency_contact?: Contact_Result[] | null;
  transactioncurrency_convertruleitem?: ConvertRuleItem_Result[] | null;
  transactioncurrency_expiredprocess?: ExpiredProcess_Result[] | null;
  transactioncurrency_externalparty?: ExternalParty_Result[] | null;
  transactioncurrency_feedback?: Feedback_Result[] | null;
  transactioncurrency_fixedmonthlyfiscalcalendar?: FixedMonthlyFiscalCalendar_Result[] | null;
  transactioncurrency_knowledgearticle?: KnowledgeArticle_Result[] | null;
  transactioncurrency_knowledgearticleviews?: KnowledgeArticleViews_Result[] | null;
  transactioncurrency_monthlyfiscalcalendar?: MonthlyFiscalCalendar_Result[] | null;
  transactioncurrency_newprocess?: NewProcess_Result[] | null;
  transactioncurrency_position?: Position_Result[] | null;
  transactioncurrency_quarterlyfiscalcalendar?: QuarterlyFiscalCalendar_Result[] | null;
  transactioncurrency_semiannualfiscalcalendar?: SemiAnnualFiscalCalendar_Result[] | null;
  transactioncurrency_socialactivity?: SocialActivity_Result[] | null;
  transactioncurrency_suggestioncardtemplate?: SuggestionCardTemplate_Result[] | null;
  transactioncurrency_translationprocess?: TranslationProcess_Result[] | null;
  transactioncurrency_userfiscalcalendar?: UserFiscalCalendar_Result[] | null;
  transactioncurrency_usersettings?: UserSettings_Result[] | null;
  userentityinstancedata_transactioncurrency?: UserEntityInstanceData_Result[] | null;
}
interface TransactionCurrency extends TransactionCurrency_Base, TransactionCurrency_Relationships {
}
interface TransactionCurrency_Create extends TransactionCurrency {
}
interface TransactionCurrency_Update extends TransactionCurrency {
}
interface TransactionCurrency_Select {
  createdby_guid: WebAttribute<TransactionCurrency_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<TransactionCurrency_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<TransactionCurrency_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  currencyname: WebAttribute<TransactionCurrency_Select, { currencyname: string | null }, {  }>;
  currencyprecision: WebAttribute<TransactionCurrency_Select, { currencyprecision: number | null }, {  }>;
  currencysymbol: WebAttribute<TransactionCurrency_Select, { currencysymbol: string | null }, {  }>;
  entityimageid: WebAttribute<TransactionCurrency_Select, { entityimageid: string | null }, {  }>;
  exchangerate: WebAttribute<TransactionCurrency_Select, { exchangerate: number | null }, {  }>;
  importsequencenumber: WebAttribute<TransactionCurrency_Select, { importsequencenumber: number | null }, {  }>;
  isocurrencycode: WebAttribute<TransactionCurrency_Select, { isocurrencycode: string | null }, {  }>;
  modifiedby_guid: WebAttribute<TransactionCurrency_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<TransactionCurrency_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<TransactionCurrency_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  organizationid_guid: WebAttribute<TransactionCurrency_Select, { organizationid_guid: string | null }, { organizationid_formatted?: string }>;
  overriddencreatedon: WebAttribute<TransactionCurrency_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  statecode: WebAttribute<TransactionCurrency_Select, { statecode: transactioncurrency_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<TransactionCurrency_Select, { statuscode: transactioncurrency_statuscode | null }, { statuscode_formatted?: string }>;
  transactioncurrencyid: WebAttribute<TransactionCurrency_Select, { transactioncurrencyid: string | null }, {  }>;
  uniquedscid: WebAttribute<TransactionCurrency_Select, { uniquedscid: string | null }, {  }>;
  versionnumber: WebAttribute<TransactionCurrency_Select, { versionnumber: number | null }, {  }>;
}
interface TransactionCurrency_Filter {
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  currencyname: string;
  currencyprecision: number;
  currencysymbol: string;
  entityimageid: XQW.Guid;
  exchangerate: any;
  importsequencenumber: number;
  isocurrencycode: string;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  organizationid_guid: XQW.Guid;
  overriddencreatedon: Date;
  statecode: transactioncurrency_statecode;
  statuscode: transactioncurrency_statuscode;
  transactioncurrencyid: XQW.Guid;
  uniquedscid: XQW.Guid;
  versionnumber: number;
}
interface TransactionCurrency_Expand {
  TransactionCurrency_ActionCardUserState: WebExpand<TransactionCurrency_Expand, ActionCardUserState_Select, ActionCardUserState_Filter, { TransactionCurrency_ActionCardUserState: ActionCardUserState_Result[] }>;
  TransactionCurrency_ActivityPointer: WebExpand<TransactionCurrency_Expand, ActivityPointer_Select, ActivityPointer_Filter, { TransactionCurrency_ActivityPointer: ActivityPointer_Result[] }>;
  TransactionCurrency_Appointment: WebExpand<TransactionCurrency_Expand, Appointment_Select, Appointment_Filter, { TransactionCurrency_Appointment: Appointment_Result[] }>;
  TransactionCurrency_AsyncOperations: WebExpand<TransactionCurrency_Expand, AsyncOperation_Select, AsyncOperation_Filter, { TransactionCurrency_AsyncOperations: AsyncOperation_Result[] }>;
  TransactionCurrency_BusinessUnit: WebExpand<TransactionCurrency_Expand, BusinessUnit_Select, BusinessUnit_Filter, { TransactionCurrency_BusinessUnit: BusinessUnit_Result[] }>;
  TransactionCurrency_Connection: WebExpand<TransactionCurrency_Expand, Connection_Select, Connection_Filter, { TransactionCurrency_Connection: Connection_Result[] }>;
  TransactionCurrency_ConvertRule: WebExpand<TransactionCurrency_Expand, ConvertRule_Select, ConvertRule_Filter, { TransactionCurrency_ConvertRule: ConvertRule_Result[] }>;
  TransactionCurrency_CustomerAddress: WebExpand<TransactionCurrency_Expand, CustomerAddress_Select, CustomerAddress_Filter, { TransactionCurrency_CustomerAddress: CustomerAddress_Result[] }>;
  TransactionCurrency_DuplicateBaseRecord: WebExpand<TransactionCurrency_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { TransactionCurrency_DuplicateBaseRecord: DuplicateRecord_Result[] }>;
  TransactionCurrency_DuplicateMatchingRecord: WebExpand<TransactionCurrency_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { TransactionCurrency_DuplicateMatchingRecord: DuplicateRecord_Result[] }>;
  TransactionCurrency_Email: WebExpand<TransactionCurrency_Expand, Email_Select, Email_Filter, { TransactionCurrency_Email: Email_Result[] }>;
  TransactionCurrency_Fax: WebExpand<TransactionCurrency_Expand, Fax_Select, Fax_Filter, { TransactionCurrency_Fax: Fax_Result[] }>;
  TransactionCurrency_Goal: WebExpand<TransactionCurrency_Expand, Goal_Select, Goal_Filter, { TransactionCurrency_Goal: Goal_Result[] }>;
  TransactionCurrency_InteractionForEmail: WebExpand<TransactionCurrency_Expand, InteractionForEmail_Select, InteractionForEmail_Filter, { TransactionCurrency_InteractionForEmail: InteractionForEmail_Result[] }>;
  TransactionCurrency_KbArticle: WebExpand<TransactionCurrency_Expand, KbArticle_Select, KbArticle_Filter, { TransactionCurrency_KbArticle: KbArticle_Result[] }>;
  TransactionCurrency_KnowledgeBaseRecord: WebExpand<TransactionCurrency_Expand, KnowledgeBaseRecord_Select, KnowledgeBaseRecord_Filter, { TransactionCurrency_KnowledgeBaseRecord: KnowledgeBaseRecord_Result[] }>;
  TransactionCurrency_Letter: WebExpand<TransactionCurrency_Expand, Letter_Select, Letter_Filter, { TransactionCurrency_Letter: Letter_Result[] }>;
  TransactionCurrency_MailMergeTemplate: WebExpand<TransactionCurrency_Expand, MailMergeTemplate_Select, MailMergeTemplate_Filter, { TransactionCurrency_MailMergeTemplate: MailMergeTemplate_Result[] }>;
  TransactionCurrency_PhoneCall: WebExpand<TransactionCurrency_Expand, PhoneCall_Select, PhoneCall_Filter, { TransactionCurrency_PhoneCall: PhoneCall_Result[] }>;
  TransactionCurrency_ProcessSessions: WebExpand<TransactionCurrency_Expand, ProcessSession_Select, ProcessSession_Filter, { TransactionCurrency_ProcessSessions: ProcessSession_Result[] }>;
  TransactionCurrency_Queue: WebExpand<TransactionCurrency_Expand, Queue_Select, Queue_Filter, { TransactionCurrency_Queue: Queue_Result[] }>;
  TransactionCurrency_QueueItem: WebExpand<TransactionCurrency_Expand, QueueItem_Select, QueueItem_Filter, { TransactionCurrency_QueueItem: QueueItem_Result[] }>;
  TransactionCurrency_RecurringAppointmentMaster: WebExpand<TransactionCurrency_Expand, RecurringAppointmentMaster_Select, RecurringAppointmentMaster_Filter, { TransactionCurrency_RecurringAppointmentMaster: RecurringAppointmentMaster_Result[] }>;
  TransactionCurrency_ReportCategory: WebExpand<TransactionCurrency_Expand, ReportCategory_Select, ReportCategory_Filter, { TransactionCurrency_ReportCategory: ReportCategory_Result[] }>;
  TransactionCurrency_Routingrule: WebExpand<TransactionCurrency_Expand, RoutingRule_Select, RoutingRule_Filter, { TransactionCurrency_Routingrule: RoutingRule_Result[] }>;
  TransactionCurrency_SLA: WebExpand<TransactionCurrency_Expand, SLA_Select, SLA_Filter, { TransactionCurrency_SLA: SLA_Result[] }>;
  TransactionCurrency_SLAItem: WebExpand<TransactionCurrency_Expand, SLAItem_Select, SLAItem_Filter, { TransactionCurrency_SLAItem: SLAItem_Result[] }>;
  TransactionCurrency_SharePointDocument: WebExpand<TransactionCurrency_Expand, SharePointDocument_Select, SharePointDocument_Filter, { TransactionCurrency_SharePointDocument: SharePointDocument_Result[] }>;
  TransactionCurrency_SharePointDocumentLocation: WebExpand<TransactionCurrency_Expand, SharePointDocumentLocation_Select, SharePointDocumentLocation_Filter, { TransactionCurrency_SharePointDocumentLocation: SharePointDocumentLocation_Result[] }>;
  TransactionCurrency_SharePointSite: WebExpand<TransactionCurrency_Expand, SharePointSite_Select, SharePointSite_Filter, { TransactionCurrency_SharePointSite: SharePointSite_Result[] }>;
  TransactionCurrency_SimilarityRule: WebExpand<TransactionCurrency_Expand, SimilarityRule_Select, SimilarityRule_Filter, { TransactionCurrency_SimilarityRule: SimilarityRule_Result[] }>;
  TransactionCurrency_SyncErrors: WebExpand<TransactionCurrency_Expand, SyncError_Select, SyncError_Filter, { TransactionCurrency_SyncErrors: SyncError_Result[] }>;
  TransactionCurrency_SystemUser: WebExpand<TransactionCurrency_Expand, SystemUser_Select, SystemUser_Filter, { TransactionCurrency_SystemUser: SystemUser_Result[] }>;
  TransactionCurrency_Task: WebExpand<TransactionCurrency_Expand, Task_Select, Task_Filter, { TransactionCurrency_Task: Task_Result[] }>;
  TransactionCurrency_Team: WebExpand<TransactionCurrency_Expand, Team_Select, Team_Filter, { TransactionCurrency_Team: Team_Result[] }>;
  TransactionCurrency_Territory: WebExpand<TransactionCurrency_Expand, Territory_Select, Territory_Filter, { TransactionCurrency_Territory: Territory_Result[] }>;
  TransactionCurrency_Theme: WebExpand<TransactionCurrency_Expand, Theme_Select, Theme_Filter, { TransactionCurrency_Theme: Theme_Result[] }>;
  TransactionCurrency_UntrackedEmail: WebExpand<TransactionCurrency_Expand, UntrackedEmail_Select, UntrackedEmail_Filter, { TransactionCurrency_UntrackedEmail: UntrackedEmail_Result[] }>;
  TransactionCurrency_UserMapping: WebExpand<TransactionCurrency_Expand, UserMapping_Select, UserMapping_Filter, { TransactionCurrency_UserMapping: UserMapping_Result[] }>;
  TransactionCurrency_delveactionhub: WebExpand<TransactionCurrency_Expand, DelveActionHub_Select, DelveActionHub_Filter, { TransactionCurrency_delveactionhub: DelveActionHub_Result[] }>;
  TransactionCurrency_externalpartyitem: WebExpand<TransactionCurrency_Expand, ExternalPartyItem_Select, ExternalPartyItem_Filter, { TransactionCurrency_externalpartyitem: ExternalPartyItem_Result[] }>;
  TransactionCurrency_officegraphdocument: WebExpand<TransactionCurrency_Expand, OfficeGraphDocument_Select, OfficeGraphDocument_Filter, { TransactionCurrency_officegraphdocument: OfficeGraphDocument_Result[] }>;
  TransactionCurrency_pc_Payment: WebExpand<TransactionCurrency_Expand, pc_Payment_Select, pc_Payment_Filter, { TransactionCurrency_pc_Payment: pc_Payment_Result[] }>;
  TransactionCurrency_pc_Transaction: WebExpand<TransactionCurrency_Expand, pc_Transaction_Select, pc_Transaction_Filter, { TransactionCurrency_pc_Transaction: pc_Transaction_Result[] }>;
  TransactionCurrency_profilerule: WebExpand<TransactionCurrency_Expand, ChannelAccessProfileRule_Select, ChannelAccessProfileRule_Filter, { TransactionCurrency_profilerule: ChannelAccessProfileRule_Result[] }>;
  TransactionCurrency_profileruleitem: WebExpand<TransactionCurrency_Expand, ChannelAccessProfileRuleItem_Select, ChannelAccessProfileRuleItem_Filter, { TransactionCurrency_profileruleitem: ChannelAccessProfileRuleItem_Result[] }>;
  TransactionCurrency_recommendeddocument: WebExpand<TransactionCurrency_Expand, RecommendedDocument_Select, RecommendedDocument_Filter, { TransactionCurrency_recommendeddocument: RecommendedDocument_Result[] }>;
  TransactionCurrency_routingruleitem: WebExpand<TransactionCurrency_Expand, RoutingRuleItem_Select, RoutingRuleItem_Filter, { TransactionCurrency_routingruleitem: RoutingRuleItem_Result[] }>;
  TransactionCurrency_slakpiinstance: WebExpand<TransactionCurrency_Expand, SLAKPIInstance_Select, SLAKPIInstance_Filter, { TransactionCurrency_slakpiinstance: SLAKPIInstance_Result[] }>;
  basecurrency_organization: WebExpand<TransactionCurrency_Expand, Organization_Select, Organization_Filter, { basecurrency_organization: Organization_Result[] }>;
  createdby: WebExpand<TransactionCurrency_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<TransactionCurrency_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  entityimageid_imagedescriptor: WebExpand<TransactionCurrency_Expand, ImageDescriptor_Select, ImageDescriptor_Filter, { entityimageid_imagedescriptor: ImageDescriptor_Result }>;
  modifiedby: WebExpand<TransactionCurrency_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<TransactionCurrency_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  organizationid: WebExpand<TransactionCurrency_Expand, Organization_Select, Organization_Filter, { organizationid: Organization_Result }>;
  transactioncurrency_SocialProfile: WebExpand<TransactionCurrency_Expand, SocialProfile_Select, SocialProfile_Filter, { transactioncurrency_SocialProfile: SocialProfile_Result[] }>;
  transactioncurrency_account: WebExpand<TransactionCurrency_Expand, Account_Select, Account_Filter, { transactioncurrency_account: Account_Result[] }>;
  transactioncurrency_actioncard: WebExpand<TransactionCurrency_Expand, ActionCard_Select, ActionCard_Filter, { transactioncurrency_actioncard: ActionCard_Result[] }>;
  transactioncurrency_annualfiscalcalendar: WebExpand<TransactionCurrency_Expand, AnnualFiscalCalendar_Select, AnnualFiscalCalendar_Filter, { transactioncurrency_annualfiscalcalendar: AnnualFiscalCalendar_Result[] }>;
  transactioncurrency_cardtype: WebExpand<TransactionCurrency_Expand, CardType_Select, CardType_Filter, { transactioncurrency_cardtype: CardType_Result[] }>;
  transactioncurrency_category: WebExpand<TransactionCurrency_Expand, Category_Select, Category_Filter, { transactioncurrency_category: Category_Result[] }>;
  transactioncurrency_channelaccessprofile: WebExpand<TransactionCurrency_Expand, ChannelAccessProfile_Select, ChannelAccessProfile_Filter, { transactioncurrency_channelaccessprofile: ChannelAccessProfile_Result[] }>;
  transactioncurrency_contact: WebExpand<TransactionCurrency_Expand, Contact_Select, Contact_Filter, { transactioncurrency_contact: Contact_Result[] }>;
  transactioncurrency_convertruleitem: WebExpand<TransactionCurrency_Expand, ConvertRuleItem_Select, ConvertRuleItem_Filter, { transactioncurrency_convertruleitem: ConvertRuleItem_Result[] }>;
  transactioncurrency_expiredprocess: WebExpand<TransactionCurrency_Expand, ExpiredProcess_Select, ExpiredProcess_Filter, { transactioncurrency_expiredprocess: ExpiredProcess_Result[] }>;
  transactioncurrency_externalparty: WebExpand<TransactionCurrency_Expand, ExternalParty_Select, ExternalParty_Filter, { transactioncurrency_externalparty: ExternalParty_Result[] }>;
  transactioncurrency_feedback: WebExpand<TransactionCurrency_Expand, Feedback_Select, Feedback_Filter, { transactioncurrency_feedback: Feedback_Result[] }>;
  transactioncurrency_fixedmonthlyfiscalcalendar: WebExpand<TransactionCurrency_Expand, FixedMonthlyFiscalCalendar_Select, FixedMonthlyFiscalCalendar_Filter, { transactioncurrency_fixedmonthlyfiscalcalendar: FixedMonthlyFiscalCalendar_Result[] }>;
  transactioncurrency_knowledgearticle: WebExpand<TransactionCurrency_Expand, KnowledgeArticle_Select, KnowledgeArticle_Filter, { transactioncurrency_knowledgearticle: KnowledgeArticle_Result[] }>;
  transactioncurrency_knowledgearticleviews: WebExpand<TransactionCurrency_Expand, KnowledgeArticleViews_Select, KnowledgeArticleViews_Filter, { transactioncurrency_knowledgearticleviews: KnowledgeArticleViews_Result[] }>;
  transactioncurrency_monthlyfiscalcalendar: WebExpand<TransactionCurrency_Expand, MonthlyFiscalCalendar_Select, MonthlyFiscalCalendar_Filter, { transactioncurrency_monthlyfiscalcalendar: MonthlyFiscalCalendar_Result[] }>;
  transactioncurrency_newprocess: WebExpand<TransactionCurrency_Expand, NewProcess_Select, NewProcess_Filter, { transactioncurrency_newprocess: NewProcess_Result[] }>;
  transactioncurrency_position: WebExpand<TransactionCurrency_Expand, Position_Select, Position_Filter, { transactioncurrency_position: Position_Result[] }>;
  transactioncurrency_quarterlyfiscalcalendar: WebExpand<TransactionCurrency_Expand, QuarterlyFiscalCalendar_Select, QuarterlyFiscalCalendar_Filter, { transactioncurrency_quarterlyfiscalcalendar: QuarterlyFiscalCalendar_Result[] }>;
  transactioncurrency_semiannualfiscalcalendar: WebExpand<TransactionCurrency_Expand, SemiAnnualFiscalCalendar_Select, SemiAnnualFiscalCalendar_Filter, { transactioncurrency_semiannualfiscalcalendar: SemiAnnualFiscalCalendar_Result[] }>;
  transactioncurrency_socialactivity: WebExpand<TransactionCurrency_Expand, SocialActivity_Select, SocialActivity_Filter, { transactioncurrency_socialactivity: SocialActivity_Result[] }>;
  transactioncurrency_suggestioncardtemplate: WebExpand<TransactionCurrency_Expand, SuggestionCardTemplate_Select, SuggestionCardTemplate_Filter, { transactioncurrency_suggestioncardtemplate: SuggestionCardTemplate_Result[] }>;
  transactioncurrency_translationprocess: WebExpand<TransactionCurrency_Expand, TranslationProcess_Select, TranslationProcess_Filter, { transactioncurrency_translationprocess: TranslationProcess_Result[] }>;
  transactioncurrency_userfiscalcalendar: WebExpand<TransactionCurrency_Expand, UserFiscalCalendar_Select, UserFiscalCalendar_Filter, { transactioncurrency_userfiscalcalendar: UserFiscalCalendar_Result[] }>;
  transactioncurrency_usersettings: WebExpand<TransactionCurrency_Expand, UserSettings_Select, UserSettings_Filter, { transactioncurrency_usersettings: UserSettings_Result[] }>;
  userentityinstancedata_transactioncurrency: WebExpand<TransactionCurrency_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { userentityinstancedata_transactioncurrency: UserEntityInstanceData_Result[] }>;
}
interface TransactionCurrency_FormattedResult {
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  organizationid_formatted?: string;
  overriddencreatedon_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
}
interface TransactionCurrency_Result extends TransactionCurrency_Base, TransactionCurrency_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  organizationid_guid: string | null;
}
interface TransactionCurrency_RelatedOne {
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  entityimageid_imagedescriptor: WebMappingRetrieve<ImageDescriptor_Select,ImageDescriptor_Expand,ImageDescriptor_Filter,ImageDescriptor_Fixed,ImageDescriptor_Result,ImageDescriptor_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  organizationid: WebMappingRetrieve<Organization_Select,Organization_Expand,Organization_Filter,Organization_Fixed,Organization_Result,Organization_FormattedResult>;
}
interface TransactionCurrency_RelatedMany {
  TransactionCurrency_ActionCardUserState: WebMappingRetrieve<ActionCardUserState_Select,ActionCardUserState_Expand,ActionCardUserState_Filter,ActionCardUserState_Fixed,ActionCardUserState_Result,ActionCardUserState_FormattedResult>;
  TransactionCurrency_ActivityPointer: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  TransactionCurrency_Appointment: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
  TransactionCurrency_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  TransactionCurrency_BusinessUnit: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  TransactionCurrency_Connection: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  TransactionCurrency_ConvertRule: WebMappingRetrieve<ConvertRule_Select,ConvertRule_Expand,ConvertRule_Filter,ConvertRule_Fixed,ConvertRule_Result,ConvertRule_FormattedResult>;
  TransactionCurrency_CustomerAddress: WebMappingRetrieve<CustomerAddress_Select,CustomerAddress_Expand,CustomerAddress_Filter,CustomerAddress_Fixed,CustomerAddress_Result,CustomerAddress_FormattedResult>;
  TransactionCurrency_DuplicateBaseRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  TransactionCurrency_DuplicateMatchingRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  TransactionCurrency_Email: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  TransactionCurrency_Fax: WebMappingRetrieve<Fax_Select,Fax_Expand,Fax_Filter,Fax_Fixed,Fax_Result,Fax_FormattedResult>;
  TransactionCurrency_Goal: WebMappingRetrieve<Goal_Select,Goal_Expand,Goal_Filter,Goal_Fixed,Goal_Result,Goal_FormattedResult>;
  TransactionCurrency_InteractionForEmail: WebMappingRetrieve<InteractionForEmail_Select,InteractionForEmail_Expand,InteractionForEmail_Filter,InteractionForEmail_Fixed,InteractionForEmail_Result,InteractionForEmail_FormattedResult>;
  TransactionCurrency_KbArticle: WebMappingRetrieve<KbArticle_Select,KbArticle_Expand,KbArticle_Filter,KbArticle_Fixed,KbArticle_Result,KbArticle_FormattedResult>;
  TransactionCurrency_KnowledgeBaseRecord: WebMappingRetrieve<KnowledgeBaseRecord_Select,KnowledgeBaseRecord_Expand,KnowledgeBaseRecord_Filter,KnowledgeBaseRecord_Fixed,KnowledgeBaseRecord_Result,KnowledgeBaseRecord_FormattedResult>;
  TransactionCurrency_Letter: WebMappingRetrieve<Letter_Select,Letter_Expand,Letter_Filter,Letter_Fixed,Letter_Result,Letter_FormattedResult>;
  TransactionCurrency_MailMergeTemplate: WebMappingRetrieve<MailMergeTemplate_Select,MailMergeTemplate_Expand,MailMergeTemplate_Filter,MailMergeTemplate_Fixed,MailMergeTemplate_Result,MailMergeTemplate_FormattedResult>;
  TransactionCurrency_PhoneCall: WebMappingRetrieve<PhoneCall_Select,PhoneCall_Expand,PhoneCall_Filter,PhoneCall_Fixed,PhoneCall_Result,PhoneCall_FormattedResult>;
  TransactionCurrency_ProcessSessions: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  TransactionCurrency_Queue: WebMappingRetrieve<Queue_Select,Queue_Expand,Queue_Filter,Queue_Fixed,Queue_Result,Queue_FormattedResult>;
  TransactionCurrency_QueueItem: WebMappingRetrieve<QueueItem_Select,QueueItem_Expand,QueueItem_Filter,QueueItem_Fixed,QueueItem_Result,QueueItem_FormattedResult>;
  TransactionCurrency_RecurringAppointmentMaster: WebMappingRetrieve<RecurringAppointmentMaster_Select,RecurringAppointmentMaster_Expand,RecurringAppointmentMaster_Filter,RecurringAppointmentMaster_Fixed,RecurringAppointmentMaster_Result,RecurringAppointmentMaster_FormattedResult>;
  TransactionCurrency_ReportCategory: WebMappingRetrieve<ReportCategory_Select,ReportCategory_Expand,ReportCategory_Filter,ReportCategory_Fixed,ReportCategory_Result,ReportCategory_FormattedResult>;
  TransactionCurrency_Routingrule: WebMappingRetrieve<RoutingRule_Select,RoutingRule_Expand,RoutingRule_Filter,RoutingRule_Fixed,RoutingRule_Result,RoutingRule_FormattedResult>;
  TransactionCurrency_SLA: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  TransactionCurrency_SLAItem: WebMappingRetrieve<SLAItem_Select,SLAItem_Expand,SLAItem_Filter,SLAItem_Fixed,SLAItem_Result,SLAItem_FormattedResult>;
  TransactionCurrency_SharePointDocument: WebMappingRetrieve<SharePointDocument_Select,SharePointDocument_Expand,SharePointDocument_Filter,SharePointDocument_Fixed,SharePointDocument_Result,SharePointDocument_FormattedResult>;
  TransactionCurrency_SharePointDocumentLocation: WebMappingRetrieve<SharePointDocumentLocation_Select,SharePointDocumentLocation_Expand,SharePointDocumentLocation_Filter,SharePointDocumentLocation_Fixed,SharePointDocumentLocation_Result,SharePointDocumentLocation_FormattedResult>;
  TransactionCurrency_SharePointSite: WebMappingRetrieve<SharePointSite_Select,SharePointSite_Expand,SharePointSite_Filter,SharePointSite_Fixed,SharePointSite_Result,SharePointSite_FormattedResult>;
  TransactionCurrency_SimilarityRule: WebMappingRetrieve<SimilarityRule_Select,SimilarityRule_Expand,SimilarityRule_Filter,SimilarityRule_Fixed,SimilarityRule_Result,SimilarityRule_FormattedResult>;
  TransactionCurrency_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  TransactionCurrency_SystemUser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  TransactionCurrency_Task: WebMappingRetrieve<Task_Select,Task_Expand,Task_Filter,Task_Fixed,Task_Result,Task_FormattedResult>;
  TransactionCurrency_Team: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  TransactionCurrency_Territory: WebMappingRetrieve<Territory_Select,Territory_Expand,Territory_Filter,Territory_Fixed,Territory_Result,Territory_FormattedResult>;
  TransactionCurrency_Theme: WebMappingRetrieve<Theme_Select,Theme_Expand,Theme_Filter,Theme_Fixed,Theme_Result,Theme_FormattedResult>;
  TransactionCurrency_UntrackedEmail: WebMappingRetrieve<UntrackedEmail_Select,UntrackedEmail_Expand,UntrackedEmail_Filter,UntrackedEmail_Fixed,UntrackedEmail_Result,UntrackedEmail_FormattedResult>;
  TransactionCurrency_UserMapping: WebMappingRetrieve<UserMapping_Select,UserMapping_Expand,UserMapping_Filter,UserMapping_Fixed,UserMapping_Result,UserMapping_FormattedResult>;
  TransactionCurrency_delveactionhub: WebMappingRetrieve<DelveActionHub_Select,DelveActionHub_Expand,DelveActionHub_Filter,DelveActionHub_Fixed,DelveActionHub_Result,DelveActionHub_FormattedResult>;
  TransactionCurrency_externalpartyitem: WebMappingRetrieve<ExternalPartyItem_Select,ExternalPartyItem_Expand,ExternalPartyItem_Filter,ExternalPartyItem_Fixed,ExternalPartyItem_Result,ExternalPartyItem_FormattedResult>;
  TransactionCurrency_officegraphdocument: WebMappingRetrieve<OfficeGraphDocument_Select,OfficeGraphDocument_Expand,OfficeGraphDocument_Filter,OfficeGraphDocument_Fixed,OfficeGraphDocument_Result,OfficeGraphDocument_FormattedResult>;
  TransactionCurrency_pc_Payment: WebMappingRetrieve<pc_Payment_Select,pc_Payment_Expand,pc_Payment_Filter,pc_Payment_Fixed,pc_Payment_Result,pc_Payment_FormattedResult>;
  TransactionCurrency_pc_Transaction: WebMappingRetrieve<pc_Transaction_Select,pc_Transaction_Expand,pc_Transaction_Filter,pc_Transaction_Fixed,pc_Transaction_Result,pc_Transaction_FormattedResult>;
  TransactionCurrency_profilerule: WebMappingRetrieve<ChannelAccessProfileRule_Select,ChannelAccessProfileRule_Expand,ChannelAccessProfileRule_Filter,ChannelAccessProfileRule_Fixed,ChannelAccessProfileRule_Result,ChannelAccessProfileRule_FormattedResult>;
  TransactionCurrency_profileruleitem: WebMappingRetrieve<ChannelAccessProfileRuleItem_Select,ChannelAccessProfileRuleItem_Expand,ChannelAccessProfileRuleItem_Filter,ChannelAccessProfileRuleItem_Fixed,ChannelAccessProfileRuleItem_Result,ChannelAccessProfileRuleItem_FormattedResult>;
  TransactionCurrency_recommendeddocument: WebMappingRetrieve<RecommendedDocument_Select,RecommendedDocument_Expand,RecommendedDocument_Filter,RecommendedDocument_Fixed,RecommendedDocument_Result,RecommendedDocument_FormattedResult>;
  TransactionCurrency_routingruleitem: WebMappingRetrieve<RoutingRuleItem_Select,RoutingRuleItem_Expand,RoutingRuleItem_Filter,RoutingRuleItem_Fixed,RoutingRuleItem_Result,RoutingRuleItem_FormattedResult>;
  TransactionCurrency_slakpiinstance: WebMappingRetrieve<SLAKPIInstance_Select,SLAKPIInstance_Expand,SLAKPIInstance_Filter,SLAKPIInstance_Fixed,SLAKPIInstance_Result,SLAKPIInstance_FormattedResult>;
  basecurrency_organization: WebMappingRetrieve<Organization_Select,Organization_Expand,Organization_Filter,Organization_Fixed,Organization_Result,Organization_FormattedResult>;
  transactioncurrency_SocialProfile: WebMappingRetrieve<SocialProfile_Select,SocialProfile_Expand,SocialProfile_Filter,SocialProfile_Fixed,SocialProfile_Result,SocialProfile_FormattedResult>;
  transactioncurrency_account: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  transactioncurrency_actioncard: WebMappingRetrieve<ActionCard_Select,ActionCard_Expand,ActionCard_Filter,ActionCard_Fixed,ActionCard_Result,ActionCard_FormattedResult>;
  transactioncurrency_annualfiscalcalendar: WebMappingRetrieve<AnnualFiscalCalendar_Select,AnnualFiscalCalendar_Expand,AnnualFiscalCalendar_Filter,AnnualFiscalCalendar_Fixed,AnnualFiscalCalendar_Result,AnnualFiscalCalendar_FormattedResult>;
  transactioncurrency_cardtype: WebMappingRetrieve<CardType_Select,CardType_Expand,CardType_Filter,CardType_Fixed,CardType_Result,CardType_FormattedResult>;
  transactioncurrency_category: WebMappingRetrieve<Category_Select,Category_Expand,Category_Filter,Category_Fixed,Category_Result,Category_FormattedResult>;
  transactioncurrency_channelaccessprofile: WebMappingRetrieve<ChannelAccessProfile_Select,ChannelAccessProfile_Expand,ChannelAccessProfile_Filter,ChannelAccessProfile_Fixed,ChannelAccessProfile_Result,ChannelAccessProfile_FormattedResult>;
  transactioncurrency_contact: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  transactioncurrency_convertruleitem: WebMappingRetrieve<ConvertRuleItem_Select,ConvertRuleItem_Expand,ConvertRuleItem_Filter,ConvertRuleItem_Fixed,ConvertRuleItem_Result,ConvertRuleItem_FormattedResult>;
  transactioncurrency_expiredprocess: WebMappingRetrieve<ExpiredProcess_Select,ExpiredProcess_Expand,ExpiredProcess_Filter,ExpiredProcess_Fixed,ExpiredProcess_Result,ExpiredProcess_FormattedResult>;
  transactioncurrency_externalparty: WebMappingRetrieve<ExternalParty_Select,ExternalParty_Expand,ExternalParty_Filter,ExternalParty_Fixed,ExternalParty_Result,ExternalParty_FormattedResult>;
  transactioncurrency_feedback: WebMappingRetrieve<Feedback_Select,Feedback_Expand,Feedback_Filter,Feedback_Fixed,Feedback_Result,Feedback_FormattedResult>;
  transactioncurrency_fixedmonthlyfiscalcalendar: WebMappingRetrieve<FixedMonthlyFiscalCalendar_Select,FixedMonthlyFiscalCalendar_Expand,FixedMonthlyFiscalCalendar_Filter,FixedMonthlyFiscalCalendar_Fixed,FixedMonthlyFiscalCalendar_Result,FixedMonthlyFiscalCalendar_FormattedResult>;
  transactioncurrency_knowledgearticle: WebMappingRetrieve<KnowledgeArticle_Select,KnowledgeArticle_Expand,KnowledgeArticle_Filter,KnowledgeArticle_Fixed,KnowledgeArticle_Result,KnowledgeArticle_FormattedResult>;
  transactioncurrency_knowledgearticleviews: WebMappingRetrieve<KnowledgeArticleViews_Select,KnowledgeArticleViews_Expand,KnowledgeArticleViews_Filter,KnowledgeArticleViews_Fixed,KnowledgeArticleViews_Result,KnowledgeArticleViews_FormattedResult>;
  transactioncurrency_monthlyfiscalcalendar: WebMappingRetrieve<MonthlyFiscalCalendar_Select,MonthlyFiscalCalendar_Expand,MonthlyFiscalCalendar_Filter,MonthlyFiscalCalendar_Fixed,MonthlyFiscalCalendar_Result,MonthlyFiscalCalendar_FormattedResult>;
  transactioncurrency_newprocess: WebMappingRetrieve<NewProcess_Select,NewProcess_Expand,NewProcess_Filter,NewProcess_Fixed,NewProcess_Result,NewProcess_FormattedResult>;
  transactioncurrency_position: WebMappingRetrieve<Position_Select,Position_Expand,Position_Filter,Position_Fixed,Position_Result,Position_FormattedResult>;
  transactioncurrency_quarterlyfiscalcalendar: WebMappingRetrieve<QuarterlyFiscalCalendar_Select,QuarterlyFiscalCalendar_Expand,QuarterlyFiscalCalendar_Filter,QuarterlyFiscalCalendar_Fixed,QuarterlyFiscalCalendar_Result,QuarterlyFiscalCalendar_FormattedResult>;
  transactioncurrency_semiannualfiscalcalendar: WebMappingRetrieve<SemiAnnualFiscalCalendar_Select,SemiAnnualFiscalCalendar_Expand,SemiAnnualFiscalCalendar_Filter,SemiAnnualFiscalCalendar_Fixed,SemiAnnualFiscalCalendar_Result,SemiAnnualFiscalCalendar_FormattedResult>;
  transactioncurrency_socialactivity: WebMappingRetrieve<SocialActivity_Select,SocialActivity_Expand,SocialActivity_Filter,SocialActivity_Fixed,SocialActivity_Result,SocialActivity_FormattedResult>;
  transactioncurrency_suggestioncardtemplate: WebMappingRetrieve<SuggestionCardTemplate_Select,SuggestionCardTemplate_Expand,SuggestionCardTemplate_Filter,SuggestionCardTemplate_Fixed,SuggestionCardTemplate_Result,SuggestionCardTemplate_FormattedResult>;
  transactioncurrency_translationprocess: WebMappingRetrieve<TranslationProcess_Select,TranslationProcess_Expand,TranslationProcess_Filter,TranslationProcess_Fixed,TranslationProcess_Result,TranslationProcess_FormattedResult>;
  transactioncurrency_userfiscalcalendar: WebMappingRetrieve<UserFiscalCalendar_Select,UserFiscalCalendar_Expand,UserFiscalCalendar_Filter,UserFiscalCalendar_Fixed,UserFiscalCalendar_Result,UserFiscalCalendar_FormattedResult>;
  transactioncurrency_usersettings: WebMappingRetrieve<UserSettings_Select,UserSettings_Expand,UserSettings_Filter,UserSettings_Fixed,UserSettings_Result,UserSettings_FormattedResult>;
  userentityinstancedata_transactioncurrency: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
}
interface WebEntitiesRetrieve {
  transactioncurrencies: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface WebEntitiesRelated {
  transactioncurrencies: WebMappingRelated<TransactionCurrency_RelatedOne,TransactionCurrency_RelatedMany>;
}
interface WebEntitiesCUDA {
  transactioncurrencies: WebMappingCUDA<TransactionCurrency_Create,TransactionCurrency_Update,TransactionCurrency_Select>;
}
