# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  commit-solution:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Export Solution
        uses: microsoft/powerplatform-actions/export-solution@v0
        with:
          app-id: ${{ secrets.DATAVERSE_APP_ID }}
          client-secret: ${{ secrets.DATAVERSE_CLIENT_SECRET }}
          environment-url: ${{ secrets.DATAVERSE_URL }}
          solution-name: CityForPeople
          solution-output-file: 'CityForPeople.zip'
          tenant-id: ${{ secrets.MICROSOFT_TENANT_ID }}

      - name: Unpack Solution
        uses: microsoft/powerplatform-actions/unpack-solution@v0
        with:
          solution-file: 'CityForPeople.zip'
          solution-folder: 'Customizations'

      - name: Remove Solution
        run: rm CityForPeople.zip
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

#       - name: Set Git Name
#         run:   git config --global user.name "GitHub Actions"

      - name: Commit
        run: git commit -a -m 'Solution update'

      - name: Push
        run: git push
